# This will run on Travis' 'new' container-based infrastructure
sudo: false 

# Blacklist
branches:
  only:
    - master

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - graphviz

# Build your code e.g. by calling make
script:
  - cd doc && doxygen Doxyfile && cd ..

# Generate and deploy documentation
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: doc/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
