Fast Methods for Cosmological Simulations: src/3party/CCL/tests/ccl_test_utils.c File Reference
ccl_test_utils.c File Reference
#include <gsl/gsl_sf_bessel.h>
#include "ccl.h"
#include "ctest.h"
#include "ccl_params.h"
#include "ccl_core.h"
Functions
void __ctest_spacing_tests_linear_spacing_simple_run ()
static struct ctest __ctest_spacing_tests_linear_spacing_simple __attribute__ ((used, section(".ctest"))) = { .ssname="spacing_tests", .ttname="log_spacing_simple", .run = __ctest_spacing_tests_log_spacing_simple_run, .skip = 0 , .data = NULL , .setup = (SetupFunc) NULL , .teardown = (TearDownFunc) NULL , .magic = (0xdeadbeef) }
void __ctest_spacing_tests_log_spacing_simple_run ()
void __ctest_spacing_tests_linlog_spacing_simple_run ()
void __ctest_spherical_bessel_tests_compare_gsl_run ()
Function Documentation
static struct ctest __ctest_spherical_bessel_tests_compare_gsl __attribute__ ((used, section(".ctest"))) = { .ssname="spacing_tests", .ttname="log_spacing_simple", .run = __ctest_spacing_tests_log_spacing_simple_run, .skip = 0 , .data = NULL , .setup = (SetupFunc) NULL , .teardown = (TearDownFunc) NULL , .magic = (0xdeadbeef) } static
void __ctest_spacing_tests_linear_spacing_simple_run ()
Definition at line 7 of file ccl_test_utils.c.
References ASSERT_DBL_NEAR_TOL, ASSERT_NOT_NULL, ccl_linear_spacing(), and m.
{
   double * m = ccl_linear_spacing(0.0, 1.0, 5);
   ASSERT_NOT_NULL(m);
   ASSERT_DBL_NEAR_TOL(0.0, m[0], 1e-10);
   ASSERT_DBL_NEAR_TOL(0.25, m[1], 1e-10);
   ASSERT_DBL_NEAR_TOL(0.5, m[2], 1e-10);
   ASSERT_DBL_NEAR_TOL(0.75, m[3], 1e-10);
   ASSERT_DBL_NEAR_TOL(1.0, m[4], 1e-10);
   free(m);
 }
void __ctest_spacing_tests_linlog_spacing_simple_run ()
Definition at line 29 of file ccl_test_utils.c.
References ASSERT_DBL_NEAR_TOL, ASSERT_NOT_NULL, ccl_linlog_spacing(), and m.
{
   double * m = ccl_linlog_spacing(1.0, 16.0, 32.0, 5, 9);
   ASSERT_NOT_NULL(m);
   ASSERT_DBL_NEAR_TOL(1.0, m[0], 1e-10);
   ASSERT_DBL_NEAR_TOL(2.0, m[1], 1e-10);
   ASSERT_DBL_NEAR_TOL(4.0, m[2], 1e-10);
   ASSERT_DBL_NEAR_TOL(8.0, m[3], 1e-10);
   ASSERT_DBL_NEAR_TOL(16.0, m[4], 1e-10);
   ASSERT_DBL_NEAR_TOL(18.0, m[5], 1e-10);
   ASSERT_DBL_NEAR_TOL(20.0, m[6], 1e-10);
   ASSERT_DBL_NEAR_TOL(22.0, m[7], 1e-10);
   ASSERT_DBL_NEAR_TOL(24.0, m[8], 1e-10);
   ASSERT_DBL_NEAR_TOL(26.0, m[9], 1e-10);
   ASSERT_DBL_NEAR_TOL(28.0, m[10], 1e-10);
   ASSERT_DBL_NEAR_TOL(30.0, m[11], 1e-10);
   ASSERT_DBL_NEAR_TOL(32.0, m[12], 1e-10);
   free(m);
 }
void __ctest_spacing_tests_log_spacing_simple_run ()
Definition at line 18 of file ccl_test_utils.c.
References ASSERT_DBL_NEAR_TOL, ASSERT_NOT_NULL, ccl_log_spacing(), and m.
{
   double * m = ccl_log_spacing(1.0, 16.0, 5);
   ASSERT_NOT_NULL(m);
   ASSERT_DBL_NEAR_TOL(1.0, m[0], 1e-10);
   ASSERT_DBL_NEAR_TOL(2.0, m[1], 1e-10);
   ASSERT_DBL_NEAR_TOL(4.0, m[2], 1e-10);
   ASSERT_DBL_NEAR_TOL(8.0, m[3], 1e-10);
   ASSERT_DBL_NEAR_TOL(16.0, m[4], 1e-10);
   free(m);
 }
void __ctest_spherical_bessel_tests_compare_gsl_run ()
Definition at line 48 of file ccl_test_utils.c.
References ASSERT_DBL_NEAR_TOL, ccl_j_bessel(), cl_cmbl_bm::l, x, xmax, and xmin.
{
   int l, i;
   double xmin = 0.0;
   double xmax = 10.0;
   int Nx = 10000;
   double x, dx;
   dx = (xmax - xmin) / (Nx - 1);
   for (l=0; l < 15; ++l) {
     for (i=0; i < Nx; ++i) {
       x = dx * i + xmin;
       ASSERT_DBL_NEAR_TOL(
         ccl_j_bessel(l, x),
         gsl_sf_bessel_jl(l, x),
         1e-4);
     }
   }
 }