Fast Methods for Cosmological Simulations: src/3party/CCL/tests/ccl_test_growth_hiz.c File Reference
ccl_test_growth_hiz.c File Reference
#include "ccl.h"
#include "ctest.h"
#include <stdio.h>
#include <math.h>
Classes
struct growth_hiz_data
Macros
#define GROWTH_HIZ_TOLERANCE 6.0e-6
Functions
static void read_growth_hiz_test_file (double z[7], double gf[3][7])
void __attribute__ ((weak))
static void compare_growth_hiz (int model, struct growth_hiz_data *data)
void __ctest_growth_hiz_model_1_run (struct growth_hiz_data *data)
void __ctest_growth_hiz_model_2_run (struct growth_hiz_data *data)
void __ctest_growth_hiz_model_3_run (struct growth_hiz_data *data)
Variables
static struct growth_hiz_data __ctest_growth_hiz_data
Macro Definition Documentation
#define GROWTH_HIZ_TOLERANCE 6.0e-6
Definition at line 7 of file ccl_test_growth_hiz.c.
Referenced by compare_growth_hiz().
Function Documentation
void __attribute__ ((weak))
Definition at line 52 of file ccl_test_growth_hiz.c.
References ccl_mnu_sum, and read_growth_hiz_test_file().
{
   // Values that are the same for all 3 models
   data->Omega_c = 0.25;
   data->Omega_b = 0.05;
   data->h = 0.7;
   data->A_s = 2.1e-9;
   data->n_s = 0.96;
   data->Neff=0;
   double mnuval = 0.;
   data->mnu= &mnuval;
   data->mnu_type = ccl_mnu_sum;
   // Values that are different for the different models
   double Omega_v[3] = {  0.7,  0.7,  0.7};
   double w_0[3]     = { -1.0, -0.9, -0.9};
   double w_a[3]     = {  0.0,  0.0,  0.1};
   // Fill in the values from these constant arrays.
   for (int i=0; i<3; i++) {
     data->Omega_v[i] = Omega_v[i];
     data->w_0[i]     = w_0[i];
     data->w_a[i]     = w_a[i];
     data->Omega_k[i] = 1.0 - data->Omega_c - data->Omega_b - data->Omega_v[i];
   }
   // The file of benchmark data.
   read_growth_hiz_test_file(data->z, data->gf);
 }
void __ctest_growth_hiz_model_1_run (struct growth_hiz_data * data)
Definition at line 107 of file ccl_test_growth_hiz.c.
References compare_growth_hiz().
{
   int model = 0;
   compare_growth_hiz(model, data);
 }
void __ctest_growth_hiz_model_2_run (struct growth_hiz_data * data)
Definition at line 112 of file ccl_test_growth_hiz.c.
References compare_growth_hiz().
{
   int model = 1;
   compare_growth_hiz(model, data);
 }
void __ctest_growth_hiz_model_3_run (struct growth_hiz_data * data)
Definition at line 117 of file ccl_test_growth_hiz.c.
References compare_growth_hiz().
{
   int model = 2;
   compare_growth_hiz(model, data);
 }
static void compare_growth_hiz (int model, struct growth_hiz_data * data) static
Definition at line 82 of file ccl_test_growth_hiz.c.
References growth_hiz_data::A_s, ASSERT_DBL_NEAR_TOL, ASSERT_NOT_NULL, ccl_cosmology_create(), ccl_cosmology_free(), ccl_growth_factor_unnorm(), ccl_parameters_create(), cl_cmbl_bm::cosmo, default_config, growth_hiz_data::gf, GROWTH_HIZ_TOLERANCE, growth_hiz_data::h, growth_hiz_data::mnu, growth_hiz_data::mnu_type, growth_hiz_data::n_s, growth_hiz_data::Neff, growth_hiz_data::Omega_b, growth_hiz_data::Omega_c, ccl_parameters::Omega_g, growth_hiz_data::Omega_k, ccl_parameters::Omega_k, ccl_parameters::Omega_l, ccl_parameters::Omega_m, halomod_bm::params, ccl_cosmology::status_message, growth_hiz_data::w_0, growth_hiz_data::w_a, and growth_hiz_data::z.
Referenced by __ctest_growth_hiz_model_1_run(), __ctest_growth_hiz_model_2_run(), and __ctest_growth_hiz_model_3_run().
 {
   int status=0;
   // Make the parameter set from the input data
   // Values of some parameters depend on the model index
   ccl_parameters params = ccl_parameters_create(data->Omega_c, data->Omega_b, data->Omega_k[model], data->Neff, data->mnu, data->mnu_type, data->w_0[model], data->w_a[model], data->h, data->A_s, data->n_s,-1,-1,-1,-1,NULL,NULL, &status);
   params.Omega_g=0; //enforce no radiation
   params.Omega_l = 1.-params.Omega_m-params.Omega_k; //reomcpute Omega_l without radiation
   // Make a cosmology object from the parameters with the default configuration
   ccl_cosmology * cosmo = ccl_cosmology_create(params, default_config);
   ASSERT_NOT_NULL(cosmo);
   // Compare to benchmark data
   for (int j=0; j<7; j++) {
     double a = 1/(1.+data->z[j]);
     double gf_ij=ccl_growth_factor_unnorm(cosmo,a, &status);
     if (status) printf("%s\n",cosmo->status_message);
     double absolute_tolerance = GROWTH_HIZ_TOLERANCE*data->gf[model][j];
     if (fabs(absolute_tolerance)<1e-12) absolute_tolerance = 1e-12;
     ASSERT_DBL_NEAR_TOL(data->gf[model][j], gf_ij, absolute_tolerance);
   }
   ccl_cosmology_free(cosmo);
 }
static void read_growth_hiz_test_file (double z[7], double gf[3][7]) static
Definition at line 29 of file ccl_test_growth_hiz.c.
References ASSERT_EQUAL, ASSERT_NOT_NULL, and Catch::Matchers::Vector::Detail::count().
Referenced by __attribute__().
 {
   //Growth is normalized to ~a at early times
   FILE * f = fopen("./tests/benchmark/growth_hiz_model1-3.txt", "r");
   ASSERT_NOT_NULL(f);
   // Ignore header line
   char str[1024];
   char* rtn;
   rtn = fgets(str, 1024, f);
     // File is fixed format - five rows and six columns
   for (int i=0; i<7; i++) {
     int count = fscanf(f, "%le %le %le %le\n", &z[i],
                &gf[0][i], &gf[1][i], &gf[2][i]);
         // Check that all the stuff in the benchmark is there
     ASSERT_EQUAL(4, count);
   }
   fclose(f);
 }
Variable Documentation
static struct growth_hiz_data __ctest_growth_hiz_data static
Definition at line 107 of file ccl_test_growth_hiz.c.