Fast Methods for Cosmological Simulations: src/3party/CCL/tests/ccl_test_emu_nu.c File Reference
ccl_test_emu_nu.c File Reference
#include "ccl.h"
#include "ccl_neutrinos.h"
#include "ctest.h"
#include <stdio.h>
#include <math.h>
Classes
struct emu_nu_data
Macros
#define EMU_TOLERANCE 3.0E-2
Functions
void __attribute__ ((weak))
static int linecount (FILE *f)
static void compare_emu_nu (int i_model, struct emu_nu_data *data)
void __ctest_emu_nu_model_1_run (struct emu_nu_data *data)
void __ctest_emu_nu_model_2_run (struct emu_nu_data *data)
void __ctest_emu_nu_model_3_run (struct emu_nu_data *data)
void __ctest_emu_nu_model_4_run (struct emu_nu_data *data)
Variables
static struct emu_nu_data __ctest_emu_nu_data
Macro Definition Documentation
#define EMU_TOLERANCE 3.0E-2
Definition at line 19 of file ccl_test_emu_nu.c.
Referenced by compare_emu_nu().
Function Documentation
void __attribute__ ((weak))
Definition at line 36 of file ccl_test_emu_nu.c.
References ccl_mnu_list, ccl_nu_equal, ccl_nu_masses(), ccl_test_distances::h, ccl_test_distances::n_s, ccl_test_distances::Omega_b, ccl_test_distances::Omega_c, halomod_bm::params, and ccl_test_power::sigma8.
                     {
   data->Neff = 3.04;
   data->mnu_type = ccl_mnu_list;
   double *sigma8;
   double *Omega_c;
   double *Omega_b;
   double *Omega_nu;
   double *n_s;
   double *h;
   double *w_0;
   double *w_a;
   double *Mnu_out;
   int status=0;
   char fname[256],str[1024];
   char* rtn;
   FILE *f;
   int i;
   ccl_parameters * params;
   sigma8=malloc(4*sizeof(double));
   Omega_c=malloc(4*sizeof(double));
   Omega_b=malloc(4*sizeof(double));
   n_s=malloc(4*sizeof(double));
   h=malloc(4*sizeof(double));
   w_0=malloc(4*sizeof(double));
   w_a=malloc(4*sizeof(double));
   Omega_nu=malloc(4*sizeof(double));
   // Omeganuh2_to_mnu will output a pointer to an array of 3 neutrino masses.
   Mnu_out=malloc(3*sizeof(double));
   //Each line of this file corresponds to the cosmological parameters for
   //cosmologies {38,39,40,42} of the emulator set. Notice that Omega_i
   //are big Omegas and not little omegas (Omega_i*h**2=omega_i)
   sprintf(fname,"./tests/benchmark/emu_nu_cosmologies.txt");
   f=fopen(fname,"r");
   if(f==NULL) {
     fprintf(stderr,"Error opening file %s\n",fname);
     exit(1);
   }
   double tmp;
   int omnustatus=0;
   for(int i=0;i<4;i++) {
     status=fscanf(f,"%le %le %le %le %le %le %le %le\n",&Omega_c[i],&Omega_b[i],&h[i],&sigma8[i],&n_s[i],&w_0[i],&w_a[i],&Omega_nu[i]);
     if(status!=8) {
       fprintf(stderr,"Error reading file %s, line %d\n",fname,i);
       exit(1);
     }
     data->w_0[i] = w_0[i];
     data->w_a[i] = w_a[i];
     data->h[i] = h[i];
     data->sigma8[i] = sigma8[i];
     data->Omega_c[i] = Omega_c[i];
     data->Omega_b[i] = Omega_b[i];
     data->n_s[i] = n_s[i];
     // Number of neutrino species is fixed to 3
     Mnu_out = ccl_nu_masses(Omega_nu[i]*h[i]*h[i], ccl_nu_equal, 2.725, &omnustatus);
     /*if (omnustatus){
       printf("%s\n",cosmo->status_message);
       exit(1);
       }*/
     data->mnu[i]=Mnu_out;
   }
   fclose(f);
 }
void __ctest_emu_nu_model_1_run (struct emu_nu_data * data)
Definition at line 177 of file ccl_test_emu_nu.c.
References compare_emu_nu().
{
   int model=1;
   compare_emu_nu(model,data);
 }
void __ctest_emu_nu_model_2_run (struct emu_nu_data * data)
Definition at line 183 of file ccl_test_emu_nu.c.
References compare_emu_nu().
{
   int model=2;
   compare_emu_nu(model,data);
   }
void __ctest_emu_nu_model_3_run (struct emu_nu_data * data)
Definition at line 188 of file ccl_test_emu_nu.c.
References compare_emu_nu().
{
   int model=3;
   compare_emu_nu(model,data);
 }
void __ctest_emu_nu_model_4_run (struct emu_nu_data * data)
Definition at line 193 of file ccl_test_emu_nu.c.
References compare_emu_nu().
{
   int model=4;
   compare_emu_nu(model,data);
   }
static void compare_emu_nu (int i_model, struct emu_nu_data * data) static
Definition at line 118 of file ccl_test_emu_nu.c.
References ASSERT_DBL_NEAR_TOL, ASSERT_NOT_NULL, ccl_cosmology_create(), ccl_cosmology_free(), ccl_emu, ccl_emulator, ccl_nonlin_matter_power(), ccl_parameters_create(), cl_cmbl_bm::cosmo, default_config, EMU_TOLERANCE, emu_nu_data::h, linecount(), ccl_configuration::matter_power_spectrum_method, emu_nu_data::mnu, emu_nu_data::mnu_type, emu_nu_data::n_s, emu_nu_data::Neff, emu_nu_data::Omega_b, emu_nu_data::Omega_c, ccl_parameters::Omega_g, ccl_parameters::Omega_l, halomod_bm::params, emu_nu_data::sigma8, ccl_cosmology::status_message, ccl_configuration::transfer_function_method, emu_nu_data::w_0, emu_nu_data::w_a, and z.
Referenced by __ctest_emu_nu_model_1_run(), __ctest_emu_nu_model_2_run(), __ctest_emu_nu_model_3_run(), and __ctest_emu_nu_model_4_run().
 {
   int nk,i,j;
   int status=0;
   char fname[256],str[1024];
   char* rtn;
   FILE *f;
   int i_model_vec[4]={38,39,40,42}; //The emulator cosmologies we can compare to
   ccl_configuration config = default_config;
   config.transfer_function_method = ccl_emulator;
   config.matter_power_spectrum_method = ccl_emu;
   //None of the current cosmologies being checked include neutrinos
   ccl_parameters params = ccl_parameters_create(data->Omega_c[i_model-1],data->Omega_b[i_model-1],0.0,data->Neff, data->mnu[i_model-1], data->mnu_type, data->w_0[i_model-1],data->w_a[i_model-1],data->h[i_model-1],data->sigma8[i_model-1],data->n_s[i_model-1],-1,-1,-1,-1,NULL,NULL, &status);
   params.Omega_l=params.Omega_l+params.Omega_g;
   params.Omega_g=0;
   ccl_cosmology * cosmo = ccl_cosmology_create(params, config);
   ASSERT_NOT_NULL(cosmo);
   //These files contain the smoothed power spectra with neutrinos
   //These are obtained as follows:
   // (1) Find the z=0 P(k) corresponding to M038. This would be column 304 of the
   //     'yalt...' file (with column numbering starting in 1).
   // (2) This column has log10(Delta_cb^2/k^1.5), so convert accordingly to Delta_cb^2.
   // (3) Take the power spectrum in the file ‘pk_lin...' for M038 (second column for P(k) in Mpc^3)
   //     and convert to Delta_nu^2 by multiplying by k^3/(2pi^2).
   // (4) Add to obtain Delta_tot=(sqrt(Delta_nu)+sqrt(Delta_cb))^2.
   // (5) Convert back to P(k)
   sprintf(fname,"./tests/benchmark/emu_nu_smooth_pk_M%d.txt",i_model_vec[i_model-1]);
   f=fopen(fname,"r");
   if(f==NULL) {
     fprintf(stderr,"Error opening file %s\n",fname);
     exit(1);
   }
   nk=linecount(f)-1; rewind(f);
   double k=0.,pk_bench=0.,pk_ccl,err;
   double z=0.; //Other redshift checks are possible but not currently implemented
   int stat=0;
   for(i=0;i<nk;i++) {
     stat=fscanf(f,"%le %le\n",&k, &pk_bench);
     if(stat!=2) {
       fprintf(stderr,"Error reading file %s, line %d\n",fname,i);
       exit(1);
     }
     pk_ccl=ccl_nonlin_matter_power(cosmo,k,1./(1+z),&status);
     if (status) printf("%s\n",cosmo->status_message);
     err=fabs(pk_ccl/pk_bench-1);
     //printf("%le %le %le %le\n",k,pk_ccl,pk_bench,err);
     ASSERT_DBL_NEAR_TOL(err,0.,EMU_TOLERANCE);
   }
   fclose(f);
   ccl_cosmology_free(cosmo);
 }
static int linecount (FILE * f) static
Definition at line 106 of file ccl_test_emu_nu.c.
Referenced by compare_emu_nu().
 {
   // Counts #lines from file
   int i0=0;
   char ch[1000];
   while((fgets(ch,sizeof(ch),f))!=NULL) {
     i0++;
   }
   return i0;
 }
Variable Documentation
static struct emu_nu_data __ctest_emu_nu_data static
Definition at line 177 of file ccl_test_emu_nu.c.