Fast Methods for Cosmological Simulations: src/3party/CCL/src/ccl_redshifts.c File Reference
ccl_redshifts.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <gsl/gsl_integration.h>
#include <gsl/gsl_spline.h>
#include <gsl/gsl_errno.h>
#include "ccl.h"
#include "ccl_params.h"
#include "ccl_redshifts.h"
Classes
struct pz_params
struct norm_params
Functions
pz_info * ccl_create_photoz_info (void *params, double(*pz_func)(double, double, void *, int *))
static double ccl_photoz (double z_ph, void *params)
double gaussian_pz (double z_ph, double z_s, void *params, int *status)
pz_info * ccl_create_gaussian_photoz_info (double sigma_z0)
void ccl_free_photoz_info (pz_info *my_photoz_info)
dNdz_info * ccl_create_dNdz_info (void *params, double(*dNdz_func)(double, void *, int *))
double dNdz_smail (double z, void *params, int *status)
dNdz_info * ccl_create_Smail_dNdz_info (double alpha, double beta, double z0)
static double ccl_dNdz (double z, dNdz_info *params, int *status)
void ccl_free_dNdz_info (dNdz_info *my_dNdz_info)
static double ccl_norm_integrand (double z, void *params)
void ccl_dNdz_tomog (double z, double bin_zmin, double bin_zmax, pz_info *photo_info, dNdz_info *dN_info, double *tomoout, int *status)
Function Documentation
dNdz_info* ccl_create_dNdz_info (void * params, double(*)(double, void *, int *) dNdz_func)
This function creates a structure amalgamating the information on an analytic true dNdz, plus some parameters.
Parameters
params parameters for the analytic dNdz form
dNdz_func dNdz function
Returns
a structure with the dNdz and parameters
Definition at line 94 of file ccl_redshifts.c.
References halomod_bm::params, and dNdz_info::your_dN_params.
Referenced by main().
 {
   dNdz_info * this_info = malloc(sizeof(dNdz_info));
   this_info ->your_dN_params = params;
   this_info -> your_dN_func = dNdz_func;
   return this_info;
 }
pz_info* ccl_create_gaussian_photoz_info (double sigma_z0)
This function creates a structure containing the photo-z model for the built-in Gaussian photo-z pdf.
Parameters
sigma_z0 The photo-z uncertainty at z=0. The photo-z uncertainty is assumed to scale like (1 + z).
Returns
a structure with the built-in Gaussian P(z) and parameters
Definition at line 67 of file ccl_redshifts.c.
References gaussian_pz(), pz_info::your_pz_func, and pz_info::your_pz_params.
Referenced by main().
{
     // Allocate memory so that this value persists
     double* sigma_z0_copy = malloc(sizeof(double));
     *sigma_z0_copy = sigma_z0;
     // Construct pz_info struct
     pz_info * this_info = malloc(sizeof(pz_info));
     this_info->your_pz_params = sigma_z0_copy;
     this_info->your_pz_func = &gaussian_pz;
     return this_info;
 }
pz_info* ccl_create_photoz_info (void * params, double(*)(double, double, void *, int *) pz_func)
This function creates a structure amalgamating the information on the photo-z model, P(z) plus some parameters.
Parameters
params parameters for the P(z) function
pz_func P(z) function
Returns
a structure with the P(z) and parameters
Definition at line 21 of file ccl_redshifts.c.
References halomod_bm::params, and pz_info::your_pz_params.
Referenced by main().
 {
   pz_info * this_info = malloc(sizeof(pz_info));
   this_info ->your_pz_params = params;
   this_info -> your_pz_func = pz_func;
   return this_info;
 }
dNdz_info* ccl_create_Smail_dNdz_info (double alpha, double beta, double z0)
This function creates a structure containing the true dNdz for the built-in Smail-type analytic form: dNdz ~ z^alpha exp(- (z/z0)^beta)
Parameters
alpha
z0
beta
Returns
a structure with the built-in Smail-type dNdz and parameters
Definition at line 120 of file ccl_redshifts.c.
References smail_params::alpha, beta, smail_params::beta, dNdz_smail(), dNdz_info::your_dN_func, dNdz_info::your_dN_params, and smail_params::z0.
Referenced by main().
{
     // Allocate a smail type parmaeter structure
     smail_params * smail_par = malloc(sizeof(smail_params));
     smail_par->alpha = alpha;
     smail_par->beta = beta;
     smail_par->z0 = z0;
     // Construct dNdz_info struct
     dNdz_info * this_info = malloc(sizeof(dNdz_info));
     this_info->your_dN_params = smail_par;
     this_info->your_dN_func = &dNdz_smail;
     return this_info;
 }
static double ccl_dNdz (double z, dNdz_info * params, int * status) static
Definition at line 142 of file ccl_redshifts.c.
References pz_params::status, dNdz_info::your_dN_func, dNdz_info::your_dN_params, and z.
Referenced by ccl_dNdz_tomog(), and ccl_norm_integrand().
 {
   return (params->your_dN_func)(z, params->your_dN_params, status);
 }
void ccl_dNdz_tomog (double z, double bin_zmin, double bin_zmax, pz_info * photo_info, dNdz_info * dN_info, double * tomoout, int * status)
Return dNdz in a particular tomographic bin, convolved with a photo-z model (defined by the user), and normalized.
Parameters
z redshift
dNdz_type the choice of dN/dz from Chang+
bin_zmin the minimum redshift of the tomorgraphic bin
bin_zmax the maximum redshift of the tomographic bin
photo_info the P(z) info struct
tomoout the output dN/dz
status Status flag. 0 if there are no errors, nonzero otherwise.
Returns
void
Definition at line 222 of file ccl_redshifts.c.
References norm_params::bin_zmax_, norm_params::bin_zmin_, ccl_cosmology_read_config(), ccl_dNdz(), CCL_ERROR_INTEG, CCL_ERROR_MISSING_CONFIG_FILE, ccl_gsl, ccl_norm_integrand(), ccl_photoz(), ccl_raise_exception(), ccl_raise_gsl_warning(), ccl_splines, norm_params::dN_information, ccl_gsl_params::INTEGRATION_DNDZ_EPSREL, ccl_gsl_params::N_ITERATION, pz_params::pz_information, norm_params::pz_information, pz_params::status, norm_params::status, z, Z_MAX_SOURCES, Z_MIN_SOURCES, and pz_params::z_true.
Referenced by main().
 {
   // This uses equation 33 of Joachimi & Schneider 2009, arxiv:0905.0393
   double numerator_integrand=0, denom_integrand=0, dNdz_t;
   // This struct contains a spec redshift and a pointer to a photoz information struct.
   struct pz_params pz_p_val; //parameters for the integral over the photoz's
   struct norm_params norm_p_val;
   // Check whether ccl_splines and ccl_gsl exist; exit gracefully if they
   // can't be loaded
   if(ccl_splines==NULL || ccl_gsl==NULL) ccl_cosmology_read_config();
   if(ccl_splines==NULL || ccl_gsl==NULL) {
     ccl_raise_exception(CCL_ERROR_MISSING_CONFIG_FILE,
                         "ccl_redshifts.c: Failed to read config file.");
     *status = CCL_ERROR_MISSING_CONFIG_FILE;
     return;
   }
   // Set up the parameters to pass to the normalising integral (of type struct norm_params
   norm_p_val.bin_zmin_=bin_zmin;
   norm_p_val.bin_zmax_=bin_zmax;
   norm_p_val.pz_information = photo_info;
   norm_p_val.status = status;
   norm_p_val.dN_information = dN_info;
   dNdz_t = ccl_dNdz(z, dN_info, status);
   // Set up the parameters for the integral over the photo z function in the numerator (of type struct pz_params)
   pz_p_val.z_true = z;
   pz_p_val.status = status;
   pz_p_val.pz_information = photo_info; // pointer to user information
   // Integrate over the assumed pdf of photo-z wrt true-z in this bin (this goes in the numerator of the result):
   gsl_integration_cquad_workspace * workspace = gsl_integration_cquad_workspace_alloc(ccl_gsl->N_ITERATION);
   gsl_function F;
   F.function = ccl_photoz;
   F.params = &pz_p_val;
   int gslstatus = gsl_integration_cquad(&F, bin_zmin, bin_zmax, 0.0,ccl_gsl->INTEGRATION_DNDZ_EPSREL,workspace,&numerator_integrand, NULL, NULL);
   if(gslstatus != GSL_SUCCESS) {
     ccl_raise_gsl_warning(gslstatus, "ccl_redshifts.c: ccl_norm_integrand():");
     *status |= gslstatus;
   }
   gsl_integration_cquad_workspace_free(workspace);
   // Now get the denominator, which normalizes dNdz over the photometric bin
   workspace = gsl_integration_cquad_workspace_alloc(ccl_gsl->N_ITERATION);
   F.function = ccl_norm_integrand;
   F.params = &norm_p_val;
   gslstatus = gsl_integration_cquad(&F, Z_MIN_SOURCES, Z_MAX_SOURCES, 0.0,ccl_gsl->INTEGRATION_DNDZ_EPSREL,workspace,&denom_integrand, NULL, NULL);
   if(gslstatus != GSL_SUCCESS) {
     ccl_raise_gsl_warning(gslstatus, "ccl_redshifts.c: ccl_norm_integrand():");
     *status |= gslstatus;
   }
   gsl_integration_cquad_workspace_free(workspace);
   if (*status) {
     *status = CCL_ERROR_INTEG;
     return;
   }
   *tomoout = dNdz_t * numerator_integrand / denom_integrand;
 }
void ccl_free_dNdz_info (dNdz_info * dN_info)
Free memory holding the structure containing dNdz information.
Parameters
dN_info that holds user-defined dNdz and parameters
Returns
void
Definition at line 152 of file ccl_redshifts.c.
Referenced by main().
 {
   free(my_dNdz_info);
 }
void ccl_free_photoz_info (pz_info * my_photoz_info)
Free memory holding the structure containing user-input photoz information.
Parameters
my_photoz_info that holds user-defined P(z) and parameters
Returns
void
Definition at line 84 of file ccl_redshifts.c.
Referenced by main().
 {
   free(my_photoz_info);
 }
static double ccl_norm_integrand (double z, void * params) static
Definition at line 173 of file ccl_redshifts.c.
References norm_params::bin_zmax_, norm_params::bin_zmin_, ccl_cosmology_read_config(), ccl_dNdz(), CCL_ERROR_MISSING_CONFIG_FILE, ccl_gsl, ccl_photoz(), ccl_raise_exception(), ccl_raise_gsl_warning(), ccl_splines, norm_params::dN_information, ccl_gsl_params::INTEGRATION_DNDZ_EPSREL, ccl_gsl_params::N_ITERATION, p, pz_params::pz_information, pz_params::status, norm_params::status, z, and pz_params::z_true.
Referenced by ccl_dNdz_tomog().
 {
   // This is a struct that contains a true redshift and a pointer to the information about the photo_z model
   struct pz_params pz_val_p; // parameters for the photoz pdf wrt true-z
   double pz_int=0; // pointer to the value of the integral over the photoz model
   struct norm_params *p = (struct norm_params *) params; // parameters of the current function (because of form required for gsl integration)
   double z_min = p->bin_zmin_;
   double z_max = p->bin_zmax_;
   // Check whether ccl_splines and ccl_gsl exist; exit gracefully if they
   // can't be loaded
   if(ccl_splines==NULL || ccl_gsl==NULL) ccl_cosmology_read_config();
   if(ccl_splines==NULL || ccl_gsl==NULL) {
     ccl_raise_exception(CCL_ERROR_MISSING_CONFIG_FILE,
                         "ccl_redshift.c: Failed to read config file.");
     return NAN;
   }
   // Set up parameters for the pz part of the intermediary integral.
   pz_val_p.z_true = z;
   pz_val_p.status = p->status;
   pz_val_p.pz_information = p-> pz_information;
   // Do the intermediary integral over the model relating  photo-z to true-z
   gsl_integration_cquad_workspace * workspace = gsl_integration_cquad_workspace_alloc(ccl_gsl->N_ITERATION);
   gsl_function F;
   F.function = ccl_photoz;
   F.params = &pz_val_p;
   int gslstatus = gsl_integration_cquad(&F, z_min, z_max, 0.0,ccl_gsl->INTEGRATION_DNDZ_EPSREL,workspace,&pz_int, NULL, NULL);
   if(gslstatus != GSL_SUCCESS) {
     ccl_raise_gsl_warning(gslstatus, "ccl_redshifts.c: ccl_specs_norm_integrand():");
     *p->status|= gslstatus;
   }
   gsl_integration_cquad_workspace_free(workspace);
   return ccl_dNdz(z, p->dN_information, p->status) * pz_int ;
 }
static double ccl_photoz (double z_ph, void * params) static
Definition at line 44 of file ccl_redshifts.c.
References p, pz_params::pz_information, pz_params::status, pz_info::your_pz_func, pz_info::your_pz_params, and pz_params::z_true.
Referenced by ccl_dNdz_tomog(), and ccl_norm_integrand().
 {
   struct pz_params * p = (struct pz_params *) params;
   pz_info * user_stuff = (pz_info*) p->pz_information;
   double z_s = p->z_true;
   return (user_stuff->your_pz_func)(z_ph, z_s, user_stuff->your_pz_params,p->status);
 }
double dNdz_smail (double z, void * params, int * status)
Definition at line 107 of file ccl_redshifts.c.
References beta, and pow().
Referenced by ccl_create_Smail_dNdz_info().
{
     double alpha = ((smail_params*) params)->alpha;
     double beta = ((smail_params*) params)->beta;
     double z0 = ((smail_params*) params)->z0;
     return pow(z, alpha) * exp(- pow(z/z0, beta) );
 }
double gaussian_pz (double z_ph, double z_s, void * params, int * status)
Definition at line 54 of file ccl_redshifts.c.
References M_PI, and sqrt().
Referenced by ccl_create_gaussian_photoz_info().
{
     double sigma_z0 = *((double*) params);
     double sigma_z = sigma_z0 * (1. + z_s);
     return exp(- (z_ph - z_s)*(z_ph - z_s) / (2.*sigma_z*sigma_z)) \
          / (sqrt(2.*M_PI) *sigma_z);
 }