Fast Methods for Cosmological Simulations: src/3party/CCL/tests/ccl_test_distances_class_allz.c File Reference
ccl_test_distances_class_allz.c File Reference
#include "ccl.h"
#include "ctest.h"
#include <stdio.h>
#include <math.h>
Classes
struct distances_class_data
Macros
#define DISTANCES_TOLERANCE 1.0e-6
#define N_MODEL 10
#define N_Z 10
Functions
static void read_benchmark_file (const char *filename, double z[10], double benchmark[10][10])
void __attribute__ ((weak))
static void compare_distances (int model, struct distances_class_data *data)
void __ctest_distances_class_model_1_run (struct distances_class_data *data)
void __ctest_distances_class_model_2_run (struct distances_class_data *data)
void __ctest_distances_class_model_3_run (struct distances_class_data *data)
void __ctest_distances_class_model_4_run (struct distances_class_data *data)
void __ctest_distances_class_model_5_run (struct distances_class_data *data)
void __ctest_distances_class_model_7_run (struct distances_class_data *data)
void __ctest_distances_class_model_8_run (struct distances_class_data *data)
void __ctest_distances_class_model_9_run (struct distances_class_data *data)
void __ctest_distances_class_model_10_run (struct distances_class_data *data)
void __ctest_distances_class_model_11_run (struct distances_class_data *data)
Variables
static struct distances_class_data __ctest_distances_class_data
Macro Definition Documentation
#define DISTANCES_TOLERANCE 1.0e-6
Definition at line 7 of file ccl_test_distances_class_allz.c.
Referenced by compare_distances().
#define N_MODEL 10
Definition at line 10 of file ccl_test_distances_class_allz.c.
Referenced by __attribute__().
#define N_Z 10
Definition at line 12 of file ccl_test_distances_class_allz.c.
Referenced by compare_distances(), and read_benchmark_file().
Function Documentation
void __attribute__ ((weak))
Definition at line 66 of file ccl_test_distances_class_allz.c.
References ccl_mnu_list, ccl_test_distances::mnu, N_MODEL, ccl_test_distances::Neff, and read_benchmark_file().
{
   // Values that are the same for all 5 models
   data->Omega_c = 0.25;
   data->Omega_b = 0.05;
   data->h = 0.7;
   data->A_s = 2.1e-9;
   data->n_s = 0.96;
   data->mnu_type = ccl_mnu_list;
   // Values that are different for the different models
   double Omega_k[N_MODEL] = {  0.0, 0.0, 0.0, 0.05, -0.05,
                                0.0, 0.0, 0.0, 0.05, -0.05 };
   double w_0[N_MODEL]     = { -1.0, -0.9, -0.9, -0.9, -0.9,
                               -1.0, -0.9, -0.9, -0.9, -0.9  };
   double w_a[N_MODEL]     = {  0.0,  0.0,  0.1,  0.1,  0.1,
                                0.0,  0.0,  0.1,  0.1,  0.1  };
   double mnu[N_MODEL][3]    = { {0.0,  0.0,  0.0},
                               {0.0,  0.0,  0.0},
                               {0.0,  0.0,  0.0},
                               {0.0,  0.0,  0.0},
                               {0.0,  0.0,  0.0},
                               {0.04, 0.0,  0.0},
                               {0.05, 0.01, 0.0},
                               {0.03, 0.02, 0.04},
                               {0.05, 0.0,  0.0},
                               {0.03, 0.02, 0.0} };
   double Neff[N_MODEL]   = {3.046, 3.046, 3.046, 3.046, 3.046,
                             3.013, 3.026, 3.040, 3.013, 3.026};
   // Fill in the values from these constant arrays.
   for(int i=0; i<N_MODEL; i++) {
     data->Omega_k[i] = Omega_k[i];
     data->w_0[i]     = w_0[i];
     data->w_a[i]     = w_a[i];
     data->Neff[i]    = Neff[i];
     for(int j=0; j<3; j++) {
       data->mnu[i][j]     = mnu[i][j];
     }
   }
   // The file of benchmark data.
   read_benchmark_file("./tests/benchmark/chi_class_allz.txt", data->z_chi, data->chi_benchmark);
   read_benchmark_file("./tests/benchmark/dm_class_allz.txt", data->z_dm, data->dm_benchmark);
 }
void __ctest_distances_class_model_10_run (struct distances_class_data * data)
Definition at line 199 of file ccl_test_distances_class_allz.c.
References compare_distances().
{
   int model = 8;
   compare_distances(model, data);
 }
void __ctest_distances_class_model_11_run (struct distances_class_data * data)
Definition at line 204 of file ccl_test_distances_class_allz.c.
References compare_distances().
{
   int model = 9;
   compare_distances(model, data);
 }
void __ctest_distances_class_model_1_run (struct distances_class_data * data)
Definition at line 159 of file ccl_test_distances_class_allz.c.
References compare_distances().
{
   int model = 0;
   compare_distances(model, data);
 }
void __ctest_distances_class_model_2_run (struct distances_class_data * data)
Definition at line 164 of file ccl_test_distances_class_allz.c.
References compare_distances().
{
   int model = 1;
   compare_distances(model, data);
 }
void __ctest_distances_class_model_3_run (struct distances_class_data * data)
Definition at line 169 of file ccl_test_distances_class_allz.c.
References compare_distances().
{
   int model = 2;
   compare_distances(model, data);
 }
void __ctest_distances_class_model_4_run (struct distances_class_data * data)
Definition at line 174 of file ccl_test_distances_class_allz.c.
References compare_distances().
{
   int model = 3;
   compare_distances(model, data);
 }
void __ctest_distances_class_model_5_run (struct distances_class_data * data)
Definition at line 179 of file ccl_test_distances_class_allz.c.
References compare_distances().
{
   int model = 4;
   compare_distances(model, data);
 }
void __ctest_distances_class_model_7_run (struct distances_class_data * data)
Definition at line 184 of file ccl_test_distances_class_allz.c.
References compare_distances().
{
   int model = 5;
   compare_distances(model, data);
 }
void __ctest_distances_class_model_8_run (struct distances_class_data * data)
Definition at line 189 of file ccl_test_distances_class_allz.c.
References compare_distances().
{
   int model = 6;
   compare_distances(model, data);
 }
void __ctest_distances_class_model_9_run (struct distances_class_data * data)
Definition at line 194 of file ccl_test_distances_class_allz.c.
References compare_distances().
{
   int model = 7;
   compare_distances(model, data);
 }
static void compare_distances (int model, struct distances_class_data * data) static
Definition at line 114 of file ccl_test_distances_class_allz.c.
References distances_class_data::A_s, ASSERT_DBL_NEAR_TOL, ASSERT_EQUAL, ASSERT_NOT_NULL, ccl_comoving_radial_distance(), ccl_cosmology_create(), ccl_cosmology_free(), ccl_distance_modulus(), ccl_parameters_create(), distances_class_data::chi_benchmark, cl_cmbl_bm::cosmo, default_config, DISTANCES_TOLERANCE, distances_class_data::dm_benchmark, distances_class_data::h, distances_class_data::mnu, distances_class_data::mnu_type, distances_class_data::n_s, N_Z, distances_class_data::Neff, distances_class_data::Omega_b, distances_class_data::Omega_c, distances_class_data::Omega_k, halomod_bm::params, ccl_cosmology::status_message, distances_class_data::w_0, distances_class_data::w_a, distances_class_data::z_chi, and distances_class_data::z_dm.
Referenced by __ctest_distances_class_model_10_run(), __ctest_distances_class_model_11_run(), __ctest_distances_class_model_1_run(), __ctest_distances_class_model_2_run(), __ctest_distances_class_model_3_run(), __ctest_distances_class_model_4_run(), __ctest_distances_class_model_5_run(), __ctest_distances_class_model_7_run(), __ctest_distances_class_model_8_run(), and __ctest_distances_class_model_9_run().
 {
   int status=0;
   // Make the parameter set from the input data
   // Values of some parameters depend on the model index
   // The arrays of massive neutrions are different lengths, so we need to have an if-statement here to deal with that.
   ccl_parameters params;
   params = ccl_parameters_create(data->Omega_c, data->Omega_b, data->Omega_k[model],
                                              data->Neff[model], data->mnu[model], data->mnu_type,
                                              data->w_0[model], data->w_a[model],
                                              data->h, data->A_s, data->n_s,
                                  -1,-1,-1,-1,NULL,NULL, &status);
   ASSERT_EQUAL(0, status);
   // Make a cosmology object from the parameters with the default configuration
   ccl_cosmology * cosmo = ccl_cosmology_create(params, default_config);
   ASSERT_NOT_NULL(cosmo);
   // Compare to benchmark data
   for(int i=0; i<N_Z; i++) {
     // Check comoving radial distance
     double a = 1/(1.+data->z_chi[i]);
     double chi_ccl = ccl_comoving_radial_distance(cosmo, a, &status);
     if(status) printf("%s\n",cosmo->status_message);
     double absolute_tolerance = DISTANCES_TOLERANCE*data->chi_benchmark[i][model];
     if (fabs(absolute_tolerance)<1e-12) absolute_tolerance = 1e-12;
     ASSERT_DBL_NEAR_TOL(data->chi_benchmark[i][model], chi_ccl, absolute_tolerance);
     // Check distance modulus
     a = 1/(1.+data->z_dm[i]);
     double dm_ccl = ccl_distance_modulus(cosmo, a, &status);
     if(status) printf("%s\n",cosmo->status_message);
     absolute_tolerance = DISTANCES_TOLERANCE*data->dm_benchmark[i][model];
     if (fabs(absolute_tolerance)<1e-12) absolute_tolerance = 1e-12;
     ASSERT_DBL_NEAR_TOL(data->dm_benchmark[i][model], dm_ccl, absolute_tolerance);
   }
   ccl_cosmology_free(cosmo);
 }
static void read_benchmark_file (const char * filename, double z[10], double benchmark[10][10]) static
Definition at line 36 of file ccl_test_distances_class_allz.c.
References ASSERT_EQUAL, ASSERT_NOT_NULL, Catch::Matchers::Vector::Detail::count(), N_Z, and z.
Referenced by __attribute__().
 {
   //Distances are in Mpc
   FILE * f = fopen(filename, "r");
   ASSERT_NOT_NULL(f);
   // Ignore header line
   fscanf(f, "%*[^\n]\n", NULL);
   double val;
   // Read the file
   for(int i_z=0; i_z<N_Z; i_z++) {
     for(int i_model=0; i_model<N_MODEL+1; i_model++) {
       int count = fscanf(f, "%le", &val);
       // Check that all the value was read successfully
       ASSERT_EQUAL(1, count);
       if(i_model == 0) {
         // The first column holds the redshift values
         z[i_z] = val;
       }
       else {
         benchmark[i_z][i_model-1] = val;
       }
     }
   }
   fclose(f);
 }
Variable Documentation
static struct distances_class_data __ctest_distances_class_data static
Definition at line 159 of file ccl_test_distances_class_allz.c.