Fast Methods for Cosmological Simulations: src/3party/CCL/tests/ccl_test_distances_cosmomad_lowz.c File Reference
ccl_test_distances_cosmomad_lowz.c File Reference
#include "ccl.h"
#include "ctest.h"
#include <stdio.h>
#include <math.h>
Classes
struct distances_cosmomad_lowz_data
Macros
#define DISTANCES_TOLERANCE 5.0e-7
#define DM_TOLERANCE 1.0E-3
Functions
static void read_chi_test_file (double z[6], double chi[5][6])
static void read_dm_test_file (double z[6], double dm[5][6])
void __attribute__ ((weak))
static void compare_distances (int model, struct distances_cosmomad_lowz_data *data)
void __ctest_distances_cosmomad_lowz_model_1_run (struct distances_cosmomad_lowz_data *data)
void __ctest_distances_cosmomad_lowz_model_2_run (struct distances_cosmomad_lowz_data *data)
void __ctest_distances_cosmomad_lowz_model_3_run (struct distances_cosmomad_lowz_data *data)
void __ctest_distances_cosmomad_lowz_model_4_run (struct distances_cosmomad_lowz_data *data)
void __ctest_distances_cosmomad_lowz_model_5_run (struct distances_cosmomad_lowz_data *data)
Variables
static struct distances_cosmomad_lowz_data __ctest_distances_cosmomad_lowz_data
Macro Definition Documentation
#define DISTANCES_TOLERANCE 5.0e-7
Definition at line 7 of file ccl_test_distances_cosmomad_lowz.c.
Referenced by compare_distances().
#define DM_TOLERANCE 1.0E-3
Definition at line 8 of file ccl_test_distances_cosmomad_lowz.c.
Referenced by compare_distances().
Function Documentation
void __attribute__ ((weak))
Definition at line 73 of file ccl_test_distances_cosmomad_lowz.c.
References ccl_mnu_sum, read_chi_test_file(), and read_dm_test_file().
{
   // Values that are the same for all 5 models
   data->Omega_c = 0.25;
   data->Omega_b = 0.05;
   data->h = 0.7;
   data->A_s = 2.1e-9;
   data->n_s = 0.96;
   data->Neff=0;
   double mnuval = 0.;
   data->mnu= &mnuval;
   data->mnu_type = ccl_mnu_sum;
   // Values that are different for the different models
   double Omega_v[5] = {  0.7,  0.7,  0.7,  0.65, 0.75 };
   double w_0[5]     = { -1.0, -0.9, -0.9, -0.9, -0.9  };
   double w_a[5]     = {  0.0,  0.0,  0.1,  0.1,  0.1  };
   // Fill in the values from these constant arrays.
   for (int i=0; i<5; i++) {
     data->Omega_v[i] = Omega_v[i];
     data->w_0[i]     = w_0[i];
     data->w_a[i]     = w_a[i];
     data->Omega_k[i] = 1.0 - data->Omega_c - data->Omega_b - data->Omega_v[i];
   }
   // The file of benchmark data.
   read_dm_test_file(data->z, data->dm);
   read_chi_test_file(data->z, data->chi);
 }
void __ctest_distances_cosmomad_lowz_model_1_run (struct distances_cosmomad_lowz_data * data)
Definition at line 143 of file ccl_test_distances_cosmomad_lowz.c.
References compare_distances().
{
   int model = 0;
   compare_distances(model, data);
 }
void __ctest_distances_cosmomad_lowz_model_2_run (struct distances_cosmomad_lowz_data * data)
Definition at line 148 of file ccl_test_distances_cosmomad_lowz.c.
References compare_distances().
{
   int model = 1;
   compare_distances(model, data);
 }
void __ctest_distances_cosmomad_lowz_model_3_run (struct distances_cosmomad_lowz_data * data)
Definition at line 153 of file ccl_test_distances_cosmomad_lowz.c.
References compare_distances().
{
   int model = 2;
   compare_distances(model, data);
 }
void __ctest_distances_cosmomad_lowz_model_4_run (struct distances_cosmomad_lowz_data * data)
Definition at line 158 of file ccl_test_distances_cosmomad_lowz.c.
References compare_distances().
{
   int model = 3;
   compare_distances(model, data);
 }
void __ctest_distances_cosmomad_lowz_model_5_run (struct distances_cosmomad_lowz_data * data)
Definition at line 163 of file ccl_test_distances_cosmomad_lowz.c.
References compare_distances().
{
   int model = 4;
   compare_distances(model, data);
 }
static void compare_distances (int model, struct distances_cosmomad_lowz_data * data) static
Definition at line 104 of file ccl_test_distances_cosmomad_lowz.c.
References distances_cosmomad_lowz_data::A_s, ASSERT_DBL_NEAR_TOL, ASSERT_NOT_NULL, ccl_comoving_radial_distance(), ccl_cosmology_create(), ccl_cosmology_free(), ccl_distance_modulus(), ccl_parameters_create(), distances_cosmomad_lowz_data::chi, cl_cmbl_bm::cosmo, default_config, DISTANCES_TOLERANCE, distances_cosmomad_lowz_data::dm, DM_TOLERANCE, distances_cosmomad_lowz_data::h, distances_cosmomad_lowz_data::mnu, distances_cosmomad_lowz_data::mnu_type, distances_cosmomad_lowz_data::n_s, distances_cosmomad_lowz_data::Neff, distances_cosmomad_lowz_data::Omega_b, distances_cosmomad_lowz_data::Omega_c, ccl_parameters::Omega_g, distances_cosmomad_lowz_data::Omega_k, ccl_parameters::Omega_k, ccl_parameters::Omega_l, ccl_parameters::Omega_m, halomod_bm::params, ccl_cosmology::status_message, distances_cosmomad_lowz_data::w_0, distances_cosmomad_lowz_data::w_a, and distances_cosmomad_lowz_data::z.
Referenced by __ctest_distances_cosmomad_lowz_model_1_run(), __ctest_distances_cosmomad_lowz_model_2_run(), __ctest_distances_cosmomad_lowz_model_3_run(), __ctest_distances_cosmomad_lowz_model_4_run(), and __ctest_distances_cosmomad_lowz_model_5_run().
 {
   int status=0;
   // Make the parameter set from the input data
   // Values of some parameters depend on the model index
   ccl_parameters params = ccl_parameters_create(data->Omega_c, data->Omega_b, data->Omega_k[model],
                         data->Neff, data->mnu, data->mnu_type,
                         data->w_0[model], data->w_a[model],
                         data->h, data->A_s, data->n_s,-1,-1,-1,-1,NULL,NULL, &status);
   params.Omega_g=0; //enforce no radiation
   params.Omega_l = 1.-params.Omega_m-params.Omega_k; //reomcpute Omega_l without radiation
   // Make a cosmology object from the parameters with the default configuration
   ccl_cosmology * cosmo = ccl_cosmology_create(params, default_config);
   ASSERT_NOT_NULL(cosmo);
   // Compare to benchmark data
   for (int j=0; j<6; j++) {
     double a = 1/(1.+data->z[j]);
     double chi_ij=ccl_comoving_radial_distance(cosmo,a, &status)*data->h;
     if (status) printf("%s\n",cosmo->status_message);
     double absolute_tolerance = DISTANCES_TOLERANCE*data->chi[model][j];
     if (fabs(absolute_tolerance)<1e-12) absolute_tolerance = 1e-12;
     ASSERT_DBL_NEAR_TOL(data->chi[model][j], chi_ij, absolute_tolerance);
     if(a!=1) {  //skip this test for a=1 since it will raise an error
         double dm_ij=ccl_distance_modulus(cosmo,a, &status);
         if (status) printf("%s\n",cosmo->status_message);
         //NOTE tolerances are different!
         absolute_tolerance = DM_TOLERANCE*data->dm[model][j];
         if (fabs(absolute_tolerance)<1e-4) absolute_tolerance = 1e-4;
         ASSERT_DBL_NEAR_TOL(data->dm[model][j], dm_ij, absolute_tolerance);
     }
   }
   ccl_cosmology_free(cosmo);
 }
static void read_chi_test_file (double z[6], double chi[5][6]) static
Definition at line 31 of file ccl_test_distances_cosmomad_lowz.c.
References ASSERT_EQUAL, ASSERT_NOT_NULL, and Catch::Matchers::Vector::Detail::count().
Referenced by __attribute__().
 {
   //Distances are in Mpc/h
   FILE * f = fopen("./tests/benchmark/chi_model1-5.txt", "r");
   ASSERT_NOT_NULL(f);
   // Ignore header line
   char str[1024];
   fgets(str, 1024, f);
   // File is fixed format - five rows and six columns
   for (int i=0; i<6; i++) {
     int count = fscanf(f, "%le %le %le %le %le %le\n", &z[i],
                &chi[0][i], &chi[1][i], &chi[2][i], &chi[3][i], &chi[4][i]);
     // Check that all the stuff in the benchmark is there
     ASSERT_EQUAL(6, count);
   }
   fclose(f);
 }
static void read_dm_test_file (double z[6], double dm[5][6]) static
Definition at line 51 of file ccl_test_distances_cosmomad_lowz.c.
References ASSERT_EQUAL, ASSERT_NOT_NULL, and Catch::Matchers::Vector::Detail::count().
Referenced by __attribute__().
 {
   //Distances are in Mpc/h
   FILE * f = fopen("./tests/benchmark/dm_model1-5.txt", "r");
   ASSERT_NOT_NULL(f);
   // Ignore header line
   char str[1024];
   fgets(str, 1024, f);
   // File is fixed format - five rows and six columns
   for (int i=0; i<6; i++) {
     int count = fscanf(f, "%le %le %le %le %le %le\n", &z[i],
                        &dm[0][i], &dm[1][i], &dm[2][i], &dm[3][i], &dm[4][i]);
     // Check that all the stuff in the benchmark is there
     ASSERT_EQUAL(6, count);
   }
   fclose(f);
 }
Variable Documentation
static struct distances_cosmomad_lowz_data __ctest_distances_cosmomad_lowz_data static
Definition at line 143 of file ccl_test_distances_cosmomad_lowz.c.