Fast Methods for Cosmological Simulations: src/3party/CCL/src/ccl_core.c File Reference
ccl_core.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <math.h>
#include <string.h>
#include <gsl/gsl_errno.h>
#include <gsl/gsl_odeiv.h>
#include <gsl/gsl_spline.h>
#include <gsl/gsl_integration.h>
#include "ccl.h"
#include "ccl_params.h"
Macros
#define EXPAND_STR(s) STRING(s)
#define STRING(s) #s
#define MATCH(s, action) if (0 == strcmp(var_name, s)) { action ; continue;} do{} while(0)
#define WRITE_DOUBLE(name) fprintf(f, #name ": %le\n",params->name)
#define WRITE_INT(name) fprintf(f, #name ": %d\n",params->name)
#define READ_DOUBLE(name) double name; *status |= (0==fscanf(f, #name ": %le\n",&name));
#define READ_INT(name) int name; *status |= (0==fscanf(f, #name ": %d\n",&name))
Functions
void ccl_cosmology_read_config (void)
ccl_cosmology * ccl_cosmology_create (ccl_parameters params, ccl_configuration config)
void ccl_parameters_fill_initial (ccl_parameters *params, int *status)
ccl_parameters ccl_parameters_create (double Omega_c, double Omega_b, double Omega_k, double Neff, double *mnu, ccl_mnu_convention mnu_type, double w0, double wa, double h, double norm_pk, double n_s, double bcm_log10Mc, double bcm_etab, double bcm_ks, int nz_mgrowth, double *zarr_mgrowth, double *dfarr_mgrowth, int *status)
ccl_parameters ccl_parameters_create_flat_lcdm (double Omega_c, double Omega_b, double h, double norm_pk, double n_s, int *status)
void ccl_parameters_write_yaml (ccl_parameters *params, const char *filename, int *status)
ccl_parameters ccl_parameters_read_yaml (const char *filename, int *status)
void ccl_data_free (ccl_data *data)
void ccl_cosmology_set_status_message (ccl_cosmology *cosmo, const char *message,...)
void ccl_parameters_free (ccl_parameters *params)
void ccl_cosmology_free (ccl_cosmology *cosmo)
Variables
const ccl_configuration default_config = {ccl_boltzmann_class, ccl_halofit, ccl_nobaryons, ccl_tinker10, ccl_duffy2008, ccl_emu_strict}
const ccl_gsl_params default_gsl_params
ccl_spline_params * ccl_splines = ((void*)0)
ccl_gsl_params * ccl_gsl = ((void*)0)
Macro Definition Documentation
#define EXPAND_STR (s) STRING(s)
Definition at line 17 of file ccl_core.c.
Referenced by ccl_cosmology_read_config().
#define MATCH (s, action) if (0 == strcmp(var_name, s)) { action ; continue;} do{} while(0)
Referenced by ccl_cosmology_read_config().
#define READ_DOUBLE (name) double name; *status |= (0==fscanf(f, #name ": %le\n",&name));
Referenced by ccl_parameters_read_yaml().
#define READ_INT (name) int name; *status |= (0==fscanf(f, #name ": %d\n",&name))
Referenced by ccl_parameters_read_yaml().
#define STRING (s) #s
Definition at line 18 of file ccl_core.c.
#define WRITE_DOUBLE (name) fprintf(f, #name ": %le\n",params->name)
Referenced by ccl_parameters_write_yaml().
#define WRITE_INT (name) fprintf(f, #name ": %d\n",params->name)
Referenced by ccl_parameters_write_yaml().
Function Documentation
ccl_cosmology* ccl_cosmology_create (ccl_parameters params, ccl_configuration config)
Definition at line 173 of file ccl_core.c.
References ccl_data::accelerator, ccl_data::accelerator_achi, ccl_data::accelerator_d, ccl_data::accelerator_k, ccl_data::accelerator_m, ccl_data::achi, ccl_data::alphahmf, ccl_data::betahmf, ccl_cosmology_set_status_message(), ccl_data::chi, ccl_cosmology::computed_distances, ccl_cosmology::computed_growth, ccl_cosmology::computed_hmfparams, ccl_cosmology::computed_power, ccl_cosmology::computed_sigma, ccl_cosmology::config, cl_cmbl_bm::cosmo, ccl_cosmology::data, ccl_data::dlnsigma_dlogm, ccl_data::E, ccl_data::etahmf, ccl_data::fgrowth, ccl_data::gammahmf, ccl_data::growth, ccl_data::growth0, ccl_data::logsigma, ccl_data::p_lin, ccl_data::p_nl, halomod_bm::params, ccl_cosmology::params, ccl_data::phihmf, and ccl_cosmology::status.
Referenced by ccl_cosmology_create_flat_lcdm(), check_mgrowth(), compare_bbks(), compare_bcm(), compare_cls(), compare_corr(), compare_correlation_3d(), compare_distances(), compare_distances_hiz(), compare_distances_hiz_mnu(), compare_distances_mnu(), compare_eh(), compare_emu(), compare_emu_nu(), compare_growth(), compare_growth_hiz(), compare_halomod(), compare_massfunc(), compare_power_nu(), compare_power_nu_nl(), compare_sigmam(), main(), test_angpow_precision(), and write_Pk_CLASS().
 {
   ccl_cosmology * cosmo = malloc(sizeof(ccl_cosmology));
   cosmo->params = params;
   cosmo->config = config;
   cosmo->data.chi = NULL;
   cosmo->data.growth = NULL;
   cosmo->data.fgrowth = NULL;
   cosmo->data.E = NULL;
   cosmo->data.accelerator=NULL;
   cosmo->data.accelerator_achi=NULL;
   cosmo->data.accelerator_m=NULL;
   cosmo->data.accelerator_d=NULL;
   cosmo->data.accelerator_k=NULL;
   cosmo->data.growth0 = 1.;
   cosmo->data.achi=NULL;
   cosmo->data.logsigma = NULL;
   cosmo->data.dlnsigma_dlogm = NULL;
   // hmf parameter for interpolation
   cosmo->data.alphahmf = NULL;
   cosmo->data.betahmf = NULL;
   cosmo->data.gammahmf = NULL;
   cosmo->data.phihmf = NULL;
   cosmo->data.etahmf = NULL;
   cosmo->data.p_lin = NULL;
   cosmo->data.p_nl = NULL;
   //cosmo->data.nu_pspace_int = NULL;
   cosmo->computed_distances = false;
   cosmo->computed_growth = false;
   cosmo->computed_power = false;
   cosmo->computed_sigma = false;
   cosmo->computed_hmfparams = false;
   cosmo->status = 0;
   ccl_cosmology_set_status_message(cosmo, "");
   return cosmo;
 }
void ccl_cosmology_free (ccl_cosmology * cosmo)
Free a cosmology struct
Parameters
cosmo Cosmological parameters
Returns
void
Definition at line 829 of file ccl_core.c.
References ccl_data_free(), and ccl_cosmology::data.
Referenced by check_mgrowth(), compare_bbks(), compare_bcm(), compare_cls(), compare_corr(), compare_correlation_3d(), compare_distances(), compare_distances_hiz(), compare_distances_hiz_mnu(), compare_distances_mnu(), compare_eh(), compare_emu(), compare_emu_nu(), compare_growth(), compare_growth_hiz(), compare_power_nu(), compare_power_nu_nl(), Cosmo_Param::init(), main(), test_angpow_precision(), write_Pk_CLASS(), and Cosmo_Param::~Cosmo_Param().
 {
   ccl_data_free(&cosmo->data);
   free(cosmo);
 }
void ccl_cosmology_read_config (void)
Definition at line 50 of file ccl_core.c.
References ccl_spline_params::A_SPLINE_MAX, ccl_spline_params::A_SPLINE_MIN, ccl_spline_params::A_SPLINE_MIN_PK, ccl_spline_params::A_SPLINE_MINLOG, ccl_spline_params::A_SPLINE_MINLOG_PK, ccl_spline_params::A_SPLINE_NA, ccl_spline_params::A_SPLINE_NA_PK, ccl_spline_params::A_SPLINE_NLOG, ccl_spline_params::A_SPLINE_NLOG_PK, CCL_ERROR_MEMORY, CCL_ERROR_MISSING_CONFIG_FILE, ccl_raise_exception(), ccl_spline_params::ELL_MAX_CORR, ccl_spline_params::ELL_MIN_CORR, ccl_gsl_params::EPSREL, EXPAND_STR, ccl_gsl_params::INTEGRATION_DISTANCE_EPSREL, ccl_gsl_params::INTEGRATION_DNDZ_EPSREL, ccl_gsl_params::INTEGRATION_EPSREL, ccl_gsl_params::INTEGRATION_GAUSS_KRONROD_POINTS, ccl_gsl_params::INTEGRATION_LIMBER_EPSREL, ccl_gsl_params::INTEGRATION_LIMBER_GAUSS_KRONROD_POINTS, ccl_gsl_params::INTEGRATION_NU_EPSABS, ccl_gsl_params::INTEGRATION_NU_EPSREL, ccl_gsl_params::INTEGRATION_SIGMAR_EPSREL, ccl_spline_params::K_MAX, ccl_spline_params::K_MAX_SPLINE, ccl_spline_params::K_MIN, ccl_spline_params::LOGM_SPLINE_DELTA, ccl_spline_params::LOGM_SPLINE_MAX, ccl_spline_params::LOGM_SPLINE_MIN, ccl_spline_params::LOGM_SPLINE_NM, MATCH, ccl_spline_params::N_ELL_CORR, ccl_gsl_params::N_ITERATION, ccl_spline_params::N_K, ccl_spline_params::N_K_3DCOR, ccl_gsl_params::ODE_GROWTH_EPSREL, ccl_gsl_params::ROOT_EPSREL, and ccl_gsl_params::ROOT_N_ITERATION.
Referenced by calculate_nu_phasespace_spline(), ccl_dNdz_tomog(), ccl_norm_integrand(), and ccl_parameters_create().
 {
   int CONFIG_LINE_BUFFER_SIZE=100;
   int MAX_CONFIG_VAR_LEN=100;
   FILE *fconfig;
   char buf[CONFIG_LINE_BUFFER_SIZE];
   char var_name[MAX_CONFIG_VAR_LEN];
   char* rtn;
   double var_dbl;
   // Get parameter .ini filename from environment variable or default location
   const char* param_file;
   const char* param_file_env = getenv("CCL_PARAM_FILE");
   if (param_file_env != NULL) {
     param_file = param_file_env;
   }
   else {
     // Use default ini file
     param_file = EXPAND_STR(__CCL_DATA_DIR__) "/ccl_params.ini";
   }
   if ((fconfig=fopen(param_file, "r")) == NULL) {
     ccl_raise_exception(CCL_ERROR_MISSING_CONFIG_FILE, "ccl_core.c: Failed to open config file: %s", param_file);
     return;
   }
   if(ccl_splines == NULL) {
     ccl_splines = malloc(sizeof(ccl_spline_params));
   }
   if(ccl_gsl == NULL) {
     ccl_gsl = malloc(sizeof(ccl_gsl_params));
     memcpy(ccl_gsl, &default_gsl_params, sizeof(ccl_gsl_params));
   }
   /* Exit gracefully if we couldn't allocate memory */
   if(ccl_splines==NULL || ccl_gsl==NULL) {
     ccl_raise_exception(CCL_ERROR_MEMORY, "ccl_core.c: Failed to allocate memory for config file data.");
     return;
   }
 #define MATCH(s, action) if (0 == strcmp(var_name, s)) { action ; continue;} do{} while(0)
   int lineno = 0;
   while(! feof(fconfig)) {
     rtn = fgets(buf, CONFIG_LINE_BUFFER_SIZE, fconfig);
     lineno ++;
     if (buf[0]==';' || buf[0]=='[' || buf[0]=='\n') {
       continue;
     }
     else {
       sscanf(buf, "%99[^=]=%le\n",var_name, &var_dbl);
       // Spline parameters
       MATCH("A_SPLINE_NA", ccl_splines->A_SPLINE_NA=(int) var_dbl);
       MATCH("A_SPLINE_NLOG", ccl_splines->A_SPLINE_NLOG=(int) var_dbl);
       MATCH("A_SPLINE_MINLOG", ccl_splines->A_SPLINE_MINLOG=var_dbl);
       MATCH("A_SPLINE_MIN", ccl_splines->A_SPLINE_MIN=var_dbl);
       MATCH("A_SPLINE_MINLOG_PK", ccl_splines->A_SPLINE_MINLOG_PK=var_dbl);
       MATCH("A_SPLINE_MIN_PK", ccl_splines->A_SPLINE_MIN_PK=var_dbl);
       MATCH("A_SPLINE_MAX", ccl_splines->A_SPLINE_MAX=var_dbl);
       MATCH("LOGM_SPLINE_DELTA", ccl_splines->LOGM_SPLINE_DELTA=var_dbl);
       MATCH("LOGM_SPLINE_NM", ccl_splines->LOGM_SPLINE_NM=(int) var_dbl);
       MATCH("LOGM_SPLINE_MIN", ccl_splines->LOGM_SPLINE_MIN=var_dbl);
       MATCH("LOGM_SPLINE_MAX", ccl_splines->LOGM_SPLINE_MAX=var_dbl);
       MATCH("A_SPLINE_NA_PK", ccl_splines->A_SPLINE_NA_PK=(int) var_dbl);
       MATCH("A_SPLINE_NLOG_PK", ccl_splines->A_SPLINE_NLOG_PK=(int) var_dbl);
       MATCH("K_MAX_SPLINE", ccl_splines->K_MAX_SPLINE=var_dbl);
       MATCH("K_MAX", ccl_splines->K_MAX=var_dbl);
       MATCH("K_MIN", ccl_splines->K_MIN=var_dbl);
       MATCH("N_K", ccl_splines->N_K=(int) var_dbl);
       // 3dcorr parameters
       MATCH("N_K_3DCOR", ccl_splines->N_K_3DCOR=(int) var_dbl);
       // Angular correlation function params
       MATCH("ELL_MIN_CORR",ccl_splines->ELL_MIN_CORR=(double) var_dbl);
       MATCH("ELL_MAX_CORR",ccl_splines->ELL_MAX_CORR=(double) var_dbl);
       MATCH("N_ELL_CORR",ccl_splines->N_ELL_CORR=(int) var_dbl);
       // GSL parameters
       MATCH("GSL_EPSREL", ccl_gsl->EPSREL=var_dbl);
       MATCH("GSL_N_ITERATION", ccl_gsl->N_ITERATION=(size_t) var_dbl);
       MATCH("GSL_INTEGRATION_GAUSS_KRONROD_POINTS", ccl_gsl->INTEGRATION_GAUSS_KRONROD_POINTS=(int) var_dbl);
       MATCH("GSL_INTEGRATION_EPSREL", ccl_gsl->INTEGRATION_EPSREL=var_dbl);
       MATCH("GSL_INTEGRATION_DISTANCE_EPSREL", ccl_gsl->INTEGRATION_DISTANCE_EPSREL=var_dbl);
       MATCH("GSL_INTEGRATION_DNDZ_EPSREL", ccl_gsl->INTEGRATION_DNDZ_EPSREL=var_dbl);
       MATCH("GSL_INTEGRATION_SIGMAR_EPSREL", ccl_gsl->INTEGRATION_SIGMAR_EPSREL=var_dbl);
       MATCH("GSL_INTEGRATION_NU_EPSREL", ccl_gsl->INTEGRATION_NU_EPSREL=var_dbl);
       MATCH("GSL_INTEGRATION_NU_EPSABS", ccl_gsl->INTEGRATION_NU_EPSABS=var_dbl);
       MATCH("GSL_INTEGRATION_LIMBER_GAUSS_KRONROD_POINTS", ccl_gsl->INTEGRATION_LIMBER_GAUSS_KRONROD_POINTS=(int) var_dbl);
       MATCH("GSL_INTEGRATION_LIMBER_EPSREL", ccl_gsl->INTEGRATION_LIMBER_EPSREL=var_dbl);
       MATCH("GSL_ROOT_EPSREL", ccl_gsl->ROOT_EPSREL=var_dbl);
       MATCH("GSL_ROOT_N_ITERATION", ccl_gsl->ROOT_N_ITERATION=(int) var_dbl);
       MATCH("GSL_ODE_GROWTH_EPSREL", ccl_gsl->ODE_GROWTH_EPSREL=var_dbl);
       ccl_raise_exception(CCL_ERROR_MISSING_CONFIG_FILE, "ccl_core.c: Failed to parse config file at line %d: %s", lineno, buf);
     }
   }
 #undef MATCH
   fclose(fconfig);
 }
void ccl_cosmology_set_status_message (ccl_cosmology * cosmo, const char * message, ...)
Definition at line 792 of file ccl_core.c.
References ccl_cosmology::status_message.
Referenced by ccl_angular_cl_native(), ccl_angular_cls(), ccl_comoving_angular_distance(), ccl_comoving_radial_distance(), ccl_correlation(), ccl_correlation_3d(), ccl_cosmology_compute_distances(), ccl_cosmology_compute_growth(), ccl_cosmology_compute_hmfparams(), ccl_cosmology_compute_power(), ccl_cosmology_compute_power_bbks(), ccl_cosmology_compute_power_class(), ccl_cosmology_compute_power_eh(), ccl_cosmology_compute_power_emu(), ccl_cosmology_compute_sigma(), ccl_cosmology_create(), ccl_cosmology_write_power_class_z(), ccl_distance_modulus(), ccl_fill_class_parameters(), ccl_free_class_structs(), ccl_get_tracer_fa(), ccl_get_tracer_fas(), ccl_growth_factor(), ccl_growth_rate(), ccl_h_over_h0(), ccl_halo_b1(), ccl_halo_bias(), ccl_halo_concentration(), ccl_linear_matter_power(), ccl_massfunc(), ccl_nonlin_matter_power(), ccl_omega_x(), ccl_pkemu(), ccl_power_extrapol_highk(), ccl_power_extrapol_lowk(), ccl_run_class(), ccl_scale_factor_of_chi(), ccl_sigmaM(), ccl_sinn(), ccl_tracer_corr_bessel(), ccl_tracer_corr_fftlog(), ccl_tracer_corr_legendre(), cl_tracer(), clt_init_ba(), clt_init_bz(), clt_init_nz(), clt_init_rf(), clt_init_wL(), clt_init_wM(), clt_nc_init(), massfunc_f(), one_halo_integral(), and two_halo_integral().
 {
   const int trunc = 480; /* must be < 500 - 4 */
   va_list va;
   va_start(va, message);
   vsnprintf(cosmo->status_message, trunc, message, va);
   va_end(va);
   /* if truncation happens, message[trunc - 1] is not NULL, ... will show up. */
   strcpy(&cosmo->status_message[trunc], "...");
 }
void ccl_data_free (ccl_data * data)
Definition at line 761 of file ccl_core.c.
References ccl_data::accelerator, ccl_data::accelerator_achi, ccl_data::accelerator_d, ccl_data::accelerator_k, ccl_data::accelerator_m, ccl_data::achi, ccl_data::alphahmf, ccl_data::betahmf, ccl_data::chi, ccl_data::dlnsigma_dlogm, ccl_data::E, ccl_data::etahmf, ccl_data::fgrowth, ccl_data::gammahmf, ccl_data::growth, ccl_data::logsigma, ccl_data::p_lin, ccl_data::p_nl, and ccl_data::phihmf.
Referenced by ccl_cosmology_free().
 {
   //We cannot assume that all of these have been allocated
   //TODO: it would actually make more sense to do this within ccl_cosmology_free,
   //where we could make use of the flags "computed_distances" etc. to figure out
   //what to free up
   gsl_spline_free(data->chi);
   gsl_spline_free(data->growth);
   gsl_spline_free(data->fgrowth);
   gsl_interp_accel_free(data->accelerator);
   gsl_interp_accel_free(data->accelerator_achi);
   gsl_spline_free(data->E);
   gsl_spline_free(data->achi);
   gsl_spline_free(data->logsigma);
   gsl_spline_free(data->dlnsigma_dlogm);
   gsl_spline2d_free(data->p_lin);
   gsl_spline2d_free(data->p_nl);
   gsl_spline_free(data->alphahmf);
   gsl_spline_free(data->betahmf);
   gsl_spline_free(data->gammahmf);
   gsl_spline_free(data->phihmf);
   gsl_spline_free(data->etahmf);
   gsl_interp_accel_free(data->accelerator_d);
   gsl_interp_accel_free(data->accelerator_m);
   gsl_interp_accel_free(data->accelerator_k);
 }
ccl_parameters ccl_parameters_create (double Omega_c, double Omega_b, double Omega_k, double Neff, double * mnu, ccl_mnu_convention mnu_type, double w0, double wa, double h, double norm_pk, double n_s, double bcm_log10Mc, double bcm_etab, double bcm_ks, int nz_mgrowth, double * zarr_mgrowth, double * dfarr_mgrowth, int * status)
Create a cosmology
Parameters
Omega_c Omega_c
Omega_b Omega_b
Omega_k Omega_k
Neff Number of relativistic neutrino species in the early universe
mnu neutrino mass, either sum or list of length 3
mnu_type determines neutrino mass convention (ccl_mnu_list, ccl_mnu_sum, ccl_mnu_sum_inverted, ccl_mnu_sum_equal)
w0 Dark energy EoS parameter
wa Dark energy EoS parameter
h Hubble constant in units of 100 km/s/Mpc
norm_pk the normalization of the power spectrum, either A_s or sigma8
n_s the power-law index of the power spectrum
bcm_log10Mc log10 cluster mass, one of the parameters of the BCM model
bcm_etab ejection radius parameter, one of the parameters of the BCM model
bcm_ks wavenumber for the stellar profile, one of the parameters of the BCM model
nz_mgrowth the number of redshifts where the modified growth is provided
zarr_mgrowth the array of redshifts where the modified growth is provided
dfarr_mgrowth the modified growth function vector provided
status Status flag. 0 if there are no errors, nonzero otherwise. For specific cases see documentation for ccl_error.c
Returns
void
Definition at line 294 of file ccl_core.c.
References ccl_parameters::A_s, ccl_parameters::bcm_etab, ccl_parameters::bcm_ks, ccl_parameters::bcm_log10Mc, ccl_check_status_nocosmo(), ccl_cosmology_read_config(), CCL_ERROR_MNU_UNPHYSICAL, CCL_ERROR_NOT_IMPLEMENTED, ccl_mnu_list, ccl_mnu_sum, ccl_mnu_sum_equal, ccl_mnu_sum_inverted, ccl_parameters_fill_initial(), DELTAM12_sq, DELTAM13_sq_neg, DELTAM13_sq_pos, ccl_parameters::df_mgrowth, ccl_test_distances::h, ccl_parameters::h, ccl_parameters::H0, ccl_parameters::has_mgrowth, ccl_test_distances::mnu, ccl_parameters::mnu, ccl_parameters::N_nu_mass, ccl_test_distances::n_s, ccl_parameters::n_s, ccl_test_distances::Neff, ccl_parameters::Neff, ccl_parameters::nz_mgrowth, ccl_parameters::Omega_b, ccl_test_distances::Omega_b, ccl_parameters::Omega_c, ccl_test_distances::Omega_c, ccl_parameters::Omega_k, halomod_bm::params, ccl_parameters::sigma8, sqrt(), ccl_parameters::sum_nu_masses, ccl_parameters::w0, ccl_parameters::wa, and ccl_parameters::z_mgrowth.
Referenced by __ctest_create_mnu_create_mnu_inv_run(), __ctest_parameters_create_general_nu_list_run(), __ctest_parameters_create_general_nu_sum_equal_run(), __ctest_parameters_create_general_nu_sum_inverted_run(), __ctest_parameters_create_general_nu_sum_run(), ccl_cosmology_create_flat_lcdm(), ccl_parameters_create_flat_lcdm(), ccl_parameters_read_yaml(), check_mgrowth(), compare_bbks(), compare_bcm(), compare_correlation_3d(), compare_distances(), compare_distances_hiz(), compare_distances_hiz_mnu(), compare_distances_mnu(), compare_eh(), compare_emu(), compare_emu_nu(), compare_growth(), compare_growth_hiz(), compare_halomod(), compare_massfunc(), compare_power_nu(), compare_power_nu_nl(), compare_sigmam(), main(), test_angpow_precision(), and write_Pk_CLASS().
 {
   #ifndef USE_GSL_ERROR
     gsl_set_error_handler_off ();
   #endif
   ccl_parameters params;
   // Initialize params
   params.mnu = NULL;
   params.z_mgrowth=NULL;
   params.df_mgrowth=NULL;
   params.sigma8 = NAN;
   params.A_s = NAN;
   params.Omega_c = Omega_c;
   params.Omega_b = Omega_b;
   params.Omega_k = Omega_k;
   params.Neff = Neff;
   // Set the sum of neutrino masses
   params.sum_nu_masses = *mnu;
   double mnusum = *mnu;
   double *mnu_in = NULL;
   /* Check whether ccl_splines and ccl_gsl exist. If either is not set yet, load
      parameters from the config file. */
   if(ccl_splines==NULL || ccl_gsl==NULL) {
     ccl_cosmology_read_config();
   }
   // Decide how to split sum of neutrino masses between 3 neutrinos. We use
   // a Newton's rule numerical solution (thanks M. Jarvis).
   if (mnu_type==ccl_mnu_sum){
       // Normal hierarchy
       mnu_in = malloc(3*sizeof(double));
       // Check if the sum is zero
       if (*mnu<1e-15){
           mnu_in[0] = 0.;
           mnu_in[1] = 0.;
           mnu_in[2] = 0.;
       } else{
           mnu_in[0] = 0.; // This is a starting guess.
           double sum_check;
           // Check that sum is consistent
           mnu_in[1] = sqrt(DELTAM12_sq);
           mnu_in[2] = sqrt(DELTAM13_sq_pos);
           sum_check = mnu_in[0] + mnu_in[1] + mnu_in[2];
           if (ccl_mnu_sum < sum_check){
               *status = CCL_ERROR_MNU_UNPHYSICAL;
           }
           double dsdm1;
           // This is the Newton's method
           while (fabs(*mnu - sum_check) > 1e-15){
               dsdm1 = 1. + mnu_in[0] / mnu_in[1] + mnu_in[0] / mnu_in[2];
               mnu_in[0] = mnu_in[0] - (sum_check - *mnu) / dsdm1;
               mnu_in[1] = sqrt(mnu_in[0]*mnu_in[0] + DELTAM12_sq);
               mnu_in[2] = sqrt(mnu_in[0]*mnu_in[0] + DELTAM13_sq_pos);
               sum_check = mnu_in[0] + mnu_in[1] + mnu_in[2];
           }
       }
   } else if (mnu_type==ccl_mnu_sum_inverted){
       // Inverted hierarchy
       mnu_in = malloc(3*sizeof(double));
           // Check if the sum is zero
       if (*mnu<1e-15){
           mnu_in[0] = 0.;
           mnu_in[1] = 0.;
           mnu_in[2] = 0.;
       } else{
           mnu_in[0] = 0.; // This is a starting guess.
           double sum_check;
           // Check that sum is consistent
           mnu_in[1] = sqrt(-1.* DELTAM13_sq_neg - DELTAM12_sq);
           mnu_in[2] = sqrt(-1.* DELTAM13_sq_neg);
           sum_check = mnu_in[0] + mnu_in[1] + mnu_in[2];
           if (ccl_mnu_sum < sum_check){
               *status = CCL_ERROR_MNU_UNPHYSICAL;
           }
           double dsdm1;
           // This is the Newton's method
           while (fabs(*mnu- sum_check) > 1e-15){
               dsdm1 = 1. + (mnu_in[0] / mnu_in[1]) + (mnu_in[0] / mnu_in[2]);
               mnu_in[0] = mnu_in[0] - (sum_check - *mnu) / dsdm1;
               mnu_in[1] = sqrt(mnu_in[0]*mnu_in[0] + DELTAM12_sq);
               mnu_in[2] = sqrt(mnu_in[0]*mnu_in[0] + DELTAM13_sq_neg);
               sum_check = mnu_in[0] + mnu_in[1] + mnu_in[2];
           }
       }
   } else if (mnu_type==ccl_mnu_sum_equal){
         // Split the sum of masses equally
         mnu_in = malloc(3*sizeof(double));
         mnu_in[0] = params.sum_nu_masses / 3.;
         mnu_in[1] = params.sum_nu_masses / 3.;
         mnu_in[2] = params.sum_nu_masses / 3.;
   } else if (mnu_type == ccl_mnu_list){
       // A list of neutrino masses was already passed in
       params.sum_nu_masses = mnu[0] + mnu[1] + mnu[2];
       mnu_in = malloc(3*sizeof(double));
       for(int i=0; i<3; i++) mnu_in[i] = mnu[i];
   } else {
       *status = CCL_ERROR_NOT_IMPLEMENTED;
   }
   // Check for errors in the neutrino set up (e.g. unphysical mnu)
   ccl_check_status_nocosmo(status);
   // Check which of the neutrino species are non-relativistic today
   int N_nu_mass = 0;
   for(int i = 0; i<3; i=i+1){
     if (mnu_in[i] > 0.00017){ // Limit taken from Lesgourges et al. 2012
         N_nu_mass = N_nu_mass + 1;
     }
   }
   params.N_nu_mass = N_nu_mass;
   // Fill the array of massive neutrinos
   if (N_nu_mass>0){
     params.mnu = malloc(params.N_nu_mass*sizeof(double));
     int relativistic[3] = {0, 0, 0};
     for (int i = 0; i < N_nu_mass; i = i + 1){
         for (int j = 0; j<3; j = j +1){
             if ((mnu_in[j]>0.00017) && (relativistic[j]==0)){
                 relativistic[j]=1;
                 params.mnu[i] = mnu_in[j];
                 break;
             }
         } // end loop over neutrinos
     } // end loop over massive neutrinos
   } else{
       params.mnu = malloc(sizeof(double));
       params.mnu[0] = 0.;
   }
   // Free mnu_in
   if (mnu_in != NULL) free(mnu_in);
   // Dark Energy
   params.w0 = w0;
   params.wa = wa;
   // Hubble parameters
   params.h = h;
   params.H0 = h*100;
   // Primordial power spectra
   if(norm_pk<1E-5)
     params.A_s=norm_pk;
   else
     params.sigma8=norm_pk;
   params.n_s = n_s;
   //Baryonic params
   if(bcm_log10Mc<0)
     params.bcm_log10Mc=log10(1.2e14);
   else
     params.bcm_log10Mc=bcm_log10Mc;
   if(bcm_etab<0)
     params.bcm_etab=0.5;
   else
     params.bcm_etab=bcm_etab;
   if(bcm_ks<0)
     params.bcm_ks=55.0;
   else
     params.bcm_ks=bcm_ks;
   // Set remaining standard and easily derived parameters
   ccl_parameters_fill_initial(&params, status);
   //Trigger modified growth function if nz>0
   if(nz_mgrowth>0) {
     params.has_mgrowth=true;
     params.nz_mgrowth=nz_mgrowth;
     params.z_mgrowth=malloc(params.nz_mgrowth*sizeof(double));
     params.df_mgrowth=malloc(params.nz_mgrowth*sizeof(double));
     memcpy(params.z_mgrowth,zarr_mgrowth,params.nz_mgrowth*sizeof(double));
     memcpy(params.df_mgrowth,dfarr_mgrowth,params.nz_mgrowth*sizeof(double));
   }
   else {
     params.has_mgrowth=false;
     params.nz_mgrowth=0;
     params.z_mgrowth=NULL;
     params.df_mgrowth=NULL;
   }
   return params;
 }
ccl_parameters ccl_parameters_create_flat_lcdm (double Omega_c, double Omega_b, double h, double norm_pk, double n_s, int * status)
Definition at line 505 of file ccl_core.c.
References ccl_mnu_sum, ccl_parameters_create(), ccl_test_distances::mnu, ccl_test_distances::Neff, and halomod_bm::params.
Referenced by __ctest_parameters_read_write_run(), compare_cls(), compare_corr(), and main().
 {
   double Omega_k = 0.0;
   double Neff = 3.046;
   double w0 = -1.0;
   double wa = 0.0;
   double *mnu;
   double mnuval = 0.;  // a pointer to the variable is not kept past the lifetime of this function
   mnu = &mnuval;
   ccl_mnu_convention mnu_type = ccl_mnu_sum;
   ccl_parameters params = ccl_parameters_create(Omega_c, Omega_b, Omega_k, Neff,
         mnu, mnu_type, w0, wa, h, norm_pk, n_s, -1, -1, -1, -1, NULL, NULL, status);
   return params;
 }
void ccl_parameters_fill_initial (ccl_parameters * params, int * status)
Definition at line 226 of file ccl_core.c.
References ccl_parameters::A_s, ccl_check_status_nocosmo(), ccl_Omeganuh2(), CLIGHT, CLIGHT_HMPC, ccl_parameters::h, ccl_parameters::k_sign, ccl_parameters::mnu, MPC_TO_METER, ccl_parameters::N_nu_mass, ccl_parameters::N_nu_rel, ccl_parameters::Neff, ccl_parameters::Omega_b, ccl_test_distances::Omega_c, ccl_parameters::Omega_g, ccl_parameters::Omega_k, ccl_parameters::Omega_l, ccl_parameters::Omega_m, ccl_parameters::Omega_n_mass, ccl_parameters::Omega_n_rel, pow(), RHO_CRITICAL, ccl_parameters::sigma8, SOLAR_MASS, sqrt(), ccl_parameters::sqrtk, STBOLTZ, ccl_parameters::T_CMB, TCMB, TNCDM, and ccl_parameters::z_star.
Referenced by ccl_parameters_create().
 {
   // Fixed radiation parameters
   // Omega_g * h**2 is known from T_CMB
   params->T_CMB =  TCMB;
   // kg / m^3
   double rho_g = 4. * STBOLTZ / pow(CLIGHT, 3) * pow(params->T_CMB, 4);
   // kg / m^3
   double rho_crit = RHO_CRITICAL * SOLAR_MASS/pow(MPC_TO_METER, 3) * pow(params->h, 2);
   params->Omega_g = rho_g/rho_crit;
   // Get the N_nu_rel from Neff and N_nu_mass
   params->N_nu_rel = params->Neff - params->N_nu_mass * pow(TNCDM, 4) / pow(4./11.,4./3.);
   // Temperature of the relativistic neutrinos in K
   double T_nu= (params->T_CMB) * pow(4./11.,1./3.);
   // in kg / m^3
   double rho_nu_rel = params->N_nu_rel* 7.0/8.0 * 4. * STBOLTZ / pow(CLIGHT, 3) * pow(T_nu, 4);
   params-> Omega_n_rel = rho_nu_rel/rho_crit;
   // If non-relativistic neutrinos are present, calculate the phase_space integral.
   if((params->N_nu_mass)>0) {
     // Pass NULL for the accelerator here because we don't have our cosmology object defined yet.
     params->Omega_n_mass = ccl_Omeganuh2(1.0, params->N_nu_mass, params->mnu, params->T_CMB, NULL, status) / ((params->h)*(params->h));
     ccl_check_status_nocosmo(status);
   }
   else{
     params->Omega_n_mass = 0.;
   }
   params->Omega_m = params->Omega_b + params-> Omega_c;
   params->Omega_l = 1.0 - params->Omega_m - params->Omega_g - params->Omega_n_rel -params->Omega_n_mass- params->Omega_k;
   // Initially undetermined parameters - set to nan to trigger
   // problems if they are mistakenly used.
   if (isfinite(params->A_s)) {params->sigma8 = NAN;}
   if (isfinite(params->sigma8)) {params->A_s = NAN;}
   params->z_star = NAN;
   if(fabs(params->Omega_k)<1E-6)
     params->k_sign=0;
   else if(params->Omega_k>0)
     params->k_sign=-1;
   else
     params->k_sign=1;
   params->sqrtk=sqrt(fabs(params->Omega_k))*params->h/CLIGHT_HMPC;
 }
void ccl_parameters_free (ccl_parameters * params)
Free a parameters struct
Parameters
params ccl_parameters struct
Returns
void
Definition at line 808 of file ccl_core.c.
References ccl_parameters::df_mgrowth, ccl_parameters::mnu, and ccl_parameters::z_mgrowth.
 {
   if (params->mnu != NULL){
     free(params->mnu);
     params->mnu = NULL;
   }
   if (params->z_mgrowth != NULL){
     free(params->z_mgrowth);
     params->z_mgrowth = NULL;
   }
   if (params->df_mgrowth != NULL){
     free(params->df_mgrowth);
     params->df_mgrowth = NULL;
   }
 }
ccl_parameters ccl_parameters_read_yaml (const char * filename, int * status)
Write a cosmology parameters object to a file in yaml format.
Parameters
cosmo Cosmological parameters
f FILE* pointer opened for reading
Returns
void
Definition at line 624 of file ccl_core.c.
References ccl_test_distances::A_s, CCL_ERROR_FILE_READ, ccl_mnu_list, ccl_parameters_create(), ccl_raise_exception(), ccl_test_distances::h, ccl_test_distances::mnu, ccl_test_distances::n_s, ccl_test_distances::Neff, ccl_test_distances::Omega_b, ccl_test_distances::Omega_c, halomod_bm::params, READ_DOUBLE, READ_INT, and ccl_test_power::sigma8.
Referenced by __ctest_parameters_read_write_run().
 {
   FILE * f = fopen(filename, "r");
   if (!f){
     *status = CCL_ERROR_FILE_READ;
     ccl_parameters bad_params;
     ccl_raise_exception(CCL_ERROR_FILE_READ, "ccl_core.c: Failed to read parameters from file.");
     return bad_params;
   }
 #define READ_DOUBLE(name) double name; *status |= (0==fscanf(f, #name ": %le\n",&name));
 #define READ_INT(name) int name; *status |= (0==fscanf(f, #name ": %d\n",&name))
   // Densities: CDM, baryons, total matter, curvature
   READ_DOUBLE(Omega_c);
   READ_DOUBLE(Omega_b);
   READ_DOUBLE(Omega_m);
   READ_DOUBLE(Omega_k);
   READ_INT(k_sign);
   // Dark Energy
   READ_DOUBLE(w0);
   READ_DOUBLE(wa);
   // Hubble parameters
   READ_DOUBLE(H0);
   READ_DOUBLE(h);
   // Neutrino properties
   READ_DOUBLE(Neff);
   READ_INT(N_nu_mass);
   READ_DOUBLE(N_nu_rel);
   double mnu[3] = {0.0, 0.0, 0.0};
   if (N_nu_mass>0){
     *status |= (0==fscanf(f, "mnu: ["));
     for (int i=0; i<N_nu_mass; i++){
       *status |= (0==fscanf(f, "%le, ", mnu+i));
     }
     *status |= (0==fscanf(f, "]\n"));
   }
   READ_DOUBLE(sum_nu_masses);
   READ_DOUBLE(Omega_n_mass);
   READ_DOUBLE(Omega_n_rel);
   // Primordial power spectra
   READ_DOUBLE(A_s);
   READ_DOUBLE(n_s);
   // Radiation parameters
   READ_DOUBLE(Omega_g);
   READ_DOUBLE(T_CMB);
   // BCM baryonic model parameters
   READ_DOUBLE(bcm_log10Mc);
   READ_DOUBLE(bcm_etab);
   READ_DOUBLE(bcm_ks);
   // Derived parameters
   READ_DOUBLE(sigma8);
   READ_DOUBLE(Omega_l);
   READ_DOUBLE(z_star);
   READ_INT(has_mgrowth);
   READ_INT(nz_mgrowth);
   double *z_mgrowth;
   double *df_mgrowth;
   if (has_mgrowth){
     z_mgrowth = malloc(nz_mgrowth*sizeof(double));
     df_mgrowth = malloc(nz_mgrowth*sizeof(double));
     *status |= (0==fscanf(f, "z_mgrowth: ["));
     for (int i=0; i<nz_mgrowth; i++){
       *status |= (0==fscanf(f, "%le, ", z_mgrowth+i));
     }
     *status |= (0==fscanf(f, "]\n"));
     *status |= (0==fscanf(f, "df_mgrowth: ["));
     for (int i=0; i<nz_mgrowth; i++){
       *status |= (0==fscanf(f, "%le, ", df_mgrowth+i));
     }
     *status |= (0==fscanf(f, "]\n"));
   }
   else{
     z_mgrowth = NULL;
     df_mgrowth = NULL;
   }
 #undef READ_DOUBLE
 #undef READ_INT
   fclose(f);
   if (status){
     char msg[256];
     snprintf(msg, 256, "ccl_core.c: Structure of YAML file incorrect: %s", filename);
     ccl_raise_exception(*status, msg);
   }
   double norm_pk;
   if (isnan(A_s)){
     norm_pk = sigma8;
   }
   else{
    norm_pk = A_s;
   }
   ccl_parameters params = ccl_parameters_create(
     Omega_c, Omega_b, Omega_k,
     Neff, mnu, ccl_mnu_list,
     w0, wa, h, norm_pk,
     n_s, bcm_log10Mc, bcm_etab,
     bcm_ks, nz_mgrowth, z_mgrowth,
     df_mgrowth, status);
   if(z_mgrowth) free(z_mgrowth);
   if (df_mgrowth) free(df_mgrowth);
   return params;
 }
void ccl_parameters_write_yaml (ccl_parameters * params, const char * filename, int * status)
Write a cosmology parameters object to a file in yaml format.
Parameters
cosmo Cosmological parameters
f FILE* pointer opened for reading
Returns
void
Definition at line 531 of file ccl_core.c.
References ccl_test_distances::A_s, CCL_ERROR_FILE_WRITE, ccl_parameters::df_mgrowth, ccl_test_distances::h, ccl_parameters::has_mgrowth, ccl_parameters::mnu, ccl_parameters::N_nu_mass, ccl_test_distances::n_s, ccl_test_distances::Neff, ccl_parameters::nz_mgrowth, ccl_test_distances::Omega_b, ccl_test_distances::Omega_c, ccl_test_power::sigma8, WRITE_DOUBLE, WRITE_INT, and ccl_parameters::z_mgrowth.
Referenced by __ctest_parameters_read_write_run().
 {
   FILE * f = fopen(filename, "w");
   if (!f){
     *status = CCL_ERROR_FILE_WRITE;
     return;
   }
 #define WRITE_DOUBLE(name) fprintf(f, #name ": %le\n",params->name)
 #define WRITE_INT(name) fprintf(f, #name ": %d\n",params->name)
   // Densities: CDM, baryons, total matter, curvature
   WRITE_DOUBLE(Omega_c);
   WRITE_DOUBLE(Omega_b);
   WRITE_DOUBLE(Omega_m);
   WRITE_DOUBLE(Omega_k);
   WRITE_INT(k_sign);
   // Dark Energy
   WRITE_DOUBLE(w0);
   WRITE_DOUBLE(wa);
   // Hubble parameters
   WRITE_DOUBLE(H0);
   WRITE_DOUBLE(h);
   // Neutrino properties
   WRITE_DOUBLE(Neff);
   WRITE_INT(N_nu_mass);
   WRITE_DOUBLE(N_nu_rel);
   if (params->N_nu_mass>0){
     fprintf(f, "mnu: [");
     for (int i=0; i<params->N_nu_mass; i++){
       fprintf(f, "%le, ", params->mnu[i]);
     }
     fprintf(f, "]\n");
   }
   WRITE_DOUBLE(sum_nu_masses);
   WRITE_DOUBLE(Omega_n_mass);
   WRITE_DOUBLE(Omega_n_rel);
   // Primordial power spectra
   WRITE_DOUBLE(A_s);
   WRITE_DOUBLE(n_s);
   // Radiation parameters
   WRITE_DOUBLE(Omega_g);
   WRITE_DOUBLE(T_CMB);
   // BCM baryonic model parameters
   WRITE_DOUBLE(bcm_log10Mc);
   WRITE_DOUBLE(bcm_etab);
   WRITE_DOUBLE(bcm_ks);
   // Derived parameters
   WRITE_DOUBLE(sigma8);
   WRITE_DOUBLE(Omega_l);
   WRITE_DOUBLE(z_star);
   WRITE_INT(has_mgrowth);
   WRITE_INT(nz_mgrowth);
   if (params->has_mgrowth){
     fprintf(f, "z_mgrowth: [");
     for (int i=0; i<params->nz_mgrowth; i++){
       fprintf(f, "%le, ", params->z_mgrowth[i]);
     }
     fprintf(f, "]\n");
     fprintf(f, "df_mgrowth: [");
     for (int i=0; i<params->nz_mgrowth; i++){
       fprintf(f, "%le, ", params->df_mgrowth[i]);
     }
     fprintf(f, "]\n");
   }
 #undef WRITE_DOUBLE
 #undef WRITE_INT
   fclose(f);
 }
Variable Documentation
ccl_gsl_params* ccl_gsl = ((void*)0)
Definition at line 48 of file ccl_core.c.
Referenced by a_of_chi(), calculate_nu_phasespace_spline(), ccl_angular_cl_native(), ccl_cosmology_compute_growth(), ccl_dNdz_tomog(), ccl_norm_integrand(), ccl_sigmaR(), ccl_sigmaV(), ccl_tracer_corr_bessel(), clt_init_nz(), compare_cls(), compare_corr(), compute_chi(), growth_factor_and_growth_rate(), window_lensing(), and window_magnification().
ccl_spline_params* ccl_splines = ((void*)0)
Definition at line 47 of file ccl_core.c.
Referenced by calculate_nu_phasespace_spline(), ccl_correlation_3d(), ccl_cosmology_compute_distances(), ccl_cosmology_compute_growth(), ccl_cosmology_compute_power_bbks(), ccl_cosmology_compute_power_class(), ccl_cosmology_compute_power_eh(), ccl_cosmology_compute_power_emu(), ccl_cosmology_compute_sigma(), ccl_dNdz_tomog(), ccl_fill_class_parameters(), ccl_linear_matter_power(), ccl_nonlin_matter_power(), ccl_norm_integrand(), ccl_sigmaR(), ccl_sigmaV(), ccl_tracer_corr_bessel(), ccl_tracer_corr_fftlog(), ccl_tracer_corr_legendre(), get_k_interval(), and main().
const ccl_configuration default_config = {ccl_boltzmann_class, ccl_halofit, ccl_nobaryons, ccl_tinker10, ccl_duffy2008, ccl_emu_strict}
The default configuration object In the default configuration, defined in ccl_core.c CCL runs with: default_config = {ccl_boltzmann_class, ccl_halofit, ccl_nobaryons, ccl_tinker10, ccl_duffy2008, ccl_emu_strict}
Definition at line 21 of file ccl_core.c.
Referenced by check_mgrowth(), compare_bbks(), compare_bcm(), compare_cls(), compare_corr(), compare_correlation_3d(), compare_distances(), compare_distances_hiz(), compare_distances_hiz_mnu(), compare_distances_mnu(), compare_eh(), compare_emu(), compare_emu_nu(), compare_growth(), compare_growth_hiz(), compare_halomod(), compare_massfunc(), compare_power_nu(), compare_power_nu_nl(), compare_sigmam(), main(), test_angpow_precision(), and write_Pk_CLASS().
const ccl_gsl_params default_gsl_params
Initial value:
= {GSL_EPSREL,
                                           GSL_N_ITERATION,
                                           GSL_INTEGRATION_GAUSS_KRONROD_POINTS,
                                           GSL_EPSREL,
                                           GSL_INTEGRATION_GAUSS_KRONROD_POINTS,
                                           GSL_EPSREL,
                                           GSL_EPSREL_DIST,
                                           GSL_EPSREL_DNDZ,
                                           GSL_EPSREL_SIGMAR,
                                           GSL_EPSREL_NU,
                                           GSL_EPSABS_NU,
                                           GSL_EPSREL,
                                           GSL_N_ITERATION,
                                           GSL_EPSREL_GROWTH
                                          }
Definition at line 23 of file ccl_core.c.