Fast Methods for Cosmological Simulations: src/3party/CCL/include/ccl_correlation.h File Reference
ccl_correlation.h File Reference
Macros
#define CCL_CORR_LGNDRE 1001
#define CCL_CORR_FFTLOG 1002
#define CCL_CORR_BESSEL 1003
#define CCL_CORR_GG 2001
#define CCL_CORR_GL 2002
#define CCL_CORR_LP 2003
#define CCL_CORR_LM 2004
Functions
CCL_BEGIN_DECLS void ccl_correlation (ccl_cosmology *cosmo, int n_ell, double *ell, double *cls, int n_theta, double *theta, double *wtheta, int corr_type, int do_taper_cl, double *taper_cl_limits, int flag_method, int *status)
void ccl_correlation_3d (ccl_cosmology *cosmo, double a, int n_r, double *r, double *xi, int do_taper_pk, double *taper_pk_limits, int *status)
Macro Definition Documentation
#define CCL_CORR_BESSEL 1003
Definition at line 8 of file ccl_correlation.h.
Referenced by __ctest_corrs_analytic_bessel_run(), __ctest_corrs_histo_bessel_run(), and ccl_correlation().
#define CCL_CORR_FFTLOG 1002
Definition at line 7 of file ccl_correlation.h.
Referenced by __ctest_corrs_histo_fftlog_run(), ccl_correlation(), and main().
#define CCL_CORR_GG 2001
Definition at line 9 of file ccl_correlation.h.
Referenced by ccl_compute_legendre_polynomial(), ccl_tracer_corr_bessel(), ccl_tracer_corr_fftlog(), compare_corr(), and main().
#define CCL_CORR_GL 2002
Definition at line 10 of file ccl_correlation.h.
Referenced by ccl_compute_legendre_polynomial(), ccl_tracer_corr_bessel(), ccl_tracer_corr_fftlog(), and compare_corr().
#define CCL_CORR_LGNDRE 1001
Definition at line 6 of file ccl_correlation.h.
Referenced by ccl_correlation().
#define CCL_CORR_LM 2004
Definition at line 12 of file ccl_correlation.h.
Referenced by ccl_tracer_corr_bessel(), ccl_tracer_corr_fftlog(), ccl_tracer_corr_legendre(), and compare_corr().
#define CCL_CORR_LP 2003
Definition at line 11 of file ccl_correlation.h.
Referenced by ccl_tracer_corr_bessel(), ccl_tracer_corr_fftlog(), ccl_tracer_corr_legendre(), and compare_corr().
Function Documentation
CCL_BEGIN_DECLS void ccl_correlation (ccl_cosmology * cosmo, int n_ell, double * ell, double * cls, int n_theta, double * theta, double * wtheta, int corr_type, int do_taper_cl, double * taper_cl_limits, int flag_method, int * status)
Computes the correlation function (wrapper)
Parameters
cosmo :Cosmological parameters
n_ell : number of multipoles in the input power spectrum
ell : multipoles at which the power spectrum is evaluated
cls : input power spectrum
n_theta : number of output values of the separation angle (theta)
theta : values of the separation angle in degrees.
wtheta : the values of the correlation function at the angles above will be returned in this array, which should be pre-allocated
do_taper_cl :
taper_cl_limits
flag_method : method to compute the correlation function. Choose between:
CCL_CORR_FFTLOG : fast integration with FFTLog
CCL_CORR_BESSEL : direct integration over the Bessel function
CCL_CORR_LGNDRE : brute-force sum over legendre polynomials
corr_type : type of correlation function. Choose between:
CCL_CORR_GG : spin0-spin0
CCL_CORR_GL : spin0-spin2
CCL_CORR_LP : spin2-spin2 (xi+)
CCL_CORR_LM : spin2-spin2 (xi-) Currently supported spin-0 fields are number counts and CMB lensing. The only spin-2 is currently shear.
Definition at line 391 of file ccl_correlation.c.
References ccl_check_status(), CCL_CORR_BESSEL, CCL_CORR_FFTLOG, CCL_CORR_LGNDRE, ccl_cosmology_set_status_message(), CCL_ERROR_INCONSISTENT, ccl_tracer_corr_bessel(), ccl_tracer_corr_fftlog(), and ccl_tracer_corr_legendre().
Referenced by compare_corr(), and main().
 {
   switch(flag_method) {
   case CCL_CORR_FFTLOG :
     ccl_tracer_corr_fftlog(cosmo,n_ell,ell,cls,n_theta,theta,wtheta,corr_type,
                do_taper_cl,taper_cl_limits,status);
     break;
   case CCL_CORR_LGNDRE :
     ccl_tracer_corr_legendre(cosmo,n_ell,ell,cls,n_theta,theta,wtheta,corr_type,
                  do_taper_cl,taper_cl_limits,status);
     break;
   case CCL_CORR_BESSEL :
     ccl_tracer_corr_bessel(cosmo,n_ell,ell,cls,n_theta,theta,wtheta,corr_type,status);
     break;
   default :
     *status=CCL_ERROR_INCONSISTENT;
     ccl_cosmology_set_status_message(cosmo, "ccl_correlation.c: ccl_correlation. Unknown algorithm\n");
   }
   ccl_check_status(cosmo,status);
 }
void ccl_correlation_3d (ccl_cosmology * cosmo, double a, int n_r, double * r, double * xi, int do_taper_pk, double * taper_pk_limits, int * status)
Computes the 3dcorrelation function (wrapper)
Parameters
cosmo :Cosmological parameters
a : scale factor
n_r : number of output values of distance r
r : values of the distance in Mpc
xi : the values of the correlation function at the distances above will be returned in this array, which should be pre-allocated
do_taper_pk : key for tapering (using cosine tapering by default)
taper_pk_limits limits of tapering
Definition at line 427 of file ccl_correlation.c.
References ccl_check_status(), ccl_cosmology_set_status_message(), CCL_ERROR_MEMORY, ccl_log_spacing(), ccl_nonlin_matter_power(), ccl_spline_eval(), ccl_spline_free(), ccl_spline_init(), ccl_splines, ccl_spline_params::K_MAX, ccl_spline_params::K_MIN, ccl_spline_params::N_K_3DCOR, pk2xi(), and taper_cl().
Referenced by compare_correlation_3d(), and main().
 {
   int i,N_ARR;
   double *k_arr,*pk_arr,*r_arr,*xi_arr;
   //number of data points for k and pk array
   N_ARR=(int)(ccl_splines->N_K_3DCOR*log10(ccl_splines->K_MAX/ccl_splines->K_MIN));
   k_arr=ccl_log_spacing(ccl_splines->K_MIN,ccl_splines->K_MAX,N_ARR);
   if(k_arr==NULL) {
     *status=CCL_ERROR_MEMORY;
     ccl_cosmology_set_status_message(cosmo, "ccl_correlation.c: ccl_correlation_3d ran out of memory\n");
     return;
   }
   pk_arr=malloc(N_ARR*sizeof(double));
   if(pk_arr==NULL) {
     free(k_arr);
     *status=CCL_ERROR_MEMORY;
     ccl_cosmology_set_status_message(cosmo, "ccl_correlation.c: ccl_correlation_3d ran out of memory\n");
     return;
   }
   for (i=0; i<N_ARR; i++)
     pk_arr[i] = ccl_nonlin_matter_power(cosmo, k_arr[i], a, status);
   if (do_taper_pk)
     taper_cl(N_ARR,k_arr,pk_arr,taper_pk_limits);
   r_arr=malloc(sizeof(double)*N_ARR);
   if(r_arr==NULL) {
     free(k_arr);
     free(pk_arr);
     *status=CCL_ERROR_MEMORY;
     ccl_cosmology_set_status_message(cosmo, "ccl_correlation.c: ccl_correlation_3d ran out of memory\n");
     return;
   }
   xi_arr=malloc(sizeof(double)*N_ARR);
   if(xi_arr==NULL) {
     free(k_arr); free(pk_arr); free(r_arr);
     *status=CCL_ERROR_MEMORY;
     ccl_cosmology_set_status_message(cosmo, "ccl_correlation.c: ccl_correlation_3d ran out of memory\n");
     return;
   }
   for(i=0;i<N_ARR;i++)
     r_arr[i]=0;
   pk2xi(N_ARR,k_arr,pk_arr,r_arr,xi_arr);
   // Interpolate to output values of r
   SplPar *xi_spl=ccl_spline_init(N_ARR,r_arr,xi_arr,xi_arr[0],0);
   for(i=0;i<n_r;i++)
     xi[i]=ccl_spline_eval(r[i],xi_spl);
   ccl_spline_free(xi_spl);
   free(k_arr); free(pk_arr);
   free(r_arr); free(xi_arr);
   ccl_check_status(cosmo,status);
   return;
 }