Fast Methods for Cosmological Simulations: src/3party/CCL/tests/ccl_test_halomod.c File Reference
ccl_test_halomod.c File Reference
#include "ccl.h"
#include "ccl_halomod.h"
#include "ctest.h"
#include <stdio.h>
#include <math.h>
#include <string.h>
Classes
struct halomod_data
Macros
#define HALOMOD_TOLERANCE 1E-3
#define NUMK 256
Functions
static void read_halomod_test_file (double k[3][2][256], double Pk[3][2][256])
void __attribute__ ((weak))
static void compare_halomod (int model, struct halomod_data *data)
void __ctest_halomod_model_1_run (struct halomod_data *data)
void __ctest_halomod_model_2_run (struct halomod_data *data)
void __ctest_halomod_model_3_run (struct halomod_data *data)
Variables
static struct halomod_data __ctest_halomod_data
Macro Definition Documentation
#define HALOMOD_TOLERANCE 1E-3
Definition at line 9 of file ccl_test_halomod.c.
Referenced by compare_halomod().
#define NUMK 256
Definition at line 10 of file ccl_test_halomod.c.
Referenced by compare_halomod(), and read_halomod_test_file().
Function Documentation
void __attribute__ ((weak))
Definition at line 80 of file ccl_test_halomod.c.
References ccl_mnu_sum, ccl_test_distances::h, ccl_test_distances::n_s, ccl_test_distances::Omega_b, ccl_test_distances::Omega_c, and read_halomod_test_file().
                     {
   // Move the cosmological parameters to the data structure
   data->Omega_k = 0.00;
   data->Neff = 0.00;
   double mnuval = 0.00;
   data->mnu = &mnuval;
   data->mnu_type = ccl_mnu_sum;
   data->w_0 = -1.00;
   data->w_a = 0.00;
   // Cosmological parameters that are different for different tests
   double Omega_c[3] = { 0.2500, 0.2265, 0.2685 };
   double Omega_b[3] = { 0.0500, 0.0455, 0.0490 };
   double h[3]       = { 0.7000, 0.7040, 0.6711 };
   double sigma_8[3] = { 0.8000, 0.8100, 0.8340 };
   double n_s[3]     = { 0.9600, 0.9670, 0.9624 };
   // Fill in the values from these constant arrays
   for (int model=0; model<3; model++){
     data->Omega_c[model] = Omega_c[model];
     data->Omega_b[model] = Omega_b[model];
     data->h[model]       = h[model];
     data->sigma_8[model] = sigma_8[model];
     data->n_s[model]     = n_s[model];
   }
   // read the file of benchmark data
   read_halomod_test_file(data->k, data->Pk);
 }
void __ctest_halomod_model_1_run (struct halomod_data * data)
Definition at line 169 of file ccl_test_halomod.c.
References compare_halomod().
{
   int model = 0;
   compare_halomod(model, data);
 }
void __ctest_halomod_model_2_run (struct halomod_data * data)
Definition at line 174 of file ccl_test_halomod.c.
References compare_halomod().
{
   int model = 1;
   compare_halomod(model, data);
 }
void __ctest_halomod_model_3_run (struct halomod_data * data)
Definition at line 179 of file ccl_test_halomod.c.
References compare_halomod().
{
   int model = 2;
   compare_halomod(model, data);
 }
static void compare_halomod (int model, struct halomod_data * data) static
Definition at line 113 of file ccl_test_halomod.c.
References ASSERT_DBL_NEAR_TOL, ASSERT_NOT_NULL, ccl_cosmology_create(), ccl_duffy2008, ccl_eisenstein_hu, ccl_halomodel_matter_power(), ccl_parameters_create(), ccl_shethtormen, cl_cmbl_bm::cosmo, default_config, halomod_data::h, ccl_parameters::h, ccl_configuration::halo_concentration_method, HALOMOD_TOLERANCE, halomod_data::k, ccl_configuration::mass_function_method, halomod_data::mnu, halomod_data::mnu_type, halomod_data::n_s, halomod_data::Neff, NUMK, halomod_data::Omega_b, halomod_data::Omega_c, halomod_data::Omega_k, halomod_bm::params, halomod_data::Pk, pow(), halomod_data::sigma_8, ccl_configuration::transfer_function_method, halomod_data::w_0, and halomod_data::w_a.
Referenced by __ctest_halomod_model_1_run(), __ctest_halomod_model_2_run(), and __ctest_halomod_model_3_run().
 {
   // Status variables
   int stat = 0;
   int* status = &stat;
   // Set the cosmology
   ccl_parameters params = ccl_parameters_create(data->Omega_c[model], data->Omega_b[model],data->Omega_k,
                         data->Neff, data->mnu, data->mnu_type, data->w_0,
                         data->w_a, data->h[model],data->sigma_8[model], data->n_s[model],
                         -1, -1, -1, -1, NULL, NULL, status);
   // Set the default configuration, but with Eisenstein & Hu linear P(k) and Sheth & Tormen mass function and Duffy (2008) halo concentrations
   ccl_configuration config = default_config;
   config.transfer_function_method = ccl_eisenstein_hu;
   config.mass_function_method = ccl_shethtormen;
   config.halo_concentration_method = ccl_duffy2008;
   // Set the configuration
   ccl_cosmology * cosmo = ccl_cosmology_create(params, config);
   // Check that the cosmology is assigned correctly
   ASSERT_NOT_NULL(cosmo);
   // Loop over redshifts
   for (int i=0; i<2; i++) {
     // Variables for the test
     double a;
     if(i==0){a = 1.0;}
     if(i==1){a = 0.5;}
     // Loop over wavenumbers
     for (int j=0; j<NUMK; j++) {
       // Set variables inside loop, convert CCL outputs to the same units as benchmark
       double k = data->k[model][i][j]*params.h; // Convert the benchmark data k/h to pure k
       double Pk = data->Pk[model][i][j]/pow(params.h,3); // Convert the benchmark data Pk units to remove factors of h
       double Pk_ccl = ccl_halomodel_matter_power(cosmo, k, a, status); // Get CCL P(k)
       double absolute_tolerance = HALOMOD_TOLERANCE*Pk; // Convert relative -> absolute tolerance
       // Do the check
       ASSERT_DBL_NEAR_TOL(Pk, Pk_ccl, absolute_tolerance);
     }
   }
   // Free the cosmology object
   free(cosmo);
 }
static void read_halomod_test_file (double k[3][2][256], double Pk[3][2][256]) static
Definition at line 35 of file ccl_test_halomod.c.
References ASSERT_EQUAL, ASSERT_NOT_NULL, Catch::Matchers::Vector::Detail::count(), and NUMK.
Referenced by __attribute__().
{
   // Variables for reading in unwanted stuff and file name
   double spam;
   char infile[256];
   // Loop over cosmological models
   for (int model=0; model<3; model++){
     // Loop over redshifts
     for (int i=0; i<2; i++){
       // File names for different redshifts and cosmological models
       if(model==0 && i==0){strncpy(infile, "./tests/benchmark/pk_hm_c1_z0.txt", 256);}
       if(model==0 && i==1){strncpy(infile, "./tests/benchmark/pk_hm_c1_z1.txt", 256);}
       if(model==1 && i==0){strncpy(infile, "./tests/benchmark/pk_hm_c2_z0.txt", 256);}
       if(model==1 && i==1){strncpy(infile, "./tests/benchmark/pk_hm_c2_z1.txt", 256);}
       if(model==2 && i==0){strncpy(infile, "./tests/benchmark/pk_hm_c3_z0.txt", 256);}
       if(model==2 && i==1){strncpy(infile, "./tests/benchmark/pk_hm_c3_z1.txt", 256);}
       // Open the file
       FILE * f = fopen(infile, "r");
       ASSERT_NOT_NULL(f);
       // Loop over wavenumbers, which  are k/h in benchmark data, power is Delta^2(k)
       for (int j=0; j<NUMK; j++) {
     // Read in data from the benchmark file
     int count = fscanf(f, "%le\t %le\t %le\t %le\t %le\n", &k[model][i][j], &spam, &spam, &spam, &Pk[model][i][j]);
     // Check that we have read in enough columns from the benchmark file
     ASSERT_EQUAL(5, count);
       }
       // Close the file
       fclose(f);
     }
   }
 }
Variable Documentation
static struct halomod_data __ctest_halomod_data static
Definition at line 169 of file ccl_test_halomod.c.