Fast Methods for Cosmological Simulations: src/3party/CCL/tests/ccl_test_sigmaM.c File Reference
ccl_test_sigmaM.c File Reference
#include "ccl.h"
#include "ctest.h"
#include <stdio.h>
#include <math.h>
Classes
struct sigmam_data
Macros
#define SIGMAM_TOLERANCE 3.0E-5
Functions
void __attribute__ ((weak))
static int linecount (FILE *f)
static void compare_sigmam (int i_model, struct sigmam_data *data)
void __ctest_sigmam_model_1_run (struct sigmam_data *data)
void __ctest_sigmam_model_2_run (struct sigmam_data *data)
void __ctest_sigmam_model_3_run (struct sigmam_data *data)
Variables
static struct sigmam_data __ctest_sigmam_data
Macro Definition Documentation
#define SIGMAM_TOLERANCE 3.0E-5
Definition at line 6 of file ccl_test_sigmaM.c.
Referenced by compare_sigmam().
Function Documentation
void __attribute__ ((weak))
Definition at line 24 of file ccl_test_sigmaM.c.
References ccl_mnu_sum.
                     {
   data->Omega_c = 0.25;
   data->Omega_b = 0.05;
   data->h = 0.7;
   data->A_s = 2.1e-9;
   data->sigma8=0.8;
   data->n_s = 0.96;
   data->Neff=0;
   double mnuval = 0.;
   data->mnu=&mnuval;
   data-> mnu_type = ccl_mnu_sum;
   double Omega_v[5]={0.7, 0.7, 0.7, 0.65, 0.75};
   double w_0[5] = {-1.0, -0.9, -0.9, -0.9, -0.9};
   double w_a[5] = {0.0, 0.0, 0.1, 0.1, 0.1};
   for(int i=0;i<5;i++) {
     data->Omega_v[i] = Omega_v[i];
     data->w_0[i] = w_0[i];
     data->w_a[i] = w_a[i];
     data->Omega_k[i] = 1.0 - data->Omega_c - data->Omega_b - data->Omega_v[i];
   }
 }
void __ctest_sigmam_model_1_run (struct sigmam_data * data)
Definition at line 108 of file ccl_test_sigmaM.c.
References compare_sigmam().
{
   int model=1;
   compare_sigmam(model,data);
 }
void __ctest_sigmam_model_2_run (struct sigmam_data * data)
Definition at line 113 of file ccl_test_sigmaM.c.
References compare_sigmam().
{
   int model=2;
   compare_sigmam(model,data);
 }
void __ctest_sigmam_model_3_run (struct sigmam_data * data)
Definition at line 118 of file ccl_test_sigmaM.c.
References compare_sigmam().
{
   int model=3;
   compare_sigmam(model,data);
 }
static void compare_sigmam (int i_model, struct sigmam_data * data) static
Definition at line 60 of file ccl_test_sigmaM.c.
References sigmam_data::A_s, ASSERT_DBL_NEAR_TOL, ASSERT_NOT_NULL, ccl_bbks, ccl_cosmology_create(), ccl_parameters_create(), ccl_sigmaM(), cl_cmbl_bm::cosmo, default_config, sigmam_data::h, linecount(), m, sigmam_data::mnu, sigmam_data::mnu_type, sigmam_data::n_s, sigmam_data::Neff, sigmam_data::Omega_b, sigmam_data::Omega_c, ccl_parameters::Omega_g, sigmam_data::Omega_k, ccl_parameters::Omega_l, sigmam_data::Omega_v, halomod_bm::params, sigmam_data::sigma8, ccl_parameters::sigma8, SIGMAM_TOLERANCE, ccl_cosmology::status_message, ccl_configuration::transfer_function_method, sigmam_data::w_0, and sigmam_data::w_a.
Referenced by __ctest_sigmam_model_1_run(), __ctest_sigmam_model_2_run(), and __ctest_sigmam_model_3_run().
 {
   int nm,i;
   char fname[256],str[1024];
   char* rtn;
   FILE *f;
   int status=0;
   ccl_configuration config = default_config;
   config.transfer_function_method = ccl_bbks;
   ccl_parameters params = ccl_parameters_create(data->Omega_c,data->Omega_b,data->Omega_k[i_model-1],
                         data->Neff, data->mnu, data->mnu_type,
                         data->w_0[i_model-1],data->w_a[i_model-1],data->h,
                         data->A_s,data->n_s,-1,-1,-1,-1,NULL,NULL, &status);
   params.sigma8=data->sigma8;
   params.Omega_g=0.;
   params.Omega_l=data->Omega_v[i_model-1];
   ccl_cosmology * cosmo = ccl_cosmology_create(params, config);
   ASSERT_NOT_NULL(cosmo);
   sprintf(fname,"./tests/benchmark/model%d_sm.txt",i_model);
   f=fopen(fname,"r");
   if(f==NULL) {
     fprintf(stderr,"Error opening file %s\n",fname);
     exit(1);
   }
   nm=linecount(f)-1; rewind(f);
   rtn = fgets(str, 1024, f);
   for(i=0;i<nm;i++) {
     double m,m_h,sm_bench,sm_h,err;
     int stat;
     stat=fscanf(f,"%lf %lf",&m_h,&sm_bench);
     if(stat!=2) {
       fprintf(stderr,"Error reading file %s, line %d\n",fname,i+2);
       exit(1);
     }
     m=m_h/data->h;
     sm_h=ccl_sigmaM(cosmo,m,1.,&status);
     if (status) printf("%s\n",cosmo->status_message);
     err=sm_h/sm_bench-1;
     ASSERT_DBL_NEAR_TOL(err,0.,SIGMAM_TOLERANCE);
   }
   fclose(f);
   free(cosmo);
 }
static int linecount (FILE * f) static
Definition at line 48 of file ccl_test_sigmaM.c.
Referenced by compare_sigmam().
 {
   // Counts #lines from file
   int i0=0;
   char ch[1000];
   while((fgets(ch,sizeof(ch),f))!=NULL) {
     i0++;
   }
   return i0;
 }
Variable Documentation
static struct sigmam_data __ctest_sigmam_data static
Definition at line 108 of file ccl_test_sigmaM.c.