Fast Methods for Cosmological Simulations: src/3party/CCL/include/ccl_halomod.h File Reference
ccl_halomod.h File Reference
Macros
#define HM_MMIN 1e7
#define HM_MMAX 1e17
#define HM_EPSABS 0
#define HM_EPSREL 1E-4
#define HM_LIMIT 1000
#define HM_INT_METHOD GSL_INTEG_GAUSS41
Typedefs
typedef CCL_BEGIN_DECLS enum ccl_win_label ccl_win_label
Enumerations
enum ccl_win_label { ccl_nfw = 1 }
Functions
double ccl_twohalo_matter_power (ccl_cosmology *cosmo, double k, double a, int *status)
double ccl_onehalo_matter_power (ccl_cosmology *cosmo, double k, double a, int *status)
double ccl_halomodel_matter_power (ccl_cosmology *cosmo, double k, double a, int *status)
double ccl_halo_concentration (ccl_cosmology *cosmo, double halomass, double a, double odelta, int *status)
Macro Definition Documentation
#define HM_EPSABS 0
Definition at line 8 of file ccl_halomod.h.
Referenced by one_halo_integral(), and two_halo_integral().
#define HM_EPSREL 1E-4
Definition at line 9 of file ccl_halomod.h.
Referenced by one_halo_integral(), and two_halo_integral().
#define HM_INT_METHOD GSL_INTEG_GAUSS41
Definition at line 11 of file ccl_halomod.h.
Referenced by one_halo_integral(), and two_halo_integral().
#define HM_LIMIT 1000
Definition at line 10 of file ccl_halomod.h.
Referenced by one_halo_integral(), and two_halo_integral().
#define HM_MMAX 1e17
Definition at line 7 of file ccl_halomod.h.
Referenced by one_halo_integral(), and two_halo_integral().
#define HM_MMIN 1e7
Definition at line 6 of file ccl_halomod.h.
Referenced by ccl_twohalo_matter_power(), one_halo_integral(), and two_halo_integral().
Typedef Documentation
typedef CCL_BEGIN_DECLS enum ccl_win_label ccl_win_label
Enumeration Type Documentation
enum ccl_win_label
Enumerator
ccl_nfw
Definition at line 16 of file ccl_halomod.h.
{
     ccl_nfw = 1,
   } ccl_win_label;
Function Documentation
double ccl_halo_concentration (ccl_cosmology * cosmo, double halomass, double a, double odelta, int * status)
Computes the concentration of a halo of mass M. This is the ratio of virial raidus to scale radius for an NFW halo.
Parameters
cosmo cosmology object containing parameters
halomass halo mass in units of Msun
a scale factor normalised to a=1 today
odelta overdensity criteria (with respect to matter density) used for halo mass
status Status flag: 0 if there are no errors, non-zero otherwise
Returns
halo_concentration: the halo concentration
Definition at line 52 of file ccl_halomod.c.
References ccl_bhattacharya2011, ccl_constant_concentration, ccl_cosmology_set_status_message(), ccl_duffy2008, CCL_ERROR_CONC_DV, CCL_ERROR_HALOCONC, ccl_growth_factor(), ccl_raise_exception(), ccl_sigmaM(), ccl_cosmology::config, Dv_BryanNorman(), ccl_parameters::h, ccl_configuration::halo_concentration_method, ccl_cosmology::params, and pow().
Referenced by window_function().
{
   double gz, g0, nu, delta_c, a_form;
   double Mpiv, A, B, C;
   switch(cosmo->config.halo_concentration_method){
     // Bhattacharya et al. (2011; 1005.2239; Delta = 200rho_m; Table 2)
   case ccl_bhattacharya2011:
     if (odelta != 200.) {
       *status = CCL_ERROR_CONC_DV;
       ccl_cosmology_set_status_message(cosmo, "ccl_halomod.c: halo_concentration(): Bhattacharya (2011) concentration relation only valid for Delta_v = 200 \n");
       return NAN;
     }
     gz = ccl_growth_factor(cosmo,a,status);
     g0 = ccl_growth_factor(cosmo,1.0,status);
     delta_c = 1.686;
     nu = delta_c/ccl_sigmaM(cosmo, halomass, a, status);
     return 9.*pow(nu,-0.29)*pow(gz/g0,1.15);
     // Duffy et al. (2008; 0804.2486; Table 1)
   case ccl_duffy2008:
     Mpiv = 2e12/cosmo->params.h; // Pivot mass in Msun (note in the paper units are Msun/h)
     if (odelta == Dv_BryanNorman(cosmo, a, status)) {
       // Duffy et al. (2008) for virial density haloes (second section in Table 1)
       A = 7.85;
       B = -0.081;
       C = -0.71;
       return A*pow(halomass/Mpiv,B)*pow(a,-C);
     } else if (odelta == 200.) {
       // Duffy et al. (2008) for x200 mean-matter-density haloes (third section in Table 1)
       A = 10.14;
       B = -0.081;
       C = -1.01;
       return A*pow(halomass/Mpiv,B)*pow(a,-C);
     } else {
       *status = CCL_ERROR_CONC_DV;
       ccl_cosmology_set_status_message(cosmo, "ccl_halomod.c: halo_concentration(): Duffy (2008) virial concentration only valid for virial Delta_v or 200\n");
       return NAN;
     }
     // Constant concentration (good for tests)
   case ccl_constant_concentration:
     return 4.;
     // Something went wrong
   default:
     *status = CCL_ERROR_HALOCONC;
     ccl_raise_exception(*status, "ccl_halomod.c: concentration-mass relation specified incorrectly");
     return NAN;
   }
 }
double ccl_halomodel_matter_power (ccl_cosmology * cosmo, double k, double a, int * status)
Computes the halo model density-density power spectrum as the sum of two- and one-halo terms.
Parameters
cosmo cosmology object containing parameters
k wavenumber in units of Mpc^{-1}
a scale factor normalised to a=1 today
status Status flag: 0 if there are no errors, non-zero otherwise
Returns
halomodel_matter_power: halo-model power spectrum, P(k), units of Mpc^{3}
Definition at line 314 of file ccl_halomod.c.
References ccl_onehalo_matter_power(), and ccl_twohalo_matter_power().
Referenced by compare_halomod().
{
   // Standard sum of two- and one-halo terms
   return ccl_twohalo_matter_power(cosmo, k, a, status)+ccl_onehalo_matter_power(cosmo, k, a, status);
 }
double ccl_onehalo_matter_power (ccl_cosmology * cosmo, double k, double a, int * status)
Computes the halo model density-density power spectrum one-halo term.
Parameters
cosmo cosmology object containing parameters
k wavenumber in units of Mpc^{-1}
a scale factor normalised to a=1 today
status Status flag: 0 if there are no errors, non-zero otherwise
Returns
1halo_matter_power: halo-model one-halo matter power spectrum, P(k), units of Mpc^{3}
Definition at line 304 of file ccl_halomod.c.
References one_halo_integral().
Referenced by ccl_halomodel_matter_power().
{
   return one_halo_integral(cosmo, k, a, status);
 }
double ccl_twohalo_matter_power (ccl_cosmology * cosmo, double k, double a, int * status)
Computes the halo model density-density power spectrum two-halo term.
Parameters
cosmo cosmology object containing parameters
k wavenumber in units of Mpc^{-1}
a scale factor normalised to a=1 today
status Status flag: 0 if there are no errors, non-zero otherwise
Returns
2halo_matter_power: halo-model two-halo matter power spectrum, P(k), units of Mpc^{3}
Definition at line 277 of file ccl_halomod.c.
References ccl_linear_matter_power(), ccl_nfw, Dv_BryanNorman(), HM_MMIN, two_halo_integral(), and window_function().
Referenced by ccl_halomodel_matter_power().
{
   // Get the integral
   double I2h = two_halo_integral(cosmo, k, a, status);
   // The addative correction is the missing part of the integral below the lower-mass limit
   double A = 1.-two_halo_integral(cosmo, 0., a, status);
   // Virial overdensity for haloes
   double odelta = Dv_BryanNorman(cosmo, a, status);
   // ...multiplied by the ratio of window functions
   double W1 = window_function(cosmo, HM_MMIN, k,  a, odelta, ccl_nfw, status);
   double W2 = window_function(cosmo, HM_MMIN, 0., a, odelta, ccl_nfw, status);
   A = A*W1/W2;
   // Add the additive correction to the calculated integral
   I2h = I2h+A;
   return ccl_linear_matter_power(cosmo, k, a, status)*I2h*I2h;
 }