Fast Methods for Cosmological Simulations: src/3party/CCL/include/ccl_error.h File Reference
ccl_error.h File Reference
Macros
#define CCL_BOUNDS_CHECK_INTERP
#define CCL_ERROR_MEMORY 1025
#define CCL_ERROR_LINSPACE 1026
#define CCL_ERROR_INCONSISTENT 1027
#define CCL_ERROR_SPLINE 1028
#define CCL_ERROR_SPLINE_EV 1029
#define CCL_ERROR_INTEG 1030
#define CCL_ERROR_ROOT 1031
#define CCL_ERROR_CLASS 1032
#define CCL_ERROR_COMPUTECHI 1033
#define CCL_ERROR_MF 1034
#define CCL_ERROR_HMF_INTERP 1035
#define CCL_ERROR_PARAMETERS 1036
#define CCL_ERROR_NU_INT 1037
#define CCL_ERROR_EMULATOR_BOUND 1038
#define CCL_ERROR_NU_SOLVE 1039
#define CCL_ERROR_NOT_IMPLEMENTED 1040
#define CCL_ERROR_MNU_UNPHYSICAL 1041
#define CCL_ERROR_ANGPOW 1042
#define CCL_ERROR_MISSING_CONFIG_FILE 1043
#define CCL_ERROR_HALOCONC 1044
#define CCL_ERROR_HALOWIN 1045
#define CCL_ERROR_HMF_DV 1046
#define CCL_ERROR_CONC_DV 1047
#define CCL_ERROR_ONE_HALO_INT 1048
#define CCL_ERROR_TWO_HALO_INT 1049
#define CCL_ERROR_FILE_WRITE 1050
#define CCL_ERROR_FILE_READ 1051
#define CCL_ERROR_LOGSPACE 1052
#define CCL_ERROR_LINLOGSPACE 1053
#define CCL_ERROR_CONFIG_FILE 1054
Enumerations
enum CCLErrorPolicy { CCL_ERROR_POLICY_EXIT = 0, CCL_ERROR_POLICY_CONTINUE = 1 }
enum CCLDebugModePolicy { CCL_DEBUG_MODE_OFF = 0, CCL_DEBUG_MODE_ON = 1, CCL_DEBUG_MODE_WARNING = 2 }
Functions
void ccl_raise_exception (int err, const char *msg,...)
void ccl_raise_warning (int err, const char *msg,...)
void ccl_raise_gsl_warning (int gslstatus, const char *msg,...)
void ccl_set_error_policy (CCLErrorPolicy error_policy)
void ccl_set_debug_policy (CCLDebugModePolicy debug_policy)
void ccl_check_status (ccl_cosmology *cosmo, int *status)
void ccl_check_status_nocosmo (int *status)
Macro Definition Documentation
#define CCL_BOUNDS_CHECK_INTERP
Definition at line 8 of file ccl_error.h.
#define CCL_ERROR_ANGPOW 1042
Definition at line 27 of file ccl_error.h.
#define CCL_ERROR_CLASS 1032
Definition at line 17 of file ccl_error.h.
Referenced by ccl_cosmology_compute_power_class(), ccl_cosmology_compute_power_emu(), ccl_cosmology_write_power_class_z(), ccl_free_class_structs(), ccl_get_class_As(), and ccl_run_class().
#define CCL_ERROR_COMPUTECHI 1033
Definition at line 18 of file ccl_error.h.
Referenced by a_of_chi(), ccl_check_status(), ccl_check_status_nocosmo(), ccl_comoving_angular_distance(), ccl_comoving_radial_distance(), ccl_cosmology_compute_distances(), ccl_distance_modulus(), ccl_growth_factor(), ccl_growth_rate(), ccl_scale_factor_of_chi(), and compute_chi().
#define CCL_ERROR_CONC_DV 1047
Definition at line 32 of file ccl_error.h.
Referenced by ccl_halo_concentration().
#define CCL_ERROR_CONFIG_FILE 1054
Definition at line 39 of file ccl_error.h.
#define CCL_ERROR_EMULATOR_BOUND 1038
Definition at line 23 of file ccl_error.h.
Referenced by ccl_nonlin_matter_power(), and ccl_pkemu().
#define CCL_ERROR_FILE_READ 1051
Definition at line 36 of file ccl_error.h.
Referenced by ccl_parameters_read_yaml().
#define CCL_ERROR_FILE_WRITE 1050
Definition at line 35 of file ccl_error.h.
Referenced by ccl_parameters_write_yaml().
#define CCL_ERROR_HALOCONC 1044
Definition at line 29 of file ccl_error.h.
Referenced by ccl_halo_concentration().
#define CCL_ERROR_HALOWIN 1045
Definition at line 30 of file ccl_error.h.
Referenced by window_function().
#define CCL_ERROR_HMF_DV 1046
Definition at line 31 of file ccl_error.h.
Referenced by ccl_halo_b1(), and massfunc_f().
#define CCL_ERROR_HMF_INTERP 1035
Definition at line 20 of file ccl_error.h.
Referenced by ccl_check_status(), ccl_check_status_nocosmo(), and massfunc_f().
#define CCL_ERROR_INCONSISTENT 1027
Definition at line 12 of file ccl_error.h.
Referenced by ccl_correlation(), ccl_cosmology_compute_power(), ccl_cosmology_compute_power_bbks(), ccl_cosmology_compute_power_eh(), ccl_cosmology_compute_power_emu(), ccl_fill_class_parameters(), ccl_get_tracer_fa(), ccl_get_tracer_fas(), ccl_linear_matter_power(), and cl_tracer().
#define CCL_ERROR_INTEG 1030
Definition at line 15 of file ccl_error.h.
Referenced by ccl_angular_cl_native(), ccl_cosmology_compute_distances(), ccl_cosmology_compute_growth(), ccl_dNdz_tomog(), clt_init_nz(), clt_init_wL(), and clt_init_wM().
#define CCL_ERROR_LINLOGSPACE 1053
Definition at line 38 of file ccl_error.h.
Referenced by ccl_linlog_spacing().
#define CCL_ERROR_LINSPACE 1026
Definition at line 11 of file ccl_error.h.
Referenced by ccl_check_status(), ccl_check_status_nocosmo(), ccl_cosmology_compute_distances(), ccl_cosmology_compute_growth(), ccl_cosmology_compute_sigma(), ccl_tracer_corr_fftlog(), clt_init_wL(), and clt_init_wM().
#define CCL_ERROR_LOGSPACE 1052
Definition at line 37 of file ccl_error.h.
Referenced by ccl_log_spacing().
#define CCL_ERROR_MEMORY 1025
Definition at line 10 of file ccl_error.h.
Referenced by ccl_angular_cls(), ccl_cl_workspace_new(), ccl_correlation_3d(), ccl_cosmology_compute_distances(), ccl_cosmology_compute_growth(), ccl_cosmology_compute_power_bbks(), ccl_cosmology_compute_power_eh(), ccl_cosmology_compute_power_emu(), ccl_cosmology_read_config(), ccl_linear_spacing(), ccl_linlog_spacing(), ccl_log_spacing(), ccl_tracer_corr_bessel(), ccl_tracer_corr_fftlog(), ccl_tracer_corr_legendre(), cl_tracer(), clt_init_nz(), clt_init_wL(), and clt_init_wM().
#define CCL_ERROR_MF 1034
Definition at line 19 of file ccl_error.h.
Referenced by ccl_halo_b1(), and massfunc_f().
#define CCL_ERROR_MISSING_CONFIG_FILE 1043
Definition at line 28 of file ccl_error.h.
Referenced by calculate_nu_phasespace_spline(), ccl_cosmology_read_config(), ccl_dNdz_tomog(), and ccl_norm_integrand().
#define CCL_ERROR_MNU_UNPHYSICAL 1041
Definition at line 26 of file ccl_error.h.
Referenced by ccl_check_status_nocosmo(), ccl_nu_masses(), and ccl_parameters_create().
#define CCL_ERROR_NOT_IMPLEMENTED 1040
Definition at line 25 of file ccl_error.h.
Referenced by ccl_check_status_nocosmo(), ccl_cosmology_compute_growth(), ccl_growth_factor(), ccl_growth_factor_unnorm(), ccl_growth_rate(), ccl_halo_bias(), ccl_massfunc(), ccl_nonlin_matter_power(), ccl_parameters_create(), ccl_sigmaM(), ccl_tracer_corr_legendre(), and clt_nc_init().
#define CCL_ERROR_NU_INT 1037
Definition at line 22 of file ccl_error.h.
Referenced by calculate_nu_phasespace_spline(), ccl_check_status(), and ccl_check_status_nocosmo().
#define CCL_ERROR_NU_SOLVE 1039
Definition at line 24 of file ccl_error.h.
Referenced by ccl_check_status(), and ccl_check_status_nocosmo().
#define CCL_ERROR_ONE_HALO_INT 1048
Definition at line 33 of file ccl_error.h.
Referenced by one_halo_integral().
#define CCL_ERROR_PARAMETERS 1036
Definition at line 21 of file ccl_error.h.
Referenced by ccl_omega_x(), and ccl_sinn().
#define CCL_ERROR_ROOT 1031
Definition at line 16 of file ccl_error.h.
Referenced by ccl_cosmology_compute_distances().
#define CCL_ERROR_SPLINE 1028
Definition at line 13 of file ccl_error.h.
Referenced by ccl_check_status(), ccl_check_status_nocosmo(), ccl_cosmology_compute_distances(), ccl_cosmology_compute_growth(), ccl_cosmology_compute_hmfparams(), ccl_cosmology_compute_power_bbks(), ccl_cosmology_compute_power_class(), ccl_cosmology_compute_power_eh(), ccl_cosmology_compute_power_emu(), ccl_cosmology_compute_sigma(), clt_init_ba(), clt_init_bz(), clt_init_nz(), clt_init_rf(), clt_init_wL(), and clt_init_wM().
#define CCL_ERROR_SPLINE_EV 1029
Definition at line 14 of file ccl_error.h.
Referenced by ccl_angular_cls(), ccl_linear_matter_power(), ccl_nonlin_matter_power(), ccl_power_extrapol_highk(), and ccl_power_extrapol_lowk().
#define CCL_ERROR_TWO_HALO_INT 1049
Definition at line 34 of file ccl_error.h.
Referenced by two_halo_integral().
Enumeration Type Documentation
enum CCLDebugModePolicy
Enumerator
CCL_DEBUG_MODE_OFF
CCL_DEBUG_MODE_ON
CCL_DEBUG_MODE_WARNING
Definition at line 46 of file ccl_error.h.
              {
   CCL_DEBUG_MODE_OFF = 0,
   CCL_DEBUG_MODE_ON = 1,
   CCL_DEBUG_MODE_WARNING = 2,
 } CCLDebugModePolicy;
enum CCLErrorPolicy
Enumerator
CCL_ERROR_POLICY_EXIT
CCL_ERROR_POLICY_CONTINUE
Definition at line 41 of file ccl_error.h.
              {
   CCL_ERROR_POLICY_EXIT = 0,
   CCL_ERROR_POLICY_CONTINUE = 1,
 } CCLErrorPolicy;
Function Documentation
void ccl_check_status (ccl_cosmology * cosmo, int * status)
Check the error status Given a status, check if any errors have occurred, based on the CCL_ERRORs defined so far.
Returns
void
Definition at line 88 of file ccl_error.c.
References CCL_ERROR_COMPUTECHI, CCL_ERROR_HMF_INTERP, CCL_ERROR_LINSPACE, CCL_ERROR_NU_INT, CCL_ERROR_NU_SOLVE, CCL_ERROR_SPLINE, ccl_raise_exception(), and ccl_cosmology::status_message.
Referenced by ccl_angular_cl_native(), ccl_angular_cls(), ccl_cl_tracer(), ccl_comoving_angular_distance(), ccl_comoving_radial_distance(), ccl_correlation(), ccl_correlation_3d(), ccl_cosmology_compute_power(), ccl_distance_modulus(), ccl_dlninvsig_dlogm(), ccl_growth_factor(), ccl_growth_factor_unnorm(), ccl_growth_rate(), ccl_h_over_h0(), ccl_halo_bias(), ccl_omega_x(), ccl_scale_factor_of_chi(), ccl_sigmaM(), h_over_h0(), and massfunc_f().
 {
   switch (*status) {
   case 0: // all good, nothing to do
     return;
   case CCL_ERROR_LINSPACE:  // spacing allocation error, always terminate
     ccl_raise_exception(*status, cosmo->status_message);
   case CCL_ERROR_SPLINE:    // spline allocation error, always terminate
     ccl_raise_exception(*status, cosmo->status_message);
   case CCL_ERROR_COMPUTECHI:    // compute_chi error //RH
     ccl_raise_exception(*status, cosmo->status_message);
   case CCL_ERROR_HMF_INTERP: // terminate if hmf definition not supported
     ccl_raise_exception(*status, cosmo->status_message);
   case CCL_ERROR_NU_INT: // error in getting the neutrino integral spline: exit. No status_message in cosmo because can't pass cosmology to the function.
     ccl_raise_exception(*status, "Error, in ccl_neutrinos.c. ccl_calculate_nu_phasespace_spline(): Error in setting neutrino phasespace spline.");
   case CCL_ERROR_NU_SOLVE: // error in converting Omeganuh2-> Mnu: exit. No status_message in cosmo because can't pass cosmology to the function.
     ccl_raise_exception(*status, "Error, in ccl_neutrinos.c. Omeganuh2_to_Mnu(): Root finding did not converge.");
     // TODO: Implement softer error handling, e.g. for integral convergence here
   default:
     ccl_raise_exception(*status, cosmo->status_message);
   }
 }
void ccl_check_status_nocosmo (int * status)
Check the error status - no cosmology Given a status, check if any errors have occurred, based on the CCL_ERRORs defined so far.
Returns
void
Definition at line 116 of file ccl_error.c.
References CCL_ERROR_COMPUTECHI, CCL_ERROR_HMF_INTERP, CCL_ERROR_LINSPACE, CCL_ERROR_MNU_UNPHYSICAL, CCL_ERROR_NOT_IMPLEMENTED, CCL_ERROR_NU_INT, CCL_ERROR_NU_SOLVE, CCL_ERROR_SPLINE, and ccl_raise_exception().
Referenced by ccl_nu_masses(), ccl_parameters_create(), ccl_parameters_fill_initial(), and nu_phasespace_intg().
 {
   switch (*status) {
   case 0: // Nothing to do
     return;
   case CCL_ERROR_LINSPACE:
     // Spacing allocation error, always terminate
     ccl_raise_exception(*status, "CCL_ERROR_LINSPACE: Spacing allocation error.");
   case CCL_ERROR_SPLINE:
     // Spline allocation error, always terminate
     ccl_raise_exception(*status, "CCL_ERROR_SPLINE: Spline allocation error.");
   case CCL_ERROR_COMPUTECHI:
     // Compute_chi error
     ccl_raise_exception(*status,
              "CCL_ERROR_COMPUTECHI: Comoving distance chi computation failed.");
   case CCL_ERROR_HMF_INTERP:
     // Terminate if hmf definition not supported
     ccl_raise_exception(*status,
           "CCL_ERROR_HMF_INTERP: Halo mass function definition not supported.");
   case CCL_ERROR_NU_INT:
     // Error in getting the neutrino integral spline: exit. No status_message
     // in cosmo because can't pass cosmology to the function.
     ccl_raise_exception(*status,
       "CCL_ERROR_NU_INT: Error getting the neutrino phase-space integral spline.");
   case CCL_ERROR_NU_SOLVE:
     // Error in converting Omeganuh2-> Mnu: exit. No status_message in cosmo
     // because can't pass cosmology to the function.
     ccl_raise_exception(*status,
                       "CCL_ERROR_NU_SOLVE: Error converting Omeganuh2 -> Mnu.");
   case CCL_ERROR_MNU_UNPHYSICAL:
     // Error in the sum of mnu or Omeganu passed for the hierarchy requested.
       ccl_raise_exception(*status,
       "CCL_ERROR_MNU_UNPHYSICAL: Sum of neutrinos masses for this Omeganu value is incompatible with the requested mass hierarchy.");
   case CCL_ERROR_NOT_IMPLEMENTED:
     ccl_raise_exception(*status,
       "CCL_ERROR_NOT_IMPLEMENTED: the type of m_nu specified is not supported.");
   default:
     ccl_raise_exception(*status,
              "Unrecognized error code (see gsl_errno.h for error codes 1-32).");
   }
 }
void ccl_raise_exception (int err, const char * msg, ...)
Raise an exception Given a status, give an error message.
Returns
void
Definition at line 35 of file ccl_error.c.
References _ccl_debug_mode_policy, _ccl_error_policy, CCL_DEBUG_MODE_ON, and CCL_ERROR_POLICY_EXIT.
Referenced by calculate_nu_phasespace_spline(), ccl_check_status(), ccl_check_status_nocosmo(), ccl_cosmology_read_config(), ccl_dNdz_tomog(), ccl_halo_concentration(), ccl_norm_integrand(), ccl_parameters_read_yaml(), ccl_pkemu(), and window_function().
 {
   char message[256];
   va_list va;
   va_start(va, msg);
   vsnprintf(message, 250, msg, va);
   va_end(va);
   // Print error message and exit if fatal errors are enabled
   if ((_ccl_error_policy == CCL_ERROR_POLICY_EXIT) && (err)) {
     fprintf(stderr, "ERROR %d: %s\n", err, message);
     exit(1);
   }
   // Print error message and exit if debug output is enabled
   else if ((_ccl_debug_mode_policy == CCL_DEBUG_MODE_ON) && (err)){
     fprintf(stderr, "ERROR %d: %s\n", err, message);
   }
 }
void ccl_raise_gsl_warning (int gslstatus, const char * msg, ...)
Raise a warning based on a GSL error message Given a GSL status, give a warning message.
Returns
void
Definition at line 75 of file ccl_error.c.
References ccl_raise_warning().
Referenced by a_of_chi(), calculate_nu_phasespace_spline(), ccl_angular_cl_native(), ccl_comoving_angular_distance(), ccl_comoving_radial_distance(), ccl_cosmology_compute_growth(), ccl_cosmology_compute_sigma(), ccl_dlninvsig_dlogm(), ccl_dNdz_tomog(), ccl_growth_factor(), ccl_growth_rate(), ccl_h_over_h0(), ccl_linear_matter_power(), ccl_nonlin_matter_power(), ccl_norm_integrand(), ccl_power_extrapol_highk(), ccl_power_extrapol_lowk(), ccl_scale_factor_of_chi(), ccl_sigmaM(), ccl_sigmaR(), ccl_sigmaV(), ccl_spline_eval(), ccl_tracer_corr_bessel(), clt_init_nz(), compute_chi(), growth_factor_and_growth_rate(), massfunc_f(), nu_phasespace_intg(), one_halo_integral(), two_halo_integral(), window_lensing(), and window_magnification().
 {
   char message[256];
   va_list va;
   va_start(va, msg);
   vsnprintf(message, 250, msg, va);
   va_end(va);
   ccl_raise_warning(gslstatus, "%s GSL error: %s", message, gsl_strerror(gslstatus));
   return;
 }
void ccl_raise_warning (int err, const char * msg, ...)
Raise a warning Given a status, give a warning message.
Returns
void
Definition at line 56 of file ccl_error.c.
References _ccl_debug_mode_policy, CCL_DEBUG_MODE_ON, and CCL_DEBUG_MODE_WARNING.
Referenced by ccl_linear_spacing(), ccl_linlog_spacing(), ccl_log_spacing(), ccl_nonlin_matter_power(), and ccl_raise_gsl_warning().
 {
   char message[256];
   va_list va;
   va_start(va, msg);
   vsnprintf(message, 250, msg, va);
   va_end(va);
   // For now just print warning to stderr if debug is enabled.
   // TODO: Implement some kind of error stack that can be passed on to, e.g.,
   // the python binding.
   if( (_ccl_debug_mode_policy == CCL_DEBUG_MODE_ON)
       || (_ccl_debug_mode_policy == CCL_DEBUG_MODE_WARNING) ) {
     fprintf(stderr, "WARNING: %s\n", message);
   }
 }
void ccl_set_debug_policy (CCLDebugModePolicy debug_policy)
Set the error policy debug_policy the debug mode policy
Returns
void
Definition at line 29 of file ccl_error.c.
References _ccl_debug_mode_policy.
Referenced by compare_cls(), compare_corr(), and Cosmo_Param::init().
 {
     _ccl_debug_mode_policy = debug_policy;
 }
void ccl_set_error_policy (CCLErrorPolicy error_policy)
Set the error policy error_policy the error policy
Returns
void
Definition at line 23 of file ccl_error.c.
References _ccl_error_policy.
Referenced by Cosmo_Param::init().
 {
   _ccl_error_policy = error_policy;
 }