Fast Methods for Cosmological Simulations: src/3party/CCL/tests/ccl_test_distances_astropy_mnu_hiz.c File Reference
ccl_test_distances_astropy_mnu_hiz.c File Reference
#include "ccl.h"
#include "ctest.h"
#include <stdio.h>
#include <math.h>
Classes
struct distances_astropy_mnu_hiz_data
Macros
#define DISTANCES_TOLERANCE 1.0e-3
Functions
static void read_chi_test_file (double z[5], double chi[5][5])
static void read_dm_test_file (double z[5], double dm[5][5])
void __attribute__ ((weak))
static void compare_distances_hiz_mnu (int model, struct distances_astropy_mnu_hiz_data *data)
void __ctest_distances_astropy_mnu_hiz_model_1_run (struct distances_astropy_mnu_hiz_data *data)
void __ctest_distances_astropy_mnu_hiz_model_2_run (struct distances_astropy_mnu_hiz_data *data)
void __ctest_distances_astropy_mnu_hiz_model_3_run (struct distances_astropy_mnu_hiz_data *data)
void __ctest_distances_astropy_mnu_hiz_model_4_run (struct distances_astropy_mnu_hiz_data *data)
void __ctest_distances_astropy_mnu_hiz_model_5_run (struct distances_astropy_mnu_hiz_data *data)
Variables
static struct distances_astropy_mnu_hiz_data __ctest_distances_astropy_mnu_hiz_data
Macro Definition Documentation
#define DISTANCES_TOLERANCE 1.0e-3
Definition at line 11 of file ccl_test_distances_astropy_mnu_hiz.c.
Referenced by compare_distances_hiz_mnu().
Function Documentation
void __attribute__ ((weak))
Definition at line 76 of file ccl_test_distances_astropy_mnu_hiz.c.
References ccl_mnu_list, ccl_test_distances::Neff, read_chi_test_file(), and read_dm_test_file().
{
   // Values that are the same for all 5 models
   data->Omega_c = 0.25;
   data->Omega_b = 0.05;
   data->h = 0.7;
   data->A_s = 2.1e-9;
   data->n_s = 0.96;
   // Values that are different for the different models
   double Omega_v[5] = {  0.7,  0.7,  0.7,  0.65, 0.75 };
   double w_0[5]     = { -1.0, -0.9, -0.9, -0.9, -0.9  };
   double w_a[5]     = {  0.0,  0.0,  0.1,  0.1,  0.1  };
   // We use a total of 3 neutrinos instead of 3.046
   // This is to compare with benchmarks from astropy
   // which splits equally total N between all species
   double Neff[5]    = {3, 3, 3, 3, 3};
   data->mnu_type = ccl_mnu_list;
   double mnu0[3]    =   {0.04, 0., 0.};
   double mnu1[3]    =   {0.05, 0.01, 0.};
   double mnu2[3]    =   {0.03, 0.02, 0.04};
   double mnu3[3]    =   {0.05, 0., 0.};
   double mnu4[3]    =   {0.03, 0.02, 0.};
   data->mnu0[0] = mnu0[0];
   data->mnu1[0] = mnu1[0];
   data->mnu2[0] = mnu2[0];
   data->mnu3[0] = mnu3[0];
   data->mnu4[0] = mnu4[0];
   data->mnu0[1] = mnu0[1];
   data->mnu1[1] = mnu1[1];
   data->mnu2[1] = mnu2[1];
   data->mnu3[1] = mnu3[1];
   data->mnu4[1] = mnu4[1];
   data->mnu0[2] = mnu0[2];
   data->mnu1[2] = mnu1[2];
   data->mnu2[2] = mnu2[2];
   data->mnu3[2] = mnu3[2];
   data->mnu4[2] = mnu4[2];
   // Fill in the values from these constant arrays.
   for (int i=0; i<5; i++) {
     data->Omega_v[i] = Omega_v[i];
     data->w_0[i]     = w_0[i];
     data->w_a[i]     = w_a[i];
     data->Omega_k[i] = 1.0 - data->Omega_c - data->Omega_b - data->Omega_v[i];
     data->Neff[i] = Neff[i];
   }
   // The file of benchmark data.
   read_dm_test_file(data->z, data->dm);
   read_chi_test_file(data->z, data->chi);
 }
void __ctest_distances_astropy_mnu_hiz_model_1_run (struct distances_astropy_mnu_hiz_data * data)
Definition at line 199 of file ccl_test_distances_astropy_mnu_hiz.c.
References compare_distances_hiz_mnu().
{
   int model = 0;
   compare_distances_hiz_mnu(model, data);
 }
void __ctest_distances_astropy_mnu_hiz_model_2_run (struct distances_astropy_mnu_hiz_data * data)
Definition at line 204 of file ccl_test_distances_astropy_mnu_hiz.c.
References compare_distances_hiz_mnu().
{
   int model = 1;
   compare_distances_hiz_mnu(model, data);
 }
void __ctest_distances_astropy_mnu_hiz_model_3_run (struct distances_astropy_mnu_hiz_data * data)
Definition at line 209 of file ccl_test_distances_astropy_mnu_hiz.c.
References compare_distances_hiz_mnu().
{
   int model = 2;
   compare_distances_hiz_mnu(model, data);
 }
void __ctest_distances_astropy_mnu_hiz_model_4_run (struct distances_astropy_mnu_hiz_data * data)
Definition at line 214 of file ccl_test_distances_astropy_mnu_hiz.c.
References compare_distances_hiz_mnu().
{
   int model = 3;
   compare_distances_hiz_mnu(model, data);
 }
void __ctest_distances_astropy_mnu_hiz_model_5_run (struct distances_astropy_mnu_hiz_data * data)
Definition at line 219 of file ccl_test_distances_astropy_mnu_hiz.c.
References compare_distances_hiz_mnu().
{
   int model = 4;
   compare_distances_hiz_mnu(model, data);
 }
static void compare_distances_hiz_mnu (int model, struct distances_astropy_mnu_hiz_data * data) static
Definition at line 134 of file ccl_test_distances_astropy_mnu_hiz.c.
References distances_astropy_mnu_hiz_data::A_s, ASSERT_DBL_NEAR_TOL, ASSERT_NOT_NULL, ccl_comoving_radial_distance(), ccl_cosmology_create(), ccl_cosmology_free(), ccl_distance_modulus(), ccl_parameters_create(), distances_astropy_mnu_hiz_data::chi, cl_cmbl_bm::cosmo, default_config, DISTANCES_TOLERANCE, distances_astropy_mnu_hiz_data::dm, distances_astropy_mnu_hiz_data::h, distances_astropy_mnu_hiz_data::mnu0, distances_astropy_mnu_hiz_data::mnu1, distances_astropy_mnu_hiz_data::mnu2, distances_astropy_mnu_hiz_data::mnu3, distances_astropy_mnu_hiz_data::mnu4, distances_astropy_mnu_hiz_data::mnu_type, distances_astropy_mnu_hiz_data::n_s, distances_astropy_mnu_hiz_data::Neff, distances_astropy_mnu_hiz_data::Omega_b, distances_astropy_mnu_hiz_data::Omega_c, distances_astropy_mnu_hiz_data::Omega_k, halomod_bm::params, ccl_cosmology::status_message, distances_astropy_mnu_hiz_data::w_0, distances_astropy_mnu_hiz_data::w_a, and distances_astropy_mnu_hiz_data::z.
Referenced by __ctest_distances_astropy_mnu_hiz_model_1_run(), __ctest_distances_astropy_mnu_hiz_model_2_run(), __ctest_distances_astropy_mnu_hiz_model_3_run(), __ctest_distances_astropy_mnu_hiz_model_4_run(), and __ctest_distances_astropy_mnu_hiz_model_5_run().
 {
   int status=0;
   // Make the parameter set from the input data
   // Values of some parameters depend on the model index
   // The arrays of massive neutrions are different lengths, so we need to have an if-statement here to deal with that.
   ccl_parameters params;
   if (model==0){
   params = ccl_parameters_create(data->Omega_c, data->Omega_b, data->Omega_k[model],
                         data->Neff[model], data->mnu0, data->mnu_type,
                         data->w_0[model], data->w_a[model],
                         data->h, data->A_s, data->n_s,-1,-1,-1,-1,NULL,NULL, &status);
   } else if (model==1){
       params = ccl_parameters_create(data->Omega_c, data->Omega_b, data->Omega_k[model],
                         data->Neff[model], data->mnu1, data->mnu_type,
                         data->w_0[model], data->w_a[model],
                         data->h, data->A_s, data->n_s,-1,-1,-1,-1,NULL,NULL, &status);
   } else if (model==2){
      params = ccl_parameters_create(data->Omega_c, data->Omega_b, data->Omega_k[model],
                         data->Neff[model], data->mnu2, data->mnu_type,
                         data->w_0[model], data->w_a[model],
                         data->h, data->A_s, data->n_s,-1,-1,-1,-1,NULL,NULL, &status);
   } else if (model ==3){
     params = ccl_parameters_create(data->Omega_c, data->Omega_b, data->Omega_k[model],
                         data->Neff[model], data->mnu3, data->mnu_type,
                         data->w_0[model], data->w_a[model],
                         data->h, data->A_s, data->n_s,-1,-1,-1,-1,NULL,NULL, &status);
   }else if (model ==4){
       params = ccl_parameters_create(data->Omega_c, data->Omega_b, data->Omega_k[model],
                         data->Neff[model], data->mnu4, data->mnu_type,
                         data->w_0[model], data->w_a[model],
                         data->h, data->A_s, data->n_s,-1,-1,-1,-1,NULL,NULL, &status);
   }
   // Make a cosmology object from the parameters with the default configuration
   ccl_cosmology * cosmo = ccl_cosmology_create(params, default_config);
   ASSERT_NOT_NULL(cosmo);
   // Compare to benchmark data
   for (int j=0; j<5; j++) {
     double a = 1/(1.+data->z[j]);
     double chi_ij=ccl_comoving_radial_distance(cosmo,a, &status);
     if (status) printf("%s\n",cosmo->status_message);
     double absolute_tolerance = DISTANCES_TOLERANCE*data->chi[model][j];
     if (fabs(absolute_tolerance)<1e-12) absolute_tolerance = 1e-12;
     ASSERT_DBL_NEAR_TOL(data->chi[model][j], chi_ij, absolute_tolerance);
     if(a!=1) {  //skip this test for a=1 since it will raise an error
         double dm_ij=ccl_distance_modulus(cosmo,a, &status);
         if (status) printf("%s\n",cosmo->status_message);
         //NOTE tolerances are different!
         absolute_tolerance = 10*DISTANCES_TOLERANCE*data->dm[model][j];
         if (fabs(absolute_tolerance)<1e-4) absolute_tolerance = 1e-4;
         ASSERT_DBL_NEAR_TOL(data->dm[model][j], dm_ij, absolute_tolerance);
     }
   }
   ccl_cosmology_free(cosmo);
 }
static void read_chi_test_file (double z[5], double chi[5][5]) static
Definition at line 34 of file ccl_test_distances_astropy_mnu_hiz.c.
References ASSERT_EQUAL, ASSERT_NOT_NULL, and Catch::Matchers::Vector::Detail::count().
Referenced by __attribute__().
 {
   //Distances are in Mpc
   FILE * f = fopen("./tests/benchmark/chi_hiz_mnu_model1-5.txt", "r");
   ASSERT_NOT_NULL(f);
   // Ignore header line
   char str[1024];
   fgets(str, 1024, f);
   // File is fixed format - five rows and six columns
   for (int i=0; i<5; i++) {
     int count = fscanf(f, "%le %le %le %le %le %le\n", &z[i],
                &chi[0][i], &chi[1][i], &chi[2][i], &chi[3][i], &chi[4][i]);
     // Check that all the stuff in the benchmark is there
     ASSERT_EQUAL(6, count);
   }
   fclose(f);
 }
static void read_dm_test_file (double z[5], double dm[5][5]) static
Definition at line 54 of file ccl_test_distances_astropy_mnu_hiz.c.
References ASSERT_EQUAL, ASSERT_NOT_NULL, and Catch::Matchers::Vector::Detail::count().
Referenced by __attribute__().
 {
   //Distances are in Mpc
   FILE * f = fopen("./tests/benchmark/dm_hiz_mnu_model1-5.txt", "r");
   ASSERT_NOT_NULL(f);
   // Ignore header line
   char str[1024];
   fgets(str, 1024, f);
   // File is fixed format - five rows and six columns
   for (int i=0; i<5; i++) {
     int count = fscanf(f, "%le %le %le %le %le %le\n", &z[i],
                        &dm[0][i], &dm[1][i], &dm[2][i], &dm[3][i], &dm[4][i]);
     // Check that all the stuff in the benchmark is there
     ASSERT_EQUAL(6, count);
   }
   fclose(f);
 }
Variable Documentation
static struct distances_astropy_mnu_hiz_data __ctest_distances_astropy_mnu_hiz_data static
Definition at line 199 of file ccl_test_distances_astropy_mnu_hiz.c.