Fast Methods for Cosmological Simulations: src/3party/CCL/tests/ccl_test_growth_allz.c File Reference
ccl_test_growth_allz.c File Reference
#include "ccl.h"
#include "ctest.h"
#include <stdio.h>
#include <math.h>
Classes
struct growth_allz_data
Macros
#define GROWTH_TOLERANCE 1.0e-4
#define N_Z 10
#define N_MODEL 5
Functions
static void read_growth_test_file (const char *filename, double z[10], double gf[10][5])
void __attribute__ ((weak))
static void compare_growth (int model, struct growth_allz_data *data)
void __ctest_growth_allz_model_1_run (struct growth_allz_data *data)
void __ctest_growth_allz_model_2_run (struct growth_allz_data *data)
void __ctest_growth_allz_model_3_run (struct growth_allz_data *data)
void __ctest_growth_allz_model_4_run (struct growth_allz_data *data)
void __ctest_growth_allz_model_5_run (struct growth_allz_data *data)
Variables
static struct growth_allz_data __ctest_growth_allz_data
Macro Definition Documentation
#define GROWTH_TOLERANCE 1.0e-4
Definition at line 7 of file ccl_test_growth_allz.c.
Referenced by compare_growth().
#define N_MODEL 5
Definition at line 10 of file ccl_test_growth_allz.c.
Referenced by __attribute__().
#define N_Z 10
Definition at line 9 of file ccl_test_growth_allz.c.
Referenced by compare_growth(), and read_growth_test_file().
Function Documentation
void __attribute__ ((weak))
Definition at line 62 of file ccl_test_growth_allz.c.
References ccl_mnu_sum, N_MODEL, and read_growth_test_file().
{
   // Values that are the same for all 5 models
   data->Omega_c = 0.25;
   data->Omega_b = 0.05;
   data->h = 0.7;
   data->A_s = 2.1e-9;
   data->n_s = 0.96;
   data->Neff=0;
   double mnuval = 0.;
   data->mnu= &mnuval;
   data-> mnu_type = ccl_mnu_sum;
   // Values that are different for the different models
   double Omega_v[N_MODEL] = {  0.7,  0.7,  0.7,  0.65, 0.75 };
   double w_0[N_MODEL]     = { -1.0, -0.9, -0.9, -0.9, -0.9  };
   double w_a[N_MODEL]     = {  0.0,  0.0,  0.1,  0.1,  0.1  };
   // Fill in the values from these constant arrays.
   for (int i=0; i<N_MODEL; i++) {
     data->Omega_v[i] = Omega_v[i];
     data->w_0[i]     = w_0[i];
     data->w_a[i]     = w_a[i];
     data->Omega_k[i] = 1.0 - data->Omega_c - data->Omega_b - data->Omega_v[i];
   }
   // The file of benchmark data.
   read_growth_test_file("./tests/benchmark/growth_cosmomad_allz.txt", data->z, data->gf);
 }
void __ctest_growth_allz_model_1_run (struct growth_allz_data * data)
Definition at line 121 of file ccl_test_growth_allz.c.
References compare_growth().
{
   int model = 0;
   compare_growth(model, data);
 }
void __ctest_growth_allz_model_2_run (struct growth_allz_data * data)
Definition at line 126 of file ccl_test_growth_allz.c.
References compare_growth().
{
   int model = 1;
   compare_growth(model, data);
 }
void __ctest_growth_allz_model_3_run (struct growth_allz_data * data)
Definition at line 131 of file ccl_test_growth_allz.c.
References compare_growth().
{
   int model = 2;
   compare_growth(model, data);
 }
void __ctest_growth_allz_model_4_run (struct growth_allz_data * data)
Definition at line 136 of file ccl_test_growth_allz.c.
References compare_growth().
{
   int model = 3;
   compare_growth(model, data);
 }
void __ctest_growth_allz_model_5_run (struct growth_allz_data * data)
Definition at line 141 of file ccl_test_growth_allz.c.
References compare_growth().
{
   int model = 4;
   compare_growth(model, data);
 }
static void compare_growth (int model, struct growth_allz_data * data) static
Definition at line 92 of file ccl_test_growth_allz.c.
References growth_allz_data::A_s, ASSERT_DBL_NEAR_TOL, ASSERT_NOT_NULL, ccl_cosmology_create(), ccl_cosmology_free(), ccl_growth_factor_unnorm(), ccl_parameters_create(), cl_cmbl_bm::cosmo, default_config, growth_allz_data::gf, GROWTH_TOLERANCE, growth_allz_data::h, growth_allz_data::mnu, growth_allz_data::mnu_type, growth_allz_data::n_s, N_Z, growth_allz_data::Neff, growth_allz_data::Omega_b, growth_allz_data::Omega_c, ccl_parameters::Omega_g, growth_allz_data::Omega_k, halomod_bm::params, ccl_cosmology::status_message, growth_allz_data::w_0, growth_allz_data::w_a, and growth_allz_data::z.
Referenced by __ctest_growth_allz_model_1_run(), __ctest_growth_allz_model_2_run(), __ctest_growth_allz_model_3_run(), __ctest_growth_allz_model_4_run(), and __ctest_growth_allz_model_5_run().
 {
   int status=0;
   // Make the parameter set from the input data
   // Values of some parameters depend on the model index
   ccl_parameters params = ccl_parameters_create(data->Omega_c, data->Omega_b, data->Omega_k[model],
                                                 data->Neff, data->mnu, data->mnu_type,
                                                 data->w_0[model], data->w_a[model],
                                                 data->h, data->A_s, data->n_s,
                                                 -1,-1,-1,-1,NULL,NULL, &status);
   params.Omega_g=0;
   // Make a cosmology object from the parameters with the default configuration
   ccl_cosmology * cosmo = ccl_cosmology_create(params, default_config);
   ASSERT_NOT_NULL(cosmo);
   // Compare to benchmark data
   for (int i=0; i<N_Z; i++) {
     double a = 1/(1.+data->z[i]);
     double gf_ccl=ccl_growth_factor_unnorm(cosmo, a, &status);
     if (status) printf("%s\n",cosmo->status_message);
     double absolute_tolerance = GROWTH_TOLERANCE*data->gf[i][model];
     if (fabs(absolute_tolerance)<1e-12) absolute_tolerance = 1e-12;
     ASSERT_DBL_NEAR_TOL(data->gf[i][model], gf_ccl, absolute_tolerance);
   }
   ccl_cosmology_free(cosmo);
 }
static void read_growth_test_file (const char * filename, double z[10], double gf[10][5]) static
Definition at line 32 of file ccl_test_growth_allz.c.
References ASSERT_EQUAL, ASSERT_NOT_NULL, Catch::Matchers::Vector::Detail::count(), N_Z, and z.
Referenced by __attribute__().
 {
   //Growth is normalized to ~a at early times
   FILE * f = fopen(filename, "r");
   ASSERT_NOT_NULL(f);
   // Ignore header line
   fscanf(f, "%*[^\n]\n", NULL);
   double val;
   // Read the file
   for(int i_z=0; i_z<N_Z; i_z++) {
     for(int i_model=0; i_model<N_MODEL+1; i_model++) {
       int count = fscanf(f, "%le", &val);
       // Check that all the value was read successfully
       ASSERT_EQUAL(1, count);
       if(i_model == 0) {
         // The first column holds the redshift values
         z[i_z] = val;
       }
       else {
         gf[i_z][i_model-1] = val;
       }
     }
   }
   fclose(f);
 }
Variable Documentation
static struct growth_allz_data __ctest_growth_allz_data static
Definition at line 121 of file ccl_test_growth_allz.c.