Fast Methods for Cosmological Simulations: src/3party/CCL/tests/ccl_test_massfunc.c File Reference
ccl_test_massfunc.c File Reference
#include "ccl.h"
#include "ccl_massfunc.h"
#include "ctest.h"
#include <stdio.h>
#include <math.h>
Classes
struct massfunc_data
Macros
#define SIGMA_TOLERANCE 3e-5
#define INVSIGMA_TOLERANCE 1e-3
#define MASSFUNC_TOLERANCE 5e-5
Functions
static void read_massfunc_test_file (double mass[13], double massfunc[3][13])
void __attribute__ ((weak))
static void compare_massfunc (int model, struct massfunc_data *data)
void __ctest_massfunc_model_1_run (struct massfunc_data *data)
Variables
static struct massfunc_data __ctest_massfunc_data
Macro Definition Documentation
#define INVSIGMA_TOLERANCE 1e-3
Definition at line 9 of file ccl_test_massfunc.c.
Referenced by compare_massfunc().
#define MASSFUNC_TOLERANCE 5e-5
Definition at line 10 of file ccl_test_massfunc.c.
Referenced by compare_massfunc().
#define SIGMA_TOLERANCE 3e-5
Definition at line 8 of file ccl_test_massfunc.c.
Referenced by compare_massfunc().
Function Documentation
void __attribute__ ((weak))
Definition at line 53 of file ccl_test_massfunc.c.
References ccl_mnu_sum, and read_massfunc_test_file().
                       {
   // only single model at tihs point
   data->Omega_c = 0.25;
   data->Omega_b = 0.05;
   data->h = 0.7;
   data->A_s = 2.1e-9;
   data->n_s = 0.96;
   data->sigma8 = 0.8;
   data->Neff=0;
   double mnuval = 0.;
   data->mnu=&mnuval;
   data->mnu_type = ccl_mnu_sum;
   double Omega_v[1] = { 0.7 };
   double w_0[1]     = {-1.0 };
   double w_a[1]     = { 0.0 };
   for (int i=0; i<1; i++) {
     data->Omega_v[i] = Omega_v[i];
     data->w_0[i] = w_0[i];
     data->w_a[i]= w_a[i];
     data->Omega_k[i] = 1.0 - data->Omega_c - data->Omega_b - data->Omega_v[i];
   }
   // read the file of benchmark data
   read_massfunc_test_file(data->mass, data->massfunc);
 }
void __ctest_massfunc_model_1_run (struct massfunc_data * data)
Definition at line 130 of file ccl_test_massfunc.c.
References compare_massfunc().
{
    int model = 0;
    compare_massfunc(model, data);
 }
static void compare_massfunc (int model, struct massfunc_data * data) static
Definition at line 80 of file ccl_test_massfunc.c.
References massfunc_data::A_s, ASSERT_DBL_NEAR_TOL, ASSERT_NOT_NULL, ccl_bbks, ccl_cosmology_create(), ccl_massfunc(), ccl_parameters_create(), ccl_sigmaM(), ccl_tinker, cl_cmbl_bm::cosmo, default_config, massfunc_data::h, ccl_parameters::h, INVSIGMA_TOLERANCE, ccl_configuration::mass_function_method, massfunc_data::massfunc, MASSFUNC_TOLERANCE, massfunc_data::mnu, massfunc_data::n_s, massfunc_data::Neff, massfunc_data::Omega_b, massfunc_data::Omega_c, ccl_parameters::Omega_g, massfunc_data::Omega_k, ccl_parameters::Omega_l, ccl_parameters::Omega_m, massfunc_data::Omega_v, halomod_bm::params, ccl_cosmology::params, pow(), RHO_CRITICAL, massfunc_data::sigma8, ccl_parameters::sigma8, SIGMA_TOLERANCE, ccl_configuration::transfer_function_method, massfunc_data::w_0, and massfunc_data::w_a.
Referenced by __ctest_massfunc_model_1_run().
 {
   int stat = 0;
   int* status = &stat;
   ccl_parameters params = ccl_parameters_create(data->Omega_c, data->Omega_b,data->Omega_k[model],
                         data->Neff, data->mnu, data-> mnu_type, data->w_0[model],
                         data->w_a[model], data->h,data->A_s, data->n_s,
                         -1, -1, -1, -1, NULL, NULL, status);
   params.sigma8 = data->sigma8;
   params.Omega_g=0.;
   params.Omega_l=data->Omega_v[model];
   ccl_configuration config = default_config;
   config.transfer_function_method = ccl_bbks;
   // test file generated using tinker 2008 currently
   config.mass_function_method = ccl_tinker;
   ccl_cosmology * cosmo = ccl_cosmology_create(params, config);
   ASSERT_NOT_NULL(cosmo);
   double a = 1.0;
   double logmass = 10;
   double odelta = 200;
   double rho_m = RHO_CRITICAL*cosmo->params.Omega_m*cosmo->params.h*cosmo->params.h;
   // compare to benchmark data
   for (int j=0; j<13; j++) {
     double mass = pow(10,logmass);
     double sigma_j = ccl_sigmaM(cosmo, mass, a, status);
     double loginvsigma_j = log10(1./sigma_j);
     double logmassfunc_j = log10(ccl_massfunc(cosmo, mass, a, odelta, status)*mass/(rho_m*log(10.)));
     double absolute_tolerance = SIGMA_TOLERANCE*data->massfunc[0][j];
     if (fabs(absolute_tolerance)<1e-12) absolute_tolerance = 1e-12;
     ASSERT_DBL_NEAR_TOL(data->massfunc[0][j], sigma_j, absolute_tolerance);
     absolute_tolerance = INVSIGMA_TOLERANCE*fabs(data->massfunc[1][j]);
     if (fabs(absolute_tolerance)<1e-12) absolute_tolerance = 1e-12;
     ASSERT_DBL_NEAR_TOL(fabs(data->massfunc[1][j]), fabs(loginvsigma_j), absolute_tolerance);
     absolute_tolerance = MASSFUNC_TOLERANCE*fabs(data->massfunc[2][j]);
     if (fabs(absolute_tolerance)<1e-12) absolute_tolerance = 1e-12;
     ASSERT_DBL_NEAR_TOL(fabs(data->massfunc[2][j]), fabs(logmassfunc_j), absolute_tolerance);
     logmass += 0.5;
   }
   free(cosmo);
 }
static void read_massfunc_test_file (double mass[13], double massfunc[3][13]) static
Definition at line 31 of file ccl_test_massfunc.c.
References ASSERT_EQUAL, ASSERT_NOT_NULL, and Catch::Matchers::Vector::Detail::count().
Referenced by __attribute__().
 {
    // Masses are in Msun/h
    FILE * f = fopen("./tests/benchmark/model1_hmf.txt", "r");
    ASSERT_NOT_NULL(f);
    // Ignore header line
    char str[1024];
    char* rtn;
    rtn = fgets(str, 1024, f);
    // file is in fixed format - logmass, sigma, invsigma, and hmf, w/ 13 rows
    for (int i=0; i<13; i++) {
      int count = fscanf(f, "%le %le %le %le\n", &mass[i],
                         &massfunc[0][i], &massfunc[1][i], &massfunc[2][i]);
      // Check that all the stuff in the benchmark is there
      ASSERT_EQUAL(4, count);
    }
    fclose(f);
 }
Variable Documentation
struct massfunc_data __ctest_massfunc_data static
Definition at line 130 of file ccl_test_massfunc.c.