Fast Methods for Cosmological Simulations: src/3party/CCL/tests/ccl_test_params.c File Reference
ccl_test_params.c File Reference
#include <math.h>
#include "ccl.h"
#include "ctest.h"
Classes
struct parameters_data
Functions
void __attribute__ ((weak))
void __ctest_parameters_create_lcdm_run (struct parameters_data *data)
void test_general (ccl_parameters params, struct parameters_data *data)
void __ctest_parameters_create_general_nu_list_run (struct parameters_data *data)
void __ctest_parameters_create_general_nu_sum_run (struct parameters_data *data)
void __ctest_parameters_create_general_nu_sum_inverted_run (struct parameters_data *data)
void __ctest_parameters_create_general_nu_sum_equal_run (struct parameters_data *data)
void __ctest_parameters_read_write_run (struct parameters_data *data)
Variables
static struct parameters_data __ctest_parameters_data
Function Documentation
void __attribute__ ((weak))
Definition at line 29 of file ccl_test_params.c.
{
   data->Omega_c = 0.25;
   data->Omega_b = 0.05;
   data->Omega_k = 0.1;
   data->Neff = 3.046;
   data->mnu[0] = 0.1;
   data->mnu[1] = 0.01;
   data->mnu[2] = 0.003;
   data->h = 0.7;
   data->A_s = 2.1e-9;
   data->n_s = 0.96;
   data->wa = 0.01;
   data->w0 = -0.8;
   data->bcm_log10Mc = 2.0;
   data->bcm_etab = 80.0;
   data->bcm_ks = 1.1,
   data->status=0;
 }
void __ctest_parameters_create_general_nu_list_run (struct parameters_data * data)
Definition at line 147 of file ccl_test_params.c.
References ASSERT_DBL_NEAR_TOL, ASSERT_EQUAL, ccl_mnu_list, ccl_parameters_create(), ccl_parameters::mnu, ccl_parameters::N_nu_mass, halomod_bm::params, ccl_parameters::sum_nu_masses, and test_general().
{
   int status = 0;
   ccl_parameters params =
     ccl_parameters_create(
       data->Omega_c,
       data->Omega_b,
       data->Omega_k,
       data->Neff,
       data->mnu,
       ccl_mnu_list,
       data->w0,
       data->wa,
       data->h,
       data->A_s,
       data->n_s,
       data->bcm_log10Mc,
       data->bcm_etab,
       data->bcm_ks,
       -1,
       NULL,
       NULL,
       &status);
   ASSERT_EQUAL(status, 0);
   test_general(params, data);
   ASSERT_EQUAL(params.N_nu_mass, 3);
   ASSERT_DBL_NEAR_TOL(params.sum_nu_masses, data->mnu[0] + data->mnu[1] + data->mnu[2], 1e-10);
   ASSERT_DBL_NEAR_TOL(params.mnu[0], 0.1, 1e-10);
   ASSERT_DBL_NEAR_TOL(params.mnu[1], 0.01, 1e-10);
   ASSERT_DBL_NEAR_TOL(params.mnu[2], 0.003, 1e-10);
 }
void __ctest_parameters_create_general_nu_sum_equal_run (struct parameters_data * data)
Definition at line 246 of file ccl_test_params.c.
References ASSERT_DBL_NEAR_TOL, ASSERT_EQUAL, ccl_mnu_sum_equal, ccl_parameters_create(), ccl_parameters::mnu, ccl_parameters::N_nu_mass, halomod_bm::params, ccl_parameters::sum_nu_masses, and test_general().
{
   int status = 0;
   ccl_parameters params =
     ccl_parameters_create(
       data->Omega_c,
       data->Omega_b,
       data->Omega_k,
       data->Neff,
       data->mnu,
       ccl_mnu_sum_equal,
       data->w0,
       data->wa,
       data->h,
       data->A_s,
       data->n_s,
       data->bcm_log10Mc,
       data->bcm_etab,
       data->bcm_ks,
       -1,
       NULL,
       NULL,
       &status);
   ASSERT_EQUAL(status, 0);
   test_general(params, data);
   ASSERT_EQUAL(params.N_nu_mass, 3);
   ASSERT_DBL_NEAR_TOL(params.sum_nu_masses, data->mnu[0], 1e-10);
   ASSERT_DBL_NEAR_TOL(params.mnu[0], data->mnu[0]/3, 1e-10);
   ASSERT_DBL_NEAR_TOL(params.mnu[1], data->mnu[0]/3, 1e-10);
   ASSERT_DBL_NEAR_TOL(params.mnu[2], data->mnu[0]/3, 1e-10);
 }
void __ctest_parameters_create_general_nu_sum_inverted_run (struct parameters_data * data)
Definition at line 214 of file ccl_test_params.c.
References ASSERT_DBL_NEAR_TOL, ASSERT_EQUAL, ccl_mnu_sum, ccl_parameters_create(), ccl_parameters::N_nu_mass, halomod_bm::params, ccl_parameters::sum_nu_masses, and test_general().
{
   int status = 0;
   ccl_parameters params =
     ccl_parameters_create(
       data->Omega_c,
       data->Omega_b,
       data->Omega_k,
       data->Neff,
       data->mnu,
       ccl_mnu_sum,
       data->w0,
       data->wa,
       data->h,
       data->A_s,
       data->n_s,
       data->bcm_log10Mc,
       data->bcm_etab,
       data->bcm_ks,
       -1,
       NULL,
       NULL,
       &status);
   ASSERT_EQUAL(status, 0);
   test_general(params, data);
   ASSERT_EQUAL(params.N_nu_mass, 3);
   ASSERT_DBL_NEAR_TOL(params.sum_nu_masses, data->mnu[0], 1e-10);
 }
void __ctest_parameters_create_general_nu_sum_run (struct parameters_data * data)
Definition at line 182 of file ccl_test_params.c.
References ASSERT_DBL_NEAR_TOL, ASSERT_EQUAL, ccl_mnu_sum, ccl_parameters_create(), ccl_parameters::N_nu_mass, halomod_bm::params, ccl_parameters::sum_nu_masses, and test_general().
{
   int status = 0;
   ccl_parameters params =
     ccl_parameters_create(
       data->Omega_c,
       data->Omega_b,
       data->Omega_k,
       data->Neff,
       data->mnu,
       ccl_mnu_sum,
       data->w0,
       data->wa,
       data->h,
       data->A_s,
       data->n_s,
       data->bcm_log10Mc,
       data->bcm_etab,
       data->bcm_ks,
       -1,
       NULL,
       NULL,
       &status);
   ASSERT_EQUAL(status, 0);
   test_general(params, data);
   ASSERT_EQUAL(params.N_nu_mass, 3);
   ASSERT_DBL_NEAR_TOL(params.sum_nu_masses, data->mnu[0], 1e-10);
 }
void __ctest_parameters_create_lcdm_run (struct parameters_data * data)
Definition at line 57 of file ccl_test_params.c.
{
   ccl_parameters params = ccl_parameters_create_flat_lcdm(
     data->Omega_c, data->Omega_b, data->h, data->A_s, data->n_s, &(data->status));
   ASSERT_DBL_NEAR_TOL(params.Omega_c, data->Omega_c, 1e-10);
   ASSERT_DBL_NEAR_TOL(params.Omega_b, data->Omega_b, 1e-10);
   ASSERT_DBL_NEAR_TOL(params.Omega_m, data->Omega_b + data->Omega_c, 1e-10);
   ASSERT_DBL_NEAR_TOL(params.Omega_k, 0.0, 1e-10);
   ASSERT_DBL_NEAR_TOL(params.sqrtk, 0.0, 1e-10);
   ASSERT_DBL_NEAR_TOL(params.k_sign, 0.0, 1e-10);
   ASSERT_DBL_NEAR_TOL(params.w0, -1.0, 1e-10);
   ASSERT_DBL_NEAR_TOL(params.wa, 0.0, 1e-10);
   ASSERT_DBL_NEAR_TOL(params.H0, 70.0, 1e-10);
   ASSERT_DBL_NEAR_TOL(params.h, 0.7, 1e-10);
   ASSERT_DBL_NEAR_TOL(params.A_s, data->A_s, 1e-10);
   ASSERT_DBL_NEAR_TOL(params.n_s, data->n_s, 1e-10);
   ASSERT_TRUE(isnan(params.sigma8));
   ASSERT_TRUE(isnan(params.z_star));
   ASSERT_DBL_NEAR_TOL(params.Neff, 3.046, 1e-10);
   ASSERT_EQUAL(params.N_nu_mass, 0);
   ASSERT_DBL_NEAR_TOL(params.N_nu_rel, 3.046, 1e-10);
   ASSERT_DBL_NEAR_TOL(params.sum_nu_masses, 0.0, 1e-10);
   ASSERT_DBL_NEAR_TOL(params.mnu[0], 0.0, 1e-10);
   ASSERT_DBL_NEAR_TOL(params.Omega_n_mass, 0.0, 1e-10);
   ASSERT_DBL_NEAR_TOL(params.T_CMB, TCMB, 1e-10);
   ASSERT_DBL_NEAR_TOL(params.bcm_ks, 55.0, 1e-10);
   ASSERT_DBL_NEAR_TOL(params.bcm_log10Mc, log10(1.2e14), 1e-10);
   ASSERT_DBL_NEAR_TOL(params.bcm_etab, 0.5, 1e-10);
   ASSERT_FALSE(params.has_mgrowth);
   ASSERT_EQUAL(params.nz_mgrowth, 0);
   ASSERT_NULL(params.z_mgrowth);
   ASSERT_NULL(params.df_mgrowth);
   /* these are defined in the code via some constants - going to test the total
     Omega_n_rel
     Omega_g
     Omega_l
   */
   ASSERT_DBL_NEAR_TOL(
     params.Omega_l + params.Omega_m +
     params.Omega_g + params.Omega_n_rel +
     params.Omega_n_mass + params.Omega_k,
     1.,
     1e-10);
 }
void __ctest_parameters_read_write_run (struct parameters_data * data)
Definition at line 282 of file ccl_test_params.c.
References ASSERT_DBL_NEAR_TOL, ASSERT_EQUAL, ccl_parameters_create_flat_lcdm(), ccl_parameters_read_yaml(), ccl_parameters_write_yaml(), ccl_parameters::Omega_c, ccl_parameters::Omega_k, halomod_bm::params, ccl_parameters::w0, and ccl_parameters::wa.
{
     char filename[32];
     snprintf(filename, 32, "ccl_test_params_rw_XXXXXX");
     mkstemp(filename);
     ccl_parameters params = ccl_parameters_create_flat_lcdm(data->Omega_c, data->Omega_b, data->h, data->A_s, data->n_s, &(data->status));
     int status = 0;
     ccl_parameters_write_yaml(&params, filename, &status);
     ASSERT_EQUAL(status, 0);
     ccl_parameters params2 = ccl_parameters_read_yaml(filename, &status);
     ASSERT_EQUAL(status, 0);
     ASSERT_DBL_NEAR_TOL(params2.Omega_c, data->Omega_c, 1e-10);
     ASSERT_DBL_NEAR_TOL(params2.Omega_k, 0.0, 1e-10);
     ASSERT_DBL_NEAR_TOL(params2.w0, -1.0, 1e-10);
     ASSERT_DBL_NEAR_TOL(params2.wa, 0.0, 1e-10);
     remove(filename);
 }
void test_general (ccl_parameters params, struct parameters_data * data)
Definition at line 107 of file ccl_test_params.c.
References parameters_data::A_s, ccl_parameters::A_s, ASSERT_DBL_NEAR_TOL, ASSERT_EQUAL, ASSERT_FALSE, ASSERT_NULL, ASSERT_TRUE, parameters_data::bcm_etab, ccl_parameters::bcm_etab, parameters_data::bcm_ks, ccl_parameters::bcm_ks, parameters_data::bcm_log10Mc, ccl_parameters::bcm_log10Mc, CLIGHT_HMPC, ccl_parameters::df_mgrowth, parameters_data::h, ccl_parameters::h, ccl_parameters::H0, ccl_parameters::has_mgrowth, ccl_parameters::k_sign, parameters_data::n_s, ccl_parameters::n_s, parameters_data::Neff, ccl_parameters::Neff, ccl_parameters::nz_mgrowth, parameters_data::Omega_b, ccl_parameters::Omega_b, parameters_data::Omega_c, ccl_parameters::Omega_c, ccl_parameters::Omega_g, parameters_data::Omega_k, ccl_parameters::Omega_k, ccl_parameters::Omega_l, ccl_parameters::Omega_m, ccl_parameters::Omega_n_mass, ccl_parameters::Omega_n_rel, ccl_parameters::sigma8, sqrt(), ccl_parameters::sqrtk, ccl_parameters::T_CMB, TCMB, parameters_data::w0, ccl_parameters::w0, parameters_data::wa, ccl_parameters::wa, ccl_parameters::z_mgrowth, and ccl_parameters::z_star.
Referenced by __ctest_parameters_create_general_nu_list_run(), __ctest_parameters_create_general_nu_sum_equal_run(), __ctest_parameters_create_general_nu_sum_inverted_run(), and __ctest_parameters_create_general_nu_sum_run().
{
   ASSERT_DBL_NEAR_TOL(params.Omega_c, data->Omega_c, 1e-10);
   ASSERT_DBL_NEAR_TOL(params.Omega_b, data->Omega_b, 1e-10);
   ASSERT_DBL_NEAR_TOL(params.Omega_m, data->Omega_b + data->Omega_c, 1e-10);
   ASSERT_DBL_NEAR_TOL(params.Omega_k, data->Omega_k, 1e-10);
   ASSERT_DBL_NEAR_TOL(params.sqrtk, sqrt(fabs(data->Omega_k))*data->h/CLIGHT_HMPC, 1e-10);
   ASSERT_DBL_NEAR_TOL(params.k_sign, -1.0, 1e-10);
   ASSERT_DBL_NEAR_TOL(params.w0, data->w0, 1e-10);
   ASSERT_DBL_NEAR_TOL(params.wa, data->wa, 1e-10);
   ASSERT_DBL_NEAR_TOL(params.H0, data->h * 100.0, 1e-10);
   ASSERT_DBL_NEAR_TOL(params.h, data->h, 1e-10);
   ASSERT_DBL_NEAR_TOL(params.A_s, data->A_s, 1e-10);
   ASSERT_DBL_NEAR_TOL(params.n_s, data->n_s, 1e-10);
   ASSERT_TRUE(isnan(params.sigma8));
   ASSERT_TRUE(isnan(params.z_star));
   ASSERT_DBL_NEAR_TOL(params.Neff, data->Neff, 1e-10);
   ASSERT_DBL_NEAR_TOL(params.T_CMB, TCMB, 1e-10);
   ASSERT_DBL_NEAR_TOL(params.bcm_ks, data->bcm_ks, 1e-10);
   ASSERT_DBL_NEAR_TOL(params.bcm_log10Mc, data->bcm_log10Mc, 1e-10);
   ASSERT_DBL_NEAR_TOL(params.bcm_etab, data->bcm_etab, 1e-10);
   ASSERT_FALSE(params.has_mgrowth);
   ASSERT_EQUAL(params.nz_mgrowth, 0);
   ASSERT_NULL(params.z_mgrowth);
   ASSERT_NULL(params.df_mgrowth);
   /* these are defined in the code via some constants - going to test the total
     Omega_n_mass
     Omega_n_rel
     Omega_g
     Omega_l
   */
   ASSERT_DBL_NEAR_TOL(
     params.Omega_l + params.Omega_m + params.Omega_g + params.Omega_n_rel + params.Omega_n_mass + params.Omega_k,
     1.,
     1e-10);
 }
Variable Documentation
static struct parameters_data __ctest_parameters_data static
Definition at line 57 of file ccl_test_params.c.