Fast Methods for Cosmological Simulations: src/3party/CCL/include/ccl_cls.h File Reference
ccl_cls.h File Reference
Classes
struct CCL_ClTracer
struct CCL_ClWorkspace
Typedefs
typedef enum ccl_tracer_t ccl_tracer_t
typedef enum ccl_tracer_func_t ccl_tracer_func_t
Enumerations
enum ccl_tracer_t { ccl_number_counts_tracer = 1, ccl_weak_lensing_tracer = 2, ccl_cmb_lensing_tracer = 3 }
enum ccl_tracer_func_t {
ccl_trf_nz = 201, ccl_trf_bz = 202, ccl_trf_sz = 203, ccl_trf_rf = 204,
ccl_trf_ba = 205, ccl_trf_wL = 206, ccl_trf_wM = 207
}
Functions
CCL_ClTracer * ccl_cl_tracer (ccl_cosmology *cosmo, int tracer_type, int has_rsd, int has_magnification, int has_intrinsic_alignment, int nz_n, double *z_n, double *n, int nz_b, double *z_b, double *b, int nz_s, double *z_s, double *s, int nz_ba, double *z_ba, double *ba, int nz_rf, double *z_rf, double *rf, double z_source, int *status)
CCL_ClTracer * ccl_cl_tracer_number_counts (ccl_cosmology *cosmo, int has_rsd, int has_magnification, int nz_n, double *z_n, double *n, int nz_b, double *z_b, double *b, int nz_s, double *z_s, double *s, int *status)
CCL_ClTracer * ccl_cl_tracer_number_counts_simple (ccl_cosmology *cosmo, int nz_n, double *z_n, double *n, int nz_b, double *z_b, double *b, int *status)
CCL_ClTracer * ccl_cl_tracer_lensing (ccl_cosmology *cosmo, int has_alignment, int nz_n, double *z_n, double *n, int nz_ba, double *z_ba, double *ba, int nz_rf, double *z_rf, double *rf, int *status)
CCL_ClTracer * ccl_cl_tracer_lensing_simple (ccl_cosmology *cosmo, int nz_n, double *z_n, double *n, int *status)
CCL_ClTracer * ccl_cl_tracer_cmblens (ccl_cosmology *cosmo, double z_source, int *status)
void ccl_cl_tracer_free (CCL_ClTracer *clt)
double ccl_get_tracer_fa (ccl_cosmology *cosmo, CCL_ClTracer *clt, double a, int func_code, int *status)
int ccl_get_tracer_fas (ccl_cosmology *cosmo, CCL_ClTracer *clt, int na, double *a, double *fa, int func_code, int *status)
CCL_ClWorkspace * ccl_cl_workspace_new (int lmax, int l_limber, double l_logstep, int l_linstep, int *status)
CCL_ClWorkspace * ccl_cl_workspace_new_limber (int lmax, double l_logstep, int l_linstep, int *status)
void ccl_cl_workspace_free (CCL_ClWorkspace *w)
void ccl_angular_cls (ccl_cosmology *cosmo, CCL_ClWorkspace *w, CCL_ClTracer *clt1, CCL_ClTracer *clt2, int nl_out, int *l, double *cl, int *status)
Typedef Documentation
typedef enum ccl_tracer_func_t ccl_tracer_func_t
typedef enum ccl_tracer_t ccl_tracer_t
Enumeration Type Documentation
enum ccl_tracer_func_t
Enumerator
ccl_trf_nz
ccl_trf_bz
ccl_trf_sz
ccl_trf_rf
ccl_trf_ba
ccl_trf_wL
ccl_trf_wM
Definition at line 12 of file ccl_cls.h.
 {
   ccl_trf_nz = 201, //Redshift distribution
   ccl_trf_bz = 202, //Clustering bias
   ccl_trf_sz = 203, //Magnification bias
   ccl_trf_rf = 204, //Aligned fraction
   ccl_trf_ba = 205, //Alignment bias
   ccl_trf_wL = 206, //Weak lensing window function
   ccl_trf_wM = 207, //Magnification window function
 } ccl_tracer_func_t;
enum ccl_tracer_t
Enumerator
ccl_number_counts_tracer
ccl_weak_lensing_tracer
ccl_cmb_lensing_tracer
Definition at line 5 of file ccl_cls.h.
 {
   ccl_number_counts_tracer = 1,
   ccl_weak_lensing_tracer  = 2,
   ccl_cmb_lensing_tracer   = 3,
 } ccl_tracer_t;
Function Documentation
void ccl_angular_cls (ccl_cosmology * cosmo, CCL_ClWorkspace * w, CCL_ClTracer * clt1, CCL_ClTracer * clt2, int nl_out, int * l, double * cl, int * status)
Computes limber or non-limber power spectrum for two different tracers
Parameters
cosmo Cosmological parameters
w a ClWorkspace
clt1 a Cltracer
clt2 a Cltracer
nl_out the maximum to ell to compute C_ell
l an array of ell values
cl the C_ell output array
status Status flag. 0 if there are no errors, nonzero otherwise. For specific cases see documentation for ccl_error.c
Returns
void
Definition at line 943 of file ccl_cls.c.
References ccl_angular_cl_native(), ccl_check_status(), ccl_cosmology_set_status_message(), CCL_ERROR_MEMORY, CCL_ERROR_SPLINE_EV, ccl_spline_eval(), ccl_spline_free(), ccl_spline_init(), ccl_weak_lensing_tracer, CCL_ClTracer::has_magnification, CCL_ClWorkspace::l_arr, CCL_ClWorkspace::l_limber, CCL_ClWorkspace::lmax, CCL_ClWorkspace::n_ls, and CCL_ClTracer::tracer_type.
Referenced by compare_cls(), compare_corr(), main(), and test_angpow_precision().
 {
   int ii,do_angpow;
   double *l_nodes,*cl_nodes;
   SplPar *spcl_nodes;
   //First check if ell range is within workspace
   for(ii=0;ii<nl_out;ii++) {
     if(l_out[ii]>w->lmax) {
       *status=CCL_ERROR_SPLINE_EV;
       ccl_cosmology_set_status_message(cosmo, "ccl_cls.c: ccl_angular_cls(); "
          "requested l beyond range allowed by workspace\n");
       return;
     }
   }
   if(*status==0) {
     //Allocate array for power spectrum at interpolation nodes
     l_nodes=(double *)malloc(w->n_ls*sizeof(double));
     if(l_nodes==NULL) {
       *status=CCL_ERROR_MEMORY;
       ccl_cosmology_set_status_message(cosmo, "ccl_cls.c: ccl_angular_cls(); memory allocation\n");
     }
   }
   if(*status==0) {
     cl_nodes=(double *)malloc(w->n_ls*sizeof(double));
     if(cl_nodes==NULL) {
       *status=CCL_ERROR_MEMORY;
       ccl_cosmology_set_status_message(cosmo, "ccl_cls.c: ccl_cl_angular_cls(); memory allocation\n");
     }
   }
   if(*status==0) {
     for(ii=0;ii<w->n_ls;ii++)
       l_nodes[ii]=(double)(w->l_arr[ii]);
     do_angpow=0;
     //Now check if angpow is needed at all
     if(w->l_limber>0) {
       for(ii=0;ii<w->n_ls;ii++) {
     if(w->l_arr[ii]<=w->l_limber)
       do_angpow=1;
       }
     }
 #ifndef HAVE_ANGPOW
     do_angpow=0;
 #endif //HAVE_ANGPOW
     //Resort to Limber if we have lensing (this will hopefully only be temporary)
     if(clt1->tracer_type==ccl_weak_lensing_tracer || clt2->tracer_type==ccl_weak_lensing_tracer ||
        clt1->has_magnification || clt2->has_magnification) {
       do_angpow=0;
     }
     //Use angpow if non-limber is needed
     if(do_angpow)
       ccl_angular_cls_angpow(cosmo,w,clt1,clt2,cl_nodes,status);
     ccl_check_status(cosmo,status);
   }
   if(*status==0) {
     //Compute limber nodes
     for(ii=0;ii<w->n_ls;ii++) {
       if((!do_angpow) || (w->l_arr[ii]>w->l_limber))
     cl_nodes[ii]=ccl_angular_cl_native(cosmo,w,ii,clt1,clt2,status);
     }
     //Interpolate into ells requested by user
     spcl_nodes=ccl_spline_init(w->n_ls,l_nodes,cl_nodes,0,0);
     if(spcl_nodes==NULL) {
       *status=CCL_ERROR_MEMORY;
       ccl_cosmology_set_status_message(cosmo, "ccl_cls.c: ccl_cl_angular_cls(); memory allocation\n");
     }
   }
   if(*status==0) {
     for(ii=0;ii<nl_out;ii++)
       cl_out[ii]=ccl_spline_eval((double)(l_out[ii]),spcl_nodes);
   }
   //Cleanup
   ccl_spline_free(spcl_nodes);
   free(cl_nodes);
   free(l_nodes);
 }
CCL_ClTracer* ccl_cl_tracer (ccl_cosmology * cosmo, int tracer_type, int has_rsd, int has_magnification, int has_intrinsic_alignment, int nz_n, double * z_n, double * n, int nz_b, double * z_b, double * b, int nz_s, double * z_s, double * s, int nz_ba, double * z_ba, double * ba, int nz_rf, double * z_rf, double * rf, double z_source, int * status)
Constructor for a ClTracer.
Parameters
Tracer_type pass ccl_number_counts_tracer (number counts), ccl_weak_lensing_tracer (weak lensing) or ccl_cmb_lensing_tracer (CMB lensing)
has_rsd Set to 1 if you want to compute the RSD contribution to number counts (0 otherwise)
has_magnification Set to 1 if you want to compute the magnification contribution to number counts (0 otherwise)
has_intrinsic_alignment Set to 1 if you want to compute the IA contribution to shear
nz_n Number of bins in z_n and n
z_n Redshifts for each redshift interval of n
n Number count of objects per redshift interval (Note: arbitrary normalization - renormalized inside)
nz_b Number of bins in z_b and b
z_b Redshifts for each redshift interval of b
b Clustering bias in each redshift bin
nz_s Number of bins in z_s and s
z_s Redshifts for each redshift interval of s
s Magnification bias in each redshift bin
nz_ba Number of bins in z_ba and ba
z_ba Redshifts for each redshift interval of ba
ba Alignment bias in each redshift bin
nz_rf Number of bins in z_f and f
z_rf Redshifts for each redshift interval of rf
rf Aligned red fraction in each redshift bin
z_source Redshift of source plane for CMB lensing (z~1100 for CMB lensing).
status Status flag. 0 if there are no errors, nonzero otherwise. For specific cases see documentation for ccl_error.c
Returns
CCL_ClTracer object
Definition at line 575 of file ccl_cls.c.
References ccl_check_status(), and cl_tracer().
Referenced by ccl_cl_tracer_cmblens(), ccl_cl_tracer_lensing(), ccl_cl_tracer_lensing_simple(), ccl_cl_tracer_number_counts(), and ccl_cl_tracer_number_counts_simple().
 {
   CCL_ClTracer *clt=cl_tracer(cosmo,tracer_type,has_rsd,has_magnification,has_intrinsic_alignment,
                   nz_n,z_n,n,nz_b,z_b,b,nz_s,z_s,s,
                   nz_ba,z_ba,ba,nz_rf,z_rf,rf,z_source,status);
   ccl_check_status(cosmo,status);
   return clt;
 }
CCL_ClTracer* ccl_cl_tracer_cmblens (ccl_cosmology * cosmo, double z_source, int * status)
Simplified constructor for a CMB lensing ClTracer.
Parameters
z_source Redshift of source plane (z~1100 for CMB lensing).
status Status flag. 0 if there are no errors, nonzero otherwise. For specific cases see documentation for ccl_error.c
Returns
CCL_ClTracer object
Definition at line 614 of file ccl_cls.c.
References ccl_cl_tracer(), and ccl_cmb_lensing_tracer.
Referenced by compare_cls(), and main().
 {
   return ccl_cl_tracer(cosmo,ccl_cmb_lensing_tracer,
                0,0,0,
                0,NULL,NULL,0,NULL,NULL,0,NULL,NULL,
                0,NULL,NULL,0,NULL,NULL,z_source,status);
 }
void ccl_cl_tracer_free (CCL_ClTracer * clt)
Destructor for a Cltracer
Parameters
clt a Cltracer
Returns
void
Definition at line 592 of file ccl_cls.c.
References ccl_number_counts_tracer, ccl_spline_free(), ccl_weak_lensing_tracer, CCL_ClTracer::has_intrinsic_alignment, CCL_ClTracer::has_magnification, CCL_ClTracer::spl_ba, CCL_ClTracer::spl_bz, CCL_ClTracer::spl_nz, CCL_ClTracer::spl_rf, CCL_ClTracer::spl_sz, CCL_ClTracer::spl_wL, CCL_ClTracer::spl_wM, and CCL_ClTracer::tracer_type.
Referenced by compare_cls(), main(), and test_angpow_precision().
 {
   if((clt->tracer_type==ccl_number_counts_tracer) || (clt->tracer_type==ccl_weak_lensing_tracer))
     ccl_spline_free(clt->spl_nz);
   if(clt->tracer_type==ccl_number_counts_tracer) {
     ccl_spline_free(clt->spl_bz);
     if(clt->has_magnification) {
       ccl_spline_free(clt->spl_sz);
       ccl_spline_free(clt->spl_wM);
     }
   }
   else if(clt->tracer_type==ccl_weak_lensing_tracer) {
     ccl_spline_free(clt->spl_wL);
     if(clt->has_intrinsic_alignment) {
       ccl_spline_free(clt->spl_ba);
       ccl_spline_free(clt->spl_rf);
     }
   }
   free(clt);
 }
CCL_ClTracer* ccl_cl_tracer_lensing (ccl_cosmology * cosmo, int has_alignment, int nz_n, double * z_n, double * n, int nz_ba, double * z_ba, double * ba, int nz_rf, double * z_rf, double * rf, int * status)
Simplified constructor for a lensing ClTracer.
Parameters
has_intrinsic_alignment Set to 1 if you want to compute the IA contribution to shear
nz_n Number of bins in z_n and n
z_n Redshifts for each redshift interval of n
n Number count of objects per redshift interval (Note: arbitrary normalization - renormalized inside)
nz_ba Number of bins in z_ba and ba
z_ba Redshifts for each redshift interval of ba
ba Alignment bias in each redshift bin
nz_rf Number of bins in z_f and f
z_rf Redshifts for each redshift interval of rf
rf Aligned red fraction in each redshift bin
status Status flag. 0 if there are no errors, nonzero otherwise. For specific cases see documentation for ccl_error.c
Returns
CCL_ClTracer object
Definition at line 642 of file ccl_cls.c.
References ccl_cl_tracer(), and ccl_weak_lensing_tracer.
Referenced by compare_cls(), and compare_corr().
 {
   return ccl_cl_tracer(cosmo,ccl_weak_lensing_tracer,0,0,has_alignment,
                nz_n,z_n,n,-1,NULL,NULL,-1,NULL,NULL,
                nz_ba,z_ba,ba,nz_rf,z_rf,rf,0, status);
 }
CCL_ClTracer* ccl_cl_tracer_lensing_simple (ccl_cosmology * cosmo, int nz_n, double * z_n, double * n, int * status)
Simplified constructor for a lensing ClTracer without intrinsic alignment.
Parameters
nz_n Number of bins in z_n and n
z_n Redshifts for each redshift interval of n
n Number count of objects per redshift interval (Note: arbitrary normalization - renormalized inside)
status Status flag. 0 if there are no errors, nonzero otherwise. For specific cases see documentation for ccl_error.c
Returns
CCL_ClTracer object
Definition at line 653 of file ccl_cls.c.
References ccl_cl_tracer(), and ccl_weak_lensing_tracer.
Referenced by compare_cls(), compare_corr(), and main().
 {
   return ccl_cl_tracer(cosmo,ccl_weak_lensing_tracer,0,0,0,
                nz_n,z_n,n,-1,NULL,NULL,-1,NULL,NULL,
                -1,NULL,NULL,-1,NULL,NULL,0, status);
 }
CCL_ClTracer* ccl_cl_tracer_number_counts (ccl_cosmology * cosmo, int has_rsd, int has_magnification, int nz_n, double * z_n, double * n, int nz_b, double * z_b, double * b, int nz_s, double * z_s, double * s, int * status)
Simplified constructor for a clustering ClTracer.
Parameters
cosmo Cosmological parameters
has_rsd Set to 1 if you want to compute the RSD contribution to number counts (0 otherwise)
has_magnification Set to 1 if you want to compute the magnification contribution to number counts (0 otherwise)
nz_n Number of bins in z_n and n
z_n Redshifts for each redshift interval of n
n Number count of objects per redshift interval (Note: arbitrary normalization - renormalized inside)
nz_b Number of bins in z_b and b
z_b Redshifts for each redshift interval of b
b Clustering bias in each redshift bin
nz_s Number of bins in z_s and s
z_s Redshifts for each redshift interval of s
s Magnification bias in each redshift bin
status Status flag. 0 if there are no errors, nonzero otherwise. For specific cases see documentation for ccl_error.c
Returns
CCL_ClTracer object
Definition at line 622 of file ccl_cls.c.
References ccl_cl_tracer(), and ccl_number_counts_tracer.
Referenced by main(), and test_angpow_precision().
 {
   return ccl_cl_tracer(cosmo,ccl_number_counts_tracer,has_rsd,has_magnification,0,
                nz_n,z_n,n,nz_b,z_b,b,nz_s,z_s,s,
                -1,NULL,NULL,-1,NULL,NULL,0, status);
 }
CCL_ClTracer* ccl_cl_tracer_number_counts_simple (ccl_cosmology * cosmo, int nz_n, double * z_n, double * n, int nz_b, double * z_b, double * b, int * status)
Simplified constructor for a ClTracer without magnification nor RSD.
Parameters
nz_n Number of bins in z_n and n
z_n Redshifts for each redshift interval of n
n Number count of objects per redshift interval (Note: arbitrary normalization - renormalized inside)
nz_b Number of bins in z_b and b
z_b Redshifts for each redshift interval of b
b Clustering bias in each redshift bin
status Status flag. 0 if there are no errors, nonzero otherwise. For specific cases see documentation for ccl_error.c
Returns
CCL_ClTracer object
Definition at line 633 of file ccl_cls.c.
References ccl_cl_tracer(), and ccl_number_counts_tracer.
Referenced by compare_cls(), compare_corr(), and main().
 {
   return ccl_cl_tracer(cosmo,ccl_number_counts_tracer,0,0,0,
                nz_n,z_n,n,nz_b,z_b,b,-1,NULL,NULL,
                -1,NULL,NULL,-1,NULL,NULL,0, status);
 }
void ccl_cl_workspace_free (CCL_ClWorkspace * w)
Definition at line 59 of file ccl_cls.c.
References CCL_ClWorkspace::l_arr.
Referenced by compare_cls(), compare_corr(), main(), and test_angpow_precision().
 {
   free(w->l_arr);
   free(w);
 }
CCL_ClWorkspace* ccl_cl_workspace_new (int lmax, int l_limber, double l_logstep, int l_linstep, int * status)
Definition at line 65 of file ccl_cls.c.
References CCL_ERROR_MEMORY, CCL_MAX, CCL_ClWorkspace::l_arr, CCL_ClWorkspace::l_limber, CCL_ClWorkspace::l_linstep, CCL_ClWorkspace::l_logstep, CCL_ClWorkspace::lmax, CCL_ClWorkspace::n_ls, and w.
Referenced by ccl_cl_workspace_new_limber(), and test_angpow_precision().
 {
   int i_l,l0,increment;
   CCL_ClWorkspace *w=(CCL_ClWorkspace *)malloc(sizeof(CCL_ClWorkspace));
   if(w==NULL)
     *status=CCL_ERROR_MEMORY;
   if(*status==0) {
     //Set params
     w->lmax=lmax;
     w->l_limber=l_limber;
     w->l_logstep=l_logstep;
     w->l_linstep=l_linstep;
     //Compute number of multipoles
     i_l=0; l0=0;
     increment=CCL_MAX(((int)(l0*(w->l_logstep-1.))),1);
     while((l0 < w->lmax) && (increment < w->l_linstep)) {
       i_l++;
       l0+=increment;
       increment=CCL_MAX(((int)(l0*(w->l_logstep-1))),1);
     }
     increment=w->l_linstep;
     while(l0 < w->lmax) {
       i_l++;
       l0+=increment;
     }
     //Allocate array of multipoles
     w->n_ls=i_l+1;
     w->l_arr=(int *)malloc(w->n_ls*sizeof(int));
     if(w->l_arr==NULL)
       *status=CCL_ERROR_MEMORY;
   }
   if(*status==0) {
     //Redo the computation above and store values of ell
     i_l=0; l0=0;
     increment=CCL_MAX(((int)(l0*(w->l_logstep-1.))),1);
     while((l0 < w->lmax) && (increment < w->l_linstep)) {
       w->l_arr[i_l]=l0;
       i_l++;
       l0+=increment;
       increment=CCL_MAX(((int)(l0*(w->l_logstep-1))),1);
     }
     increment=w->l_linstep;
     while(l0 < w->lmax) {
       w->l_arr[i_l]=l0;
       i_l++;
       l0+=increment;
     }
     //Don't go further than lmaw
     w->l_arr[w->n_ls-1]=w->lmax;
   }
   return w;
 }
CCL_ClWorkspace* ccl_cl_workspace_new_limber (int lmax, double l_logstep, int l_linstep, int * status)
Definition at line 124 of file ccl_cls.c.
References ccl_cl_workspace_new().
Referenced by compare_cls(), compare_corr(), and main().
 {
   return ccl_cl_workspace_new(lmax,-1,l_logstep,l_linstep,status);
 }
double ccl_get_tracer_fa (ccl_cosmology * cosmo, CCL_ClTracer * clt, double a, int func_code, int * status)
Method to return certain redshift or distance-dependent internal quantities for a given tracer.
Parameters
cosmo Cosmological parameters
clt ClTracer object
a scale factor at which the function is to be evaluated
func_code integer defining which internal function to evaluate. Choose between: ccl_trf_nz (redshift distribution), ccl_trf_bz (clustering bias), ccl_trf_sz (magnification bias), ccl_trf_rf (aligned fraction), ccl_trf_ba (alignment bias), ccl_trf_wL (weak lensing window function), ccl_trf_wM (magnification window function)
status Status flag. 0 if there are no errors, nonzero otherwise. For specific cases see documentation for ccl_error.c
Returns
interpolated value of the requested function
Definition at line 1048 of file ccl_cls.c.
References ccl_comoving_radial_distance(), ccl_cosmology_set_status_message(), CCL_ERROR_INCONSISTENT, ccl_spline_eval(), ccl_trf_ba, ccl_trf_bz, ccl_trf_nz, ccl_trf_rf, ccl_trf_sz, ccl_trf_wL, ccl_trf_wM, check_clt_fa_inconsistency(), CCL_ClTracer::spl_ba, CCL_ClTracer::spl_bz, CCL_ClTracer::spl_nz, CCL_ClTracer::spl_rf, CCL_ClTracer::spl_sz, CCL_ClTracer::spl_wL, CCL_ClTracer::spl_wM, and x.
 {
   SplPar *spl;
   if(check_clt_fa_inconsistency(clt,func_code)) {
     *status=CCL_ERROR_INCONSISTENT;
     ccl_cosmology_set_status_message(cosmo, "ccl_cls.c: inconsistent combination of tracer and internal function to be evaluated");
     return -1;
   }
   switch(func_code) {
   case ccl_trf_nz :
     spl=clt->spl_nz;
     break;
   case ccl_trf_bz :
     spl=clt->spl_bz;
     break;
   case ccl_trf_sz :
     spl=clt->spl_sz;
     break;
   case ccl_trf_rf :
     spl=clt->spl_rf;
     break;
   case ccl_trf_ba :
     spl=clt->spl_ba;
     break;
   case ccl_trf_wL :
     spl=clt->spl_wL;
     break;
   case ccl_trf_wM :
     spl=clt->spl_wM;
     break;
   }
   double x;
   if((func_code==ccl_trf_wL) || (func_code==ccl_trf_wM))
     x=ccl_comoving_radial_distance(cosmo,a,status); //x-variable is comoving distance for lensing kernels
   else
     x=1./a-1; //x-variable is redshift by default
   return ccl_spline_eval(x,spl);
 }
int ccl_get_tracer_fas (ccl_cosmology * cosmo, CCL_ClTracer * clt, int na, double * a, double * fa, int func_code, int * status)
Method to return certain redshift or distance-dependent internal quantities for a given tracer.
Parameters
cosmo Cosmological parameters
clt ClTracer object
na number of points at which the function will be evaluated
a na values of the scale factor at which the function is to be evaluated
fa output array with na values that will store the interpolated function values
func_code integer defining which internal function to evaluate. Choose between: ccl_trf_nz (redshift distribution), ccl_trf_bz (clustering bias), ccl_trf_sz (magnification bias), ccl_trf_rf (aligned fraction), ccl_trf_ba (alignment bias), ccl_trf_wL (weak lensing window function), ccl_trf_wM (magnification window function)
status Status flag. 0 if there are no errors, nonzero otherwise. For specific cases see documentation for ccl_error.c
Returns
void
Definition at line 1091 of file ccl_cls.c.
References ccl_comoving_radial_distance(), ccl_cosmology_set_status_message(), CCL_ERROR_INCONSISTENT, ccl_spline_eval(), ccl_trf_ba, ccl_trf_bz, ccl_trf_nz, ccl_trf_rf, ccl_trf_sz, ccl_trf_wL, ccl_trf_wM, check_clt_fa_inconsistency(), CCL_ClTracer::spl_ba, CCL_ClTracer::spl_bz, CCL_ClTracer::spl_nz, CCL_ClTracer::spl_rf, CCL_ClTracer::spl_sz, CCL_ClTracer::spl_wL, CCL_ClTracer::spl_wM, and x.
Referenced by main().
 {
   SplPar *spl;
   if(check_clt_fa_inconsistency(clt,func_code)) {
     *status=CCL_ERROR_INCONSISTENT;
     ccl_cosmology_set_status_message(cosmo, "ccl_cls.c: inconsistent combination of tracer and internal function to be evaluated");
     return -1;
   }
   switch(func_code) {
   case ccl_trf_nz :
     spl=clt->spl_nz;
     break;
   case ccl_trf_bz :
     spl=clt->spl_bz;
     break;
   case ccl_trf_sz :
     spl=clt->spl_sz;
     break;
   case ccl_trf_rf :
     spl=clt->spl_rf;
     break;
   case ccl_trf_ba :
     spl=clt->spl_ba;
     break;
   case ccl_trf_wL :
     spl=clt->spl_wL;
     break;
   case ccl_trf_wM :
     spl=clt->spl_wM;
     break;
   }
   int compchi = (func_code==ccl_trf_wL) || (func_code==ccl_trf_wM);
   int ia;
   for(ia=0;ia<na;ia++) {
     double x;
     if(compchi) //x-variable is comoving distance for lensing kernels
       x=ccl_comoving_radial_distance(cosmo,a[ia],status);
     else //x-variable is redshift by default
       x=1./a[ia]-1;
     fa[ia]=ccl_spline_eval(x,spl);
   }
   return 0;
 }