Fast Methods for Cosmological Simulations: src/3party/CCL/tests/ccl_test_angpow.c File Reference
ccl_test_angpow.c File Reference
#include "ccl.h"
#include "ctest.h"
#include <stdio.h>
#include <math.h>
Classes
struct angpow_data
Macros
#define NZ 1024
#define Z0_GC 1.0
#define SZ_GC 0.02
#define NL 499
#define CLS_PRECISION 3E-3
Functions
void __attribute__ ((weak))
static void test_angpow_precision (struct angpow_data *data)
void __ctest_angpow_precision_run (struct angpow_data *data)
Variables
static struct angpow_data __ctest_angpow_data
Macro Definition Documentation
#define CLS_PRECISION 3E-3
Definition at line 11 of file ccl_test_angpow.c.
Referenced by test_angpow_precision().
#define NL 499
Definition at line 9 of file ccl_test_angpow.c.
Referenced by test_angpow_precision().
#define NZ 1024
Definition at line 6 of file ccl_test_angpow.c.
Referenced by test_angpow_precision().
#define SZ_GC 0.02
Definition at line 8 of file ccl_test_angpow.c.
Referenced by test_angpow_precision().
#define Z0_GC 1.0
Definition at line 7 of file ccl_test_angpow.c.
Referenced by test_angpow_precision().
Function Documentation
void __attribute__ ((weak))
Definition at line 32 of file ccl_test_angpow.c.
References ccl_mnu_sum.
                    {
   data->Omega_c = 0.25;
   data->Omega_b = 0.05;
   data->h = 0.7;
   data->A_s = 2.1e-9;
   data->n_s = 0.96;
   data->Omega_v = 0.7;
   data->Neff=3.046;
   double mnuval = 0.;
   data->mnu = &mnuval;
   data->mnu_type = ccl_mnu_sum;
   data->w_0     = -1;
   data->w_a    = 0;
   data->Omega_k = 0;
 }
void __ctest_angpow_precision_run (struct angpow_data * data)
Definition at line 119 of file ccl_test_angpow.c.
References test_angpow_precision().
{
   test_angpow_precision(data);
 }
static void test_angpow_precision (struct angpow_data * data) static
Definition at line 50 of file ccl_test_angpow.c.
References angpow_data::A_s, ASSERT_TRUE, ccl_angular_cls(), ccl_boltzmann_class, ccl_cl_tracer_free(), ccl_cl_tracer_number_counts(), ccl_cl_workspace_free(), ccl_cl_workspace_new(), ccl_cosmology_create(), ccl_cosmology_free(), ccl_linear, ccl_parameters_create(), CCL_ClTracer::chimax, CCL_ClTracer::chimin, CLS_PRECISION, default_config, angpow_data::h, cl_cmbl_bm::l, ccl_configuration::matter_power_spectrum_method, angpow_data::mnu, angpow_data::mnu_type, angpow_data::n_s, angpow_data::Neff, NL, NZ, angpow_data::Omega_b, angpow_data::Omega_c, ccl_parameters::Omega_g, angpow_data::Omega_k, ccl_parameters::Omega_l, angpow_data::Omega_v, pow(), SZ_GC, ccl_configuration::transfer_function_method, angpow_data::w_0, angpow_data::w_a, and Z0_GC.
Referenced by __ctest_angpow_precision_run().
 {
   // Status flag
   int status =0;
   // Initialize cosmological parameters
   ccl_configuration ccl_config=default_config;
   ccl_config.transfer_function_method=ccl_boltzmann_class;
   ccl_config.matter_power_spectrum_method=ccl_linear;
   ccl_parameters ccl_params = ccl_parameters_create(data->Omega_c, data->Omega_b, data->Omega_k, data->Neff, data->mnu, data->mnu_type,data->w_0, data->w_a, data->h, data->A_s, data->n_s,-1,-1,-1,-1,NULL,NULL, &status);
   ccl_params.Omega_g=0.;
   ccl_params.Omega_l=data->Omega_v;
   // Initialize cosmology object given cosmo params
   ccl_cosmology *ccl_cosmo=ccl_cosmology_create(ccl_params,ccl_config);
   // Create tracers for angular power spectra
   double z_arr_gc[NZ],nz_arr_gc[NZ],bz_arr[NZ];
   for(int i=0;i<NZ;i++)
     {
       z_arr_gc[i]=Z0_GC-5*SZ_GC+10*SZ_GC*(i+0.5)/NZ;
       nz_arr_gc[i]=exp(-0.5*pow((z_arr_gc[i]-Z0_GC)/SZ_GC,2));
       bz_arr[i]=1;
     }
   // Galaxy clustering tracer
   bool has_rsd = true;
   bool has_magnification = false;
   CCL_ClTracer *ct_gc_A=ccl_cl_tracer_number_counts(ccl_cosmo,has_rsd,has_magnification,NZ,z_arr_gc,nz_arr_gc,NZ,z_arr_gc,bz_arr,-1,NULL,NULL, &status);
   CCL_ClTracer *ct_gc_B=ccl_cl_tracer_number_counts(ccl_cosmo,has_rsd,has_magnification,NZ,z_arr_gc,nz_arr_gc,NZ,z_arr_gc,bz_arr,-1,NULL,NULL, &status);
   int *ells=malloc(NL*sizeof(int));
   double *cells_gg_angpow=malloc(NL*sizeof(double));
   for(int ii=0;ii<NL;ii++)
     ells[ii]=ii;
   // Workspaces
   double linstep = 40;
   double logstep = 1.15;
   double dchi = (ct_gc_A->chimax-ct_gc_A->chimin)/1000.;
   CCL_ClWorkspace *wap=ccl_cl_workspace_new(NL+1,2*ells[NL-1],logstep,linstep,&status);
   // Compute C_ell
   ccl_angular_cls(ccl_cosmo,wap,ct_gc_A,ct_gc_A,NL,ells,cells_gg_angpow,&status);
   double rel_precision = 0.;
   FILE *f=fopen("./tests/benchmark/angpow_gg.txt","r");
   for(int ii=2;ii<NL;ii++) {
     int l;
     double ratio,cl_gg_nl,cl_gg_ap=cells_gg_angpow[ii];
     int stat=fscanf(f,"%d %lE",&l,&cl_gg_nl);
     ASSERT_TRUE(l==ells[ii]);
     ASSERT_TRUE(stat==2);
     ratio = fabs(cl_gg_nl-cl_gg_ap)/cl_gg_nl;
     rel_precision += ratio;
   }
   fclose(f);
   rel_precision /= NL;
   ASSERT_TRUE(rel_precision < CLS_PRECISION);
   //Free up tracers
   ccl_cl_tracer_free(ct_gc_A);
   ccl_cl_tracer_free(ct_gc_B);
   free(ells);
   ccl_cl_workspace_free(wap);
   free(cells_gg_angpow);
   ccl_cosmology_free(ccl_cosmo);
 }
Variable Documentation
struct angpow_data __ctest_angpow_data static
Definition at line 119 of file ccl_test_angpow.c.