Fast Methods for Cosmological Simulations: src/3party/CCL/tests/ccl_test_growth_lowz.c File Reference
ccl_test_growth_lowz.c File Reference
#include "ccl.h"
#include "ctest.h"
#include <stdio.h>
#include <math.h>
Classes
struct growth_lowz_data
Macros
#define GROWTH_TOLERANCE 6e-6
#define MGROWTH_TOLERANCE 5.0e-5
Functions
static void read_growth_test_file (double z[6], double gf[5][6])
void __attribute__ ((weak))
static void compare_growth (int model, struct growth_lowz_data *data)
static void check_mgrowth (void)
void __ctest_growth_lowz_model_1_run (struct growth_lowz_data *data)
void __ctest_growth_lowz_model_2_run (struct growth_lowz_data *data)
void __ctest_growth_lowz_model_3_run (struct growth_lowz_data *data)
void __ctest_growth_lowz_model_4_run (struct growth_lowz_data *data)
void __ctest_growth_lowz_model_5_run (struct growth_lowz_data *data)
void __ctest_growth_lowz_mgrowth_run (struct growth_lowz_data *data)
Variables
static struct growth_lowz_data __ctest_growth_lowz_data
Macro Definition Documentation
#define GROWTH_TOLERANCE 6e-6
Definition at line 7 of file ccl_test_growth_lowz.c.
Referenced by compare_growth().
#define MGROWTH_TOLERANCE 5.0e-5
Definition at line 8 of file ccl_test_growth_lowz.c.
Referenced by check_mgrowth().
Function Documentation
void __attribute__ ((weak))
Definition at line 53 of file ccl_test_growth_lowz.c.
References ccl_mnu_sum, and read_growth_test_file().
{
   // Values that are the same for all 5 models
   data->Omega_c = 0.25;
   data->Omega_b = 0.05;
   data->h = 0.7;
   data->A_s = 2.1e-9;
   data->n_s = 0.96;
   data->Neff=0;
   double mnuval = 0.;
   data->mnu= &mnuval;
   data-> mnu_type = ccl_mnu_sum;
   // Values that are different for the different models
   double Omega_v[5] = {  0.7,  0.7,  0.7,  0.65, 0.75 };
   double w_0[5]     = { -1.0, -0.9, -0.9, -0.9, -0.9  };
   double w_a[5]     = {  0.0,  0.0,  0.1,  0.1,  0.1  };
   // Fill in the values from these constant arrays.
   for (int i=0; i<5; i++) {
     data->Omega_v[i] = Omega_v[i];
     data->w_0[i]     = w_0[i];
     data->w_a[i]     = w_a[i];
     data->Omega_k[i] = 1.0 - data->Omega_c - data->Omega_b - data->Omega_v[i];
   }
   // The file of benchmark data.
   read_growth_test_file(data->z, data->gf);
 }
void __ctest_growth_lowz_mgrowth_run (struct growth_lowz_data * data)
Definition at line 181 of file ccl_test_growth_lowz.c.
References check_mgrowth().
{
   check_mgrowth();
 }
void __ctest_growth_lowz_model_1_run (struct growth_lowz_data * data)
Definition at line 156 of file ccl_test_growth_lowz.c.
References compare_growth().
{
   int model = 0;
   compare_growth(model, data);
 }
void __ctest_growth_lowz_model_2_run (struct growth_lowz_data * data)
Definition at line 161 of file ccl_test_growth_lowz.c.
References compare_growth().
{
   int model = 1;
   compare_growth(model, data);
 }
void __ctest_growth_lowz_model_3_run (struct growth_lowz_data * data)
Definition at line 166 of file ccl_test_growth_lowz.c.
References compare_growth().
{
   int model = 2;
   compare_growth(model, data);
 }
void __ctest_growth_lowz_model_4_run (struct growth_lowz_data * data)
Definition at line 171 of file ccl_test_growth_lowz.c.
References compare_growth().
{
   int model = 3;
   compare_growth(model, data);
 }
void __ctest_growth_lowz_model_5_run (struct growth_lowz_data * data)
Definition at line 176 of file ccl_test_growth_lowz.c.
References compare_growth().
{
   int model = 4;
   compare_growth(model, data);
 }
static void check_mgrowth (void) static
Definition at line 110 of file ccl_test_growth_lowz.c.
References ASSERT_DBL_NEAR_TOL, ccl_cosmology_create(), ccl_cosmology_free(), ccl_growth_factor(), ccl_growth_rate(), ccl_parameters_create(), default_config, MGROWTH_TOLERANCE, ccl_parameters::Omega_g, ccl_parameters::Omega_k, ccl_parameters::Omega_l, and ccl_parameters::Omega_m.
Referenced by __ctest_growth_lowz_mgrowth_run().
 {
   int ii,nz_mg=128;
   double *z_mg,*df_mg;
   ccl_parameters params1,params2;
   ccl_cosmology *cosmo1,*cosmo2;
   int status=0;
   z_mg=malloc(nz_mg*sizeof(double));
   df_mg=malloc(nz_mg*sizeof(double));
   for(ii=0;ii<nz_mg;ii++) {
     z_mg[ii]=4*(ii+0.0)/(nz_mg-1.);
     df_mg[ii]=0.1/(1+z_mg[ii]);
   }
   double mnuval = 0;
   params1=ccl_parameters_create(0.25,0.05,0,0,&mnuval, 1, -1,0,0.7,2.1E-9,0.96,-1,-1,-1,-1,NULL,NULL, &status);
   params2=ccl_parameters_create(0.25,0.05,0,0,&mnuval, 1, -1,0,0.7,2.1E-9,0.96,-1,-1,-1,nz_mg,z_mg,df_mg, &status);
   params1.Omega_g=0; //enforce no radiation
   params1.Omega_l = 1.-params1.Omega_m-params1.Omega_k; //reomcpute Omega_l without radiation
   params2.Omega_g=0; //enforce no radiation
   params2.Omega_l = 1.-params2.Omega_m-params2.Omega_k; //reomcpute Omega_l without radiation
   cosmo1=ccl_cosmology_create(params1,default_config);
   cosmo2=ccl_cosmology_create(params2,default_config);
   //We have included a growth modification \delta f = K*a (with K==0.1 arbitrarily)
   //This case has an analytic solution, given by D(a) = D_0(a)*exp(K*(a-1))
   //Here we check the growth computed by the library with the analytic solution.
   for(ii=0;ii<nz_mg;ii++) {
     double a=1./(1+z_mg[ii]);
     double d1=ccl_growth_factor(cosmo1,a,&status);
     double d2=ccl_growth_factor(cosmo2,a,&status);
     double f1=ccl_growth_rate(cosmo1,a,&status);
     double f2=ccl_growth_rate(cosmo2,a,&status);
     double f2r=f1+0.1*a;
     double d2r=d1*exp(0.1*(a-1));
     ASSERT_DBL_NEAR_TOL(d2r/d2,1.,MGROWTH_TOLERANCE);
     ASSERT_DBL_NEAR_TOL(f2r/f2,1.,MGROWTH_TOLERANCE);
   }
   free(z_mg);
   free(df_mg);
   ccl_cosmology_free(cosmo1);
   ccl_cosmology_free(cosmo2);
 }
static void compare_growth (int model, struct growth_lowz_data * data) static
Definition at line 83 of file ccl_test_growth_lowz.c.
References growth_lowz_data::A_s, ASSERT_DBL_NEAR_TOL, ASSERT_NOT_NULL, ccl_cosmology_create(), ccl_cosmology_free(), ccl_growth_factor_unnorm(), ccl_parameters_create(), cl_cmbl_bm::cosmo, default_config, growth_lowz_data::gf, GROWTH_TOLERANCE, growth_lowz_data::h, growth_lowz_data::mnu, growth_lowz_data::mnu_type, growth_lowz_data::n_s, growth_lowz_data::Neff, growth_lowz_data::Omega_b, growth_lowz_data::Omega_c, ccl_parameters::Omega_g, growth_lowz_data::Omega_k, ccl_parameters::Omega_k, ccl_parameters::Omega_l, ccl_parameters::Omega_m, halomod_bm::params, ccl_cosmology::status_message, growth_lowz_data::w_0, growth_lowz_data::w_a, and growth_lowz_data::z.
Referenced by __ctest_growth_lowz_model_1_run(), __ctest_growth_lowz_model_2_run(), __ctest_growth_lowz_model_3_run(), __ctest_growth_lowz_model_4_run(), and __ctest_growth_lowz_model_5_run().
 {
   int status=0;
   // Make the parameter set from the input data
   // Values of some parameters depend on the model index
   ccl_parameters params = ccl_parameters_create(data->Omega_c, data->Omega_b, data->Omega_k[model], data->Neff, data->mnu, data->mnu_type, data->w_0[model], data->w_a[model], data->h, data->A_s, data->n_s,-1,-1,-1,-1,NULL,NULL, &status);
   params.Omega_g=0;//enforce no radiation
   params.Omega_l = 1.-params.Omega_m-params.Omega_k; //recompute Omega_l without radiation
   // Make a cosmology object from the parameters with the default configuration
   ccl_cosmology * cosmo = ccl_cosmology_create(params, default_config);
   ASSERT_NOT_NULL(cosmo);
   // Compare to benchmark data
   for (int j=0; j<6; j++) {
     double a = 1/(1.+data->z[j]);
     double gf_ij=ccl_growth_factor_unnorm(cosmo,a, &status);
     if (status) printf("%s\n",cosmo->status_message);
     double absolute_tolerance = GROWTH_TOLERANCE*data->gf[model][j];
     if (fabs(absolute_tolerance)<1e-12) absolute_tolerance = 1e-12;
     ASSERT_DBL_NEAR_TOL(data->gf[model][j], gf_ij, absolute_tolerance);
   }
   ccl_cosmology_free(cosmo);
 }
static void read_growth_test_file (double z[6], double gf[5][6]) static
Definition at line 30 of file ccl_test_growth_lowz.c.
References ASSERT_EQUAL, ASSERT_NOT_NULL, and Catch::Matchers::Vector::Detail::count().
Referenced by __attribute__().
 {
   //Growth is normalized to ~a at early times
   FILE * f = fopen("./tests/benchmark/growth_model1-5.txt", "r");
   ASSERT_NOT_NULL(f);
   // Ignore header line
   char str[1024];
   char* rtn;
   rtn = fgets(str, 1024, f);
     // File is fixed format - five rows and six columns
   for (int i=0; i<6; i++) {
     int count = fscanf(f, "%le %le %le %le %le %le\n", &z[i],
                &gf[0][i], &gf[1][i], &gf[2][i], &gf[3][i], &gf[4][i]);
         // Check that all the stuff in the benchmark is there
     ASSERT_EQUAL(6, count);
   }
   fclose(f);
 }
Variable Documentation
static struct growth_lowz_data __ctest_growth_lowz_data static
Definition at line 156 of file ccl_test_growth_lowz.c.