Fast Methods for Cosmological Simulations: src/3party/CCL/include/ccl_massfunc.h File Reference
ccl_massfunc.h File Reference
Functions
CCL_BEGIN_DECLS void ccl_cosmology_compute_sigma (ccl_cosmology *cosmo, int *status)
double ccl_massfunc (ccl_cosmology *cosmo, double smooth_mass, double a, double odelta, int *status)
double ccl_halo_bias (ccl_cosmology *cosmo, double smooth_mass, double a, double odelta, int *status)
double ccl_massfunc_m2r (ccl_cosmology *cosmo, double smooth_mass, int *status)
double ccl_sigmaM (ccl_cosmology *cosmo, double smooth_mass, double a, int *status)
double dc_NakamuraSuto (ccl_cosmology *cosmo, double a, int *status)
double Dv_BryanNorman (ccl_cosmology *cosmo, double a, int *status)
double r_delta (ccl_cosmology *cosmo, double halomass, double a, double odelta, int *status)
Function Documentation
CCL_BEGIN_DECLS void ccl_cosmology_compute_sigma (ccl_cosmology * cosmo, int * status)
Definition at line 431 of file ccl_massfunc.c.
References ccl_data::accelerator_m, ccl_cosmology_set_status_message(), CCL_ERROR_LINSPACE, CCL_ERROR_SPLINE, ccl_linear_spacing(), ccl_massfunc_m2r(), ccl_raise_gsl_warning(), ccl_sigmaR(), ccl_splines, ccl_cosmology::computed_sigma, ccl_cosmology::data, ccl_data::dlnsigma_dlogm, ccl_spline_params::LOGM_SPLINE_DELTA, ccl_spline_params::LOGM_SPLINE_MAX, ccl_spline_params::LOGM_SPLINE_MIN, ccl_spline_params::LOGM_SPLINE_NM, ccl_data::logsigma, m, M_SPLINE_TYPE, and pow().
Referenced by ccl_dlninvsig_dlogm(), ccl_halo_bias(), and ccl_sigmaM().
 {
   if(cosmo->computed_sigma)
     return;
   // create linearly-spaced values of the mass.
   int nm=ccl_splines->LOGM_SPLINE_NM;
   double * m = ccl_linear_spacing(ccl_splines->LOGM_SPLINE_MIN, ccl_splines->LOGM_SPLINE_MAX, nm);
   // create space for y, to be filled with sigma and dlnsigma_dlogm
   double * y = malloc(sizeof(double)*nm);
   double smooth_radius;
   double na, nb;
   // start up of GSL pointers
   int gslstatus = 0;
   gsl_spline *logsigma;
   gsl_spline *dlnsigma_dlogm;
   if (m==NULL ||
       (fabs(m[0]-ccl_splines->LOGM_SPLINE_MIN)>1e-5) ||
       (fabs(m[nm-1]-ccl_splines->LOGM_SPLINE_MAX)>1e-5) ||
       (m[nm-1]>10E17)
       ) {
     *status = CCL_ERROR_LINSPACE;
     ccl_cosmology_set_status_message(cosmo,"ccl_cosmology_compute_sigmas(): Error creating linear spacing in m\n");
   }
   // fill in sigma, if no errors have been triggered at this time.
   if (*status == 0) {
     for (int i=0; i<nm; i++) {
       smooth_radius = ccl_massfunc_m2r(cosmo, pow(10,m[i]), status);
       y[i] = log10(ccl_sigmaR(cosmo, smooth_radius, 1., status));
     }
     logsigma = gsl_spline_alloc(M_SPLINE_TYPE, nm);
     *status = gsl_spline_init(logsigma, m, y, nm);
   }
   if (*status !=0 ) {
     *status = CCL_ERROR_SPLINE ;
     ccl_cosmology_set_status_message(cosmo, "ccl_massfunc.c: ccl_cosmology_compute_sigma(): Error creating sigma(M) spline\n");
   }
   // again, making splines assuming nothing bad has happened to this point
   if (*status == 0 ) {
     for (int i=0; i<nm; i++) {
       if(i==0) {
         gslstatus |= gsl_spline_eval_e(logsigma, m[i], NULL,&na);
         gslstatus |= gsl_spline_eval_e(logsigma, m[i]+ccl_splines->LOGM_SPLINE_DELTA/2., NULL,&nb);
         y[i] = (na-nb)*log(10.);
         y[i] = 2.*y[i] / ccl_splines->LOGM_SPLINE_DELTA;
       }
       else if (i==nm-1) {
         gslstatus |= gsl_spline_eval_e(logsigma, m[i]-ccl_splines->LOGM_SPLINE_DELTA/2., NULL,&na);
         gslstatus |= gsl_spline_eval_e(logsigma, m[i], NULL,&nb);
         y[i] = (na-nb)*log(10.);
         y[i] = 2.*y[i] / ccl_splines->LOGM_SPLINE_DELTA;
       }
       else {
         gslstatus |= gsl_spline_eval_e(logsigma, m[i]-ccl_splines->LOGM_SPLINE_DELTA/2., NULL,&na);
         gslstatus |= gsl_spline_eval_e(logsigma, m[i]+ccl_splines->LOGM_SPLINE_DELTA/2., NULL,&nb);
         y[i] = (na-nb)*log(10.);
         y[i] = y[i] / ccl_splines->LOGM_SPLINE_DELTA;
       }
     }
   }
   if(gslstatus != GSL_SUCCESS) {
     ccl_raise_gsl_warning(gslstatus, "ccl_massfunc.c: ccl_cosmology_compute_sigma():");
     *status |= gslstatus;
     *status = CCL_ERROR_SPLINE ;
     ccl_cosmology_set_status_message(cosmo, "ccl_massfunc.c: ccl_cosmology_compute_sigma(): Error evaluating grid points for dlnsigma/dlogM spline\n");
   }
   if(*status==0) {
     dlnsigma_dlogm = gsl_spline_alloc(M_SPLINE_TYPE, nm);
     *status = gsl_spline_init(dlnsigma_dlogm, m, y, nm);
     if(cosmo->data.accelerator_m==NULL)
       cosmo->data.accelerator_m=gsl_interp_accel_alloc();
   }
   if(*status!=0) {
     *status = CCL_ERROR_SPLINE ;
     ccl_cosmology_set_status_message(cosmo, "ccl_massfunc.c: ccl_cosmology_compute_sigma(): Error creating dlnsigma/dlogM spline\n");
   }
   cosmo->data.logsigma = logsigma;
   cosmo->data.dlnsigma_dlogm = dlnsigma_dlogm;
   cosmo->computed_sigma = true;
   free(m);
   free(y);
   if(*status != 0) {
     gsl_spline_free(logsigma);
     gsl_spline_free(dlnsigma_dlogm);
   }
   return;
 }
double ccl_halo_bias (ccl_cosmology * cosmo, double smooth_mass, double a, double odelta, int * status)
Definition at line 582 of file ccl_massfunc.c.
References ccl_check_status(), ccl_cosmology_compute_sigma(), ccl_cosmology_set_status_message(), CCL_ERROR_NOT_IMPLEMENTED, ccl_halo_b1(), ccl_cosmology::computed_sigma, ccl_parameters::N_nu_mass, and ccl_cosmology::params.
Referenced by main(), and two_halo_integrand().
 {
   if (cosmo->params.N_nu_mass>0){
       *status = CCL_ERROR_NOT_IMPLEMENTED;
       ccl_cosmology_set_status_message(cosmo, "ccl_background.c: ccl_cosmology_compute_growth(): Support for the halo bias in cosmologies with massive neutrinos is not yet implemented.\n");
       return NAN;
   }
   if (!cosmo->computed_sigma) {
     ccl_cosmology_compute_sigma(cosmo, status);
     ccl_check_status(cosmo, status);
   }
   double f;
   f = ccl_halo_b1(cosmo,halomass,a,odelta, status);
   ccl_check_status(cosmo, status);
   return f;
 }
double ccl_massfunc (ccl_cosmology * cosmo, double smooth_mass, double a, double odelta, int * status)
Definition at line 562 of file ccl_massfunc.c.
References ccl_cosmology_set_status_message(), ccl_dlninvsig_dlogm(), CCL_ERROR_NOT_IMPLEMENTED, ccl_parameters::h, massfunc_f(), ccl_parameters::N_nu_mass, ccl_parameters::Omega_m, ccl_cosmology::params, and RHO_CRITICAL.
Referenced by compare_massfunc(), main(), one_halo_integrand(), and two_halo_integrand().
 {
   if (cosmo->params.N_nu_mass>0){
       *status = CCL_ERROR_NOT_IMPLEMENTED;
       ccl_cosmology_set_status_message(cosmo, "ccl_background.c: ccl_cosmology_compute_growth(): Support for the halo mass function in cosmologies with massive neutrinos is not yet implemented.\n");
       return NAN;
   }
   double f, rho_m;
   rho_m = RHO_CRITICAL*cosmo->params.Omega_m*cosmo->params.h*cosmo->params.h;
   f=massfunc_f(cosmo,halomass,a,odelta,status);
   return f*rho_m*ccl_dlninvsig_dlogm(cosmo,halomass,status)/halomass;
 }
double ccl_massfunc_m2r (ccl_cosmology * cosmo, double smooth_mass, int * status)
Definition at line 606 of file ccl_massfunc.c.
References ccl_rho_x(), ccl_species_m_label, M_PI, and pow().
Referenced by ccl_cosmology_compute_sigma().
 {
   double rho_m, smooth_radius;
   // Comoving matter density
   //rho_m = RHO_CRITICAL*cosmo->params.Omega_m*cosmo->params.h*cosmo->params.h;
   rho_m = ccl_rho_x(cosmo, 1., ccl_species_m_label, 1, status);
   smooth_radius = pow((3.0*halomass) / (4*M_PI*rho_m), (1.0/3.0));
   return smooth_radius;
 }
double ccl_sigmaM (ccl_cosmology * cosmo, double smooth_mass, double a, int * status)
Definition at line 624 of file ccl_massfunc.c.
References ccl_data::accelerator_m, ccl_check_status(), ccl_cosmology_compute_sigma(), ccl_cosmology_set_status_message(), CCL_ERROR_NOT_IMPLEMENTED, ccl_growth_factor(), ccl_raise_gsl_warning(), ccl_cosmology::computed_sigma, ccl_cosmology::data, ccl_data::logsigma, ccl_parameters::N_nu_mass, ccl_cosmology::params, and pow().
Referenced by ccl_halo_b1(), ccl_halo_concentration(), compare_massfunc(), compare_sigmam(), and massfunc_f().
 {
   if (cosmo->params.N_nu_mass>0){
       *status = CCL_ERROR_NOT_IMPLEMENTED;
       ccl_cosmology_set_status_message(cosmo, "ccl_background.c: ccl_cosmology_compute_growth(): Support for the sigma(M) function in cosmologies with massive neutrinos is not yet implemented.\n");
       return NAN;
   }
   double sigmaM;
   // Check if sigma has already been calculated
   if (!cosmo->computed_sigma) {
     ccl_cosmology_compute_sigma(cosmo, status);
     ccl_check_status(cosmo, status);
   }
   double lgsigmaM;
   int gslstatus = gsl_spline_eval_e(cosmo->data.logsigma,
                                     log10(halomass),
                                     cosmo->data.accelerator_m,&lgsigmaM);
   if(gslstatus != GSL_SUCCESS) {
     ccl_raise_gsl_warning(gslstatus, "ccl_massfunc.c: ccl_sigmaM():");
     *status |= gslstatus;
   }
   // Interpolate to get sigma
   sigmaM = pow(10,lgsigmaM)*ccl_growth_factor(cosmo, a, status);
   ccl_check_status(cosmo, status);
   return sigmaM;
 }
double dc_NakamuraSuto (ccl_cosmology * cosmo, double a, int * status)
Definition at line 21 of file ccl_massfunc.c.
References ccl_omega_x(), ccl_species_m_label, M_PI, and pow().
Referenced by ccl_halo_b1(), and massfunc_f().
{
   double Om_mz = ccl_omega_x(cosmo, a, ccl_species_m_label, status);
   double dc0 = (3./20.)*pow(12.*M_PI,2./3.);
   double dc = dc0*(1.+0.012299*log10(Om_mz));
   return dc;
 }
double Dv_BryanNorman (ccl_cosmology * cosmo, double a, int * status)
Definition at line 37 of file ccl_massfunc.c.
References ccl_omega_x(), ccl_species_m_label, M_PI, pow(), and x.
Referenced by ccl_halo_b1(), ccl_halo_concentration(), ccl_twohalo_matter_power(), massfunc_f(), one_halo_integrand(), and two_halo_integrand().
{
   double Om_mz = ccl_omega_x(cosmo, a, ccl_species_m_label, status);
   double x = Om_mz-1.;
   double Dv0 = 18.*pow(M_PI,2);
   double Dv = (Dv0+82.*x-39.*pow(x,2))/Om_mz;
   return Dv;
 }
double r_delta (ccl_cosmology * cosmo, double halomass, double a, double odelta, int * status)
Definition at line 52 of file ccl_massfunc.c.
References ccl_rho_x(), M_PI, and pow().
Referenced by window_function().
{
   double rho_matter = ccl_rho_x(cosmo, 1., 1, 1, status);
   return pow(halomass*3.0/(4.0*M_PI*rho_matter*odelta),1.0/3.0);
 }