Fast Methods for Cosmological Simulations: App_Var_AA::AAImpl Class Reference
App_Var_AA::AAImpl Class Reference
Public Member Functions
AAImpl (const Sim_Param &sim)
void aa_convolution (App_Var_AA &APP)
Public Attributes
Mesh expotential
uint64_t memory_alloc
Detailed Description
Definition at line 152 of file adhesion.cpp.
Constructor & Destructor Documentation
App_Var_AA::AAImpl::AAImpl (const Sim_Param & sim) inline
Definition at line 155 of file adhesion.cpp.
References expotential, Mesh_base< T >::length, and memory_alloc.
                                 : expotential(sim.box_opt.mesh_num)
     {
         memory_alloc = sizeof(FTYPE_t)*expotential.length;
     }
Member Function Documentation
void App_Var_AA::AAImpl::aa_convolution (App_Var_AA & APP) inline
Definition at line 160 of file adhesion.cpp.
References App_Var< T >::a_half(), App_Var< T >::app_field, Sim_Param::app_opt, expotential, fftw_execute_dft_c2r_triple(), fftw_execute_dft_r2c(), gen_displ_k(), anonymous_namespace{adhesion.cpp}::gen_expot(), App_Opt::nu, App_Var< T >::p_B, App_Var< T >::p_F, and App_Var< T >::sim.
     {
         BOOST_LOG_TRIVIAL(debug) << "Computing potential...";
         gen_expot(APP.app_field[0], expotential, APP.sim.app_opt.nu, APP.a_half());
         APP.app_field[0] *= -2*APP.sim.app_opt.nu;
         BOOST_LOG_TRIVIAL(debug) << "Computing velocity field via FFT...";
         fftw_execute_dft_r2c(APP.p_F, APP.app_field[0]);
         gen_displ_k(APP.app_field, APP.app_field[0]);
         fftw_execute_dft_c2r_triple(APP.p_B, APP.app_field);
     }
Member Data Documentation
Mesh App_Var_AA::AAImpl::expotential
Definition at line 173 of file adhesion.cpp.
Referenced by aa_convolution(), and AAImpl().
uint64_t App_Var_AA::AAImpl::memory_alloc
Definition at line 174 of file adhesion.cpp.
Referenced by AAImpl().
The documentation for this class was generated from the following file:
src/ApproximationsSchemes/adhesion.cpp