Fast Methods for Cosmological Simulations: Catch::Capturer Class Reference
Catch::Capturer Class Reference
#include <catch.hpp>
Public Member Functions
Capturer (StringRef macroName, SourceLineInfo const &lineInfo, ResultWas::OfType resultType, StringRef names)
~Capturer ()
void captureValue (size_t index, StringRef value)
template<typename T >
void captureValues (size_t index, T &&value)
template<typename T , typename... Ts>
void captureValues (size_t index, T &&value, Ts &&...values)
Private Attributes
std::vector< MessageInfo > m_messages
IResultCapture & m_resultCapture = getResultCapture()
size_t m_captured = 0
Detailed Description
Definition at line 1818 of file catch.hpp.
Constructor & Destructor Documentation
Catch::Capturer::Capturer (StringRef macroName, SourceLineInfo const & lineInfo, ResultWas::OfType resultType, StringRef names)
Catch::Capturer::~Capturer ()
Member Function Documentation
void Catch::Capturer::captureValue (size_t index, StringRef value)
template<typename T > void Catch::Capturer::captureValues (size_t index, T && value) inline
Definition at line 1829 of file catch.hpp.
References Catch::Detail::stringify(), growth_allz::T, and Catch::Generators::value().
{
             captureValue( index, Catch::Detail::stringify( value ) );
         }
template<typename T , typename... Ts> void Catch::Capturer::captureValues (size_t index, T && value, Ts &&... values) inline
Definition at line 1834 of file catch.hpp.
References Catch::Generators::value(), and Catch::Generators::values().
{
             captureValues( index, value );
             captureValues( index+1, values... );
         }
Member Data Documentation
size_t Catch::Capturer::m_captured = 0 private
Definition at line 1821 of file catch.hpp.
std::vector<MessageInfo> Catch::Capturer::m_messages private
Definition at line 1819 of file catch.hpp.
IResultCapture& Catch::Capturer::m_resultCapture = getResultCapture() private
Definition at line 1820 of file catch.hpp.
The documentation for this class was generated from the following file:
src/3party/Catch/catch.hpp