Fast Methods for Cosmological Simulations: Catch::AssertionHandler Class Reference
Catch::AssertionHandler Class Reference
#include <catch.hpp>
Public Member Functions
AssertionHandler (StringRef const &macroName, SourceLineInfo const &lineInfo, StringRef capturedExpression, ResultDisposition::Flags resultDisposition)
~AssertionHandler ()
template<typename T >
void handleExpr (ExprLhs< T > const &expr)
void handleExpr (ITransientExpression const &expr)
void handleMessage (ResultWas::OfType resultType, StringRef const &message)
void handleExceptionThrownAsExpected ()
void handleUnexpectedExceptionNotThrown ()
void handleExceptionNotThrownAsExpected ()
void handleThrowingCallSkipped ()
void handleUnexpectedInflightException ()
void complete ()
void setCompleted ()
auto allowThrows () const -> bool
Private Attributes
AssertionInfo m_assertionInfo
AssertionReaction m_reaction
bool m_completed = false
IResultCapture & m_resultCapture
Detailed Description
Definition at line 1717 of file catch.hpp.
Constructor & Destructor Documentation
Catch::AssertionHandler::AssertionHandler (StringRef const & macroName, SourceLineInfo const & lineInfo, StringRef capturedExpression, ResultDisposition::Flags resultDisposition)
Catch::AssertionHandler::~AssertionHandler () inline
Definition at line 1729 of file catch.hpp.
References Catch::IResultCapture::handleIncomplete().
{
             if ( !m_completed ) {
                 m_resultCapture.handleIncomplete( m_assertionInfo );
             }
         }
Member Function Documentation
auto Catch::AssertionHandler::allowThrows () const -> bool
void Catch::AssertionHandler::complete ()
void Catch::AssertionHandler::handleExceptionNotThrownAsExpected ()
void Catch::AssertionHandler::handleExceptionThrownAsExpected ()
template<typename T > void Catch::AssertionHandler::handleExpr (ExprLhs< T > const & expr) inline
Definition at line 1736 of file catch.hpp.
References Catch::handleExceptionMatchExpr(), and Catch::ExprLhs< LhsT >::makeUnaryExpr().
{
             handleExpr( expr.makeUnaryExpr() );
         }
void Catch::AssertionHandler::handleExpr (ITransientExpression const & expr)
void Catch::AssertionHandler::handleMessage (ResultWas::OfType resultType, StringRef const & message)
void Catch::AssertionHandler::handleThrowingCallSkipped ()
void Catch::AssertionHandler::handleUnexpectedExceptionNotThrown ()
void Catch::AssertionHandler::handleUnexpectedInflightException ()
void Catch::AssertionHandler::setCompleted ()
Member Data Documentation
AssertionInfo Catch::AssertionHandler::m_assertionInfo private
Definition at line 1718 of file catch.hpp.
bool Catch::AssertionHandler::m_completed = false private
Definition at line 1720 of file catch.hpp.
AssertionReaction Catch::AssertionHandler::m_reaction private
Definition at line 1719 of file catch.hpp.
IResultCapture& Catch::AssertionHandler::m_resultCapture private
Definition at line 1721 of file catch.hpp.
The documentation for this class was generated from the following file:
src/3party/Catch/catch.hpp