Fast Methods for Cosmological Simulations: App_Var_FP Class Reference
App_Var_FP Class Reference
Approximations
: class containing variables and methods for Frozen-potential approximation
#include <frozen_potential.hpp>
Public Member Functions
App_Var_FP (const Sim_Param &sim)
Public Member Functions inherited from App_Var< Particle_v< double > >
App_Var (const Sim_Param &sim, const std::string &app_short, const std::string &app_long)
virtual ~App_Var ()
void run_simulation ()
virtual void update_cosmo (Cosmo_Param &cosmo)
no truncation by default
std::string get_out_dir () const
Protected Member Functions
App_Var_FP (const Sim_Param &sim, const std::string &app_short, const std::string &app_long)
Protected Member Functions inherited from App_Var< Particle_v< double > >
double a ()
double a_half ()
double da ()
std::string get_z_suffix () const
virtual void print_output ()
virtual void pot_corr (std::vector< Mesh > &vel_field, Mesh &pot_k)
Private Member Functions
void upd_pos () override
Additional Inherited Members
Protected Attributes inherited from App_Var< Particle_v< double > >
const Sim_Param & sim
uint64_t memory_alloc
std::vector< Mesh > app_field
std::vector< Mesh > power_aux
std::vector< Particle_v< double > > particles
Data_Vec< double, 2 > corr_func_binned
Data_Vec< double, 2 > pwr_spec_binned
Data_Vec< double, 2 > pwr_spec_binned_0
Data_Vec< double, 2 > vel_pwr_spec_binned_0
FFTW_PLAN_TYPE p_F
FFTW_PLAN_TYPE p_B
FFTW_PLAN_TYPE p_F_pwr
FFTW_PLAN_TYPE p_B_pwr
std::vector< size_t > dens_binned
Detailed Description
: class containing variables and methods for Frozen-potential approximation
PUBLIC METHODS * PUBLIC CLASSES *
Definition at line 35 of file frozen_potential.hpp.
Constructor & Destructor Documentation
App_Var_FP::App_Var_FP (const Sim_Param & sim)
Definition at line 15 of file frozen_potential.cpp.
                                           :
     App_Var<Particle_v<FTYPE_t>>(sim, "FP", "Frozen-potential approximation") {}
App_Var_FP::App_Var_FP (const Sim_Param & sim, const std::string & app_short, const std::string & app_long) protected
Definition at line 18 of file frozen_potential.cpp.
                                                                                                  :
     App_Var<Particle_v<FTYPE_t>>(sim, app_short, app_long) {}
Member Function Documentation
void App_Var_FP::upd_pos () override private virtual
Implements App_Var< Particle_v< double > >.
Reimplemented in App_Var_PM.
Definition at line 21 of file frozen_potential.cpp.
References App_Var< Particle_v< double > >::a_half(), App_Var< Particle_v< double > >::app_field, Sim_Param::box_opt, Sim_Param::cosmo, App_Var< Particle_v< double > >::da(), kick_step_w_momentum(), Box_Opt::mesh_num, App_Var< Particle_v< double > >::particles, App_Var< Particle_v< double > >::sim, and stream_kick_stream().
 {// Leapfrog method for frozen-potential
     auto kick_step = [&](){ kick_step_w_momentum(sim.cosmo, a_half(), da(), particles, app_field); };
     stream_kick_stream(da(), particles, kick_step, sim.box_opt.mesh_num);
 }
The documentation for this class was generated from the following files:
src/ApproximationsSchemes/include/frozen_potential.hpp
src/ApproximationsSchemes/frozen_potential.cpp