Fast Methods for Cosmological Simulations: Catch::ExprLhs< LhsT > Class Template Reference
Catch::ExprLhs< LhsT > Class Template Reference
#include <catch.hpp>
Public Member Functions
ExprLhs (LhsT lhs)
template<typename RhsT >
auto operator== (RhsT const &rhs) -> BinaryExpr< LhsT, RhsT const & > const
auto operator== (bool rhs) -> BinaryExpr< LhsT, bool > const
template<typename RhsT >
auto operator!= (RhsT const &rhs) -> BinaryExpr< LhsT, RhsT const & > const
auto operator!= (bool rhs) -> BinaryExpr< LhsT, bool > const
template<typename RhsT >
auto operator> (RhsT const &rhs) -> BinaryExpr< LhsT, RhsT const & > const
template<typename RhsT >
auto operator< (RhsT const &rhs) -> BinaryExpr< LhsT, RhsT const & > const
template<typename RhsT >
auto operator>= (RhsT const &rhs) -> BinaryExpr< LhsT, RhsT const & > const
template<typename RhsT >
auto operator<= (RhsT const &rhs) -> BinaryExpr< LhsT, RhsT const & > const
auto makeUnaryExpr () const -> UnaryExpr< LhsT >
Private Attributes
LhsT m_lhs
Detailed Description
template<typename LhsT>
class Catch::ExprLhs< LhsT >
Definition at line 1545 of file catch.hpp.
Constructor & Destructor Documentation
template<typename LhsT> Catch::ExprLhs< LhsT >::ExprLhs (LhsT lhs) inline explicit
Definition at line 1548 of file catch.hpp.
 : m_lhs( lhs ) {}
Member Function Documentation
template<typename LhsT> auto Catch::ExprLhs< LhsT >::makeUnaryExpr () const -> UnaryExpr<LhsT> inline
Definition at line 1583 of file catch.hpp.
References Catch::handleExpression().
Referenced by Catch::AssertionHandler::handleExpr(), and Catch::handleExpression().
{
             return UnaryExpr<LhsT>{ m_lhs };
         }
template<typename LhsT> template<typename RhsT > auto Catch::ExprLhs< LhsT >::operator!= (RhsT const & rhs) -> BinaryExpr<LhsT, RhsT const&> const inline
Definition at line 1559 of file catch.hpp.
References Catch::compareNotEqual().
{
             return { compareNotEqual( m_lhs, rhs ), m_lhs, "!=", rhs };
         }
template<typename LhsT> auto Catch::ExprLhs< LhsT >::operator!= (bool rhs) -> BinaryExpr<LhsT, bool> const inline
Definition at line 1562 of file catch.hpp.
{
             return { m_lhs != rhs, m_lhs, "!=", rhs };
         }
template<typename LhsT> template<typename RhsT > auto Catch::ExprLhs< LhsT >::operator< (RhsT const & rhs) -> BinaryExpr<LhsT, RhsT const&> const inline
Definition at line 1571 of file catch.hpp.
{
             return { static_cast<bool>(m_lhs < rhs), m_lhs, "<", rhs };
         }
template<typename LhsT> template<typename RhsT > auto Catch::ExprLhs< LhsT >::operator<= (RhsT const & rhs) -> BinaryExpr<LhsT, RhsT const&> const inline
Definition at line 1579 of file catch.hpp.
{
             return { static_cast<bool>(m_lhs <= rhs), m_lhs, "<=", rhs };
         }
template<typename LhsT> template<typename RhsT > auto Catch::ExprLhs< LhsT >::operator== (RhsT const & rhs) -> BinaryExpr<LhsT, RhsT const&> const inline
Definition at line 1551 of file catch.hpp.
References Catch::compareEqual().
{
             return { compareEqual( m_lhs, rhs ), m_lhs, "==", rhs };
         }
template<typename LhsT> auto Catch::ExprLhs< LhsT >::operator== (bool rhs) -> BinaryExpr<LhsT, bool> const inline
Definition at line 1554 of file catch.hpp.
{
             return { m_lhs == rhs, m_lhs, "==", rhs };
         }
template<typename LhsT> template<typename RhsT > auto Catch::ExprLhs< LhsT >::operator> (RhsT const & rhs) -> BinaryExpr<LhsT, RhsT const&> const inline
Definition at line 1567 of file catch.hpp.
{
             return { static_cast<bool>(m_lhs > rhs), m_lhs, ">", rhs };
         }
template<typename LhsT> template<typename RhsT > auto Catch::ExprLhs< LhsT >::operator>= (RhsT const & rhs) -> BinaryExpr<LhsT, RhsT const&> const inline
Definition at line 1575 of file catch.hpp.
{
             return { static_cast<bool>(m_lhs >= rhs), m_lhs, ">=", rhs };
         }
Member Data Documentation
template<typename LhsT> LhsT Catch::ExprLhs< LhsT >::m_lhs private
Definition at line 1546 of file catch.hpp.
The documentation for this class was generated from the following file:
src/3party/Catch/catch.hpp