Fast Methods for Cosmological Simulations: src/data/include/class_mesh.hpp File Reference
class_mesh.hpp File Reference
define container Mesh
#include "stdafx.h"
#include "precision.hpp"
#include "class_vec_3d.hpp"
Classes
class Mesh_base< T >
: class handling basic mesh functions, the most important are creating and destroing the underlying data structure creates a mesh of N1*N2*N3 cells
class Mesh
: creates a mesh of N*N*(N+2) cells
Functions
template<typename T >
void get_per (Vec_3D< T > &position, size_t per)
template<typename T >
void get_per (Vec_3D< T > &position, size_t perx, size_t pery, size_t perz)
Detailed Description
define container Mesh
Author
Michal Vrastil
Date
2018-06-24
Definition in file class_mesh.hpp.
Function Documentation
template<typename T > void get_per (Vec_3D< T > & position, size_t per)
Definition at line 66 of file core_mesh.cpp.
References get_per(), and growth_allz::T.
Referenced by Mesh_base< size_t >::operator()(), and Mesh::operator()().
 {
     for (T& pos : position) pos = get_per(pos, per);
 }
template<typename T > void get_per (Vec_3D< T > & position, size_t perx, size_t pery, size_t perz)
Definition at line 72 of file core_mesh.cpp.
References get_per().
 {
     position[0] = get_per(position[0], perx);
     position[1] = get_per(position[1], pery);
     position[2] = get_per(position[2], perz);
 }