Fast Methods for Cosmological Simulations: IT< points > Class Template Reference
IT< points > Class Template Reference
: class for effective iteration of cube of mesh cells
#include <core_mesh.h>
Public Member Functions
IT (const Vec_3D< double > &pos)
IT (const Vec_3D< double > &pos, double Hc)
bool iter ()
Public Attributes
size_t counter
Vec_3D< size_t > vec
Detailed Description
template<unsigned int points>
class IT< points >
: class for effective iteration of cube of mesh cells
Definition at line 66 of file core_mesh.h.
Constructor & Destructor Documentation
template<unsigned int points> IT< points >::IT (const Vec_3D< double > & pos)
Definition at line 171 of file core_mesh.cpp.
References IT< points >::vec.
                                         : counter(0)
 {
     for(size_t i = 0; i < 3; i++){
         vec[i] = (int)(pos[i] - 0.5*(int(points) - 2));
     }
 }
template<unsigned int points> IT< points >::IT (const Vec_3D< double > & pos, double Hc)
Definition at line 179 of file core_mesh.cpp.
References IT< points >::vec.
                                                     : counter(0)
 {
     for(size_t i = 0; i < 3; i++){
         vec[i] = (int)(pos[i]/Hc) - 1;
     }
 }
Member Function Documentation
template<unsigned int points> bool IT< points >::iter ()
Definition at line 187 of file core_mesh.cpp.
References IT< points >::counter, and IT< points >::vec.
Referenced by assign_from(), assign_to(), anonymous_namespace{mod_frozen_potential.cpp}::force_short(), and TEST_CASE().
                      {
     if (++counter == (points*points*points)) return false;
     vec[2]++;
     if ((counter % points) == 0){
         vec[2] -= points;
         vec[1]++;
         if ((counter % (points*points)) == 0){
             vec[1] -= points;
             vec[0]++;
         }
     }
     return true;
 }
Member Data Documentation
template<unsigned int points> size_t IT< points >::counter
Definition at line 72 of file core_mesh.h.
Referenced by IT< points >::iter(), and TEST_CASE().
template<unsigned int points> Vec_3D<size_t> IT< points >::vec
Definition at line 73 of file core_mesh.h.
Referenced by assign_from(), assign_to(), anonymous_namespace{mod_frozen_potential.cpp}::force_short(), IT< points >::IT(), IT< points >::iter(), and TEST_CASE().
The documentation for this class was generated from the following files:
src/core/include/core_mesh.h
src/core/core_mesh.cpp