Fast Methods for Cosmological Simulations: nlohmann::detail::input_adapter Class Reference
nlohmann::detail::input_adapter Class Reference
#include <json.hpp>
Public Member Functions
input_adapter (std::istream &i)
input adapter for input stream
input_adapter (std::istream &&i)
input adapter for input stream
input_adapter (const std::wstring &ws)
input_adapter (const std::u16string &ws)
input_adapter (const std::u32string &ws)
template<typename CharT , typename std::enable_if< std::is_pointer< CharT >::value andstd::is_integral< typename std::remove_pointer< CharT >::type >::value andsizeof(typename std::remove_pointer< CharT >::type)==1, int >::type = 0>
input_adapter (CharT b, std::size_t l)
input adapter for buffer
template<typename CharT , typename std::enable_if< std::is_pointer< CharT >::value andstd::is_integral< typename std::remove_pointer< CharT >::type >::value andsizeof(typename std::remove_pointer< CharT >::type)==1, int >::type = 0>
input_adapter (CharT b)
input adapter for string literal
template<class IteratorType , typename std::enable_if< std::is_same< typename std::iterator_traits< IteratorType >::iterator_category, std::random_access_iterator_tag >::value, int >::type = 0>
input_adapter (IteratorType first, IteratorType last)
input adapter for iterator range with contiguous storage
template<class T , std::size_t N>
input_adapter (T(&array)[N])
input adapter for array
template<class ContiguousContainer , typename std::enable_if< not std::is_pointer< ContiguousContainer >::value andstd::is_base_of< std::random_access_iterator_tag, typename std::iterator_traits< decltype(std::begin(std::declval< ContiguousContainer const >()))>::iterator_category >::value, int >::type = 0>
input_adapter (const ContiguousContainer &c)
input adapter for contiguous container
operator input_adapter_t ()
Private Attributes
input_adapter_t ia = nullptr
the actual adapter
Detailed Description
Definition at line 2335 of file json.hpp.
Constructor & Destructor Documentation
nlohmann::detail::input_adapter::input_adapter (std::istream & i) inline
input adapter for input stream
Definition at line 2341 of file json.hpp.
         : ia(std::make_shared<input_stream_adapter>(i)) {}
nlohmann::detail::input_adapter::input_adapter (std::istream && i) inline
input adapter for input stream
Definition at line 2345 of file json.hpp.
         : ia(std::make_shared<input_stream_adapter>(i)) {}
nlohmann::detail::input_adapter::input_adapter (const std::wstring & ws) inline
Definition at line 2348 of file json.hpp.
         : ia(std::make_shared<wide_string_input_adapter<std::wstring>>(ws)) {}
nlohmann::detail::input_adapter::input_adapter (const std::u16string & ws) inline
Definition at line 2351 of file json.hpp.
         : ia(std::make_shared<wide_string_input_adapter<std::u16string>>(ws)) {}
nlohmann::detail::input_adapter::input_adapter (const std::u32string & ws) inline
Definition at line 2354 of file json.hpp.
References Catch::Generators::value().
         : ia(std::make_shared<wide_string_input_adapter<std::u32string>>(ws)) {}
template<typename CharT , typename std::enable_if< std::is_pointer< CharT >::value andstd::is_integral< typename std::remove_pointer< CharT >::type >::value andsizeof(typename std::remove_pointer< CharT >::type)==1, int >::type = 0> nlohmann::detail::input_adapter::input_adapter (CharT b, std::size_t l) inline
input adapter for buffer
Definition at line 2364 of file json.hpp.
References Catch::Generators::value().
         : ia(std::make_shared<input_buffer_adapter>(reinterpret_cast<const char*>(b), l)) {}
template<typename CharT , typename std::enable_if< std::is_pointer< CharT >::value andstd::is_integral< typename std::remove_pointer< CharT >::type >::value andsizeof(typename std::remove_pointer< CharT >::type)==1, int >::type = 0> nlohmann::detail::input_adapter::input_adapter (CharT b) inline
input adapter for string literal
Definition at line 2376 of file json.hpp.
References Catch::Generators::value().
         : input_adapter(reinterpret_cast<const char*>(b),
                         std::strlen(reinterpret_cast<const char*>(b))) {}
template<class IteratorType , typename std::enable_if< std::is_same< typename std::iterator_traits< IteratorType >::iterator_category, std::random_access_iterator_tag >::value, int >::type = 0> nlohmann::detail::input_adapter::input_adapter (IteratorType first, IteratorType last) inline
input adapter for iterator range with contiguous storage
Definition at line 2385 of file json.hpp.
References JSON_LIKELY.
     {
 #ifndef NDEBUG
         // assertion to check that the iterator range is indeed contiguous,
         // see http://stackoverflow.com/a/35008842/266378 for more discussion
         const auto is_contiguous = std::accumulate(
                                        first, last, std::pair<bool, int>(true, 0),
                                        [&first](std::pair<bool, int> res, decltype(*first) val)
         {
             res.first &= (val == *(std::next(std::addressof(*first), res.second++)));
             return res;
         }).first;
         assert(is_contiguous);
 #endif
         // assertion to check that each element is 1 byte long
         static_assert(
             sizeof(typename std::iterator_traits<IteratorType>::value_type) == 1,
             "each element in the iterator range must have the size of 1 byte");
         const auto len = static_cast<size_t>(std::distance(first, last));
         if (JSON_LIKELY(len > 0))
         {
             // there is at least one element: use the address of first
             ia = std::make_shared<input_buffer_adapter>(reinterpret_cast<const char*>(&(*first)), len);
         }
         else
         {
             // the address of first cannot be used: use nullptr
             ia = std::make_shared<input_buffer_adapter>(nullptr, len);
         }
     }
template<class T , std::size_t N> nlohmann::detail::input_adapter::input_adapter (T(&) array[N]) inline
input adapter for array
Definition at line 2420 of file json.hpp.
References Catch::Generators::value().
         : input_adapter(std::begin(array), std::end(array)) {}
template<class ContiguousContainer , typename std::enable_if< not std::is_pointer< ContiguousContainer >::value andstd::is_base_of< std::random_access_iterator_tag, typename std::iterator_traits< decltype(std::begin(std::declval< ContiguousContainer const >()))>::iterator_category >::value, int >::type = 0> nlohmann::detail::input_adapter::input_adapter (const ContiguousContainer & c) inline
input adapter for contiguous container
Definition at line 2428 of file json.hpp.
         : input_adapter(std::begin(c), std::end(c)) {}
Member Function Documentation
nlohmann::detail::input_adapter::operator input_adapter_t () inline
Definition at line 2431 of file json.hpp.
     {
         return ia;
     }
Member Data Documentation
input_adapter_t nlohmann::detail::input_adapter::ia = nullptr private
the actual adapter
Definition at line 2438 of file json.hpp.
The documentation for this class was generated from the following file:
src/3party/JSON/json.hpp