Fast Methods for Cosmological Simulations: ContinuitySolver< NDIM, T > Class Template Reference
ContinuitySolver< NDIM, T > Class Template Reference
#include <continuity_solver.h>
Public Member Functions
ContinuitySolver ()
ContinuitySolver (unsigned int N, bool verbose=true)
ContinuitySolver (unsigned int N, unsigned int Nmin, bool verbose=true)
ContinuitySolver (MultiGrid< NDIM, T > &source, bool verbose=true)
void set_rhomax (double rhomax)
void set_rhomin (double rhomin)
void set_growthfachubble (double growthfachubble)
T bfunc (T delta_rho)
T l_operator (unsigned int level, std::vector< unsigned int > &index_list, bool addsource)
T dl_operator (unsigned int level, std::vector< unsigned int > &index_list)
Public Member Functions inherited from MultiGridSolver< NDIM, T >
MultiGridSolver ()
MultiGridSolver (size_t N)
MultiGridSolver (size_t N, bool verbose)
MultiGridSolver (size_t N, size_t Nmin, bool verbose)
size_t get_istep () const
T * get_y (size_t level=0)
T const * get_y (size_t level=0) const
Grid< NDIM, T > & get_grid (size_t level=0)
const Grid< NDIM, T > & get_grid (size_t level=0) const
MultiGrid< NDIM, T > & get_mlt_grid (size_t level=0)
const MultiGrid< NDIM, T > & get_mlt_grid (size_t level=0) const
T * get_external_field (size_t level, size_t field)
T const * get_external_field (size_t level, size_t field) const
Grid< NDIM, T > & get_external_grid (size_t level, size_t field)
const Grid< NDIM, T > & get_external_grid (size_t level, size_t field) const
size_t get_external_field_size () const
T get_multigrid_source (size_t level, size_t i) const
void set_epsilon (double eps_converge)
void set_maxsteps (size_t maxsteps)
void set_ngs_sweeps (size_t ngs_fine, size_t ngs_coarse)
void set_convergence_criterion_residual (bool use_residual)
void set_Nlevel (size_t N)
size_t get_N (size_t level=0) const
size_t get_Ntot (size_t level=0) const
size_t get_Nlevel () const
void add_external_grid (MultiGrid< NDIM, T > *field)
void set_initial_guess (T guess)
void set_initial_guess (T *guess)
void set_initial_guess (Grid< NDIM, T > &guess)
Exit_Status solve ()
void clear ()
virtual T upd_operator (const T f, const size_t level, const std::vector< size_t > &index_list, const T h) const
virtual T l_operator (const size_t level, const std::vector< size_t > &index_list, bool addsource, const T h) const
virtual T dl_operator (const size_t level, const std::vector< size_t > &index_list, const T h) const
virtual void correct_sol (Grid< NDIM, T > &f, const Grid< NDIM, T > &corr, const size_t level)
virtual Exit_Status check_convergence ()
virtual void check_solution (size_t level, Grid< NDIM, T > &sol)
void check_solution (size_t level)
Private Attributes
double _rhomin = 0.1
double _rhomax = 1e30
double _growthfachubble = 0.5
Additional Inherited Members
Public Types inherited from MultiGridSolver< NDIM, T >
enum Exit_Status {
Exit_Status::SUCCESS, Exit_Status::FAILURE, Exit_Status::SLOW, Exit_Status::ITERATE,
Exit_Status::MAX_STEPS
}
Public Attributes inherited from MultiGridSolver< NDIM, T >
bool _store_all_residual = false
std::vector< double > _res_domain_array
Protected Member Functions inherited from MultiGridSolver< NDIM, T >
void get_neighbor_gridindex (std::vector< size_t > &index_list, size_t i, size_t ngrid)
Protected Attributes inherited from MultiGridSolver< NDIM, T >
bool _verbose
bool _conv_criterion_residual = true
double _eps_converge = 1e-5
size_t _maxsteps = 1000
size_t _istep_vcycle = 0
double _rms_res
double _rms_res_i
double _rms_res_old
Detailed Description
template<unsigned int NDIM, typename T>
class ContinuitySolver< NDIM, T >
Definition at line 25 of file continuity_solver.h.
Constructor & Destructor Documentation
template<unsigned int NDIM, typename T> ContinuitySolver< NDIM, T >::ContinuitySolver () inline
Definition at line 34 of file continuity_solver.h.
 {}
template<unsigned int NDIM, typename T> ContinuitySolver< NDIM, T >::ContinuitySolver (unsigned int N, bool verbose = true) inline
Definition at line 35 of file continuity_solver.h.
 : MultiGridSolver<NDIM,T>(N, verbose) {} ;
template<unsigned int NDIM, typename T> ContinuitySolver< NDIM, T >::ContinuitySolver (unsigned int N, unsigned int Nmin, bool verbose = true) inline
Definition at line 36 of file continuity_solver.h.
 : MultiGridSolver<NDIM,T>(N, Nmin, verbose) {} ;
template<unsigned int NDIM, typename T> ContinuitySolver< NDIM, T >::ContinuitySolver (MultiGrid< NDIM, T > & source, bool verbose = true) inline
Definition at line 37 of file continuity_solver.h.
References MultiGridSolver< NDIM, T >::add_external_grid().
                                                                      : MultiGridSolver<NDIM,T>(source.get_N(), source.get_Nmin(), verbose) {
       MultiGridSolver<NDIM,T>::add_external_grid(&source);
     }
Member Function Documentation
template<unsigned int NDIM, typename T> T ContinuitySolver< NDIM, T >::bfunc (T delta_rho) inline
Definition at line 53 of file continuity_solver.h.
References max(), and anonymous_namespace{chameleon.cpp}::min().
Referenced by ContinuitySolver< NDIM, T >::dl_operator(), and ContinuitySolver< NDIM, T >::l_operator().
{
       return std::min( std::max(1.0 + delta_rho, _rhomin) , _rhomax);
     }
template<unsigned int NDIM, typename T> T ContinuitySolver< NDIM, T >::dl_operator (unsigned int level, std::vector< unsigned int > & index_list) inline
Definition at line 94 of file continuity_solver.h.
References ContinuitySolver< NDIM, T >::bfunc(), Catch::cout(), MultiGridSolver< NDIM, T >::get_external_field(), ccl_test_distances::h, and growth_allz::T.
{
       unsigned int i = index_list[0];
       // Gridspacing
       T h = 1.0/T( MultiGridSolver<NDIM,T>::get_N(level) );
       // Solution and pde-source grid at current level
       T *delta = MultiGridSolver<NDIM,T>::get_external_field(level, 0);
       // Derivative of the kinetic term
       T dkinetic = 0.0;
       T boff = bfunc(delta[i]);
       for(unsigned int j = 0; j < NDIM; j++){
         unsigned int iminus = index_list[2*j+1];
         unsigned int iplus  = index_list[2*j+2];
         T bminus = 0.5 * ( bfunc(delta[iminus]) + boff );
         T bplus  = 0.5 * ( bfunc(delta[iplus])  + boff );
         dkinetic += -(bplus + bminus);
       }
       // The derivative of the source is zero as there is no field dependence
       T dsource = 0.0;
       // Check for error
       T dl = dkinetic/(h*h) - dsource;
       if(fabs(dl) < 1e-5){
         std::cout << "Error: dl = " << dl << " delta_rho = " << delta[i] << " b = " << boff << std::endl;
         exit(1);
       }
       return dl;
     }
template<unsigned int NDIM, typename T> T ContinuitySolver< NDIM, T >::l_operator (unsigned int level, std::vector< unsigned int > & index_list, bool addsource) inline
Definition at line 58 of file continuity_solver.h.
References ContinuitySolver< NDIM, T >::bfunc(), MultiGridSolver< NDIM, T >::get_external_field(), MultiGridSolver< NDIM, T >::get_multigrid_source(), MultiGridSolver< NDIM, T >::get_y(), ccl_test_distances::h, and growth_allz::T.
{
       unsigned int i = index_list[0];
       // Gridspacing
       T h = 1.0/T( MultiGridSolver<NDIM,T>::get_N(level) );
       // Solution and pde-source grid at current level
       T *phi = MultiGridSolver<NDIM,T>::get_y(level);
       T *delta = MultiGridSolver<NDIM,T>::get_external_field(level, 0);
       // Compute the kinetic term D[b Df] (in 1D this is phi''_i =  phi_{i+1} + phi_{i-1} - 2 phi_{i} )
       T kinetic = 0.0;
       T f    = phi[i];
       T boff = bfunc(delta[i]);
       for(unsigned int j = 0; j < NDIM; j++){
         unsigned int iminus = index_list[2*j+1];
         unsigned int iplus  = index_list[2*j+2];
         T fminus = phi[iminus];
         T fplus  = phi[iplus];
         T bminus = 0.5 * ( bfunc(delta[iminus]) + boff );
         T bplus  = 0.5 * ( bfunc(delta[iplus])  + boff );
         kinetic += bplus * (fplus - f) - bminus * (f - fminus);
       }
       // The right hand side of the PDE with the source term arising
       // from restricting the equation down to the lower level
       T source = -_growthfachubble * delta[i];
       if( level > 0 && addsource ){
         source += MultiGridSolver<NDIM,T>::get_multigrid_source(level, i);
       }
       // The discretized equation of motion L_{ijk...}(phi)
       return kinetic/(h*h) - source;
     }
template<unsigned int NDIM, typename T> void ContinuitySolver< NDIM, T >::set_growthfachubble (double growthfachubble) inline
Definition at line 49 of file continuity_solver.h.
References growthfachubble.
Referenced by main().
{
       _growthfachubble = growthfachubble;
     }
template<unsigned int NDIM, typename T> void ContinuitySolver< NDIM, T >::set_rhomax (double rhomax) inline
Definition at line 41 of file continuity_solver.h.
Referenced by main().
{
       _rhomax = rhomax;
     }
template<unsigned int NDIM, typename T> void ContinuitySolver< NDIM, T >::set_rhomin (double rhomin) inline
Definition at line 45 of file continuity_solver.h.
Referenced by main().
{
       _rhomin = rhomin;
     }
Member Data Documentation
template<unsigned int NDIM, typename T> double ContinuitySolver< NDIM, T >::_growthfachubble = 0.5 private
Definition at line 30 of file continuity_solver.h.
template<unsigned int NDIM, typename T> double ContinuitySolver< NDIM, T >::_rhomax = 1e30 private
Definition at line 29 of file continuity_solver.h.
template<unsigned int NDIM, typename T> double ContinuitySolver< NDIM, T >::_rhomin = 0.1 private
Definition at line 28 of file continuity_solver.h.
The documentation for this class was generated from the following file:
src/3party/MultiGridSolver/example_continuity_equation/continuity_solver.h