Fast Methods for Cosmological Simulations: App_Var_AA Class Reference
App_Var_AA Class Reference
Approximations
: class containing variables and methods for adhesion approximation
#include <adhesion.hpp>
Classes
class AAImpl
Public Member Functions
App_Var_AA (const Sim_Param &sim)
~App_Var_AA ()
Public Member Functions inherited from App_Var< Particle_v< double > >
App_Var (const Sim_Param &sim, const std::string &app_short, const std::string &app_long)
virtual ~App_Var ()
void run_simulation ()
virtual void update_cosmo (Cosmo_Param &cosmo)
no truncation by default
std::string get_out_dir () const
Private Member Functions
void pot_corr (std::vector< Mesh > &vel_field, Mesh &pot_k) override
void upd_pos () override
Private Attributes
const std::unique_ptr< AAImpl > m_impl
Additional Inherited Members
Protected Member Functions inherited from App_Var< Particle_v< double > >
double a ()
double a_half ()
double da ()
std::string get_z_suffix () const
virtual void print_output ()
Protected Attributes inherited from App_Var< Particle_v< double > >
const Sim_Param & sim
uint64_t memory_alloc
std::vector< Mesh > app_field
std::vector< Mesh > power_aux
std::vector< Particle_v< double > > particles
Data_Vec< double, 2 > corr_func_binned
Data_Vec< double, 2 > pwr_spec_binned
Data_Vec< double, 2 > pwr_spec_binned_0
Data_Vec< double, 2 > vel_pwr_spec_binned_0
FFTW_PLAN_TYPE p_F
FFTW_PLAN_TYPE p_B
FFTW_PLAN_TYPE p_F_pwr
FFTW_PLAN_TYPE p_B_pwr
std::vector< size_t > dens_binned
Detailed Description
: class containing variables and methods for adhesion approximation
PUBLIC METHODS * PUBLIC CLASSES *
Definition at line 35 of file adhesion.hpp.
Constructor & Destructor Documentation
App_Var_AA::App_Var_AA (const Sim_Param & sim)
Definition at line 177 of file adhesion.cpp.
References m_impl, App_Var< Particle_v< double > >::memory_alloc, and ~App_Var_AA().
                                           :
     App_Var<Particle_v<FTYPE_t>>(sim, "AA", "Adhesion approximation"), m_impl(new AAImpl(sim))
 {
     memory_alloc += m_impl->memory_alloc;
 }
App_Var_AA::~App_Var_AA () default
Referenced by App_Var_AA().
Member Function Documentation
void App_Var_AA::pot_corr (std::vector< Mesh > & vel_field, Mesh & pot_k) override private virtual
Reimplemented from App_Var< Particle_v< double > >.
Definition at line 185 of file adhesion.cpp.
References Sim_Param::app_opt, fftw_execute_dft_c2r(), anonymous_namespace{adhesion.cpp}::gen_init_expot(), m_impl, App_Opt::nu, App_Var< Particle_v< double > >::p_B, and App_Var< Particle_v< double > >::sim.
 {
     /* Computing initial expotential */
     fftw_execute_dft_c2r(p_B, pot_k);
     gen_init_expot(pot_k, m_impl->expotential, sim.app_opt.nu);
 }
void App_Var_AA::upd_pos () override private virtual
Implements App_Var< Particle_v< double > >.
Definition at line 192 of file adhesion.cpp.
References App_Var< Particle_v< double > >::a_half(), App_Var< Particle_v< double > >::app_field, Sim_Param::box_opt, Sim_Param::cosmo, App_Var< Particle_v< double > >::da(), kick_step_w_momentum(), m_impl, Box_Opt::mesh_num, App_Var< Particle_v< double > >::particles, App_Var< Particle_v< double > >::sim, and stream_kick_stream().
 {// Leapfrog method for adhesion
     m_impl->aa_convolution(*this);
     auto kick_step = [&](){ kick_step_w_momentum(sim.cosmo, a_half(), da(), particles, app_field); };
     stream_kick_stream(da(), particles, kick_step, sim.box_opt.mesh_num);
 }
Member Data Documentation
const std::unique_ptr<AAImpl> App_Var_AA::m_impl private
Definition at line 44 of file adhesion.hpp.
Referenced by App_Var_AA(), pot_corr(), and upd_pos().
The documentation for this class was generated from the following files:
src/ApproximationsSchemes/include/adhesion.hpp
src/ApproximationsSchemes/adhesion.cpp