Fast Methods for Cosmological Simulations: App_Var< T >::Impl< T > Class Template Reference
App_Var< T >::Impl< T > Class Template Reference
Public Member Functions
Impl (const Sim_Param &sim, const std::string &app_short, const std::string &app_long)
uint64_t alloc_mesh_vec (App_Var< T > &APP)
uint64_t alloc_bin_spec (App_Var< T > &APP)
uint64_t alloc_bin_corr (App_Var< T > &APP)
uint64_t alloc_particles (App_Var< T > &APP)
void fftw_prep (App_Var< T > &APP)
void set_init_pos (App_Var< T > &APP)
void set_init_cond (App_Var< T > &APP)
void print_sim_name () const
void print_end ()
std::string z_suffix () const
void print_input_realisation (App_Var< T > &APP)
void print_output (App_Var< T > &APP)
void create_work_dir (const Out_Opt &out_opt)
void integration (App_Var< T > &APP)
Public Attributes
const std::string app_str
const std::string app_long
const std::string z_suffix_const
const std::string out_dir_app
double a
double a_out
double da
Private Member Functions
bool printing () const
void print_info (const Sim_Param &sim) const
void print_position (const App_Var< T > &APP) const
void print_density (App_Var< T > &APP) const
void get_binned_power_spec (App_Var< T > &APP) const
void print_power_spec (App_Var< T > &APP)
void print_extrap_pwr (App_Var< T > &APP, const Extrap_Pk< double, 2 > &P_k) const
void print_corr (App_Var< T > &APP, const Extrap_Pk< double, 2 > &P_k) const
void print_vel_pwr (App_Var< T > &APP)
void print_init (App_Var< T > &APP)
bool integrate () const
void upd_time ()
double z () const
Private Attributes
unsigned int print_every
unsigned int step
Tracking track
Interp_obj pwr_spec_input
double D_init
double dDda_init
bool is_init_pwr_spec_0
bool is_init_vel_pwr_spec_0
Detailed Description
template<class T>
template<class T>
class App_Var< T >::Impl< T >
Definition at line 132 of file app_var.cpp.
Constructor & Destructor Documentation
template<class T> template<class T > App_Var< T >::Impl< T >::Impl (const Sim_Param & sim, const std::string & app_short, const std::string & app_long) inline
Definition at line 136 of file app_var.cpp.
                                                                                      :
         step(0), print_every(sim.out_opt.print_every),
         app_str(app_short), app_long(app_long), z_suffix_const("_" + app_short + "_"), out_dir_app(std_out_dir(app_short + "_run/", sim)),
         track(4, sim.box_opt.par_num_1d),
         a(sim.integ_opt.a_in), a_out(sim.integ_opt.a_out), da(sim.integ_opt.db),
         is_init_pwr_spec_0(false), is_init_vel_pwr_spec_0(false)
     {}
Member Function Documentation
template<class T> template<class T > uint64_t App_Var< T >::Impl< T >::alloc_bin_corr (App_Var< T > & APP) inline
Definition at line 167 of file app_var.cpp.
References App_Var< T >::corr_func_binned, Data_Vec< T, N >::dim(), Range::lower, Sim_Param::other_par, Sim_Param::out_opt, Out_Opt::points_per_10_Mpc, Data_Vec< T, N >::reserve(), App_Var< T >::sim, Data_Vec< T, N >::size(), Range::upper, and Other_par::x_corr.
     {
         size_t bin_num =  (size_t)ceil((APP.sim.other_par.x_corr.upper - APP.sim.other_par.x_corr.lower)/ 10. * APP.sim.out_opt.points_per_10_Mpc);
         APP.corr_func_binned.reserve(bin_num);
         return sizeof(FTYPE_t)*APP.corr_func_binned.dim()*APP.corr_func_binned.size();
     }
template<class T> template<class T > uint64_t App_Var< T >::Impl< T >::alloc_bin_spec (App_Var< T > & APP) inline
Definition at line 157 of file app_var.cpp.
References Out_Opt::bins_per_decade, Sim_Param::box_opt, Data_Vec< T, N >::dim(), Box_Opt::mesh_num_pwr, Sim_Param::out_opt, App_Var< T >::pwr_spec_binned, App_Var< T >::pwr_spec_binned_0, Data_Vec< T, N >::reserve(), App_Var< T >::sim, Data_Vec< T, N >::size(), and App_Var< T >::vel_pwr_spec_binned_0.
     {
         size_t bin_num = (size_t)ceil(log10(APP.sim.box_opt.mesh_num_pwr)*APP.sim.out_opt.bins_per_decade);
         APP.pwr_spec_binned.reserve(bin_num);
         APP.pwr_spec_binned_0.reserve(bin_num);
         APP.vel_pwr_spec_binned_0.reserve(bin_num);
         return sizeof(FTYPE_t)*APP.pwr_spec_binned.dim()*APP.pwr_spec_binned.size()*3;
     }
template<class T> template<class T > uint64_t App_Var< T >::Impl< T >::alloc_mesh_vec (App_Var< T > & APP) inline
Definition at line 145 of file app_var.cpp.
References App_Var< T >::app_field, Sim_Param::box_opt, Box_Opt::mesh_num, Box_Opt::mesh_num_pwr, App_Var< T >::power_aux, and App_Var< T >::sim.
     {
         APP.app_field.reserve(3);
         APP.power_aux.reserve(3);
         for(size_t i = 0; i < 3; i++){
             APP.app_field.emplace_back(APP.sim.box_opt.mesh_num);
             APP.power_aux.emplace_back(APP.sim.box_opt.mesh_num_pwr);
         }
         return sizeof(FTYPE_t)*(APP.app_field[0].length*APP.app_field.size()+APP.power_aux[0].length*APP.power_aux.size());
     }
template<class T> template<class T > uint64_t App_Var< T >::Impl< T >::alloc_particles (App_Var< T > & APP) inline
Definition at line 175 of file app_var.cpp.
References Sim_Param::box_opt, Box_Opt::par_num, App_Var< T >::particles, App_Var< T >::sim, and growth_allz::T.
     {
         APP.particles.resize(APP.sim.box_opt.par_num); //< use resize instead of reserve for initialization of particles
         return sizeof(T)*APP.sim.box_opt.par_num;
     }
template<class T> template<class T > void App_Var< T >::Impl< T >::create_work_dir (const Out_Opt & out_opt) inline
Definition at line 296 of file app_var.cpp.
References create_dir(), Out_Opt::print_corr, Out_Opt::print_dens, Out_Opt::print_par_pos, Out_Opt::print_pwr, and Out_Opt::print_vel_pwr.
     {
         create_dir(out_dir_app + "log/");
         if (print_every)
         {
             if (out_opt.print_corr) create_dir(out_dir_app + "corr_func/");
             if (out_opt.print_par_pos) create_dir(out_dir_app + "par_cut/");
             if (out_opt.print_pwr)
             {
                 create_dir(out_dir_app + "pwr_diff/");
                 create_dir(out_dir_app + "pwr_spec/");
             }
             if (out_opt.print_dens)
             {
                 create_dir(out_dir_app + "rho_bin/");
                 create_dir(out_dir_app + "rho_map/");
             }
             if (out_opt.print_vel_pwr)
             {
                 create_dir(out_dir_app + "vel_pwr_diff/");
                 create_dir(out_dir_app + "vel_pwr_spec/");
             }
         }
     }
template<class T> template<class T > void App_Var< T >::Impl< T >::fftw_prep (App_Var< T > & APP) inline
Definition at line 181 of file app_var.cpp.
References App_Var< T >::app_field, Sim_Param::box_opt, FFTW_PLAN_C2R, FFTW_PLAN_OMP, FFTW_PLAN_OMP_INIT, FFTW_PLAN_R2C, Box_Opt::mesh_num, Box_Opt::mesh_num_pwr, Run_Opt::nt_fftw, App_Var< T >::p_B, App_Var< T >::p_B_pwr, App_Var< T >::p_F, App_Var< T >::p_F_pwr, App_Var< T >::power_aux, Sim_Param::run_opt, and App_Var< T >::sim.
     {
         const Sim_Param& sim = APP.sim; // get rid of 'APP.sim'
         if (!FFTW_PLAN_OMP_INIT()){
             throw std::runtime_error("Errors during multi-thread initialization");
         }
         FFTW_PLAN_OMP(sim.run_opt.nt_fftw);
         const size_t N_pot = sim.box_opt.mesh_num;
         const size_t N_pwr = sim.box_opt.mesh_num_pwr;
         APP.p_F = FFTW_PLAN_R2C(N_pot, N_pot, N_pot, APP.app_field[0].real(), APP.app_field[0].complex(), FFTW_ESTIMATE);
         APP.p_B = FFTW_PLAN_C2R(N_pot, N_pot, N_pot, APP.app_field[0].complex(), APP.app_field[0].real(), FFTW_ESTIMATE);
         APP.p_F_pwr = FFTW_PLAN_R2C(N_pwr, N_pwr, N_pwr, APP.power_aux[0].real(), APP.power_aux[0].complex(), FFTW_ESTIMATE);
         APP.p_B_pwr = FFTW_PLAN_C2R(N_pwr, N_pwr, N_pwr, APP.power_aux[0].complex(), APP.power_aux[0].real(), FFTW_ESTIMATE);
     }
template<class T> template<class T > void App_Var< T >::Impl< T >::get_binned_power_spec (App_Var< T > & APP) const inline private
Definition at line 368 of file app_var.cpp.
References fftw_execute_dft_r2c(), gen_pow_spec_binned(), App_Var< T >::p_F_pwr, App_Var< T >::power_aux, App_Var< T >::pwr_spec_binned, pwr_spec_k(), and App_Var< T >::sim.
     {/* Compute power spectrum and bin it */
         fftw_execute_dft_r2c(APP.p_F_pwr, APP.power_aux[0]);
         pwr_spec_k(APP.power_aux[0], APP.power_aux[0]);
         gen_pow_spec_binned(APP.sim, APP.power_aux[0], APP.pwr_spec_binned);
     }
template<class T> template<class T > bool App_Var< T >::Impl< T >::integrate () const inline private
Definition at line 431 of file app_var.cpp.
     {
         return (a <= a_out) && (da > 0);
     }
template<class T> template<class T > void App_Var< T >::Impl< T >::integration (App_Var< T > & APP) inline
Definition at line 325 of file app_var.cpp.
References halomod_bm::integrate, App_Var< T >::particles, App_Var< T >::print_output(), App_Var< T >::sim, App_Var< T >::upd_pos(), and z.
     {
         print_init(APP); // WARNING: power_aux[0] is modified
         while(integrate())
         {
             BOOST_LOG_TRIVIAL(info) << "Starting computing step with z = " << z() << " (a = " << a << ")";
             APP.upd_pos();
             track.update_track_par(APP.particles);
             if (printing()) APP.print_output();
             upd_time();
         }
         print_info(APP.sim);
     }
template<class T> template<class T > void App_Var< T >::Impl< T >::print_corr (App_Var< T > & APP, const Extrap_Pk< double, 2 > & P_k) const inline private
Definition at line 397 of file app_var.cpp.
References App_Var< T >::corr_func_binned, gen_corr_func_binned_gsl_qawf(), gen_corr_func_binned_gsl_qawf_lin(), print_corr_func(), and App_Var< T >::sim.
     {/* Printing correlation function */
         gen_corr_func_binned_gsl_qawf(APP.sim, P_k, APP.corr_func_binned);
         print_corr_func(APP.corr_func_binned, out_dir_app, "_gsl_qawf_par" + z_suffix());
         gen_corr_func_binned_gsl_qawf_lin(APP.sim, a, APP.corr_func_binned);
         print_corr_func(APP.corr_func_binned, out_dir_app, "_gsl_qawf_lin" + z_suffix());
     }
template<class T> template<class T > void App_Var< T >::Impl< T >::print_density (App_Var< T > & APP) const inline private
Definition at line 361 of file app_var.cpp.
References App_Var< T >::dens_binned, gen_dens_binned(), App_Var< T >::power_aux, print_dens_bin(), print_rho_map(), and App_Var< T >::sim.
     {/* Printing density */
         gen_dens_binned(APP.power_aux[0], APP.dens_binned, APP.sim);
         print_rho_map(APP.power_aux[0], APP.sim, out_dir_app, z_suffix());
         print_dens_bin(APP.dens_binned, out_dir_app, z_suffix());
     }
template<class T> template<class T > void App_Var< T >::Impl< T >::print_end () inline
Definition at line 242 of file app_var.cpp.
     {
         BOOST_LOG_TRIVIAL(info) << app_long << " ended successfully.";
     }
template<class T> template<class T > void App_Var< T >::Impl< T >::print_extrap_pwr (App_Var< T > & APP, const Extrap_Pk< double, 2 > & P_k) const inline private
Definition at line 391 of file app_var.cpp.
References gen_pow_spec_binned_from_extrap(), print_pow_spec(), App_Var< T >::pwr_spec_binned, and App_Var< T >::sim.
     {/* Print extrapolated power spectrum */
         gen_pow_spec_binned_from_extrap(APP.sim, P_k, APP.pwr_spec_binned);
         print_pow_spec(APP.pwr_spec_binned, out_dir_app, "_extrap" + z_suffix());
     }
template<class T> template<class T > void App_Var< T >::Impl< T >::print_info (const Sim_Param & sim) const inline private
Definition at line 350 of file app_var.cpp.
References Sim_Param::print_info().
     {
         sim.print_info(out_dir_app, app_str);
     }
template<class T> template<class T > void App_Var< T >::Impl< T >::print_init (App_Var< T > & APP) inline private
Definition at line 419 of file app_var.cpp.
References App_Var< T >::particles, and App_Var< T >::print_output().
     {
         /* Setting initial (binned) power spectrum, WARNING: power_aux[0] is modified */
         track.update_track_par(APP.particles);
         if (print_every) APP.print_output();
         upd_time();
     }
template<class T> template<class T > void App_Var< T >::Impl< T >::print_input_realisation (App_Var< T > & APP) inline
Definition at line 254 of file app_var.cpp.
References App_Var< T >::app_field, gen_pow_spec_binned_init(), App_Var< T >::power_aux, print_pow_spec(), App_Var< T >::pwr_spec_binned_0, pwr_spec_k_init(), and App_Var< T >::sim.
     {
         /* Print input power spectrum (one realisation), before Zel`dovich push */
         pwr_spec_k_init(APP.app_field[0], APP.power_aux[0]);
         gen_pow_spec_binned_init(APP.sim, APP.power_aux[0], APP.app_field[0].length/2, APP.pwr_spec_binned_0);
         pwr_spec_input.init(APP.pwr_spec_binned_0);
         print_pow_spec(APP.pwr_spec_binned_0, out_dir_app, z_suffix_const + "init");
     }
template<class T> template<class T > void App_Var< T >::Impl< T >::print_output (App_Var< T > & APP) inline
Definition at line 263 of file app_var.cpp.
References Out_Opt::get_pk_extrap, Out_Opt::get_pwr, Out_Opt::get_rho, get_rho_from_par(), get_vel_from_par(), Sim_Param::out_opt, App_Var< T >::particles, App_Var< T >::power_aux, Out_Opt::print_corr, Out_Opt::print_dens, Out_Opt::print_extrap_pwr, Out_Opt::print_par_pos, Out_Opt::print_pwr, Out_Opt::print_vel_pwr, App_Var< T >::pwr_spec_binned, and App_Var< T >::sim.
     {
         const Out_Opt& out_opt = APP.sim.out_opt;
         /* Printing positions */
         if (out_opt.print_par_pos) print_position(APP);
         /* Get discrete density from particles */
         if (out_opt.get_rho) get_rho_from_par(APP.particles, APP.power_aux[0], APP.sim);
         /* Printing density */
         if (out_opt.print_dens) print_density(APP);
         /* Compute power spectrum and bin it */
         if (out_opt.get_pwr) get_binned_power_spec(APP);
         /* Printing power spectrum */
         if (out_opt.print_pwr) print_power_spec(APP);
         /* Extrapolate power spectrum beyond range of simulation box */
         if (out_opt.get_pk_extrap){
             const Extrap_Pk<FTYPE_t, 2> P_k(APP.pwr_spec_binned, APP.sim);
             /* Print extrapolated power spectrum */
             if (out_opt.print_extrap_pwr) print_extrap_pwr(APP, P_k);
             /* Printing correlation function */
             if (out_opt.print_corr) print_corr(APP, P_k);
         }
         /* Velocity power spectrum */
         if (out_opt.print_vel_pwr && get_vel_from_par(APP.particles, APP.power_aux, APP.sim)) print_vel_pwr(APP);
     }
template<class T> template<class T > void App_Var< T >::Impl< T >::print_position (const App_Var< T > & APP) const inline private
Definition at line 355 of file app_var.cpp.
References App_Var< T >::particles, print_par_pos_cut_small(), and App_Var< T >::sim.
     {/* Printing positions */
         print_par_pos_cut_small(APP.particles, APP.sim, out_dir_app, z_suffix());
         track.print_track_par(APP.sim, out_dir_app, z_suffix());
     }
template<class T> template<class T > void App_Var< T >::Impl< T >::print_power_spec (App_Var< T > & APP) inline private
Definition at line 375 of file app_var.cpp.
References Sim_Param::cosmo, growth_allz::growth_factor, print_pow_spec(), print_pow_spec_diff(), App_Var< T >::pwr_spec_binned, App_Var< T >::pwr_spec_binned_0, and App_Var< T >::sim.
     {/* Printing power spectrum */
         print_pow_spec(APP.pwr_spec_binned, out_dir_app, "_par" + z_suffix());
         if (!is_init_pwr_spec_0){
             APP.pwr_spec_binned_0 = APP.pwr_spec_binned;
             D_init = growth_factor(a, APP.sim.cosmo);
             is_init_pwr_spec_0 = true;
         }
         FTYPE_t D_now = growth_factor(a, APP.sim.cosmo);
         print_pow_spec_diff(APP.pwr_spec_binned, APP.pwr_spec_binned_0, D_now / D_init, out_dir_app, "_par" + z_suffix());
         print_pow_spec_diff(APP.pwr_spec_binned, pwr_spec_input, D_now, out_dir_app, "_input" + z_suffix());
         print_pow_spec_diff(APP.pwr_spec_binned, APP.pwr_spec_binned_0, pwr_spec_input, D_now, D_init,
                             out_dir_app, "_hybrid" + z_suffix());
     }
template<class T> template<class T > void App_Var< T >::Impl< T >::print_sim_name () const inline
Definition at line 235 of file app_var.cpp.
     {
         std::string app_long_upper(app_long);
         std::transform(app_long_upper.begin(), app_long_upper.end(), app_long_upper.begin(), ::toupper);
         BOOST_LOG_TRIVIAL(info) << "Starting: " << app_long_upper;
     }
template<class T> template<class T > void App_Var< T >::Impl< T >::print_vel_pwr (App_Var< T > & APP) inline private
Definition at line 405 of file app_var.cpp.
References Sim_Param::cosmo, fftw_execute_dft_r2c_triple(), gen_pow_spec_binned(), growth_change(), App_Var< T >::p_F_pwr, App_Var< T >::power_aux, print_vel_pow_spec(), print_vel_pow_spec_diff(), App_Var< T >::pwr_spec_binned, App_Var< T >::sim, App_Var< T >::vel_pwr_spec_binned_0, and vel_pwr_spec_k().
     {/* Print velocity power spectrum */
         fftw_execute_dft_r2c_triple(APP.p_F_pwr, APP.power_aux);
         vel_pwr_spec_k(APP.power_aux, APP.power_aux[0]);
         gen_pow_spec_binned(APP.sim, APP.power_aux[0], APP.pwr_spec_binned);
         print_vel_pow_spec(APP.pwr_spec_binned, out_dir_app, z_suffix());
         if (!is_init_vel_pwr_spec_0){
             APP.vel_pwr_spec_binned_0 = APP.pwr_spec_binned;
             is_init_vel_pwr_spec_0 = true;
             dDda_init = growth_change(a, APP.sim.cosmo);
         }
         print_vel_pow_spec_diff(APP.pwr_spec_binned, APP.vel_pwr_spec_binned_0, growth_change(a, APP.sim.cosmo) / dDda_init, out_dir_app, z_suffix());
     }
template<class T> template<class T > bool App_Var< T >::Impl< T >::printing () const inline private
Definition at line 345 of file app_var.cpp.
     {
         return print_every ? ((step % print_every) == 0) or (a == a_out) : false ;
     }
template<class T> template<class T > void App_Var< T >::Impl< T >::set_init_cond (App_Var< T > & APP) inline
Definition at line 210 of file app_var.cpp.
References App_Var< T >::app_field, fftw_execute_dft_c2r_triple(), gen_displ_k(), gen_pot_k(), gen_rho_dist_k(), Sim_Param::out_opt, App_Var< T >::p_B, App_Var< T >::p_F, App_Var< T >::power_aux, Out_Opt::print_pwr, and App_Var< T >::sim.
     {
         /* Generating the right density distribution in k-space */
         gen_rho_dist_k(APP.sim, APP.app_field[0], APP.p_F);
         /* Print input power spectrum (one realisation), before Zel`dovich push */
         if (print_every && APP.sim.out_opt.print_pwr) print_input_realisation(APP);
         /* Computing initial potential in k-space */
         gen_pot_k(APP.app_field[0], APP.power_aux[0]);
         /* Computing displacement in k-space */
         gen_displ_k(APP.app_field, APP.power_aux[0]);
         /* Computing displacement in q-space */
         BOOST_LOG_TRIVIAL(debug) << "Computing displacement in q-space...";
         fftw_execute_dft_c2r_triple(APP.p_B, APP.app_field);
         /* Set initial positions of particles (with or without velocities)  */
         set_init_pos(APP);
     }
template<class T> template<class T > void App_Var< T >::Impl< T >::set_init_pos (App_Var< T > & APP) inline
Definition at line 205 of file app_var.cpp.
References Integ_Opt::a_in, App_Var< T >::app_field, Sim_Param::integ_opt, App_Var< T >::particles, set_pert_pos(), and App_Var< T >::sim.
     {
         set_pert_pos(APP.sim, APP.sim.integ_opt.a_in, APP.particles, APP.app_field);
     }
template<class T> template<class T > void App_Var< T >::Impl< T >::upd_time () inline private
Definition at line 436 of file app_var.cpp.
     {
         step++;
         if ((a_out - a) < da) da = a_out - a;
         a += da;
     }
template<class T> template<class T > double App_Var< T >::Impl< T >::z () const inline private
Definition at line 444 of file app_var.cpp.
     {
         return 1/a - 1;
     }
template<class T> template<class T > std::string App_Var< T >::Impl< T >::z_suffix () const inline
Definition at line 247 of file app_var.cpp.
References z.
     {
         std::stringstream z_suffix_num;
         z_suffix_num << std::fixed << std::setprecision(2) << z();
         return z_suffix_const + "z" + z_suffix_num.str();
     }
Member Data Documentation
template<class T> template<class T > double App_Var< T >::Impl< T >::a
Definition at line 323 of file app_var.cpp.
template<class T> template<class T > double App_Var< T >::Impl< T >::a_out
Definition at line 323 of file app_var.cpp.
template<class T> template<class T > const std::string App_Var< T >::Impl< T >::app_long
Definition at line 233 of file app_var.cpp.
template<class T> template<class T > const std::string App_Var< T >::Impl< T >::app_str
Definition at line 233 of file app_var.cpp.
template<class T> template<class T > double App_Var< T >::Impl< T >::D_init private
Definition at line 428 of file app_var.cpp.
template<class T> template<class T > double App_Var< T >::Impl< T >::da
Definition at line 323 of file app_var.cpp.
template<class T> template<class T > double App_Var< T >::Impl< T >::dDda_init private
Definition at line 428 of file app_var.cpp.
template<class T> template<class T > bool App_Var< T >::Impl< T >::is_init_pwr_spec_0 private
Definition at line 429 of file app_var.cpp.
template<class T> template<class T > bool App_Var< T >::Impl< T >::is_init_vel_pwr_spec_0 private
Definition at line 429 of file app_var.cpp.
template<class T> template<class T > const std::string App_Var< T >::Impl< T >::out_dir_app
Definition at line 233 of file app_var.cpp.
template<class T> template<class T > unsigned int App_Var< T >::Impl< T >::print_every private
Definition at line 341 of file app_var.cpp.
template<class T> template<class T > Interp_obj App_Var< T >::Impl< T >::pwr_spec_input private
Definition at line 343 of file app_var.cpp.
template<class T> template<class T > unsigned int App_Var< T >::Impl< T >::step private
Definition at line 341 of file app_var.cpp.
template<class T> template<class T > Tracking App_Var< T >::Impl< T >::track private
Definition at line 342 of file app_var.cpp.
template<class T> template<class T > const std::string App_Var< T >::Impl< T >::z_suffix_const
Definition at line 233 of file app_var.cpp.
The documentation for this class was generated from the following file:
src/ApproximationsSchemes/app_var.cpp