Fast Methods for Cosmological Simulations: Grid< NDIM, T > Class Template Reference
Grid< NDIM, T > Class Template Reference
#include <grid.h>
Public Member Functions
Grid ()
Grid (size_t N)
Grid (size_t N, T yini)
T * get_y ()
T const * get_y () const
const std::vector< T > & get_vec () const
T & operator[] (size_t i)
const T & operator[] (size_t i) const
T get_y (size_t i)
void set_y (std::vector< T > &y)
void set_y (size_t i, T &value)
std::vector< size_t > index_list (size_t i)
size_t get_N () const
size_t get_Ntot () const
size_t grid_index (std::vector< size_t > &index_list)
size_t grid_index_3d (size_t ix, size_t iy, size_t iz)
size_t grid_index_2d (size_t ix, size_t iy)
void dump_to_file (std::string filename)
void read_from_file (std::string filename)
double max ()
double min ()
void clear ()
template<size_t NNDIM, typename TT >
Grid< NNDIM, TT > & operator+= (const Grid< NNDIM, TT > &rhs)
template<size_t NNDIM, typename TT >
Grid< NNDIM, TT > & operator-= (const Grid< NNDIM, TT > &rhs)
template<size_t NNDIM, typename TT >
Grid< NNDIM, TT > & operator*= (const Grid< NNDIM, TT > &rhs)
template<size_t NNDIM, typename TT >
Grid< NNDIM, TT > & operator/= (const Grid< NNDIM, TT > &rhs)
Grid< NDIM, T > & operator*= (const T &rhs)
Grid< NDIM, T > & operator/= (const T &rhs)
double rms_norm ()
void check_for_nan (bool exitifnan)
Private Attributes
size_t _N
size_t _Ntot
std::vector< T > _y
Detailed Description
template<size_t NDIM, typename T>
class Grid< NDIM, T >
Definition at line 21 of file grid.h.
Constructor & Destructor Documentation
template<size_t NDIM, typename T> Grid< NDIM, T >::Grid () inline
Definition at line 32 of file grid.h.
Referenced by Grid< NDIM, T >::Grid().
 : Grid(0, 0.0) {}
template<size_t NDIM, typename T> Grid< NDIM, T >::Grid (size_t N) inline
Definition at line 33 of file grid.h.
References Grid< NDIM, T >::dump_to_file(), Grid< NDIM, T >::get_N(), Grid< NDIM, T >::get_Ntot(), Grid< NDIM, T >::get_vec(), Grid< NDIM, T >::get_y(), Grid< NDIM, T >::Grid(), Grid< NDIM, T >::grid_index(), Grid< NDIM, T >::grid_index_2d(), Grid< NDIM, T >::grid_index_3d(), Grid< NDIM, T >::index_list(), mfunc_bm::iz, Grid< NDIM, T >::operator[](), Grid< NDIM, T >::read_from_file(), Grid< NDIM, T >::set_y(), growth_allz::T, and Catch::Generators::value().
 : Grid(N, 0.0) {}
template<size_t NDIM, typename T > Grid< NDIM, T >::Grid (size_t N, T yini)
Definition at line 37 of file grid.cpp.
 : _N(N), _Ntot(power(_N, NDIM)), _y(std::vector<T>(_Ntot, yini)) {}
Member Function Documentation
template<size_t NDIM, typename T > void Grid< NDIM, T >::check_for_nan (bool exitifnan)
Definition at line 20 of file grid.cpp.
Referenced by Grid< NDIM, T >::operator/=().
{
   bool nanfound = false;
   for(size_t i = 0; i < _Ntot; i++){
     if(_y[i] != _y[i]){
       nanfound = true;
       break;
     }
   }
   if(nanfound){
     BOOST_LOG_TRIVIAL(error) << "Warning: NaN found in grid" << (exitifnan ? " ...aborting!" : "" ) << std::endl;
     if(exitifnan) exit(1);
   }
 }
template<size_t NDIM, typename T > void Grid< NDIM, T >::clear ()
Definition at line 197 of file grid.cpp.
References Grid< NDIM, T >::_N, Grid< NDIM, T >::_Ntot, and Grid< NDIM, T >::_y.
Referenced by Grid< NDIM, T >::min().
{
   _N = _Ntot = 0;
   _y.clear();
 }
template<size_t NDIM, typename T > void Grid< NDIM, T >::dump_to_file (std::string filename)
Definition at line 147 of file grid.cpp.
References Grid< NDIM, T >::_N, Grid< NDIM, T >::_Ntot, Grid< NDIM, T >::_y, and growth_allz::T.
Referenced by assign_to_grid(), and Grid< NDIM, T >::Grid().
{
   size_t ndim = NDIM;
   // Verbose
   BOOST_LOG_TRIVIAL(debug) << "==> Dumping grid to file [" << filename << "]" << std::endl;
   BOOST_LOG_TRIVIAL(debug) << "    Ndim: " << NDIM << " N: " << _N << " Ntot: " << _Ntot << std::endl;
   // Write header
   std::ofstream fout(filename.c_str(), std::ios::out | std::ios::binary);
   fout.write((char*)&_N, sizeof(size_t));
   fout.write((char*)&ndim, sizeof(size_t));
   // Write the grid-data
   fout.write((char*)&_y[0], _y.size() * sizeof(T));
 }
template<size_t NDIM, typename T > size_t Grid< NDIM, T >::get_N () const
Definition at line 135 of file grid.cpp.
References Grid< NDIM, T >::_N.
Referenced by assign_to_grid(), compute_v(), Grid< NDIM, T >::Grid(), main(), MultiGrid< NDIM, T >::MultiGrid(), MultiGrid< NDIM, T >::restrict_down(), solve_with_fft(), anonymous_namespace{chameleon.cpp}::transform_Grid_to_Mesh(), and anonymous_namespace{chameleon.cpp}::transform_Mesh_to_Grid().
{
   return _N;
 }
template<size_t NDIM, typename T > size_t Grid< NDIM, T >::get_Ntot () const
Definition at line 141 of file grid.cpp.
References Grid< NDIM, T >::_Ntot.
Referenced by assign_to_grid(), compute_v(), anonymous_namespace{chameleon.cpp}::ChiSolver< T >::correct_sol(), Grid< NDIM, T >::Grid(), MultiGridSolver< NDIM, T >::make_prolongation_array(), solve_with_fft(), sqrt(), anonymous_namespace{chameleon.cpp}::transform_Grid_to_Mesh(), and anonymous_namespace{chameleon.cpp}::transform_Mesh_to_Grid().
{
   return _Ntot;
 }
template<size_t NDIM, typename T > const std::vector< T > & Grid< NDIM, T >::get_vec () const
Definition at line 51 of file grid.cpp.
References Grid< NDIM, T >::_y.
Referenced by Grid< NDIM, T >::Grid(), and anonymous_namespace{chameleon.cpp}::min().
 {
     return _y;
 }
template<size_t NDIM, typename T > T * Grid< NDIM, T >::get_y ()
Definition at line 41 of file grid.cpp.
References Grid< NDIM, T >::_y.
Referenced by assign_to_grid(), Grid< NDIM, T >::Grid(), MultiGrid< NDIM, T >::restrict_down(), MultiGridSolver< NDIM, T >::set_initial_guess(), and set_rho().
{
   return &_y[0];
 }
template<size_t NDIM, typename T > T const * Grid< NDIM, T >::get_y () const
Definition at line 46 of file grid.cpp.
References Grid< NDIM, T >::_y.
{
   return &_y[0];
 }
template<size_t NDIM, typename T > T Grid< NDIM, T >::get_y (size_t i)
Definition at line 75 of file grid.cpp.
References Grid< NDIM, T >::_Ntot, and Grid< NDIM, T >::_y.
{
 #ifdef _BOUNDSCHECK
   assert(i < _Ntot);
 #endif
   return _y[i];
 }
template<size_t NDIM, typename T > size_t Grid< NDIM, T >::grid_index (std::vector< size_t > & index_list)
Definition at line 112 of file grid.cpp.
References Grid< NDIM, T >::_N, and Grid< NDIM, T >::_Ntot.
Referenced by Grid< NDIM, T >::Grid().
{
   size_t index = 0;
   for(size_t j = 0, n = 1; j < NDIM; j++, n *= _N)
     index += index_list[j] * n;
 #ifdef _BOUNDSCHECK
   assert(index < _Ntot);
 #endif
   return index;
 }
template<size_t NDIM, typename T > size_t Grid< NDIM, T >::grid_index_2d (size_t ix, size_t iy)
Definition at line 130 of file grid.cpp.
References Grid< NDIM, T >::_N.
Referenced by Grid< NDIM, T >::Grid().
{
   return ix + _N*iy;
 }
template<size_t NDIM, typename T > size_t Grid< NDIM, T >::grid_index_3d (size_t ix, size_t iy, size_t iz)
Definition at line 124 of file grid.cpp.
References Grid< NDIM, T >::_N, and mfunc_bm::iz.
Referenced by compute_v(), and Grid< NDIM, T >::Grid().
{
   return ix + _N*(iy + _N*iz);
 }
template<size_t NDIM, typename T > std::vector< size_t > Grid< NDIM, T >::index_list (size_t i)
Definition at line 102 of file grid.cpp.
References Grid< NDIM, T >::_N.
Referenced by compute_v(), and Grid< NDIM, T >::Grid().
{
   std::vector<size_t> ii(NDIM, 0);
   for(size_t j = 0, n = 1; j < NDIM; j++, n *= _N){
     ii[j] = i / n % _N;
   }
   return ii;
 }
template<size_t NDIM, typename T> double Grid< NDIM, T >::max () inline
Definition at line 71 of file grid.h.
References Grid< NDIM, T >::_Ntot, and sqrt().
Referenced by main().
                 {
       double maxval = std::norm(_y[0]);
 #ifdef OPENMP
 #pragma omp parallel for reduction(max: maxval)
 #endif
       for(size_t i = 0; i < _Ntot; i++){
         double curval = std::norm(_y[i]);
         if(curval > maxval) maxval = curval;
       }
       return std::sqrt( maxval );
     }
template<size_t NDIM, typename T> double Grid< NDIM, T >::min () inline
Definition at line 84 of file grid.h.
References Grid< NDIM, T >::_Ntot, Grid< NDIM, T >::clear(), and sqrt().
Referenced by main().
                 {
       double minval = std::norm(_y[0]);
 #ifdef OPENMP
 #pragma omp parallel for reduction(min: minval)
 #endif
       for(size_t i = 0; i < _Ntot; i++){
         double curval = std::norm(_y[i]);
         if(curval < minval) minval = curval;
       }
       return std::sqrt( minval );
     }
template<size_t NDIM, typename T> template<size_t NNDIM, typename TT > Grid<NNDIM,TT>& Grid< NDIM, T >::operator*= (const Grid< NNDIM, TT > & rhs) inline
Definition at line 129 of file grid.h.
References Grid< NDIM, T >::_N, Grid< NDIM, T >::_Ntot, and Grid< NDIM, T >::_y.
{
 #ifdef _BOUNDSCHECK
       assert(this->_N == rhs._N);
 #endif
 #ifdef OPENMP
 #pragma omp parallel for
 #endif
       for(size_t i = 0; i < _Ntot; i++)
         this->_y[i] *= rhs._y[i];
       return *this;
     }
template<size_t NDIM, typename T> Grid<NDIM,T>& Grid< NDIM, T >::operator*= (const T & rhs) inline
Definition at line 156 of file grid.h.
References Grid< NDIM, T >::_Ntot.
{
 #ifdef OPENMP
 #pragma omp parallel for
 #endif
       for(size_t i = 0; i < _Ntot; i++)
         this->_y[i] *= rhs;
       return *this;
     }
template<size_t NDIM, typename T> template<size_t NNDIM, typename TT > Grid<NNDIM,TT>& Grid< NDIM, T >::operator+= (const Grid< NNDIM, TT > & rhs) inline
Definition at line 101 of file grid.h.
References Grid< NDIM, T >::_N, Grid< NDIM, T >::_Ntot, and Grid< NDIM, T >::_y.
{
 #ifdef _BOUNDSCHECK
       assert(this->_N == rhs._N);
 #endif
 #ifdef OPENMP
 #pragma omp parallel for
 #endif
       for(size_t i = 0; i < _Ntot; i++)
         this->_y[i] += rhs._y[i];
       return *this;
     }
template<size_t NDIM, typename T> template<size_t NNDIM, typename TT > Grid<NNDIM,TT>& Grid< NDIM, T >::operator-= (const Grid< NNDIM, TT > & rhs) inline
Definition at line 115 of file grid.h.
References Grid< NDIM, T >::_N, Grid< NDIM, T >::_Ntot, and Grid< NDIM, T >::_y.
{
 #ifdef _BOUNDSCHECK
       assert(this->_N == rhs._N);
 #endif
 #ifdef OPENMP
 #pragma omp parallel for
 #endif
       for(size_t i = 0; i < _Ntot; i++)
         this->_y[i] -= rhs._y[i];
       return *this;
     }
template<size_t NDIM, typename T> template<size_t NNDIM, typename TT > Grid<NNDIM,TT>& Grid< NDIM, T >::operator/= (const Grid< NNDIM, TT > & rhs) inline
Definition at line 143 of file grid.h.
References Grid< NDIM, T >::_N, Grid< NDIM, T >::_Ntot, and Grid< NDIM, T >::_y.
{
 #ifdef _BOUNDSCHECK
       assert(this->_N == rhs._N);
 #endif
 #ifdef OPENMP
 #pragma omp parallel for
 #endif
       for(size_t i = 0; i < _Ntot; i++)
         this->_y[i] /= rhs._y[i];
       return *this;
     }
template<size_t NDIM, typename T> Grid<NDIM,T>& Grid< NDIM, T >::operator/= (const T & rhs) inline
Definition at line 166 of file grid.h.
References Grid< NDIM, T >::_Ntot, Grid< NDIM, T >::check_for_nan(), and Grid< NDIM, T >::rms_norm().
{
 #ifdef OPENMP
 #pragma omp parallel for
 #endif
       for(size_t i = 0; i < _Ntot; i++)
         this->_y[i] /= rhs;
       return *this;
     }
template<size_t NDIM, typename T > T & Grid< NDIM, T >::operator[] (size_t i)
Definition at line 58 of file grid.cpp.
References Grid< NDIM, T >::_Ntot, and Grid< NDIM, T >::_y.
Referenced by Grid< NDIM, T >::Grid().
{
 #ifdef _BOUNDSCHECK
   assert(i < _Ntot);
 #endif
   return _y[i];
 }
template<size_t NDIM, typename T > const T & Grid< NDIM, T >::operator[] (size_t i) const
Definition at line 66 of file grid.cpp.
References Grid< NDIM, T >::_Ntot, and Grid< NDIM, T >::_y.
{
 #ifdef _BOUNDSCHECK
   assert(i < _Ntot);
 #endif
   return _y[i];
 }
template<size_t NDIM, typename T > void Grid< NDIM, T >::read_from_file (std::string filename)
Definition at line 165 of file grid.cpp.
References Grid< NDIM, T >::_N, Grid< NDIM, T >::_Ntot, Grid< NDIM, T >::_y, power(), and growth_allz::T.
Referenced by Grid< NDIM, T >::Grid(), and main().
{
   size_t ninfile = 0, ntot = 0, ndim = 0, size = 0;
   // Read header: N and NDIM
   std::ifstream input(filename.c_str(), std::ios::in | std::ifstream::binary);
   input.read((char *) &ninfile, sizeof(size_t));
   input.read((char *) &ndim, sizeof(size_t));
   ntot = power(ninfile, NDIM);
   size = sizeof(T) * ntot;
   // Checks
   assert(ndim == NDIM);
   assert(ninfile > 0 && ntot < INT_MAX);
   // Verbose
   BOOST_LOG_TRIVIAL(debug) << "==> Reading file into grid [" << filename << "]" << std::endl;
   BOOST_LOG_TRIVIAL(debug) << "    Ndim: " << ndim << " Nfile: " << ninfile << " Ntot: " << ntot << std::endl;
   // Read the data
   std::vector<char> tempvec(size, 0);
   input.read(&tempvec[0], tempvec.size());
   // Copy the grid-data and set parameters
   _N = ninfile;
   _Ntot = ntot;
   _y = std::vector<T>(ntot, 0.0);
   std::memcpy(&_y[0], &tempvec[0], size);
 }
template<size_t NDIM, typename T > double Grid< NDIM, T >::rms_norm ()
Definition at line 238 of file grid.h.
References Grid< NDIM, T >::_Ntot, Grid< NDIM, T >::_y, and sqrt().
Referenced by MultiGridSolver< NDIM, T >::calculate_residual(), main(), and Grid< NDIM, T >::operator/=().
{
   double rms = 0.0;
 #ifdef OPENMP
 #pragma omp parallel for reduction(+:rms)
 #endif
   for(size_t i = 0; i < _Ntot; i++){
     rms += std::norm(_y[i]);
   }
   rms = std::sqrt(rms / double(_Ntot));
   return rms;
 }
template<size_t NDIM, typename T > void Grid< NDIM, T >::set_y (std::vector< T > & y)
Definition at line 84 of file grid.cpp.
References Grid< NDIM, T >::_Ntot, and Grid< NDIM, T >::_y.
Referenced by Grid< NDIM, T >::Grid().
{
 #ifdef _BOUNDSCHECK
   assert(y.size() == _Ntot);
 #endif
   _y = y;
 }
template<size_t NDIM, typename T > void Grid< NDIM, T >::set_y (size_t i, T & value)
Definition at line 93 of file grid.cpp.
References Grid< NDIM, T >::_Ntot, Grid< NDIM, T >::_y, and Catch::Generators::value().
{
 #ifdef _BOUNDSCHECK
   assert(i < _Ntot);
 #endif
   _y[i] = value;
 }
Member Data Documentation
template<size_t NDIM, typename T> size_t Grid< NDIM, T >::_N private
Definition at line 25 of file grid.h.
Referenced by Grid< NDIM, T >::clear(), Grid< NDIM, T >::dump_to_file(), Grid< NDIM, T >::get_N(), Grid< NDIM, T >::grid_index(), Grid< NDIM, T >::grid_index_2d(), Grid< NDIM, T >::grid_index_3d(), Grid< NDIM, T >::index_list(), Grid< NDIM, T >::operator*=(), Grid< NDIM, T >::operator+=(), Grid< NDIM, T >::operator-=(), Grid< NDIM, T >::operator/=(), and Grid< NDIM, T >::read_from_file().
template<size_t NDIM, typename T> size_t Grid< NDIM, T >::_Ntot private
Definition at line 26 of file grid.h.
Referenced by Grid< NDIM, T >::clear(), Grid< NDIM, T >::dump_to_file(), Grid< NDIM, T >::get_Ntot(), Grid< NDIM, T >::get_y(), Grid< NDIM, T >::grid_index(), Grid< NDIM, T >::max(), Grid< NDIM, T >::min(), Grid< NDIM, T >::operator*=(), Grid< NDIM, T >::operator+=(), Grid< NDIM, T >::operator-=(), Grid< NDIM, T >::operator/=(), Grid< NDIM, T >::operator[](), Grid< NDIM, T >::read_from_file(), Grid< NDIM, T >::rms_norm(), and Grid< NDIM, T >::set_y().
template<size_t NDIM, typename T> std::vector<T> Grid< NDIM, T >::_y private
Definition at line 27 of file grid.h.
Referenced by Grid< NDIM, T >::clear(), Grid< NDIM, T >::dump_to_file(), Grid< NDIM, T >::get_vec(), Grid< NDIM, T >::get_y(), Grid< NDIM, T >::operator*=(), Grid< NDIM, T >::operator+=(), Grid< NDIM, T >::operator-=(), Grid< NDIM, T >::operator/=(), Grid< NDIM, T >::operator[](), Grid< NDIM, T >::read_from_file(), Grid< NDIM, T >::rms_norm(), and Grid< NDIM, T >::set_y().
The documentation for this class was generated from the following files:
src/3party/MultiGridSolver/src/grid.h
src/3party/MultiGridSolver/src/grid.cpp