Fast Methods for Cosmological Simulations: MultiGrid< NDIM, T > Class Template Reference
MultiGrid< NDIM, T > Class Template Reference
#include <multigrid.h>
Public Member Functions
MultiGrid ()
MultiGrid (size_t N)
MultiGrid (size_t N, size_t Nlevel)
MultiGrid (Grid< NDIM, T > &y, size_t Nlevel)
MultiGrid (Grid< NDIM, T > &y)
Grid< NDIM, T > & get_grid (size_t level=0)
const Grid< NDIM, T > & get_grid (size_t level=0) const
T * operator[] (size_t level)
const T * operator[] (size_t level) const
T * get_y (size_t level=0)
T const *const get_y (size_t level=0) const
T get_y (size_t level, size_t i)
T get_y (size_t level, std::vector< size_t > &coord_list)
size_t get_N (size_t level=0) const
size_t get_Ntot (size_t level=0) const
size_t get_Ndim () const
size_t get_Nlevel () const
size_t get_Nmin () const
void set_y (size_t level, size_t i, T value)
size_t gridindex_from_coord (size_t level, std::vector< size_t > &coord_list)
std::vector< size_t > coord_from_gridindex (size_t level, size_t i)
void clear ()
void restrict_down (size_t from_level)
void restrict_down (size_t from_level, Grid< NDIM, T > &to_grid)
void restrict_down_all ()
Private Attributes
size_t _N
size_t _Ntot
size_t _Nlevel
std::vector< size_t > _NinLevel
std::vector< size_t > _NtotinLevel
std::vector< Grid< NDIM, T > > _y
Detailed Description
template<size_t NDIM, typename T>
class MultiGrid< NDIM, T >
Definition at line 21 of file multigrid.h.
Constructor & Destructor Documentation
template<size_t NDIM, typename T> MultiGrid< NDIM, T >::MultiGrid () inline
Definition at line 34 of file multigrid.h.
Referenced by MultiGrid< 3, CHI_PREC_t >::MultiGrid().
 {}
template<size_t NDIM, typename T> MultiGrid< NDIM, T >::MultiGrid (size_t N) inline
Definition at line 35 of file multigrid.h.
 :  MultiGrid(N, int(log2(N)+1)) {}
template<size_t NDIM, typename T > MultiGrid< NDIM, T >::MultiGrid (size_t N, size_t Nlevel)
Definition at line 132 of file multigrid.cpp.
References MultiGrid< NDIM, T >::_N, MultiGrid< NDIM, T >::_NinLevel, MultiGrid< NDIM, T >::_Nlevel, MultiGrid< NDIM, T >::_NtotinLevel, MultiGrid< NDIM, T >::_y, and power().
                                                     : _N(N), _Ntot(power(_N, NDIM)), _Nlevel(Nlevel), _NinLevel(std::vector<size_t>(_Nlevel, _N)), _NtotinLevel(std::vector<size_t>(_Nlevel, _Ntot)) {
   // Check that N is positive and divisible by 2^{Nlevel - 1}
   assert( ( _N / power(2, _Nlevel - 1) ) * power(2, _Nlevel - 1) == _N && _N > 0);
   // We need atleast 1 level
   assert( _Nlevel > 0 );
   // Total number of cells in finest level should not be too large (otherwise we cannot use [int])
   assert( log2(INT_MAX) / log2(_N) > NDIM );
   // Allocate memory
   _y = std::vector<Grid<NDIM, T> >(_Nlevel);
   _y[0] = Grid<NDIM, T> (_N, 0.0);
   for(size_t level = 1; level < _Nlevel; level++){
     _NinLevel[level] = _NinLevel[level-1] / 2;
     _NtotinLevel[level] = power(_NinLevel[level], NDIM);
     assert(_NinLevel[level] > 0);
     _y[level] = Grid<NDIM, T>(_NinLevel[level], 0.0);
   }
 }
template<size_t NDIM, typename T> MultiGrid< NDIM, T >::MultiGrid (Grid< NDIM, T > & y, size_t Nlevel)
Definition at line 127 of file multigrid.cpp.
References MultiGrid< NDIM, T >::_y.
                                                             : MultiGrid(y.get_N(), Nlevel) {
   _y[0] = y;
 }
template<size_t NDIM, typename T> MultiGrid< NDIM, T >::MultiGrid (Grid< NDIM, T > & y)
Definition at line 121 of file multigrid.cpp.
References MultiGrid< NDIM, T >::_Nlevel, MultiGrid< NDIM, T >::_y, Grid< NDIM, T >::get_N(), and power().
                                              : MultiGrid(y.get_N(), int(log2(y.get_N())+1)){
   assert( power(2, _Nlevel - 1 ) == y.get_N()  );
   _y[0] = y;
 }
Member Function Documentation
template<size_t NDIM, typename T > void MultiGrid< NDIM, T >::clear ()
Definition at line 236 of file multigrid.cpp.
References MultiGrid< NDIM, T >::_N, MultiGrid< NDIM, T >::_NinLevel, MultiGrid< NDIM, T >::_Nlevel, MultiGrid< NDIM, T >::_Ntot, MultiGrid< NDIM, T >::_NtotinLevel, and MultiGrid< NDIM, T >::_y.
Referenced by MultiGrid< 3, CHI_PREC_t >::MultiGrid().
{
   _N = _Ntot = _Nlevel = 0;
   _NinLevel.clear();
   _NtotinLevel.clear();
   _y.clear();
 }
template<size_t NDIM, typename T > std::vector< size_t > MultiGrid< NDIM, T >::coord_from_gridindex (size_t level, size_t i)
Definition at line 215 of file multigrid.cpp.
References MultiGrid< NDIM, T >::_NinLevel, and MultiGrid< NDIM, T >::_NtotinLevel.
Referenced by MultiGrid< 3, CHI_PREC_t >::MultiGrid().
{
 #ifdef _BOUNDSCHECK
   assert(i < _NtotinLevel[level]);
 #endif
   std::vector<size_t> index(NDIM, 0);
   size_t N = _NinLevel[level];
   for(size_t idim = 0, n = 1; idim < NDIM; idim++, n *= N){
     index[idim] = i / n % N;
   }
   return index;
 }
template<size_t NDIM, typename T > Grid< NDIM, T > & MultiGrid< NDIM, T >::get_grid (size_t level = 0)
Definition at line 17 of file multigrid.cpp.
Referenced by assign_to_grid(), MultiGridSolver< 3, T >::get_grid(), main(), anonymous_namespace{chameleon.cpp}::min(), MultiGrid< 3, CHI_PREC_t >::MultiGrid(), anonymous_namespace{chameleon.cpp}::transform_Mesh_to_MultiGrid(), and anonymous_namespace{chameleon.cpp}::transform_MultiGrid_to_Mesh().
{
 #ifdef _BOUNDSCHECK
   assert(level < _Nlevel);
 #endif
   return _y[level];
 }
template<size_t NDIM, typename T > const Grid< NDIM, T > & MultiGrid< NDIM, T >::get_grid (size_t level = 0) const
Definition at line 25 of file multigrid.cpp.
{
 #ifdef _BOUNDSCHECK
   assert(level < _Nlevel);
 #endif
   return _y[level];
 }
template<size_t NDIM, typename T > size_t MultiGrid< NDIM, T >::get_N (size_t level = 0) const
Definition at line 90 of file multigrid.cpp.
Referenced by assign_to_grid(), main(), MultiGrid< 3, CHI_PREC_t >::MultiGrid(), and set_rho().
{
 #ifdef _BOUNDSCHECK
   assert(level < _Nlevel);
 #endif
   return _NinLevel[level];
 }
template<size_t NDIM, typename T > size_t MultiGrid< NDIM, T >::get_Ndim () const
Definition at line 106 of file multigrid.cpp.
Referenced by MultiGrid< 3, CHI_PREC_t >::MultiGrid().
{
   return NDIM;
 }
template<size_t NDIM, typename T > size_t MultiGrid< NDIM, T >::get_Nlevel () const
Definition at line 111 of file multigrid.cpp.
Referenced by MultiGridSolver< NDIM, T >::add_external_grid(), main(), and MultiGrid< 3, CHI_PREC_t >::MultiGrid().
{
   return _Nlevel;
 }
template<size_t NDIM, typename T > size_t MultiGrid< NDIM, T >::get_Nmin () const
Definition at line 116 of file multigrid.cpp.
Referenced by MultiGrid< 3, CHI_PREC_t >::MultiGrid().
{
   return _NinLevel[_Nlevel-1];
 }
template<size_t NDIM, typename T > size_t MultiGrid< NDIM, T >::get_Ntot (size_t level = 0) const
Definition at line 98 of file multigrid.cpp.
Referenced by assign_to_grid(), MultiGrid< 3, CHI_PREC_t >::MultiGrid(), and set_rho().
{
 #ifdef _BOUNDSCHECK
   assert(level < _Nlevel);
 #endif
   return _NtotinLevel[level];
 }
template<size_t NDIM, typename T > T * MultiGrid< NDIM, T >::get_y (size_t level = 0)
Definition at line 49 of file multigrid.cpp.
Referenced by assign_to_grid(), MultiGrid< 3, CHI_PREC_t >::MultiGrid(), and set_rho().
{
 #ifdef _BOUNDSCHECK
   assert(level < _Nlevel);
 #endif
   return _y[level].get_y();
 }
template<size_t NDIM, typename T > T const *const MultiGrid< NDIM, T >::get_y (size_t level = 0) const
Definition at line 57 of file multigrid.cpp.
{
 #ifdef _BOUNDSCHECK
   assert(level < _Nlevel);
 #endif
   return _y[level].get_y();
 }
template<size_t NDIM, typename T > T MultiGrid< NDIM, T >::get_y (size_t level, size_t i)
Definition at line 65 of file multigrid.cpp.
{
 #ifdef _BOUNDSCHECK
   assert(level < _Nlevel);
 #endif
   return _y[level].get_y(i);
 }
template<size_t NDIM, typename T > T MultiGrid< NDIM, T >::get_y (size_t level, std::vector< size_t > & coord_list)
Definition at line 73 of file multigrid.cpp.
{
   size_t ind = gridindex_from_coord(level, coord_list);
 #ifdef _BOUNDSCHECK
   assert(level < _Nlevel);
 #endif
   return _y[level].get_y(ind);
 }
template<size_t NDIM, typename T > size_t MultiGrid< NDIM, T >::gridindex_from_coord (size_t level, std::vector< size_t > & coord_list)
Definition at line 228 of file multigrid.cpp.
References MultiGrid< NDIM, T >::_NinLevel.
Referenced by MultiGrid< 3, CHI_PREC_t >::MultiGrid().
{
   size_t index = 0;
   for(size_t j = 0, N = 1; j < NDIM; j++, N *= _NinLevel[level])
     index += coord_list[j] * N;
   return index;
 }
template<size_t NDIM, typename T > T * MultiGrid< NDIM, T >::operator[] (size_t level)
Definition at line 33 of file multigrid.cpp.
Referenced by MultiGrid< 3, CHI_PREC_t >::MultiGrid().
{
 #ifdef _BOUNDSCHECK
   assert(level < _Nlevel);
 #endif
   return _y[level].get_y();
 }
template<size_t NDIM, typename T > const T * MultiGrid< NDIM, T >::operator[] (size_t level) const
Definition at line 41 of file multigrid.cpp.
{
 #ifdef _BOUNDSCHECK
   assert(level < _Nlevel);
 #endif
   return _y[level].get_y();
 }
template<size_t NDIM, typename T > void MultiGrid< NDIM, T >::restrict_down (size_t from_level)
Definition at line 204 of file multigrid.cpp.
References MultiGrid< NDIM, T >::_y.
Referenced by main(), MultiGrid< 3, CHI_PREC_t >::MultiGrid(), and MultiGrid< NDIM, T >::restrict_down_all().
{
   restrict_down(from_level, _y[from_level+1]);
 }
template<size_t NDIM, typename T> void MultiGrid< NDIM, T >::restrict_down (size_t from_level, Grid< NDIM, T > & to_grid)
Definition at line 155 of file multigrid.cpp.
References MultiGrid< NDIM, T >::_NinLevel, MultiGrid< NDIM, T >::_Nlevel, MultiGrid< NDIM, T >::_NtotinLevel, MultiGrid< NDIM, T >::_y, Grid< NDIM, T >::get_N(), Grid< NDIM, T >::get_y(), and growth_allz::T.
{
   // Cannot restict down if we are at the bottom
   if(from_level + 1 >= _Nlevel) return;
   // Sanity check
   assert( to_grid.get_N() == _y[from_level + 1].get_N() );
   // One over number of cells averaged over  [ = 1 / 2^Ndim ]
   T oneovernumcells = 1.0/T(1 << NDIM);
   // Pointers to Top and Bottom grid
   T *Top = _y[from_level].get_y();
   T *Bottom = to_grid.get_y();//_y[from_level+1].get_y();
   // Nodes on top and bottom level
   size_t NTop = _NinLevel[from_level];
   size_t NtotTop = _NtotinLevel[from_level];
   size_t NBottom = _NinLevel[from_level+1];
   size_t NtotBottom = _NtotinLevel[from_level+1];
   // Clear bottom array
   std::fill_n(Bottom, NtotBottom, 0.0);
   // Compute N^j
   std::vector<size_t> NpowTop(NDIM, 1);
   std::vector<size_t> NpowBottom(NDIM, 1);
   for(size_t j = 1; j < NDIM; j++){
     NpowTop[j] = NpowTop[j-1] * NTop;
     NpowBottom[j] = NpowBottom[j-1] * NBottom;
   }
   // Loop over top grid
   for (size_t i = 0; i < NtotTop; i++) {
     // Compute bottom array index the top cell 'belongs to'
     size_t i_bottom = 0;
     for(size_t j = 0; j < NDIM; j++){
       size_t ii = i / NpowTop[j] % NTop;
       i_bottom += (ii/2) * NpowBottom[j];
     }
     // Add up to restricted grid
     Bottom[i_bottom] += Top[i] * oneovernumcells;
   }
 }
template<size_t NDIM, typename T > void MultiGrid< NDIM, T >::restrict_down_all ()
Definition at line 209 of file multigrid.cpp.
References MultiGrid< NDIM, T >::_Nlevel, and MultiGrid< NDIM, T >::restrict_down().
Referenced by main(), MultiGrid< 3, CHI_PREC_t >::MultiGrid(), set_rho(), and anonymous_namespace{chameleon.cpp}::transform_Mesh_to_MultiGrid().
{
   for(size_t i = 0; i < _Nlevel-1; i++)
     restrict_down(i);
 }
template<size_t NDIM, typename T> void MultiGrid< NDIM, T >::set_y (size_t level, size_t i, T value)
Definition at line 82 of file multigrid.cpp.
Referenced by MultiGrid< 3, CHI_PREC_t >::MultiGrid().
{
 #ifdef _BOUNDSCHECK
   assert(level < _Nlevel);
 #endif
   _y[level].set_y(i, value);
 }
Member Data Documentation
template<size_t NDIM, typename T> size_t MultiGrid< NDIM, T >::_N private
Definition at line 24 of file multigrid.h.
Referenced by MultiGrid< NDIM, T >::clear(), and MultiGrid< NDIM, T >::MultiGrid().
template<size_t NDIM, typename T> std::vector<size_t> MultiGrid< NDIM, T >::_NinLevel private
Definition at line 27 of file multigrid.h.
Referenced by MultiGrid< NDIM, T >::clear(), MultiGrid< NDIM, T >::coord_from_gridindex(), MultiGrid< NDIM, T >::gridindex_from_coord(), MultiGrid< NDIM, T >::MultiGrid(), and MultiGrid< NDIM, T >::restrict_down().
template<size_t NDIM, typename T> size_t MultiGrid< NDIM, T >::_Nlevel private
Definition at line 26 of file multigrid.h.
Referenced by MultiGrid< NDIM, T >::clear(), MultiGrid< NDIM, T >::MultiGrid(), MultiGrid< NDIM, T >::restrict_down(), and MultiGrid< NDIM, T >::restrict_down_all().
template<size_t NDIM, typename T> size_t MultiGrid< NDIM, T >::_Ntot private
Definition at line 25 of file multigrid.h.
Referenced by MultiGrid< NDIM, T >::clear().
template<size_t NDIM, typename T> std::vector<size_t> MultiGrid< NDIM, T >::_NtotinLevel private
Definition at line 28 of file multigrid.h.
Referenced by MultiGrid< NDIM, T >::clear(), MultiGrid< NDIM, T >::coord_from_gridindex(), MultiGrid< NDIM, T >::MultiGrid(), and MultiGrid< NDIM, T >::restrict_down().
template<size_t NDIM, typename T> std::vector<Grid<NDIM,T> > MultiGrid< NDIM, T >::_y private
Definition at line 29 of file multigrid.h.
Referenced by MultiGrid< NDIM, T >::clear(), MultiGrid< NDIM, T >::MultiGrid(), and MultiGrid< NDIM, T >::restrict_down().
The documentation for this class was generated from the following files:
src/3party/MultiGridSolver/src/multigrid.h
src/3party/MultiGridSolver/src/multigrid.cpp