Fast Methods for Cosmological Simulations: App_Var_FP_mod::FP_ppImpl Class Reference
App_Var_FP_mod::FP_ppImpl Class Reference
Public Member Functions
FP_ppImpl (const Sim_Param &sim)
Public Attributes
LinkedList linked_list
Interp_obj fs_interp
uint64_t memory_alloc
Detailed Description
Definition at line 127 of file mod_frozen_potential.cpp.
Constructor & Destructor Documentation
App_Var_FP_mod::FP_ppImpl::FP_ppImpl (const Sim_Param & sim) inline
Definition at line 130 of file mod_frozen_potential.cpp.
References App_Opt::a, Sim_Param::app_opt, Sim_Param::box_opt, anonymous_namespace{mod_frozen_potential.cpp}::force_ref(), anonymous_namespace{mod_frozen_potential.cpp}::force_tot(), Box_Opt::Ng, PI, pow2(), and App_Opt::rs.
                                    : linked_list(sim.box_opt.par_num, sim.app_opt.M, sim.app_opt.Hc)
     {
         memory_alloc = sizeof(size_t)*(linked_list.HOC.length+linked_list.par_num);
         // precompute short range force
         size_t res = size_t(sim.app_opt.rs/0.05)+1; // force resolution 5% of mesh cell
         const FTYPE_t r0 = sim.app_opt.rs / (res-1);
         Data_Vec<FTYPE_t, 2> data(res);
         FTYPE_t r;
         const FTYPE_t e2 = pow2(sim.box_opt.Ng*0.1); // softening of 10% of average interparticle length
         #pragma omp parallel for private(r)
         for(size_t i = 0; i < res; i++)
         {
             r = i*r0;
             data[0][i] = pow2(r); // store square of r
             data[1][i] = (force_tot(r, e2) - force_ref(r, sim.app_opt.a))/(4*PI);
         }
         fs_interp.init(data);
     }
Member Data Documentation
Interp_obj App_Var_FP_mod::FP_ppImpl::fs_interp
Definition at line 153 of file mod_frozen_potential.cpp.
LinkedList App_Var_FP_mod::FP_ppImpl::linked_list
Definition at line 152 of file mod_frozen_potential.cpp.
uint64_t App_Var_FP_mod::FP_ppImpl::memory_alloc
Definition at line 154 of file mod_frozen_potential.cpp.
The documentation for this class was generated from the following file:
src/ApproximationsSchemes/mod_frozen_potential.cpp