Fast Methods for Cosmological Simulations: App_Var_Chi Class Reference
App_Var_Chi Class Reference
Approximations
< end of anonymous namespace (private definitions)
#include <chameleon.hpp>
Classes
class ChiImpl
Public Member Functions
App_Var_Chi (const Sim_Param &sim)
~App_Var_Chi ()
Public Member Functions inherited from App_Var< Particle_v< double > >
App_Var (const Sim_Param &sim, const std::string &app_short, const std::string &app_long)
virtual ~App_Var ()
void run_simulation ()
virtual void update_cosmo (Cosmo_Param &cosmo)
no truncation by default
std::string get_out_dir () const
Protected Member Functions
App_Var_Chi (const Sim_Param &sim, const std::string &app_short, const std::string &app_long)
Protected Member Functions inherited from App_Var< Particle_v< double > >
double a ()
double a_half ()
double da ()
std::string get_z_suffix () const
virtual void pot_corr (std::vector< Mesh > &vel_field, Mesh &pot_k)
Protected Attributes
const std::unique_ptr< ChiImpl > m_impl
Protected Attributes inherited from App_Var< Particle_v< double > >
const Sim_Param & sim
uint64_t memory_alloc
std::vector< Mesh > app_field
std::vector< Mesh > power_aux
std::vector< Particle_v< double > > particles
Data_Vec< double, 2 > corr_func_binned
Data_Vec< double, 2 > pwr_spec_binned
Data_Vec< double, 2 > pwr_spec_binned_0
Data_Vec< double, 2 > vel_pwr_spec_binned_0
FFTW_PLAN_TYPE p_F
FFTW_PLAN_TYPE p_B
FFTW_PLAN_TYPE p_F_pwr
FFTW_PLAN_TYPE p_B_pwr
std::vector< size_t > dens_binned
Private Member Functions
void upd_pos () override
void print_output () override
Detailed Description
< end of anonymous namespace (private definitions)
: class containing variables and methods for chameleon gravity
PUBLIC FUNCTIONS DEFINITIONS *
: class containing variables and methods for chameleon gravity
PUBLIC METHODS * PUBLIC CLASSES *
Definition at line 35 of file chameleon.hpp.
Constructor & Destructor Documentation
App_Var_Chi::App_Var_Chi (const Sim_Param & sim)
Definition at line 836 of file chameleon.cpp.
References ~App_Var_Chi().
                                             :
     App_Var_Chi(sim, "CHI", "Chameleon gravity (FP)") {}
App_Var_Chi::~App_Var_Chi () default
Referenced by App_Var_Chi().
App_Var_Chi::App_Var_Chi (const Sim_Param & sim, const std::string & app_short, const std::string & app_long) protected
Definition at line 830 of file chameleon.cpp.
References m_impl, and App_Var< Particle_v< double > >::memory_alloc.
                                                                                                    :
     App_Var<Particle_v<FTYPE_t>>(sim, app_short, app_long), m_impl(new ChiImpl(sim))
 {
     memory_alloc += m_impl->memory_alloc;
 }
Member Function Documentation
void App_Var_Chi::print_output () override private virtual
Reimplemented from App_Var< Particle_v< double > >.
Definition at line 841 of file chameleon.cpp.
References App_Var< Particle_v< double > >::a(), App_Var< Particle_v< double > >::get_out_dir(), App_Var< Particle_v< double > >::get_z_suffix(), m_impl, Sim_Param::out_opt, App_Var< Particle_v< double > >::p_B, App_Var< Particle_v< double > >::p_F, App_Var< Particle_v< double > >::particles, print_pow_spec(), Out_Opt::print_pwr, App_Var< Particle_v< double > >::pwr_spec_binned, and App_Var< Particle_v< double > >::sim.
 {
     /* Print standard output */
     App_Var<Particle_v<FTYPE_t>>::print_output();
     /* Chameleon power spectrum */
     if (sim.out_opt.print_pwr)
     {
         m_impl->solve(a(), particles, sim, p_F, p_B); // get solution for current time
         m_impl->gen_pow_spec_binned(sim, pwr_spec_binned, p_F); // get chameleon power spectrum
         print_pow_spec(pwr_spec_binned, get_out_dir(), "_chi" + get_z_suffix()); // print
     }
 }
void App_Var_Chi::upd_pos () override private virtual
Implements App_Var< Particle_v< double > >.
Reimplemented in App_Var_Chi_FF.
Definition at line 855 of file chameleon.cpp.
References App_Var< Particle_v< double > >::a_half(), App_Var< Particle_v< double > >::app_field, Sim_Param::box_opt, Sim_Param::cosmo, App_Var< Particle_v< double > >::da(), m_impl, Box_Opt::mesh_num, App_Var< Particle_v< double > >::p_B, App_Var< Particle_v< double > >::p_F, App_Var< Particle_v< double > >::particles, App_Var< Particle_v< double > >::sim, and stream_kick_stream().
 {// Leapfrog method for chameleon gravity (frozen-potential)
     auto kick_step = [&]()
     {
         m_impl->solve(a_half(), particles, sim, p_F, p_B);
         m_impl->get_chi_force(p_F, p_B);
         m_impl->kick_step_w_chi(sim.cosmo, a_half(), da(), particles, app_field);
     };
     stream_kick_stream(da(), particles, kick_step, sim.box_opt.mesh_num);
 }
Member Data Documentation
const std::unique_ptr<ChiImpl> App_Var_Chi::m_impl protected
Definition at line 44 of file chameleon.hpp.
Referenced by App_Var_Chi(), print_output(), upd_pos(), and App_Var_Chi_FF::upd_pos().
The documentation for this class was generated from the following files:
src/ApproximationsSchemes/include/chameleon.hpp
src/ApproximationsSchemes/chameleon.cpp