Fast Methods for Cosmological Simulations: src/3party/CCL/include/fftlog.h File Reference
fftlog.h File Reference
#include <complex.h>
Macros
#define FFTLOG_H
Functions
void pk2xi (int N, const double k[], const double pk[], double r[], double xi[])
void xi2pk (int N, const double r[], const double xi[], double k[], double pk[])
void fftlog_ComputeXiLM (double l, double m, int N, const double k[], const double pk[], double r[], double xi[])
void fftlog_ComputeXi2D (double bessel_order, int N, const double l[], const double cl[], double th[], double xi[])
void fht (int N, const double r[], const double _Complex a[], double k[], double _Complex b[], double mu, double q, double kcrc, int noring, double _Complex *u)
void compute_u_coefficients (int N, double mu, double q, double L, double kcrc, double _Complex u[])
Macro Definition Documentation
#define FFTLOG_H
Definition at line 6 of file fftlog.h.
Function Documentation
void compute_u_coefficients (int N, double mu, double q, double L, double kcrc, double _Complex u[])
void fftlog_ComputeXi2D (double bessel_order, int N, const double l[], const double cl[], double th[], double xi[])
Definition at line 144 of file fftlog.c.
References fht(), and M_PI.
Referenced by ccl_tracer_corr_fftlog().
 {
   double complex* a = malloc(sizeof(complex double)*N);
   double complex* b = malloc(sizeof(complex double)*N);
   for(int i=0;i<N;i++)
     a[i]=l[i]*cl[i];
   fht(N,l,a,th,b,bessel_order,0,1,1,NULL);
   for(int i=0;i<N;i++)
     xi[i]=creal(b[i]/(2*M_PI*th[i]));
   free(a);
   free(b);
 }
void fftlog_ComputeXiLM (double l, double m, int N, const double k[], const double pk[], double r[], double xi[])
Definition at line 160 of file fftlog.c.
References fht(), M_PI, and pow().
Referenced by pk2xi(), and xi2pk().
 {
   double complex* a = malloc(sizeof(complex double)*N);
   double complex* b = malloc(sizeof(complex double)*N);
   for(int i = 0; i < N; i++)
     a[i] = pow(k[i], m - 0.5) * pk[i];
   fht(N, k, a, r, b, l + 0.5, 0, 1, 1, NULL);
   for(int i = 0; i < N; i++)
     xi[i] = creal(pow(2*M_PI*r[i], -(m-0.5)) * b[i]);
   free(a);
   free(b);
 }
void fht (int N, const double r[], const double _Complex a[], double k[], double _Complex b[], double mu, double q, double kcrc, int noring, double _Complex * u)
void pk2xi (int N, const double k[], const double pk[], double r[], double xi[])
Definition at line 176 of file fftlog.c.
References fftlog_ComputeXiLM().
Referenced by ccl_correlation_3d().
 {
   fftlog_ComputeXiLM(0, 2, N, k, pk, r, xi);
 }
void xi2pk (int N, const double r[], const double xi[], double k[], double pk[])
Definition at line 181 of file fftlog.c.
References fftlog_ComputeXiLM(), and M_PI.
 {
   static const double TwoPiCubed = 8*M_PI*M_PI*M_PI;
   fftlog_ComputeXiLM(0, 2, N, r, xi, k, pk);
   for(int j = 0; j < N; j++)
     pk[j] *= TwoPiCubed;
 }