Fast Methods for Cosmological Simulations: src/3party/MultiGridSolver/src/grid.h File Reference
grid.h File Reference
#include <assert.h>
#include <cstring>
#include <iosfwd>
#include <fstream>
#include <complex>
#include <vector>
#include <climits>
Classes
class Grid< NDIM, T >
Functions
template<size_t NDIM, typename T >
Grid< NDIM, T > operator+ (Grid< NDIM, T > lhs, const Grid< NDIM, T > &rhs)
template<size_t NDIM, typename T >
Grid< NDIM, T > operator- (Grid< NDIM, T > lhs, const Grid< NDIM, T > &rhs)
template<size_t NDIM, typename T >
Grid< NDIM, T > operator* (Grid< NDIM, T > lhs, const Grid< NDIM, T > &rhs)
template<size_t NDIM, typename T >
Grid< NDIM, T > operator/ (Grid< NDIM, T > lhs, const Grid< NDIM, T > &rhs)
template<size_t NDIM, typename T >
Grid< NDIM, T > operator* (Grid< NDIM, T > lhs, const T &rhs)
template<size_t NDIM, typename T >
Grid< NDIM, T > operator/ (Grid< NDIM, T > lhs, const T &rhs)
template<size_t NDIM, typename T >
Grid< NDIM, T > operator+ (Grid< NDIM, T > lhs, const T &rhs)
template<size_t NDIM, typename T >
Grid< NDIM, T > operator- (Grid< NDIM, T > lhs, const T &rhs)
template<size_t NDIM, typename T >
Grid< NDIM, T > sqrt (Grid< NDIM, T > lhs)
Function Documentation
template<size_t NDIM, typename T > Grid<NDIM,T> operator* (Grid< NDIM, T > lhs, const Grid< NDIM, T > & rhs)
Definition at line 195 of file grid.h.
Referenced by nlohmann::detail::iter_impl< BasicJsonType >::value().
{
   lhs *= rhs;
   return lhs;
 }
template<size_t NDIM, typename T > Grid<NDIM,T> operator* (Grid< NDIM, T > lhs, const T & rhs)
Definition at line 207 of file grid.h.
{
   lhs *= rhs;
   return lhs;
 }
template<size_t NDIM, typename T > Grid<NDIM,T> operator+ (Grid< NDIM, T > lhs, const Grid< NDIM, T > & rhs)
Definition at line 183 of file grid.h.
{
   lhs += rhs;
   return lhs;
 }
template<size_t NDIM, typename T > Grid<NDIM,T> operator+ (Grid< NDIM, T > lhs, const T & rhs)
Definition at line 219 of file grid.h.
{
   lhs += rhs;
   return lhs;
 }
template<size_t NDIM, typename T > Grid<NDIM,T> operator- (Grid< NDIM, T > lhs, const Grid< NDIM, T > & rhs)
Definition at line 189 of file grid.h.
Referenced by nlohmann::detail::json_reverse_iterator< Base >::operator-().
{
   lhs -= rhs;
   return lhs;
 }
template<size_t NDIM, typename T > Grid<NDIM,T> operator- (Grid< NDIM, T > lhs, const T & rhs)
Definition at line 225 of file grid.h.
{
   lhs -= rhs;
   return lhs;
 }
template<size_t NDIM, typename T > Grid<NDIM,T> operator/ (Grid< NDIM, T > lhs, const Grid< NDIM, T > & rhs)
Definition at line 201 of file grid.h.
{
   lhs /= rhs;
   return lhs;
 }
template<size_t NDIM, typename T > Grid<NDIM,T> operator/ (Grid< NDIM, T > lhs, const T & rhs)
Definition at line 213 of file grid.h.
{
   lhs /= rhs;
   return lhs;
 }
template<size_t NDIM, typename T > Grid<NDIM,T> sqrt (Grid< NDIM, T > lhs)
Definition at line 231 of file grid.h.
References Grid< NDIM, T >::get_Ntot().
Referenced by assign_to_grid(), ccl_j_bessel(), ccl_parameters_create(), ccl_parameters_fill_initial(), ccl_sigmaR(), ccl_sigmaV(), compare_cls(), compute_v(), eh_struct_new(), Extrap_Pk< T, N >::fit_lin(), Extrap_Pk< T, N >::fit_power_law(), anonymous_namespace{mod_frozen_potential.cpp}::force_short(), gamma_fftlog(), gaussian_pz(), gen_gauss_white_noise(), gen_rho_w_pow_k(), get_distance(), h_over_h0(), handle_cmd_line(), anonymous_namespace{core_power.cpp}::hubble_param(), if(), main(), Grid< NDIM, T >::max(), Grid< NDIM, T >::min(), nu_integrand(), Sim_Param::print_info(), anonymous_namespace{test_chameleon.cpp}::print_mesh(), Grid< NDIM, T >::rms_norm(), S2_shape(), set_rho(), std_dev(), TEST_CASE(), test_general(), transfer_nc(), transfer_rsd(), and transfer_wl().
{
   for(size_t i = 0; i < lhs.get_Ntot(); i++)
     lhs[i] = sqrt(fabs(lhs[i]));
   return lhs;
 }