Fast Methods for Cosmological Simulations: src/core/integration.cpp File Reference
integration.cpp File Reference
functions for integration of particle trajectories
#include "core_mesh.h"
#include "core_power.h"
#include "integration.hpp"
#include "params.hpp"
Functions
void stream_step (const double da, std::vector< Particle_v< double >> &particles)
void stream_kick_stream (const double da, std::vector< Particle_v< double >> &particles, std::function< void()> kick_step, size_t per)
void kick_step_no_momentum (const Cosmo_Param &cosmo, const double a, std::vector< Particle_v< double >> &particles, const std::vector< Mesh > &vel_field)
void kick_step_w_momentum (const Cosmo_Param &cosmo, const double a, const double da, std::vector< Particle_v< double >> &particles, const std::vector< Mesh > &force_field)
void kick_step_w_momentum_pm (const Cosmo_Param &cosmo, const double a, const double da, std::vector< Particle_v< double >> &particles, const std::vector< Mesh > &force_field)
Detailed Description
functions for integration of particle trajectories
Author
Michal Vrastil
Date
2018-07-11
Definition in file integration.cpp.
Function Documentation
void kick_step_no_momentum (const Cosmo_Param & cosmo, const double a, std::vector< Particle_v< double >> & particles, const std::vector< Mesh > & vel_field)
Definition at line 32 of file integration.cpp.
References assign_from(), and growth_change().
Referenced by App_Var_FF::upd_pos().
 {
     // no memory of previus velocity, 1st order ODE
     const size_t Np = particles.size();
     Vec_3D<FTYPE_t> vel;
     const FTYPE_t dDda = growth_change(a, cosmo); // dD / da
     #pragma omp parallel for private(vel)
     for (size_t i = 0; i < Np; i++)
     {
         vel.fill(0.);
         assign_from(vel_field, particles[i].position, vel);
         particles[i].velocity = vel*dDda;
     }
 }
void kick_step_w_momentum (const Cosmo_Param & cosmo, const double a, const double da, std::vector< Particle_v< double >> & particles, const std::vector< Mesh > & force_field)
Definition at line 48 of file integration.cpp.
References assign_from(), growth_allz::growth_factor, Cosmo_Param::Omega_L(), Cosmo_Param::Omega_m, and pow().
Referenced by App_Var_FP::upd_pos(), and App_Var_AA::upd_pos().
 {
     // classical 2nd order ODE
     const size_t Np = particles.size();
     Vec_3D<FTYPE_t> force;
     const FTYPE_t D = growth_factor(a, cosmo);
     const FTYPE_t OL = cosmo.Omega_L()*pow(a,3);
     const FTYPE_t Om = cosmo.Omega_m;
     // -3/2a represents usual EOM, the rest are LCDM corrections
     const FTYPE_t f1 = 3/(2*a)*(Om+2*OL)/(Om+OL);
     const FTYPE_t f2 = 3/(2*a)*Om/(Om+OL)*D/a;
     #pragma omp parallel for private(force)
     for (size_t i = 0; i < Np; i++)
     {
         force.fill(0.);
         assign_from(force_field, particles[i].position, force);
         force = force*f2 - particles[i].velocity*f1;
         particles[i].velocity += force*da;
     }
 }
void kick_step_w_momentum_pm (const Cosmo_Param & cosmo, const double a, const double da, std::vector< Particle_v< double >> & particles, const std::vector< Mesh > & force_field)
Definition at line 70 of file integration.cpp.
References assign_from(), growth_allz::growth_factor, Cosmo_Param::Omega_L(), Cosmo_Param::Omega_m, and pow().
Referenced by App_Var_PM::upd_pos().
 {
     // classical 2nd order ODE
     const size_t Np = particles.size();
     Vec_3D<FTYPE_t> force;
     const FTYPE_t D = growth_factor(a, cosmo);
     const FTYPE_t OL = cosmo.Omega_L()*pow(a,3);
     const FTYPE_t Om = cosmo.Omega_m;
     // -3/2a represents usual EOM, the rest are LCDM corrections
     const FTYPE_t f1 = 3/(2*a)*(Om+2*OL)/(Om+OL);
     const FTYPE_t f2 = 3/(2*a)*Om/(Om+OL)/a;
     #pragma omp parallel for private(force)
     for (size_t i = 0; i < Np; i++)
     {
         force.fill(0.);
         assign_from(force_field, particles[i].position, force);
         force = force*f2 - particles[i].velocity*f1;
         particles[i].velocity += force*da;
     }
 }
void stream_kick_stream (const double da, std::vector< Particle_v< double >> & particles, std::function< void()> kick_step, size_t per)
Definition at line 24 of file integration.cpp.
References get_per(), and stream_step().
Referenced by App_Var_FF::upd_pos(), App_Var_FP::upd_pos(), App_Var_Chi::upd_pos(), App_Var_FP_mod::upd_pos(), App_Var_AA::upd_pos(), App_Var_PM::upd_pos(), and App_Var_Chi_FF::upd_pos().
 {// general Leapfrog method: Stream-Kick-Stream & ensure periodicity
     stream_step(da/2, particles);
     kick_step();
     stream_step(da/2, particles);
     get_per(particles, per);
 }
void stream_step (const double da, std::vector< Particle_v< double >> & particles)
Definition at line 14 of file integration.cpp.
Referenced by stream_kick_stream().
 {
     const size_t Np = particles.size();
     #pragma omp parallel for
     for (size_t i = 0; i < Np; i++)
     {
         particles[i].position += particles[i].velocity*da;
     }
 }