Fast Methods for Cosmological Simulations: src/3party/CCL/tests/benchmark/codes/cl_corr_bm/src/limberjack.c File Reference
limberjack.c File Reference
#include "common.h"
Functions
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 3 of file limberjack.c.
References compute_spectra(), compute_w_theta(), init_params(), param_free(), and write_output().
 {
   char fname_ini[256];
   if(argc!=2) {
     printf("Usage: limberjack param_file\n");
     exit(0);
   }
   sprintf(fname_ini,"%s",argv[1]);
   RunParams *par=init_params(fname_ini);
   compute_spectra(par);
   compute_w_theta(par);
   write_output(par);
   param_free(par);
   return 0;
 }