Fast Methods for Cosmological Simulations: anonymous_namespace{test_chameleon.cpp} Namespace Reference
anonymous_namespace{test_chameleon.cpp} Namespace Reference
Functions
template<typename T >
T mean (const std::vector< T > &data)
double mean (const Mesh &data)
void get_neighbor_gridindex (std::vector< size_t > &index_list, size_t i, size_t N)
void init_overdensity (Sim_Param &sim, Mesh &rho, MultiGrid< 3, CHI_PREC_t > &rho_grid)
void get_grav_pot (Mesh &rho, const FFTW_PLAN_TYPE &p_F, const FFTW_PLAN_TYPE &p_B, double box_size, double phi_prefactor)
template<typename T >
static int sgn (T val)
void print_mesh (const std::string &file_name, const Mesh &pot, const double mod=-1-CHI_MIN)
Function Documentation
void anonymous_namespace{test_chameleon.cpp}::get_grav_pot (Mesh & rho, const FFTW_PLAN_TYPE & p_F, const FFTW_PLAN_TYPE & p_B, double box_size, double phi_prefactor)
Definition at line 73 of file test_chameleon.cpp.
References fftw_execute_dft_c2r(), fftw_execute_dft_r2c(), gen_pot_k(), Mesh::N, and pow().
Referenced by TEST_CASE().
 {
     fftw_execute_dft_r2c(p_F, rho);
     gen_pot_k(rho);
     fftw_execute_dft_c2r(p_B, rho);
     rho *= pow(box_size / rho.N, 2) // computing units (laplace)
         *  phi_prefactor; // prefactor of poisson equation
 }
void anonymous_namespace{test_chameleon.cpp}::get_neighbor_gridindex (std::vector< size_t > & index_list, size_t i, size_t N)
Definition at line 20 of file test_chameleon.cpp.
Referenced by anonymous_namespace{chameleon.cpp}::ChiSolver< T >::check_surr_dens(), anonymous_namespace{chameleon.cpp}::ChiSolver< T >::correct_sol(), and TEST_CASE().
 {
     index_list = std::vector<size_t>(7);
     index_list[0] = i;
     for(size_t j = 0, n = 1; j < 3; j++, n *= N){
         size_t ii = i/n % N;
         size_t iminus = ii >= 1   ? ii - 1 : N - 1;
         size_t iplus  = ii <= N-2 ? ii + 1 : 0;
         index_list[2*j+1] = i + (iminus - ii) * n;
         index_list[2*j+2] = i + (iplus - ii) * n;
     }
 }
void anonymous_namespace{test_chameleon.cpp}::init_overdensity (Sim_Param & sim, Mesh & rho, MultiGrid< 3, CHI_PREC_t > & rho_grid)
Definition at line 33 of file test_chameleon.cpp.
References mfunc_bm::iz, Mesh_base< T >::length, mean(), Test_Opt::N_grid, pow2(), Test_Opt::R_sphere, REQUIRE, Test_Opt::rho_b, Test_Opt::rho_sphere, Sim_Param::test_opt, and anonymous_namespace{chameleon.cpp}::transform_Mesh_to_MultiGrid().
Referenced by TEST_CASE().
 {
     const size_t N = sim.test_opt.N_grid;
     const FTYPE_t R = sim.test_opt.R_sphere;
     const FTYPE_t rho_0 = sim.test_opt.rho_sphere;
     const size_t N_tot = rho.length;
     FTYPE_t mean_rho;
     FTYPE_t R2_;
     const FTYPE_t R2 = R*R;
     size_t ix0 = N/2, iy0 = N/2, iz0 = N/2;
     #pragma omp parallel for private(R2_)
     for (size_t ix = 0; ix < N; ++ix)
     {
         for (size_t iy = 0; iy < N; ++iy)
         {
             for (size_t iz = 0; iz < N; ++iz)
             {
                 R2_ = pow2(ix - ix0) + pow2(iy - iy0) + pow2(iz - iz0);
                 rho(ix, iy, iz) = R2_ <= R2 ? rho_0 : 0;
             }
         }
     }
     mean_rho = mean(rho);
     if (mean_rho > 1) throw std::out_of_range("invalid values of sphere parameters (overdensity: " + std::to_string(-mean_rho) + " < -1)");
     rho -= mean_rho;
     transform_Mesh_to_MultiGrid(rho, rho_grid);
     // check density
     REQUIRE( mean(rho) == Approx(0.) );
     REQUIRE( rho(ix0, iy0, iz0) == Approx(rho_0 - mean_rho) );
     REQUIRE( rho(0, 0, 0) == Approx(-mean_rho) );
     // update background underdensity
     sim.test_opt.rho_b = -mean_rho;
 }
template<typename T > T anonymous_namespace{test_chameleon.cpp}::mean (const std::vector< T > & data)
Definition at line 8 of file test_chameleon.cpp.
References growth_allz::T.
 {
     T tmp(0);
     #pragma omp parallel for reduction(+:tmp)
     for (auto it = data.begin(); it < data.end(); ++it) tmp += *it;
     return tmp / data.size();
 }
double anonymous_namespace{test_chameleon.cpp}::mean (const Mesh & data)
Definition at line 18 of file test_chameleon.cpp.
References Mesh_base< T >::data.
Referenced by init_overdensity().
 { return mean(data.data); }
void anonymous_namespace{test_chameleon.cpp}::print_mesh (const std::string & file_name, const Mesh & pot, const double mod = -1 - CHI_MIN)
Definition at line 87 of file test_chameleon.cpp.
References Mesh::N, pow2(), and sqrt().
Referenced by TEST_CASE().
 {
     Ofstream File(file_name);
     size_t N = pot.N;
     int ix0 = N/2, iy0 = N/2, iz0 = N/2;
     auto print_r_chi = [&File, ix0, iy0, iz0,&pot, mod]
                        (int i, int j, int k)
{
                             Vec_3D<size_t> pos(i, j, k); //< to call periodic position on Mesh
                             FTYPE_t r = sqrt(pow2(i - ix0) + pow2(j - iy0) + pow2(k - iz0));
                             File << r << "\t" << pot(pos) + mod  << "\n";
                         };
     for (size_t i = 0; i < N; ++i)
     {
         print_r_chi(i, i, i);
         print_r_chi(i, i, i + 1);
         print_r_chi(i, i + 1, i + 1);
     }
 }
template<typename T > static int anonymous_namespace{test_chameleon.cpp}::sgn (T val) static
Definition at line 82 of file test_chameleon.cpp.
References growth_allz::T.
 {
     return (T(0) < val) - (val < T(0));
 }