Fast Methods for Cosmological Simulations: ccl_test_distances Namespace Reference
ccl_test_distances Namespace Reference
Functions
def Neff_from_N_ur_N_ncdm (N_ur, N_ncdm)
def read_chi_benchmark_file ()
def read_chi_hiz_benchmark_file ()
def read_chi_mnu_benchmark_file ()
def read_chi_mnu_hiz_benchmark_file ()
def read_class_allz_chi_benchmark_file ()
def read_class_mnu_chi_benchmark_file ()
def read_dm_benchmark_file ()
def read_dm_mnu_benchmark_file ()
def read_dm_mnu_hiz_benchmark_file ()
def read_class_allz_dm_benchmark_file ()
def read_class_mnu_dm_benchmark_file ()
def compare_distances (z, chi_bench, dm_bench, Omega_v, w0, wa)
def compare_distances_hiz (z, chi_bench, Omega_v, w0, wa)
def compare_distances_mnu (z, chi_bench, dm_bench, Omega_v, w0, wa, Neff, mnu)
def compare_distances_mnu_hiz (z, chi_bench, dm_bench, Omega_v, w0, wa, Neff_mnu, mnu)
def compare_class_distances (z, chi_bench, dm_bench, Neff=3.0, m_nu=0.0, Omega_k=0.0, w0=-1.0, wa=0.0)
def test_distance_model_0 ()
def test_distance_model_1 ()
def test_distance_model_2 ()
def test_distance_model_3 ()
def test_distance_model_4 ()
def test_distance_hiz_model_0 ()
def test_distance_hiz_model_1 ()
def test_distance_hiz_model_2 ()
def test_distance_mnu_model_0 ()
def test_distance_mnu_model_1 ()
def test_distance_mnu_model_2 ()
def test_distance_mnu_model_3 ()
def test_distance_mnu_model_4 ()
def test_distance_mnu_hiz_model_0 ()
def test_distance_mnu_hiz_model_1 ()
def test_distance_mnu_hiz_model_2 ()
def test_distance_mnu_hiz_model_3 ()
def test_distance_mnu_hiz_model_4 ()
def test_class_distance_model_flat_nonu ()
def test_class_distance_model_pos_curv_nonu ()
def test_class_distance_model_neg_curv_nonu ()
def test_class_distance_model_flat_massnu1 ()
def test_class_distance_model_flat_massnu2 ()
def test_class_distance_model_flat_massnu3 ()
def test_class_distance_model_flat_manynu1 ()
def test_class_distance_model_neg_curv_massnu1 ()
def test_class_distance_model_pos_curv_massnu1 ()
def test_class_allz_distance_model_ccl1 ()
def test_class_allz_distance_model_ccl2 ()
def test_class_allz_distance_model_ccl3 ()
def test_class_allz_distance_model_ccl4 ()
def test_class_allz_distance_model_ccl5 ()
def test_class_allz_distance_model_ccl7 ()
def test_class_allz_distance_model_ccl8 ()
def test_class_allz_distance_model_ccl9 ()
def test_class_allz_distance_model_ccl10 ()
def test_class_allz_distance_model_ccl11 ()
Variables
int DISTANCES_TOLERANCE = 1
int DISTANCES_TOLERANCE_MNU = 1
int DISTANCES_TOLERANCE_CLASS = 1
float Omega_c = 0.25
float Omega_b = 0.05
float h = 0.7
float A_s = 2.1e-9
float n_s = 0.96
int Neff = 0
Omega_v_vals = np.array([0.7, 0.7, 0.7, 0.65, 0.75])
w0_vals = np.array([-1.0, -0.9, -0.9, -0.9, -0.9])
wa_vals = np.array([0.0, 0.0, 0.1, 0.1, 0.1])
list mnu
float Neff_mnu = 3.0
dictionary class_models
path = dirname(abspath(__file__))
Function Documentation
def ccl_test_distances.compare_class_distances (z, chi_bench, dm_bench, Neff = 3.0, m_nu = 0.0, Omega_k = 0.0, w0 = -1.0, wa = 0.0)
Compare distances calculated by pyccl with the distances in the CLASS
benchmark file.
Definition at line 392 of file ccl_test_distances.py.
Referenced by compare_distances_mnu_hiz(), test_class_allz_distance_model_ccl1(), test_class_allz_distance_model_ccl10(), test_class_allz_distance_model_ccl11(), test_class_allz_distance_model_ccl2(), test_class_allz_distance_model_ccl3(), test_class_allz_distance_model_ccl4(), test_class_allz_distance_model_ccl5(), test_class_allz_distance_model_ccl7(), test_class_allz_distance_model_ccl8(), test_class_allz_distance_model_ccl9(), test_class_distance_model_flat_manynu1(), test_class_distance_model_flat_massnu1(), test_class_distance_model_flat_massnu2(), test_class_distance_model_flat_massnu3(), test_class_distance_model_flat_nonu(), test_class_distance_model_neg_curv_massnu1(), test_class_distance_model_neg_curv_nonu(), test_class_distance_model_pos_curv_massnu1(), and test_class_distance_model_pos_curv_nonu().
                             Omega_k=0.0, w0=-1.0, wa=0.0):
     """
     Compare distances calculated by pyccl with the distances in the CLASS
     benchmark file.
     """
     cosmo = ccl.Cosmology(Omega_c=Omega_c, Omega_b=Omega_b, Neff=Neff,
                        h=h, A_s=A_s, n_s=n_s, Omega_k=Omega_k, m_nu=m_nu,
                        w0=w0, wa=wa)
     # Calculate distance using pyccl
     a = 1. / (1. + z)
     chi = ccl.comoving_radial_distance(cosmo, a)
     # Compare to benchmark data
     assert_allclose(chi, chi_bench, rtol=DISTANCES_TOLERANCE_CLASS)
     # Compare distance moudli where a!=1
     a_not_one = a != 1
     dm = ccl.distance_modulus(cosmo, a[a_not_one])
     assert_allclose(dm, dm_bench[a_not_one], rtol=DISTANCES_TOLERANCE_CLASS)
def ccl_test_distances.compare_distances (z, chi_bench, dm_bench, Omega_v, w0, wa)
Compare distances calculated by pyccl with the distances in the benchmark
file.
This test is only valid when radiation is explicitly set to 0.
Definition at line 297 of file ccl_test_distances.py.
Referenced by test_distance_model_0(), test_distance_model_1(), test_distance_model_2(), test_distance_model_3(), and test_distance_model_4().
 def compare_distances(z, chi_bench,dm_bench, Omega_v, w0, wa):
     """
     Compare distances calculated by pyccl with the distances in the benchmark
     file.
     This test is only valid when radiation is explicitly set to 0.
     """
     # Set Omega_K in a consistent way
     Omega_k = 1.0 - Omega_c - Omega_b - Omega_v
     cosmo = ccl.Cosmology(Omega_c=Omega_c, Omega_b=Omega_b, Neff = Neff,
                        h=h, A_s=A_s, n_s=n_s, Omega_k=Omega_k,
                        w0=w0, wa=wa, Omega_g=0)
     # Calculate distance using pyccl
     a = 1. / (1. + z)
     chi = ccl.comoving_radial_distance(cosmo, a) * h
     # Compare to benchmark data
     assert_allclose(chi, chi_bench, atol=1e-12, rtol=DISTANCES_TOLERANCE)
     #compare distance moudli where a!=1
     a_not_one = (a!=1).nonzero()
     dm = ccl.distance_modulus(cosmo,a[a_not_one])
     assert_allclose(dm, dm_bench[a_not_one], atol=1e-3, rtol = DISTANCES_TOLERANCE*10)
def ccl_test_distances.compare_distances_hiz (z, chi_bench, Omega_v, w0, wa)
Compare distances calculated by pyccl with the distances in the benchmark
file.
This test is only valid when radiation is explicitly set to 0.
Definition at line 322 of file ccl_test_distances.py.
Referenced by test_distance_hiz_model_0(), test_distance_hiz_model_1(), and test_distance_hiz_model_2().
 def compare_distances_hiz(z, chi_bench, Omega_v, w0, wa):
     """
     Compare distances calculated by pyccl with the distances in the benchmark
     file.
     This test is only valid when radiation is explicitly set to 0.
     """
     # Set Omega_K in a consistent way
     Omega_k = 1.0 - Omega_c - Omega_b - Omega_v
     cosmo = ccl.Cosmology(Omega_c=Omega_c, Omega_b=Omega_b, Neff=Neff,
                        h=h, A_s=A_s, n_s=n_s, Omega_k=Omega_k,
                        w0=w0, wa=wa, Omega_g=0)
     # Calculate distance using pyccl
     a = 1. / (1. + z)
     chi = ccl.comoving_radial_distance(cosmo, a) * h
     # Compare to benchmark data
     assert_allclose(chi, chi_bench, atol=1e-12, rtol=DISTANCES_TOLERANCE)
 @numpy.testing.dec.slow
def ccl_test_distances.compare_distances_mnu (z, chi_bench, dm_bench, Omega_v, w0, wa, Neff, mnu)
Compare distances calculated by pyccl with the distances in the benchmark
file.
Definition at line 342 of file ccl_test_distances.py.
Referenced by test_distance_mnu_hiz_model_0(), test_distance_mnu_hiz_model_1(), test_distance_mnu_hiz_model_2(), test_distance_mnu_hiz_model_3(), test_distance_mnu_hiz_model_4(), test_distance_mnu_model_0(), test_distance_mnu_model_1(), test_distance_mnu_model_2(), test_distance_mnu_model_3(), and test_distance_mnu_model_4().
 def compare_distances_mnu(z, chi_bench,dm_bench, Omega_v, w0, wa, Neff, mnu):
     """
     Compare distances calculated by pyccl with the distances in the benchmark
     file.
     """
     # Set Omega_K in a consistent way
     Omega_k = 1.0 - Omega_c - Omega_b - Omega_v
     cosmo = ccl.Cosmology(Omega_c=Omega_c, Omega_b=Omega_b, Neff=Neff_mnu,
                        h=h, A_s=A_s, n_s=n_s, Omega_k=Omega_k,
                        w0=w0, wa=wa, m_nu=mnu)
     # Calculate distance using pyccl
     a = 1. / (1. + z)
     chi = ccl.comoving_radial_distance(cosmo, a)
     # Compare to benchmark data
     assert_allclose(chi, chi_bench, atol=1e-12, rtol=DISTANCES_TOLERANCE_MNU)
     #compare distance moudli where a!=1
     a_not_one = (a!=1).nonzero()
     dm = ccl.distance_modulus(cosmo,a[a_not_one])
     assert_allclose(dm, dm_bench[a_not_one], atol=1e-3, rtol = DISTANCES_TOLERANCE_MNU)
 @numpy.testing.dec.slow
def ccl_test_distances.compare_distances_mnu_hiz (z, chi_bench, dm_bench, Omega_v, w0, wa, Neff_mnu, mnu)
Compare distances calculated by pyccl with the distances in the benchmark
file.
Definition at line 367 of file ccl_test_distances.py.
References compare_class_distances().
 def compare_distances_mnu_hiz(z, chi_bench,dm_bench, Omega_v, w0, wa, Neff_mnu, mnu):
     """
     Compare distances calculated by pyccl with the distances in the benchmark
     file.
     """
     # Set Omega_K in a consistent way
     Omega_k = 1.0 - Omega_c - Omega_b - Omega_v
     cosmo = ccl.Cosmology(Omega_c=Omega_c, Omega_b=Omega_b, Neff=Neff,
                        h=h, A_s=A_s, n_s=n_s, Omega_k=Omega_k,
                        w0=w0, wa=wa, m_nu=mnu)
     # Calculate distance using pyccl
     a = 1. / (1. + z)
     chi = ccl.comoving_radial_distance(cosmo, a)
     # Compare to benchmark data
     assert_allclose(chi, chi_bench, atol=1e-12, rtol=DISTANCES_TOLERANCE_MNU)
     #compare distance moudli where a!=1
     a_not_one = (a!=1).nonzero()
     dm = ccl.distance_modulus(cosmo,a[a_not_one])
     assert_allclose(dm, dm_bench[a_not_one], atol=1e-3, rtol = DISTANCES_TOLERANCE_MNU)
def ccl_test_distances.Neff_from_N_ur_N_ncdm (N_ur, N_ncdm)
Calculate N_eff from the number of relativistic and massive neutrinos.
Definition at line 41 of file ccl_test_distances.py.
 def Neff_from_N_ur_N_ncdm(N_ur, N_ncdm):
     """Calculate N_eff from the number of relativistic and massive neutrinos."""
     Neff = N_ur + N_ncdm * ccl.ccllib.TNCDM**4 / (4./11.)**(4./3.)
     return Neff
def ccl_test_distances.read_chi_benchmark_file ()
Read the file containing all the radial comoving distance benchmarks
(distances are in Mpc/h)
Definition at line 115 of file ccl_test_distances.py.
Referenced by read_class_mnu_dm_benchmark_file().
 def read_chi_benchmark_file():
     """
     Read the file containing all the radial comoving distance benchmarks
     (distances are in Mpc/h)
     """
     # Load data from file
     dat = np.genfromtxt(join(path,"benchmark/chi_model1-5.txt")).T
     assert(dat.shape == (6,6))
     # Split into redshift column and chi(z) columns
     z = dat[0]
     chi = dat[1:]
     return z, chi
def ccl_test_distances.read_chi_hiz_benchmark_file ()
Read the file containing all the radial comoving distance benchmarks
(distances are in Mpc/h)
Definition at line 129 of file ccl_test_distances.py.
Referenced by read_chi_mnu_benchmark_file(), and read_class_mnu_dm_benchmark_file().
 def read_chi_hiz_benchmark_file():
     """
     Read the file containing all the radial comoving distance benchmarks
     (distances are in Mpc/h)
     """
     # Load data from file
     dat = np.genfromtxt(join(path,"benchmark/chi_hiz_model1-3.txt")).T
     assert(dat.shape == (4,7))
     # Split into redshift column and chi(z) columns
     z = dat[0]
     chi = dat[1:]
     return z, chi
def ccl_test_distances.read_chi_mnu_benchmark_file ()
Read the file containing all the radial comoving distance benchmarks
with non-zero massive neutrinos
(distances are in Mpc)
Definition at line 143 of file ccl_test_distances.py.
References read_chi_hiz_benchmark_file().
Referenced by read_class_mnu_dm_benchmark_file().
 def read_chi_mnu_benchmark_file():
     """
     Read the file containing all the radial comoving distance benchmarks
     with non-zero massive neutrinos
     (distances are in Mpc)
     """
     # Load data from file
     dat = np.genfromtxt(join(path,"benchmark/chi_mnu_model1-5.txt")).T
     assert(dat.shape == (6,5))
     # Split into redshift column and chi(z) columns
     z = dat[0]
     chi = dat[1:]
     return z, chi
def ccl_test_distances.read_chi_mnu_hiz_benchmark_file ()
Read the file containing all the radial comoving distance benchmarks
with non-zero massive neutrinos
(distances are in Mpc)
Definition at line 172 of file ccl_test_distances.py.
Referenced by read_class_mnu_dm_benchmark_file().
 def read_chi_mnu_hiz_benchmark_file():
     """
     Read the file containing all the radial comoving distance benchmarks
     with non-zero massive neutrinos
     (distances are in Mpc)
     """
     # Load data from file
     dat = np.genfromtxt(join(path,"benchmark/chi_hiz_mnu_model1-5.txt")).T
     assert(dat.shape == (6,7))
     # Split into redshift column and chi(z) columns
     z = dat[0]
     chi = dat[1:]
     return z, chi
def ccl_test_distances.read_class_allz_chi_benchmark_file ()
Read the file containing the radial comoving distance benchmarks from
CLASS for the CCL paper models. (distances are in Mpc)
Definition at line 187 of file ccl_test_distances.py.
Referenced by read_class_mnu_dm_benchmark_file().
 def read_class_allz_chi_benchmark_file():
     """
     Read the file containing the radial comoving distance benchmarks from
     CLASS for the CCL paper models. (distances are in Mpc)
     """
     # Load data from file
     dat = np.genfromtxt(join(path, "benchmark/chi_class_allz.txt")).T
     assert(dat.shape == (11, 10))
     # Split into redshift column and chi(z) columns
     z = dat[0]
     chi = dat[1:]
     return z, chi
def ccl_test_distances.read_class_allz_dm_benchmark_file ()
Read the file containing the distance modulus benchmarks from
CLASS for the CCL paper models.
Definition at line 256 of file ccl_test_distances.py.
Referenced by read_class_mnu_dm_benchmark_file().
 def read_class_allz_dm_benchmark_file():
     """
     Read the file containing the distance modulus benchmarks from
     CLASS for the CCL paper models.
     """
     # Load data from file
     dat = np.genfromtxt(join(path, "benchmark/dm_class_allz.txt")).T
     assert(dat.shape == (11, 10))
     # Split into redshift column and dm(z) columns
     z = dat[0]
     dm = dat[1:]
     return z, dm
def ccl_test_distances.read_class_mnu_chi_benchmark_file ()
Read the file containing the radial comoving distance benchmarks from
CLASS additional massive neutrino models. (distances are in Mpc)
Definition at line 201 of file ccl_test_distances.py.
Referenced by read_class_mnu_dm_benchmark_file().
 def read_class_mnu_chi_benchmark_file():
     """
     Read the file containing the radial comoving distance benchmarks from
     CLASS additional massive neutrino models. (distances are in Mpc)
     """
     # Load data from file
     dat = np.genfromtxt(join(path, "benchmark/chi_class_extra_mnu.txt")).T
     assert(dat.shape == (10, 10))
     # Split into redshift column and chi(z) columns
     z = dat[0]
     chi = dat[1:]
     return z, chi
def ccl_test_distances.read_class_mnu_dm_benchmark_file ()
Read the file containing the distance modulus benchmarks from
CLASS for additional massive neutrino models.
Definition at line 270 of file ccl_test_distances.py.
References read_chi_benchmark_file(), read_chi_hiz_benchmark_file(), read_chi_mnu_benchmark_file(), read_chi_mnu_hiz_benchmark_file(), read_class_allz_chi_benchmark_file(), read_class_allz_dm_benchmark_file(), read_class_mnu_chi_benchmark_file(), read_dm_benchmark_file(), read_dm_mnu_benchmark_file(), and read_dm_mnu_hiz_benchmark_file().
 def read_class_mnu_dm_benchmark_file():
     """
     Read the file containing the distance modulus benchmarks from
     CLASS for additional massive neutrino models.
     """
     # Load data from file
     dat = np.genfromtxt(join(path, "benchmark/dm_class_extra_mnu.txt")).T
     assert(dat.shape == (10, 10))
     # Split into redshift column and dm(z) columns
     z = dat[0]
     dm = dat[1:]
     return z, dm
 # Set-up test data
 z, chi = read_chi_benchmark_file()
 zhi, chi_hiz = read_chi_hiz_benchmark_file()
 _, dm = read_dm_benchmark_file()
 znu, chi_nu = read_chi_mnu_benchmark_file()
 znuhi, chi_nu_hiz = read_chi_mnu_hiz_benchmark_file()
 z_class_mnu, chi_class_mnu = read_class_mnu_chi_benchmark_file()
 z_dm_class_mnu, dm_class_mnu = read_class_mnu_dm_benchmark_file()
 z_class_allz, chi_class_allz = read_class_allz_chi_benchmark_file()
 z_dm_class_allz, dm_class_allz = read_class_allz_dm_benchmark_file()
 _znu, dm_nu = read_dm_mnu_benchmark_file()
 _znuhi, dm_nu_hiz = read_dm_mnu_hiz_benchmark_file()
def ccl_test_distances.read_dm_benchmark_file ()
Read the file containing all the distance modulus benchmarks
Definition at line 215 of file ccl_test_distances.py.
Referenced by read_class_mnu_dm_benchmark_file().
 def read_dm_benchmark_file():
     """
     Read the file containing all the distance modulus benchmarks
     """
     # Load data from file
     dat = np.genfromtxt(join(path,"benchmark/dm_model1-5.txt")).T
     assert(dat.shape == (6,6))
     # Split into redshift column and chi(z) columns
     z = dat[0]
     dm = dat[1:]
     return z, dm
def ccl_test_distances.read_dm_mnu_benchmark_file ()
Read the file containing all the distance modulus benchmarks
for non-zero massive neutrinos.
Definition at line 228 of file ccl_test_distances.py.
Referenced by read_class_mnu_dm_benchmark_file().
 def read_dm_mnu_benchmark_file():
     """
     Read the file containing all the distance modulus benchmarks
     for non-zero massive neutrinos.
     """
     # Load data from file
     dat = np.genfromtxt(join(path,"benchmark/dm_mnu_model1-5.txt")).T
     assert(dat.shape == (6,5))
     # Split into redshift column and chi(z) columns
     z = dat[0]
     dm = dat[1:]
     return z, dm
def ccl_test_distances.read_dm_mnu_hiz_benchmark_file ()
Read the file containing all the distance modulus benchmarks
for non-zero massive neutrinos at high z.
Definition at line 242 of file ccl_test_distances.py.
Referenced by read_class_mnu_dm_benchmark_file().
 def read_dm_mnu_hiz_benchmark_file():
     """
     Read the file containing all the distance modulus benchmarks
     for non-zero massive neutrinos at high z.
     """
     # Load data from file
     dat = np.genfromtxt(join(path,"benchmark/dm_hiz_mnu_model1-5.txt")).T
     assert(dat.shape == (6,7))
     # Split into redshift column and chi(z) columns
     z = dat[0]
     dm = dat[1:]
     return z, dm
def ccl_test_distances.test_class_allz_distance_model_ccl1 ()
Definition at line 521 of file ccl_test_distances.py.
References compare_class_distances().
 def test_class_allz_distance_model_ccl1():
     i = 0
     compare_class_distances(z_class_allz, chi_class_allz[i], dm_class_allz[i], **class_models["CCL1"])
def ccl_test_distances.test_class_allz_distance_model_ccl10 ()
Definition at line 553 of file ccl_test_distances.py.
References compare_class_distances().
 def test_class_allz_distance_model_ccl10():
     i = 8
     compare_class_distances(z_class_allz, chi_class_allz[i], dm_class_allz[i], **class_models["CCL10"])
def ccl_test_distances.test_class_allz_distance_model_ccl11 ()
Definition at line 557 of file ccl_test_distances.py.
References compare_class_distances().
 def test_class_allz_distance_model_ccl11():
     i = 9
     compare_class_distances(z_class_allz, chi_class_allz[i], dm_class_allz[i], **class_models["CCL11"])
def ccl_test_distances.test_class_allz_distance_model_ccl2 ()
Definition at line 525 of file ccl_test_distances.py.
References compare_class_distances().
 def test_class_allz_distance_model_ccl2():
     i = 1
     compare_class_distances(z_class_allz, chi_class_allz[i], dm_class_allz[i], **class_models["CCL2"])
def ccl_test_distances.test_class_allz_distance_model_ccl3 ()
Definition at line 529 of file ccl_test_distances.py.
References compare_class_distances().
 def test_class_allz_distance_model_ccl3():
     i = 2
     compare_class_distances(z_class_allz, chi_class_allz[i], dm_class_allz[i], **class_models["CCL3"])
def ccl_test_distances.test_class_allz_distance_model_ccl4 ()
Definition at line 533 of file ccl_test_distances.py.
References compare_class_distances().
 def test_class_allz_distance_model_ccl4():
     i = 3
     compare_class_distances(z_class_allz, chi_class_allz[i], dm_class_allz[i], **class_models["CCL4"])
def ccl_test_distances.test_class_allz_distance_model_ccl5 ()
Definition at line 537 of file ccl_test_distances.py.
References compare_class_distances().
 def test_class_allz_distance_model_ccl5():
     i = 4
     compare_class_distances(z_class_allz, chi_class_allz[i], dm_class_allz[i], **class_models["CCL5"])
def ccl_test_distances.test_class_allz_distance_model_ccl7 ()
Definition at line 541 of file ccl_test_distances.py.
References compare_class_distances().
 def test_class_allz_distance_model_ccl7():
     i = 5
     compare_class_distances(z_class_allz, chi_class_allz[i], dm_class_allz[i], **class_models["CCL7"])
def ccl_test_distances.test_class_allz_distance_model_ccl8 ()
Definition at line 545 of file ccl_test_distances.py.
References compare_class_distances().
 def test_class_allz_distance_model_ccl8():
     i = 6
     compare_class_distances(z_class_allz, chi_class_allz[i], dm_class_allz[i], **class_models["CCL8"])
def ccl_test_distances.test_class_allz_distance_model_ccl9 ()
Definition at line 549 of file ccl_test_distances.py.
References compare_class_distances().
 def test_class_allz_distance_model_ccl9():
     i = 7
     compare_class_distances(z_class_allz, chi_class_allz[i], dm_class_allz[i], **class_models["CCL9"])
def ccl_test_distances.test_class_distance_model_flat_manynu1 ()
Definition at line 509 of file ccl_test_distances.py.
References compare_class_distances().
 def test_class_distance_model_flat_manynu1():
     i = 6
     compare_class_distances(z_class_mnu, chi_class_mnu[i], dm_class_mnu[i], **class_models["flat_manynu1"])
def ccl_test_distances.test_class_distance_model_flat_massnu1 ()
Definition at line 497 of file ccl_test_distances.py.
References compare_class_distances().
 def test_class_distance_model_flat_massnu1():
     i = 3
     compare_class_distances(z_class_mnu, chi_class_mnu[i], dm_class_mnu[i], **class_models["flat_massnu1"])
def ccl_test_distances.test_class_distance_model_flat_massnu2 ()
Definition at line 501 of file ccl_test_distances.py.
References compare_class_distances().
 def test_class_distance_model_flat_massnu2():
     i = 4
     compare_class_distances(z_class_mnu, chi_class_mnu[i], dm_class_mnu[i], **class_models["flat_massnu2"])
def ccl_test_distances.test_class_distance_model_flat_massnu3 ()
Definition at line 505 of file ccl_test_distances.py.
References compare_class_distances().
 def test_class_distance_model_flat_massnu3():
     i = 5
     compare_class_distances(z_class_mnu, chi_class_mnu[i], dm_class_mnu[i], **class_models["flat_massnu3"])
def ccl_test_distances.test_class_distance_model_flat_nonu ()
Definition at line 485 of file ccl_test_distances.py.
References compare_class_distances().
 def test_class_distance_model_flat_nonu():
     i = 0
     compare_class_distances(z_class_mnu, chi_class_mnu[i], dm_class_mnu[i], **class_models["flat_nonu"])
def ccl_test_distances.test_class_distance_model_neg_curv_massnu1 ()
Definition at line 513 of file ccl_test_distances.py.
References compare_class_distances().
 def test_class_distance_model_neg_curv_massnu1():
     i = 7
     compare_class_distances(z_class_mnu, chi_class_mnu[i], dm_class_mnu[i], **class_models["neg_curv_massnu1"])
def ccl_test_distances.test_class_distance_model_neg_curv_nonu ()
Definition at line 493 of file ccl_test_distances.py.
References compare_class_distances().
 def test_class_distance_model_neg_curv_nonu():
     i = 2
     compare_class_distances(z_class_mnu, chi_class_mnu[i], dm_class_mnu[i], **class_models["neg_curv_nonu"])
def ccl_test_distances.test_class_distance_model_pos_curv_massnu1 ()
Definition at line 517 of file ccl_test_distances.py.
References compare_class_distances().
 def test_class_distance_model_pos_curv_massnu1():
     i = 8
     compare_class_distances(z_class_mnu, chi_class_mnu[i], dm_class_mnu[i], **class_models["pos_curv_manynu1"])
def ccl_test_distances.test_class_distance_model_pos_curv_nonu ()
Definition at line 489 of file ccl_test_distances.py.
References compare_class_distances().
 def test_class_distance_model_pos_curv_nonu():
     i = 1
     compare_class_distances(z_class_mnu, chi_class_mnu[i], dm_class_mnu[i], **class_models["pos_curv_nonu"])
def ccl_test_distances.test_distance_hiz_model_0 ()
Definition at line 433 of file ccl_test_distances.py.
References compare_distances_hiz().
 def test_distance_hiz_model_0():
     i = 0
     compare_distances_hiz(zhi, chi_hiz[i], Omega_v_vals[i], w0_vals[i], wa_vals[i])
def ccl_test_distances.test_distance_hiz_model_1 ()
Definition at line 437 of file ccl_test_distances.py.
References compare_distances_hiz().
 def test_distance_hiz_model_1():
     i = 1
     compare_distances_hiz(zhi, chi_hiz[i], Omega_v_vals[i], w0_vals[i], wa_vals[i])
def ccl_test_distances.test_distance_hiz_model_2 ()
Definition at line 441 of file ccl_test_distances.py.
References compare_distances_hiz().
 def test_distance_hiz_model_2():
     i = 2
     compare_distances_hiz(zhi, chi_hiz[i], Omega_v_vals[i], w0_vals[i], wa_vals[i])
def ccl_test_distances.test_distance_mnu_hiz_model_0 ()
Definition at line 465 of file ccl_test_distances.py.
References compare_distances_mnu().
 def test_distance_mnu_hiz_model_0():
     i=0
     compare_distances_mnu(znuhi, chi_nu_hiz[i],dm_nu_hiz[i], Omega_v_vals[i], w0_vals[i], wa_vals[i], Neff, mnu[i])
def ccl_test_distances.test_distance_mnu_hiz_model_1 ()
Definition at line 469 of file ccl_test_distances.py.
References compare_distances_mnu().
 def test_distance_mnu_hiz_model_1():
     i=1
     compare_distances_mnu(znuhi, chi_nu_hiz[i],dm_nu_hiz[i], Omega_v_vals[i], w0_vals[i], wa_vals[i], Neff, mnu[i])
def ccl_test_distances.test_distance_mnu_hiz_model_2 ()
Definition at line 473 of file ccl_test_distances.py.
References compare_distances_mnu().
 def test_distance_mnu_hiz_model_2():
     i=2
     compare_distances_mnu(znuhi, chi_nu_hiz[i],dm_nu_hiz[i], Omega_v_vals[i], w0_vals[i], wa_vals[i], Neff, mnu[i])
def ccl_test_distances.test_distance_mnu_hiz_model_3 ()
Definition at line 477 of file ccl_test_distances.py.
References compare_distances_mnu().
 def test_distance_mnu_hiz_model_3():
     i=3
     compare_distances_mnu(znuhi, chi_nu_hiz[i],dm_nu_hiz[i], Omega_v_vals[i], w0_vals[i], wa_vals[i], Neff, mnu[i])
def ccl_test_distances.test_distance_mnu_hiz_model_4 ()
Definition at line 481 of file ccl_test_distances.py.
References compare_distances_mnu().
 def test_distance_mnu_hiz_model_4():
     i=4
     compare_distances_mnu(znuhi, chi_nu_hiz[i],dm_nu_hiz[i], Omega_v_vals[i], w0_vals[i], wa_vals[i], Neff, mnu[i])
def ccl_test_distances.test_distance_mnu_model_0 ()
Definition at line 445 of file ccl_test_distances.py.
References compare_distances_mnu().
 def test_distance_mnu_model_0():
     i=0
     compare_distances_mnu(znu, chi_nu[i],dm_nu[i], Omega_v_vals[i], w0_vals[i], wa_vals[i], Neff, mnu[i])
def ccl_test_distances.test_distance_mnu_model_1 ()
Definition at line 449 of file ccl_test_distances.py.
References compare_distances_mnu().
 def test_distance_mnu_model_1():
     i=1
     compare_distances_mnu(znu, chi_nu[i],dm_nu[i], Omega_v_vals[i], w0_vals[i], wa_vals[i], Neff, mnu[i])
def ccl_test_distances.test_distance_mnu_model_2 ()
Definition at line 453 of file ccl_test_distances.py.
References compare_distances_mnu().
 def test_distance_mnu_model_2():
     i=2
     compare_distances_mnu(znu, chi_nu[i],dm_nu[i], Omega_v_vals[i], w0_vals[i], wa_vals[i], Neff, mnu[i])
def ccl_test_distances.test_distance_mnu_model_3 ()
Definition at line 457 of file ccl_test_distances.py.
References compare_distances_mnu().
 def test_distance_mnu_model_3():
     i=3
     compare_distances_mnu(znu, chi_nu[i],dm_nu[i], Omega_v_vals[i], w0_vals[i], wa_vals[i], Neff, mnu[i])
def ccl_test_distances.test_distance_mnu_model_4 ()
Definition at line 461 of file ccl_test_distances.py.
References compare_distances_mnu().
 def test_distance_mnu_model_4():
     i=4
     compare_distances_mnu(znu, chi_nu[i],dm_nu[i], Omega_v_vals[i], w0_vals[i], wa_vals[i], Neff, mnu[i])
def ccl_test_distances.test_distance_model_0 ()
Definition at line 413 of file ccl_test_distances.py.
References compare_distances().
 def test_distance_model_0():
     i = 0
     compare_distances(z, chi[i],dm[i], Omega_v_vals[i], w0_vals[i], wa_vals[i])
def ccl_test_distances.test_distance_model_1 ()
Definition at line 417 of file ccl_test_distances.py.
References compare_distances().
 def test_distance_model_1():
     i = 1
     compare_distances(z, chi[i],dm[i], Omega_v_vals[i], w0_vals[i], wa_vals[i])
def ccl_test_distances.test_distance_model_2 ()
Definition at line 421 of file ccl_test_distances.py.
References compare_distances().
 def test_distance_model_2():
     i = 2
     compare_distances(z, chi[i],dm[i], Omega_v_vals[i], w0_vals[i], wa_vals[i])
def ccl_test_distances.test_distance_model_3 ()
Definition at line 425 of file ccl_test_distances.py.
References compare_distances().
 def test_distance_model_3():
     i = 3
     compare_distances(z, chi[i],dm[i], Omega_v_vals[i], w0_vals[i], wa_vals[i])
def ccl_test_distances.test_distance_model_4 ()
Definition at line 429 of file ccl_test_distances.py.
References compare_distances().
 def test_distance_model_4():
     i = 4
     compare_distances(z, chi[i],dm[i], Omega_v_vals[i], w0_vals[i], wa_vals[i])
Variable Documentation
float ccl_test_distances.A_s = 2.1e-9
Definition at line 23 of file ccl_test_distances.py.
Referenced by ccl_parameters_read_yaml(), ccl_parameters_write_yaml(), and main().
dictionary ccl_test_distances.class_models
Definition at line 46 of file ccl_test_distances.py.
int ccl_test_distances.DISTANCES_TOLERANCE = 1
Definition at line 8 of file ccl_test_distances.py.
int ccl_test_distances.DISTANCES_TOLERANCE_CLASS = 1
Definition at line 16 of file ccl_test_distances.py.
int ccl_test_distances.DISTANCES_TOLERANCE_MNU = 1
Definition at line 13 of file ccl_test_distances.py.
float ccl_test_distances.h = 0.7
Definition at line 22 of file ccl_test_distances.py.
Referenced by __attribute__(), MultiGridSolver< NDIM, T >.calculate_residual(), ccl_parameters_create(), ccl_parameters_read_yaml(), ccl_parameters_write_yaml(), anonymous_namespace{chameleon.cpp}::ChiSolver< T >.correct_sol(), dfzero(), PoissonSolver< NDIM, T >.dl_operator(), ContinuitySolver< NDIM, T >.dl_operator(), FofrSolver< NDIM, T >.dl_operator(), MultiGridSolver< NDIM, T >.dl_operator(), anonymous_namespace{chameleon.cpp}::ChiSolver< T >.dl_operator(), f_dens(), f_IA_NLA(), f_rsd(), MultiGridSolver< NDIM, T >.GaussSeidelSweep(), MultiGridSolver< 3, T >.get_multigrid_source(), integrand_mag(), integrand_wl(), integrand_wm(), PoissonSolver< NDIM, T >.l_operator(), ContinuitySolver< NDIM, T >.l_operator(), FofrSolver< NDIM, T >.l_operator(), MultiGridSolver< NDIM, T >.l_operator(), anonymous_namespace{chameleon.cpp}::ChiSolver< T >.l_operator(), main(), MultiGridSolver< NDIM, T >.make_new_source(), nlohmann::detail::dtoa_impl::diyfp.mul(), std::hash< nlohmann::json >.operator()(), TEST_CASE(), transfer_dens(), transfer_isw(), and write_Pk_CLASS().
list ccl_test_distances.mnu
Initial value:
 = [
     [0.04, 0., 0.], [0.05, 0.01, 0.], [0.03, 0.02, 0.04], [0.05, 0., 0.],
     [0.03, 0.02, 0.]]
Definition at line 32 of file ccl_test_distances.py.
Referenced by __attribute__(), ccl_cosmology_create_flat_lcdm(), ccl_nu_masses(), ccl_parameters_create(), ccl_parameters_create_flat_lcdm(), ccl_parameters_read_yaml(), and main().
float ccl_test_distances.n_s = 0.96
Definition at line 24 of file ccl_test_distances.py.
Referenced by __attribute__(), ccl_parameters_create(), ccl_parameters_read_yaml(), ccl_parameters_write_yaml(), main(), and write_Pk_CLASS().
int ccl_test_distances.Neff = 0
Definition at line 25 of file ccl_test_distances.py.
Referenced by __attribute__(), ccl_cosmology_create_flat_lcdm(), ccl_parameters_create(), ccl_parameters_create_flat_lcdm(), ccl_parameters_read_yaml(), ccl_parameters_write_yaml(), and main().
float ccl_test_distances.Neff_mnu = 3.0
Definition at line 38 of file ccl_test_distances.py.
float ccl_test_distances.Omega_b = 0.05
Definition at line 21 of file ccl_test_distances.py.
Referenced by __attribute__(), ccl_parameters_create(), ccl_parameters_read_yaml(), ccl_parameters_write_yaml(), main(), and write_Pk_CLASS().
float ccl_test_distances.Omega_c = 0.25
Definition at line 20 of file ccl_test_distances.py.
Referenced by __attribute__(), ccl_parameters_create(), ccl_parameters_fill_initial(), ccl_parameters_read_yaml(), ccl_parameters_write_yaml(), main(), and write_Pk_CLASS().
ccl_test_distances.Omega_v_vals = np.array([0.7, 0.7, 0.7, 0.65, 0.75])
Definition at line 28 of file ccl_test_distances.py.
ccl_test_distances.path = dirname(abspath(__file__))
Definition at line 114 of file ccl_test_distances.py.
Referenced by create_dir(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >.diff(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >.patch(), remove_all_files(), remove_dir(), and std_out_dir().
ccl_test_distances.w0_vals = np.array([-1.0, -0.9, -0.9, -0.9, -0.9])
Definition at line 29 of file ccl_test_distances.py.
ccl_test_distances.wa_vals = np.array([0.0, 0.0, 0.1, 0.1, 0.1])
Definition at line 30 of file ccl_test_distances.py.