var namespaceCatch =
[
    [ "Detail", "namespaceCatch_1_1Detail.html", "namespaceCatch_1_1Detail" ],
    [ "Generators", "namespaceCatch_1_1Generators.html", "namespaceCatch_1_1Generators" ],
    [ "Matchers", "namespaceCatch_1_1Matchers.html", "namespaceCatch_1_1Matchers" ],
    [ "AssertionHandler", "classCatch_1_1AssertionHandler.html", "classCatch_1_1AssertionHandler" ],
    [ "AssertionInfo", "structCatch_1_1AssertionInfo.html", "structCatch_1_1AssertionInfo" ],
    [ "AssertionReaction", "structCatch_1_1AssertionReaction.html", "structCatch_1_1AssertionReaction" ],
    [ "AutoReg", "structCatch_1_1AutoReg.html", "structCatch_1_1AutoReg" ],
    [ "BenchmarkLooper", "classCatch_1_1BenchmarkLooper.html", "classCatch_1_1BenchmarkLooper" ],
    [ "BinaryExpr", "classCatch_1_1BinaryExpr.html", "classCatch_1_1BinaryExpr" ],
    [ "Capturer", "classCatch_1_1Capturer.html", "classCatch_1_1Capturer" ],
    [ "CaseSensitive", "structCatch_1_1CaseSensitive.html", "structCatch_1_1CaseSensitive" ],
    [ "Counts", "structCatch_1_1Counts.html", "structCatch_1_1Counts" ],
    [ "Decomposer", "structCatch_1_1Decomposer.html", "structCatch_1_1Decomposer" ],
    [ "ExceptionTranslatorRegistrar", "classCatch_1_1ExceptionTranslatorRegistrar.html", "classCatch_1_1ExceptionTranslatorRegistrar" ],
    [ "ExprLhs", "classCatch_1_1ExprLhs.html", "classCatch_1_1ExprLhs" ],
    [ "IExceptionTranslator", "structCatch_1_1IExceptionTranslator.html", "structCatch_1_1IExceptionTranslator" ],
    [ "IExceptionTranslatorRegistry", "structCatch_1_1IExceptionTranslatorRegistry.html", "structCatch_1_1IExceptionTranslatorRegistry" ],
    [ "IGeneratorTracker", "structCatch_1_1IGeneratorTracker.html", "structCatch_1_1IGeneratorTracker" ],
    [ "IMutableRegistryHub", "structCatch_1_1IMutableRegistryHub.html", "structCatch_1_1IMutableRegistryHub" ],
    [ "IRegistryHub", "structCatch_1_1IRegistryHub.html", "structCatch_1_1IRegistryHub" ],
    [ "IResultCapture", "structCatch_1_1IResultCapture.html", "structCatch_1_1IResultCapture" ],
    [ "IRunner", "structCatch_1_1IRunner.html", "structCatch_1_1IRunner" ],
    [ "is_range", "structCatch_1_1is__range.html", "structCatch_1_1is__range" ],
    [ "IStream", "structCatch_1_1IStream.html", "structCatch_1_1IStream" ],
    [ "ITestCaseRegistry", "structCatch_1_1ITestCaseRegistry.html", "structCatch_1_1ITestCaseRegistry" ],
    [ "ITestInvoker", "structCatch_1_1ITestInvoker.html", "structCatch_1_1ITestInvoker" ],
    [ "ITransientExpression", "structCatch_1_1ITransientExpression.html", "structCatch_1_1ITransientExpression" ],
    [ "LazyExpression", "classCatch_1_1LazyExpression.html", "classCatch_1_1LazyExpression" ],
    [ "MatchExpr", "classCatch_1_1MatchExpr.html", "classCatch_1_1MatchExpr" ],
    [ "MessageBuilder", "structCatch_1_1MessageBuilder.html", "structCatch_1_1MessageBuilder" ],
    [ "MessageInfo", "structCatch_1_1MessageInfo.html", "structCatch_1_1MessageInfo" ],
    [ "MessageStream", "structCatch_1_1MessageStream.html", "structCatch_1_1MessageStream" ],
    [ "NameAndTags", "structCatch_1_1NameAndTags.html", "structCatch_1_1NameAndTags" ],
    [ "NonCopyable", "classCatch_1_1NonCopyable.html", "classCatch_1_1NonCopyable" ],
    [ "not_this_one", "structCatch_1_1not__this__one.html", null ],
    [ "pluralise", "structCatch_1_1pluralise.html", "structCatch_1_1pluralise" ],
    [ "RegistrarForTagAliases", "structCatch_1_1RegistrarForTagAliases.html", "structCatch_1_1RegistrarForTagAliases" ],
    [ "ResultDisposition", "structCatch_1_1ResultDisposition.html", "structCatch_1_1ResultDisposition" ],
    [ "ResultWas", "structCatch_1_1ResultWas.html", "structCatch_1_1ResultWas" ],
    [ "ReusableStringStream", "classCatch_1_1ReusableStringStream.html", "classCatch_1_1ReusableStringStream" ],
    [ "ScopedMessage", "classCatch_1_1ScopedMessage.html", "classCatch_1_1ScopedMessage" ],
    [ "Section", "classCatch_1_1Section.html", "classCatch_1_1Section" ],
    [ "SectionEndInfo", "structCatch_1_1SectionEndInfo.html", "structCatch_1_1SectionEndInfo" ],
    [ "SectionInfo", "structCatch_1_1SectionInfo.html", "structCatch_1_1SectionInfo" ],
    [ "SourceLineInfo", "structCatch_1_1SourceLineInfo.html", "structCatch_1_1SourceLineInfo" ],
    [ "StreamEndStop", "structCatch_1_1StreamEndStop.html", "structCatch_1_1StreamEndStop" ],
    [ "StringMaker", "structCatch_1_1StringMaker.html", "structCatch_1_1StringMaker" ],
    [ "StringMaker< bool >", "structCatch_1_1StringMaker_3_01bool_01_4.html", "structCatch_1_1StringMaker_3_01bool_01_4" ],
    [ "StringMaker< Catch::Detail::Approx >", "structCatch_1_1StringMaker_3_01Catch_1_1Detail_1_1Approx_01_4.html", "structCatch_1_1StringMaker_3_01Catch_1_1Detail_1_1Approx_01_4" ],
    [ "StringMaker< char * >", "structCatch_1_1StringMaker_3_01char_01_5_01_4.html", "structCatch_1_1StringMaker_3_01char_01_5_01_4" ],
    [ "StringMaker< char >", "structCatch_1_1StringMaker_3_01char_01_4.html", "structCatch_1_1StringMaker_3_01char_01_4" ],
    [ "StringMaker< char const * >", "structCatch_1_1StringMaker_3_01char_01const_01_5_01_4.html", "structCatch_1_1StringMaker_3_01char_01const_01_5_01_4" ],
    [ "StringMaker< char[SZ]>", "structCatch_1_1StringMaker_3_01char[SZ]_4.html", "structCatch_1_1StringMaker_3_01char[SZ]_4" ],
    [ "StringMaker< double >", "structCatch_1_1StringMaker_3_01double_01_4.html", "structCatch_1_1StringMaker_3_01double_01_4" ],
    [ "StringMaker< float >", "structCatch_1_1StringMaker_3_01float_01_4.html", "structCatch_1_1StringMaker_3_01float_01_4" ],
    [ "StringMaker< int >", "structCatch_1_1StringMaker_3_01int_01_4.html", "structCatch_1_1StringMaker_3_01int_01_4" ],
    [ "StringMaker< long >", "structCatch_1_1StringMaker_3_01long_01_4.html", "structCatch_1_1StringMaker_3_01long_01_4" ],
    [ "StringMaker< long long >", "structCatch_1_1StringMaker_3_01long_01long_01_4.html", "structCatch_1_1StringMaker_3_01long_01long_01_4" ],
    [ "StringMaker< R C::* >", "structCatch_1_1StringMaker_3_01R_01C_1_1_5_01_4.html", "structCatch_1_1StringMaker_3_01R_01C_1_1_5_01_4" ],
    [ "StringMaker< R, typename std::enable_if< is_range< R >::value &&!::Catch::Detail::IsStreamInsertable< R >::value >::type >", "structCatch_1_1StringMaker_3_01R_00_01typename_01std_1_1enable__if_3_01is__range_3_01R_01_4_1_1ve8233c20b54b69b4771fbd413409d181.html", "structCatch_1_1StringMaker_3_01R_00_01typename_01std_1_1enable__if_3_01is__range_3_01R_01_4_1_1ve8233c20b54b69b4771fbd413409d181" ],
    [ "StringMaker< signed char >", "structCatch_1_1StringMaker_3_01signed_01char_01_4.html", "structCatch_1_1StringMaker_3_01signed_01char_01_4" ],
    [ "StringMaker< signed char[SZ]>", "structCatch_1_1StringMaker_3_01signed_01char[SZ]_4.html", "structCatch_1_1StringMaker_3_01signed_01char[SZ]_4" ],
    [ "StringMaker< std::nullptr_t >", "structCatch_1_1StringMaker_3_01std_1_1nullptr__t_01_4.html", "structCatch_1_1StringMaker_3_01std_1_1nullptr__t_01_4" ],
    [ "StringMaker< std::string >", "structCatch_1_1StringMaker_3_01std_1_1string_01_4.html", "structCatch_1_1StringMaker_3_01std_1_1string_01_4" ],
    [ "StringMaker< std::wstring >", "structCatch_1_1StringMaker_3_01std_1_1wstring_01_4.html", "structCatch_1_1StringMaker_3_01std_1_1wstring_01_4" ],
    [ "StringMaker< T * >", "structCatch_1_1StringMaker_3_01T_01_5_01_4.html", "structCatch_1_1StringMaker_3_01T_01_5_01_4" ],
    [ "StringMaker< T[SZ]>", "structCatch_1_1StringMaker_3_01T[SZ]_4.html", "structCatch_1_1StringMaker_3_01T[SZ]_4" ],
    [ "StringMaker< unsigned char >", "structCatch_1_1StringMaker_3_01unsigned_01char_01_4.html", "structCatch_1_1StringMaker_3_01unsigned_01char_01_4" ],
    [ "StringMaker< unsigned char[SZ]>", "structCatch_1_1StringMaker_3_01unsigned_01char[SZ]_4.html", "structCatch_1_1StringMaker_3_01unsigned_01char[SZ]_4" ],
    [ "StringMaker< unsigned int >", "structCatch_1_1StringMaker_3_01unsigned_01int_01_4.html", "structCatch_1_1StringMaker_3_01unsigned_01int_01_4" ],
    [ "StringMaker< unsigned long >", "structCatch_1_1StringMaker_3_01unsigned_01long_01_4.html", "structCatch_1_1StringMaker_3_01unsigned_01long_01_4" ],
    [ "StringMaker< unsigned long long >", "structCatch_1_1StringMaker_3_01unsigned_01long_01long_01_4.html", "structCatch_1_1StringMaker_3_01unsigned_01long_01long_01_4" ],
    [ "StringMaker< wchar_t * >", "structCatch_1_1StringMaker_3_01wchar__t_01_5_01_4.html", "structCatch_1_1StringMaker_3_01wchar__t_01_5_01_4" ],
    [ "StringMaker< wchar_t const * >", "structCatch_1_1StringMaker_3_01wchar__t_01const_01_5_01_4.html", "structCatch_1_1StringMaker_3_01wchar__t_01const_01_5_01_4" ],
    [ "StringRef", "classCatch_1_1StringRef.html", "classCatch_1_1StringRef" ],
    [ "TestCase", "classCatch_1_1TestCase.html", "classCatch_1_1TestCase" ],
    [ "TestCaseInfo", "structCatch_1_1TestCaseInfo.html", "structCatch_1_1TestCaseInfo" ],
    [ "TestFailureException", "structCatch_1_1TestFailureException.html", null ],
    [ "TestInvokerAsMethod", "classCatch_1_1TestInvokerAsMethod.html", "classCatch_1_1TestInvokerAsMethod" ],
    [ "Timer", "classCatch_1_1Timer.html", "classCatch_1_1Timer" ],
    [ "Totals", "structCatch_1_1Totals.html", "structCatch_1_1Totals" ],
    [ "UnaryExpr", "classCatch_1_1UnaryExpr.html", "classCatch_1_1UnaryExpr" ]
];