Fast Methods for Cosmological Simulations: anonymous_namespace{mod_frozen_potential.cpp} Namespace Reference
anonymous_namespace{mod_frozen_potential.cpp} Namespace Reference
Classes
class LinkedList
class handling linked lists
Functions
double force_ref (const double r, const double a)
double force_tot (const double r, const double e2)
void force_short (const Sim_Param &sim, const double D, const LinkedList &linked_list, const std::vector< Particle_v< double >> &particles, const Vec_3D< double > &position, Vec_3D< double > &force, Interp_obj &fs_interp)
void kick_step_w_pp (const Sim_Param &sim, const double a, const double da, std::vector< Particle_v< double >> &particles, const std::vector< Mesh > &force_field, LinkedList &linked_list, Interp_obj &fs_interp)
Function Documentation
double anonymous_namespace{mod_frozen_potential.cpp}::force_ref (const double r, const double a)
Definition at line 46 of file mod_frozen_potential.cpp.
References pow(), and z.
Referenced by force_short(), and App_Var_FP_mod::FP_ppImpl::FP_ppImpl().
{
     // Reference force for an S_2-shaped particle
     FTYPE_t z = 2 * r / a;
     if (z > 2) return 1 / (r*r);
     else if (z > 1) return (12 / (z*z) - 224 + 896 * z - 840 * z*z + 224 * pow(z, 3) +
                             70 * pow(z, 4) - 48 * pow(z, 5) + 7 * pow(z, 6)) / (35 * a*a);
     else return (224 * z - 224 * pow(z, 3) + 70 * pow(z, 4) + 48 * pow(z, 5) - 21 * pow(z, 7)) / (35 * a*a);
 }
void anonymous_namespace{mod_frozen_potential.cpp}::force_short (const Sim_Param & sim, const double D, const LinkedList & linked_list, const std::vector< Particle_v< double >> & particles, const Vec_3D< double > & position, Vec_3D< double > & force, Interp_obj & fs_interp)
Definition at line 59 of file mod_frozen_potential.cpp.
References App_Opt::a, Sim_Param::app_opt, Sim_Param::box_opt, force_ref(), force_tot(), get_sgn_distance(), App_Opt::Hc, anonymous_namespace{mod_frozen_potential.cpp}::LinkedList::HOC, IT< points >::iter(), anonymous_namespace{mod_frozen_potential.cpp}::LinkedList::LL, m, Box_Opt::mesh_num, Box_Opt::Ng, p, PI, pow(), pow2(), App_Opt::rs, sqrt(), and IT< points >::vec.
Referenced by kick_step_w_pp().
 {   // Calculate short range force in position, force is added
     #define FORCE_SHORT_NO_INTER
     size_t p;
     Vec_3D<FTYPE_t> dr_vec;
     FTYPE_t dr2;
     FTYPE_t dr; // <-- #ifdef FORCE_SHORT_NO_INTER
     const FTYPE_t m = pow((FTYPE_t)sim.box_opt.Ng, 3) / D;
     const size_t Nm = sim.box_opt.mesh_num;
     const FTYPE_t rs2 = pow2(sim.app_opt.rs);
     const FTYPE_t e2 = pow2(sim.box_opt.Ng*0.1); // <-- #ifdef FORCE_SHORT_NO_INTER
     IT<3> it(position, sim.app_opt.Hc);
     do{
         p = linked_list.HOC(it.vec);
         while (p != -1){
             dr_vec = get_sgn_distance(particles[p].position, position, Nm);
             dr2 = dr_vec.norm2();
             if ((dr2 < rs2) && (dr2 != 0)) // Short range force is set 0 for separation larger than cutoff radius
             {
                 #ifdef FORCE_SHORT_NO_INTER
                 dr = sqrt(dr2);
                 force += dr_vec*(force_tot(dr, e2) - force_ref(dr, sim.app_opt.a))*m/(dr*4*PI);
                 #else
                 force += dr_vec*(m/sqrt(dr2)*fs_interp.eval(dr2));
                 #endif
             }
             p = linked_list.LL[p];
         }
     } while( it.iter() );
 }
double anonymous_namespace{mod_frozen_potential.cpp}::force_tot (const double r, const double e2)
Definition at line 55 of file mod_frozen_potential.cpp.
Referenced by force_short(), and App_Var_FP_mod::FP_ppImpl::FP_ppImpl().
{
     return 1 / (r*r+e2);
 }
void anonymous_namespace{mod_frozen_potential.cpp}::kick_step_w_pp (const Sim_Param & sim, const double a, const double da, std::vector< Particle_v< double >> & particles, const std::vector< Mesh > & force_field, LinkedList & linked_list, Interp_obj & fs_interp)
Definition at line 92 of file mod_frozen_potential.cpp.
References assign_from(), Sim_Param::cosmo, force_short(), anonymous_namespace{mod_frozen_potential.cpp}::LinkedList::get_linked_list(), growth_allz::growth_factor, Cosmo_Param::Omega_L(), Cosmo_Param::Omega_m, and pow().
Referenced by App_Var_FP_mod::upd_pos().
 {    // 2nd order ODE with long & short range potential
     const size_t Np = particles.size();
     Vec_3D<FTYPE_t> force;
     const FTYPE_t D = growth_factor(a, sim.cosmo);
     const FTYPE_t OL = sim.cosmo.Omega_L()*pow(a,3);
     const FTYPE_t Om = sim.cosmo.Omega_m;
     // -3/2a represents usual EOM, the rest are LCDM corrections
     const FTYPE_t f1 = 3/(2*a)*(Om+2*OL)/(Om+OL);
     const FTYPE_t f2 = 3/(2*a)*Om/(Om+OL)*D/a;
     BOOST_LOG_TRIVIAL(debug) << "Creating linked list...";
     linked_list.get_linked_list(particles);
     BOOST_LOG_TRIVIAL(debug) << "Computing short and long range parts of the potential...";
     #pragma omp parallel for private(force)
     for (size_t i = 0; i < Np; i++)
     {
         force.fill(0.);
         assign_from(force_field, particles[i].position, force); // long-range force
         force_short(sim, D, linked_list, particles, particles[i].position, force, fs_interp); // short range force
         force = force*f2 - particles[i].velocity*f1;
         particles[i].velocity += force*da;
     }
 }