Fast Methods for Cosmological Simulations: anonymous_namespace{core_power.cpp} Namespace Reference
anonymous_namespace{core_power.cpp} Namespace Reference
Classes
class Integr_obj
basic integration object, wrapper for GSL integration functions
class Integr_obj_qag
QAG adaptive integration.
class Integr_obj_qagiu
QAGI adaptive integration on infinite intervals.
class Integr_obj_qawf
QAWF adaptive integration for Fourier integrals.
class Integr_obj_qawo
QAWO adaptive integration for oscillatory functions.
struct integrand_param
general integrand with callable function and one parameter
class ODE_Solver
: Explicit embedded Runge-Kutta Prince-Dormand (8, 9) method.
Functions
template<typename T >
T hubble_param (T a, const Cosmo_Param &cosmo)
double growth_factor_integrand (double a, void *params)
double growth_factor (double a, void *params)
double ln_growth_factor (double log_a, void *parameters)
template<typename T >
size_t get_nearest (const T val, const std::vector< T > &vec)
template<class P >
double xi_integrand_W (double k, void *params)
integrand for correlation function when weight-function 'sin(kr)' is used in integration
template<class P >
double xi_integrand_G (double k, void *params)
integrand for correlation function when non-weighted integration is used
template<class P >
double sigma_integrand_G (double k, void *params)
integrand for amplitude of mass fluctuaton when non-weighted integration is used
template<class P , class T >
void gen_fce_r_binned_gsl (const double x_min, const double x_max, const double lin_bin, const P &P_k, Data_Vec< double, 2 > &fce_binned, T &fce_r)
compute given function in linear range and store results
template<class P , class T >
void gen_corr_func_binned_gsl (const Sim_Param &sim, const P &P_k, Data_Vec< double, 2 > &corr_func_binned, T &xi_r)
compute correlation function and store results
template<class P , class T >
void gen_sigma_func_binned_gsl (const Sim_Param &sim, const P &P_k, Data_Vec< double, 2 > &sigma_binned, T &sigma_r)
compute amplitude of density fluctuation and store results
Variables
constexpr double GSL_EPSABS = 1e-7
absolute error at z = 0, scales for higher redshifts
constexpr size_t GSL_LIMIT = 1000
max. number of subintervals for adaptive integration
constexpr size_t GSL_N = 100
max. number of bisections of integration interval (QAWO / QAWF)
Detailed Description
PRIVATE FUNCTIONS DEFINITIONS *
Function Documentation
template<class P , class T > void anonymous_namespace{core_power.cpp}::gen_corr_func_binned_gsl (const Sim_Param & sim, const P & P_k, Data_Vec< double, 2 > & corr_func_binned, T & xi_r)
compute correlation function and store results
Template Parameters
P callable object with 'operator()(double)'
T callable object with 'operator()(double)'
Parameters
sim simulation parameters
P_k power spectrum (callable)
corr_func_binned object to store binned correlation function
xi_r correlation function at given r (callable)
Definition at line 362 of file core_power.cpp.
References gen_fce_r_binned_gsl(), Range::lower, Sim_Param::other_par, Sim_Param::out_opt, Out_Opt::points_per_10_Mpc, Range::upper, and Other_par::x_corr.
Referenced by gen_corr_func_binned_gsl_qawf().
 {
     const double x_min = sim.other_par.x_corr.lower;
     const double x_max = sim.other_par.x_corr.upper;
     const double lin_bin = 10./sim.out_opt.points_per_10_Mpc;
     gen_fce_r_binned_gsl(x_min, x_max, lin_bin, P_k, corr_func_binned, xi_r);
 }
template<class P , class T > void anonymous_namespace{core_power.cpp}::gen_fce_r_binned_gsl (const double x_min, const double x_max, const double lin_bin, const P & P_k, Data_Vec< double, 2 > & fce_binned, T & fce_r)
compute given function in linear range and store results
Template Parameters
P callable object with 'operator()(double)'
T callable object with 'operator()(double)'
Parameters
x_min starting radius of function evaluation
x_max last radius of function evaluation
lin_bin linear step between function evaluations
P_k power spectrum (callable)
fce_binned object to store binned function
fce_r callable function
Definition at line 335 of file core_power.cpp.
References anonymous_namespace{core_power.cpp}::integrand_param< P >::r, and Data_Vec< T, N >::resize().
Referenced by gen_corr_func_binned_gsl(), and gen_sigma_func_binned_gsl().
 {
     const size_t req_size = (size_t)ceil((x_max - x_min)/lin_bin);
     fce_binned.resize(req_size);
     integrand_param<P> my_param(0, P_k);
     for(size_t i = 0; i < req_size; i++){
         double r = x_min + i*lin_bin;
         my_param.r = r;
         fce_binned[0][i] = r;
         fce_binned[1][i] = fce_r(r, &my_param);
     }
 }
template<class P , class T > void anonymous_namespace{core_power.cpp}::gen_sigma_func_binned_gsl (const Sim_Param & sim, const P & P_k, Data_Vec< double, 2 > & sigma_binned, T & sigma_r)
compute amplitude of density fluctuation and store results
Template Parameters
P callable object with 'operator()(double)'
T callable object with 'operator()(double)'
Parameters
sim simulation parameters
P_k power spectrum (callable)
sigma_binned object to store binned amplitude of density fluctuation
sigma_r amplitude of density fluctuation at given r (callable)
Definition at line 382 of file core_power.cpp.
References gen_fce_r_binned_gsl(), Range::lower, Sim_Param::other_par, Sim_Param::out_opt, Out_Opt::points_per_10_Mpc, Range::upper, and Other_par::x_corr.
Referenced by gen_sigma_binned_gsl_qawf().
 {
     const double x_min = sim.other_par.x_corr.lower;
     const double x_max = sim.other_par.x_corr.upper;
     const double lin_bin = 10./sim.out_opt.points_per_10_Mpc;
     gen_fce_r_binned_gsl(x_min, x_max, lin_bin, P_k, sigma_binned, sigma_r);
 }
template<typename T > size_t anonymous_namespace{core_power.cpp}::get_nearest (const T val, const std::vector< T > & vec)
Definition at line 260 of file core_power.cpp.
 {   // assume data in 'vec' are ordered, vec[0] < vec[1] < ...
     return lower_bound(vec.begin(), vec.end(), val) - vec.begin();
 }
double anonymous_namespace{core_power.cpp}::growth_factor (double a, void * params)
Definition at line 249 of file core_power.cpp.
References growth_factor().
 {
     return growth_factor(a, *static_cast<const Cosmo_Param*>(params));
 }
double anonymous_namespace{core_power.cpp}::growth_factor_integrand (double a, void * params)
Definition at line 244 of file core_power.cpp.
References hubble_param(), and pow().
Referenced by growth_factor(), and norm_growth_factor().
 {
     return pow(a*hubble_param(a, *static_cast<const Cosmo_Param*>(params)), -3);
 }
template<typename T > T anonymous_namespace{core_power.cpp}::hubble_param (T a, const Cosmo_Param & cosmo)
Definition at line 239 of file core_power.cpp.
References Cosmo_Param::Omega_L(), Cosmo_Param::Omega_m, pow(), and sqrt().
Referenced by growth_factor(), and growth_factor_integrand().
 {   // hubble normalize to H(a = 1) == 1
     return sqrt(cosmo.Omega_m/pow(a, 3) + cosmo.Omega_L());
 }
double anonymous_namespace{core_power.cpp}::ln_growth_factor (double log_a, void * parameters)
Definition at line 254 of file core_power.cpp.
References growth_factor().
Referenced by growth_rate().
 {
     return log(growth_factor(exp(log_a), parameters));
 }
template<class P > double anonymous_namespace{core_power.cpp}::sigma_integrand_G (double k, void * params)
integrand for amplitude of mass fluctuaton when non-weighted integration is used
Template Parameters
P
Parameters
k
params
Returns
double
Definition at line 307 of file core_power.cpp.
References anonymous_namespace{core_power.cpp}::integrand_param< P >::P_k, PI, anonymous_namespace{core_power.cpp}::integrand_param< P >::r, and w.
{
     integrand_param<P>* my_par = (integrand_param<P>*) params;
     const double kr = k*my_par->r;
     const double w = kr < 0.1 ?
         1.-0.1*kr*kr+0.003571429*kr*kr*kr*kr
         -6.61376E-5*kr*kr*kr*kr*kr*kr
         +7.51563E-7*kr*kr*kr*kr*kr*kr*kr*kr
         :
         3.*(sin(kr) - kr*cos(kr))/(kr*kr*kr);
     const P& P_k = my_par->P_k;
     return 1/(2*PI*PI)*k*k*w*w*P_k(k);
 };
template<class P > double anonymous_namespace{core_power.cpp}::xi_integrand_G (double k, void * params)
integrand for correlation function when non-weighted integration is used
Template Parameters
P callable object with 'operator()(double)'
Parameters
k
params
Returns
double
Definition at line 290 of file core_power.cpp.
References anonymous_namespace{core_power.cpp}::integrand_param< P >::P_k, PI, and anonymous_namespace{core_power.cpp}::integrand_param< P >::r.
{
     integrand_param<P>* my_par = (integrand_param<P>*) params;
     const double kr = k*my_par->r;
     double j0 = kr < 1e-6 ? 1 - kr*kr/6. : sin(kr) / (kr);
     const P& P_k = my_par->P_k;
     return 1/(2*PI*PI)*k*k*j0*P_k(k);
 };
template<class P > double anonymous_namespace{core_power.cpp}::xi_integrand_W (double k, void * params)
integrand for correlation function when weight-function 'sin(kr)' is used in integration
Template Parameters
P callable object with 'operator()(double)'
Parameters
k
params
Returns
double
Definition at line 274 of file core_power.cpp.
References anonymous_namespace{core_power.cpp}::integrand_param< P >::P_k, PI, and anonymous_namespace{core_power.cpp}::integrand_param< P >::r.
{
     integrand_param<P>* my_par = (integrand_param<P>*) params;
     const double r = my_par->r;
     const P& P_k = my_par->P_k;
     return 1/(2*PI*PI)*k/r*P_k(k);
 };
Variable Documentation
constexpr double anonymous_namespace{core_power.cpp}::GSL_EPSABS = 1e-7
absolute error at z = 0, scales for higher redshifts
Definition at line 390 of file core_power.cpp.
Referenced by get_gsl_error().
constexpr size_t anonymous_namespace{core_power.cpp}::GSL_LIMIT = 1000
max. number of subintervals for adaptive integration
Definition at line 391 of file core_power.cpp.
Referenced by gen_corr_func_binned_gsl_qawf(), and gen_sigma_binned_gsl_qawf().
constexpr size_t anonymous_namespace{core_power.cpp}::GSL_N = 100
max. number of bisections of integration interval (QAWO / QAWF)
Definition at line 392 of file core_power.cpp.
Referenced by gen_corr_func_binned_gsl_qawf(), and gen_sigma_binned_gsl_qawf().