var namespacenlohmann_1_1detail =
[
    [ "dtoa_impl", "namespacenlohmann_1_1detail_1_1dtoa__impl.html", "namespacenlohmann_1_1detail_1_1dtoa__impl" ],
    [ "binary_reader", "classnlohmann_1_1detail_1_1binary__reader.html", "classnlohmann_1_1detail_1_1binary__reader" ],
    [ "binary_writer", "classnlohmann_1_1detail_1_1binary__writer.html", "classnlohmann_1_1detail_1_1binary__writer" ],
    [ "detector", "structnlohmann_1_1detail_1_1detector.html", "structnlohmann_1_1detail_1_1detector" ],
    [ "detector< Default, void_t< Op< Args... > >, Op, Args... >", "structnlohmann_1_1detail_1_1detector_3_01Default_00_01void__t_3_01Op_3_01Args_8_8_8_01_4_01_4_00_01Op_00_01Args_8_8_8_01_4.html", "structnlohmann_1_1detail_1_1detector_3_01Default_00_01void__t_3_01Op_3_01Args_8_8_8_01_4_01_4_00_01Op_00_01Args_8_8_8_01_4" ],
    [ "exception", "classnlohmann_1_1detail_1_1exception.html", "classnlohmann_1_1detail_1_1exception" ],
    [ "external_constructor", "structnlohmann_1_1detail_1_1external__constructor.html", null ],
    [ "external_constructor< value_t::array >", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1array_01_4.html", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1array_01_4" ],
    [ "external_constructor< value_t::boolean >", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1boolean_01_4.html", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1boolean_01_4" ],
    [ "external_constructor< value_t::number_float >", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1number__float_01_4.html", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1number__float_01_4" ],
    [ "external_constructor< value_t::number_integer >", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1number__integer_01_4.html", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1number__integer_01_4" ],
    [ "external_constructor< value_t::number_unsigned >", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1number__unsigned_01_4.html", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1number__unsigned_01_4" ],
    [ "external_constructor< value_t::object >", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1object_01_4.html", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1object_01_4" ],
    [ "external_constructor< value_t::string >", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1string_01_4.html", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1string_01_4" ],
    [ "from_json_fn", "structnlohmann_1_1detail_1_1from__json__fn.html", "structnlohmann_1_1detail_1_1from__json__fn" ],
    [ "has_from_json", "structnlohmann_1_1detail_1_1has__from__json.html", null ],
    [ "has_from_json< BasicJsonType, T, enable_if_t< not is_basic_json< T >::value > >", "structnlohmann_1_1detail_1_1has__from__json_3_01BasicJsonType_00_01T_00_01enable__if__t_3_01not_5e786a91cad76ed1c14f425887b41640.html", "structnlohmann_1_1detail_1_1has__from__json_3_01BasicJsonType_00_01T_00_01enable__if__t_3_01not_5e786a91cad76ed1c14f425887b41640" ],
    [ "has_non_default_from_json", "structnlohmann_1_1detail_1_1has__non__default__from__json.html", null ],
    [ "has_non_default_from_json< BasicJsonType, T, enable_if_t< not is_basic_json< T >::value > >", "structnlohmann_1_1detail_1_1has__non__default__from__json_3_01BasicJsonType_00_01T_00_01enable__a9e4562f31f7ed523e6e0f675606b0f2.html", "structnlohmann_1_1detail_1_1has__non__default__from__json_3_01BasicJsonType_00_01T_00_01enable__a9e4562f31f7ed523e6e0f675606b0f2" ],
    [ "has_to_json", "structnlohmann_1_1detail_1_1has__to__json.html", null ],
    [ "has_to_json< BasicJsonType, T, enable_if_t< not is_basic_json< T >::value > >", "structnlohmann_1_1detail_1_1has__to__json_3_01BasicJsonType_00_01T_00_01enable__if__t_3_01not_01737900a749c335e922e2f74e2face5e4.html", "structnlohmann_1_1detail_1_1has__to__json_3_01BasicJsonType_00_01T_00_01enable__if__t_3_01not_01737900a749c335e922e2f74e2face5e4" ],
    [ "index_sequence", "structnlohmann_1_1detail_1_1index__sequence.html", "structnlohmann_1_1detail_1_1index__sequence" ],
    [ "input_adapter", "classnlohmann_1_1detail_1_1input__adapter.html", "classnlohmann_1_1detail_1_1input__adapter" ],
    [ "input_adapter_protocol", "structnlohmann_1_1detail_1_1input__adapter__protocol.html", "structnlohmann_1_1detail_1_1input__adapter__protocol" ],
    [ "input_buffer_adapter", "classnlohmann_1_1detail_1_1input__buffer__adapter.html", "classnlohmann_1_1detail_1_1input__buffer__adapter" ],
    [ "input_stream_adapter", "classnlohmann_1_1detail_1_1input__stream__adapter.html", "classnlohmann_1_1detail_1_1input__stream__adapter" ],
    [ "internal_iterator", "structnlohmann_1_1detail_1_1internal__iterator.html", "structnlohmann_1_1detail_1_1internal__iterator" ],
    [ "invalid_iterator", "classnlohmann_1_1detail_1_1invalid__iterator.html", "classnlohmann_1_1detail_1_1invalid__iterator" ],
    [ "is_basic_json", "structnlohmann_1_1detail_1_1is__basic__json.html", null ],
    [ "is_basic_json< basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer > >", "structnlohmann_1_1detail_1_1is__basic__json_3_01basic__json_3_01ObjectType_00_01ArrayType_00_01S3f08839a6bb9b0e8b6454fd0720d949c.html", null ],
    [ "is_compatible_array_type", "structnlohmann_1_1detail_1_1is__compatible__array__type.html", null ],
    [ "is_compatible_array_type_impl", "structnlohmann_1_1detail_1_1is__compatible__array__type__impl.html", null ],
    [ "is_compatible_array_type_impl< BasicJsonType, CompatibleArrayType, enable_if_t< is_detected< value_type_t, CompatibleArrayType >::value andis_detected< iterator_t, CompatibleArrayType >::value andnot is_iterator_traits< std::iterator_traits< CompatibleArrayType > >::value > >", "structnlohmann_1_1detail_1_1is__compatible__array__type__impl_3_01BasicJsonType_00_01CompatibleA04b910efc9a72e55223e3cf87abae531.html", "structnlohmann_1_1detail_1_1is__compatible__array__type__impl_3_01BasicJsonType_00_01CompatibleA04b910efc9a72e55223e3cf87abae531" ],
    [ "is_compatible_integer_type", "structnlohmann_1_1detail_1_1is__compatible__integer__type.html", null ],
    [ "is_compatible_integer_type_impl", "structnlohmann_1_1detail_1_1is__compatible__integer__type__impl.html", null ],
    [ "is_compatible_integer_type_impl< RealIntegerType, CompatibleNumberIntegerType, enable_if_t< std::is_integral< RealIntegerType >::value andstd::is_integral< CompatibleNumberIntegerType >::value andnot std::is_same< bool, CompatibleNumberIntegerType >::value > >", "structnlohmann_1_1detail_1_1is__compatible__integer__type__impl_3_01RealIntegerType_00_01Compati58dfea94b501210ab5eb55b99717d8e4.html", "structnlohmann_1_1detail_1_1is__compatible__integer__type__impl_3_01RealIntegerType_00_01Compati58dfea94b501210ab5eb55b99717d8e4" ],
    [ "is_compatible_object_type", "structnlohmann_1_1detail_1_1is__compatible__object__type.html", null ],
    [ "is_compatible_object_type_impl", "structnlohmann_1_1detail_1_1is__compatible__object__type__impl.html", null ],
    [ "is_compatible_object_type_impl< BasicJsonType, CompatibleObjectType, enable_if_t< is_detected< mapped_type_t, CompatibleObjectType >::value andis_detected< key_type_t, CompatibleObjectType >::value > >", "structnlohmann_1_1detail_1_1is__compatible__object__type__impl_3_01BasicJsonType_00_01Compatiblec558c526350bd43442874eb4ca19fa08.html", "structnlohmann_1_1detail_1_1is__compatible__object__type__impl_3_01BasicJsonType_00_01Compatiblec558c526350bd43442874eb4ca19fa08" ],
    [ "is_compatible_string_type", "structnlohmann_1_1detail_1_1is__compatible__string__type.html", null ],
    [ "is_compatible_string_type_impl", "structnlohmann_1_1detail_1_1is__compatible__string__type__impl.html", null ],
    [ "is_compatible_string_type_impl< BasicJsonType, CompatibleStringType, enable_if_t< is_detected_exact< typename BasicJsonType::string_t::value_type, value_type_t, CompatibleStringType >::value > >", "structnlohmann_1_1detail_1_1is__compatible__string__type__impl_3_01BasicJsonType_00_01Compatible494e9dc742c819c61e54b8282030b5b6.html", "structnlohmann_1_1detail_1_1is__compatible__string__type__impl_3_01BasicJsonType_00_01Compatible494e9dc742c819c61e54b8282030b5b6" ],
    [ "is_compatible_type", "structnlohmann_1_1detail_1_1is__compatible__type.html", null ],
    [ "is_compatible_type_impl", "structnlohmann_1_1detail_1_1is__compatible__type__impl.html", null ],
    [ "is_compatible_type_impl< BasicJsonType, CompatibleType, enable_if_t< is_complete_type< CompatibleType >::value > >", "structnlohmann_1_1detail_1_1is__compatible__type__impl_3_01BasicJsonType_00_01CompatibleType_00_fa54cb60e66f5c6ba93b1dd3f418b703.html", "structnlohmann_1_1detail_1_1is__compatible__type__impl_3_01BasicJsonType_00_01CompatibleType_00_fa54cb60e66f5c6ba93b1dd3f418b703" ],
    [ "is_complete_type", "structnlohmann_1_1detail_1_1is__complete__type.html", null ],
    [ "is_complete_type< T, decltype(void(sizeof(T)))>", "structnlohmann_1_1detail_1_1is__complete__type_3_01T_00_01decltype_07void_07sizeof_07T_08_08_08_4.html", null ],
    [ "is_constructible_array_type", "structnlohmann_1_1detail_1_1is__constructible__array__type.html", null ],
    [ "is_constructible_array_type_impl", "structnlohmann_1_1detail_1_1is__constructible__array__type__impl.html", null ],
    [ "is_constructible_array_type_impl< BasicJsonType, ConstructibleArrayType, enable_if_t< not std::is_same< ConstructibleArrayType, typename BasicJsonType::value_type >::value andis_detected< value_type_t, ConstructibleArrayType >::value andis_detected< iterator_t, ConstructibleArrayType >::value andis_complete_type< detected_t< value_type_t, ConstructibleArrayType > >::value > >", "structnlohmann_1_1detail_1_1is__constructible__array__type__impl_3_01BasicJsonType_00_01Construce5264f88a89941b90919c7113fd8118f.html", "structnlohmann_1_1detail_1_1is__constructible__array__type__impl_3_01BasicJsonType_00_01Construce5264f88a89941b90919c7113fd8118f" ],
    [ "is_constructible_array_type_impl< BasicJsonType, ConstructibleArrayType, enable_if_t< std::is_same< ConstructibleArrayType, typename BasicJsonType::value_type >::value > >", "structnlohmann_1_1detail_1_1is__constructible__array__type__impl_3_01BasicJsonType_00_01Construce6fa33688da703b95649da4749cdeb98.html", null ],
    [ "is_constructible_object_type", "structnlohmann_1_1detail_1_1is__constructible__object__type.html", null ],
    [ "is_constructible_object_type_impl", "structnlohmann_1_1detail_1_1is__constructible__object__type__impl.html", null ],
    [ "is_constructible_object_type_impl< BasicJsonType, ConstructibleObjectType, enable_if_t< is_detected< mapped_type_t, ConstructibleObjectType >::value andis_detected< key_type_t, ConstructibleObjectType >::value > >", "structnlohmann_1_1detail_1_1is__constructible__object__type__impl_3_01BasicJsonType_00_01Constru221c0a7596f8e20cb0d2a2164a8c10a0.html", "structnlohmann_1_1detail_1_1is__constructible__object__type__impl_3_01BasicJsonType_00_01Constru221c0a7596f8e20cb0d2a2164a8c10a0" ],
    [ "is_constructible_string_type", "structnlohmann_1_1detail_1_1is__constructible__string__type.html", null ],
    [ "is_constructible_string_type_impl", "structnlohmann_1_1detail_1_1is__constructible__string__type__impl.html", null ],
    [ "is_constructible_string_type_impl< BasicJsonType, ConstructibleStringType, enable_if_t< is_detected_exact< typename BasicJsonType::string_t::value_type, value_type_t, ConstructibleStringType >::value > >", "structnlohmann_1_1detail_1_1is__constructible__string__type__impl_3_01BasicJsonType_00_01Construe4743afb22172cdb3c5f428800835387.html", "structnlohmann_1_1detail_1_1is__constructible__string__type__impl_3_01BasicJsonType_00_01Construe4743afb22172cdb3c5f428800835387" ],
    [ "is_iterator_traits", "structnlohmann_1_1detail_1_1is__iterator__traits.html", null ],
    [ "is_iterator_traits< std::iterator_traits< T > >", "structnlohmann_1_1detail_1_1is__iterator__traits_3_01std_1_1iterator__traits_3_01T_01_4_01_4.html", "structnlohmann_1_1detail_1_1is__iterator__traits_3_01std_1_1iterator__traits_3_01T_01_4_01_4" ],
    [ "is_sax", "structnlohmann_1_1detail_1_1is__sax.html", "structnlohmann_1_1detail_1_1is__sax" ],
    [ "is_sax_static_asserts", "structnlohmann_1_1detail_1_1is__sax__static__asserts.html", "structnlohmann_1_1detail_1_1is__sax__static__asserts" ],
    [ "iter_impl", "classnlohmann_1_1detail_1_1iter__impl.html", "classnlohmann_1_1detail_1_1iter__impl" ],
    [ "iteration_proxy", "classnlohmann_1_1detail_1_1iteration__proxy.html", "classnlohmann_1_1detail_1_1iteration__proxy" ],
    [ "json_ref", "classnlohmann_1_1detail_1_1json__ref.html", "classnlohmann_1_1detail_1_1json__ref" ],
    [ "json_reverse_iterator", "classnlohmann_1_1detail_1_1json__reverse__iterator.html", "classnlohmann_1_1detail_1_1json__reverse__iterator" ],
    [ "json_sax_acceptor", "classnlohmann_1_1detail_1_1json__sax__acceptor.html", "classnlohmann_1_1detail_1_1json__sax__acceptor" ],
    [ "json_sax_dom_callback_parser", "classnlohmann_1_1detail_1_1json__sax__dom__callback__parser.html", "classnlohmann_1_1detail_1_1json__sax__dom__callback__parser" ],
    [ "json_sax_dom_parser", "classnlohmann_1_1detail_1_1json__sax__dom__parser.html", "classnlohmann_1_1detail_1_1json__sax__dom__parser" ],
    [ "lexer", "classnlohmann_1_1detail_1_1lexer.html", "classnlohmann_1_1detail_1_1lexer" ],
    [ "make_index_sequence", "structnlohmann_1_1detail_1_1make__index__sequence.html", null ],
    [ "make_index_sequence< 0 >", "structnlohmann_1_1detail_1_1make__index__sequence_3_010_01_4.html", null ],
    [ "make_index_sequence< 1 >", "structnlohmann_1_1detail_1_1make__index__sequence_3_011_01_4.html", null ],
    [ "make_void", "structnlohmann_1_1detail_1_1make__void.html", "structnlohmann_1_1detail_1_1make__void" ],
    [ "merge_and_renumber", "structnlohmann_1_1detail_1_1merge__and__renumber.html", null ],
    [ "merge_and_renumber< index_sequence< I1... >, index_sequence< I2... > >", "structnlohmann_1_1detail_1_1merge__and__renumber_3_01index__sequence_3_01I1_8_8_8_01_4_00_01inde4885d6f1d93a04f25932afbd429c4793.html", null ],
    [ "nonesuch", "structnlohmann_1_1detail_1_1nonesuch.html", "structnlohmann_1_1detail_1_1nonesuch" ],
    [ "other_error", "classnlohmann_1_1detail_1_1other__error.html", "classnlohmann_1_1detail_1_1other__error" ],
    [ "out_of_range", "classnlohmann_1_1detail_1_1out__of__range.html", "classnlohmann_1_1detail_1_1out__of__range" ],
    [ "output_adapter", "classnlohmann_1_1detail_1_1output__adapter.html", "classnlohmann_1_1detail_1_1output__adapter" ],
    [ "output_adapter_protocol", "structnlohmann_1_1detail_1_1output__adapter__protocol.html", "structnlohmann_1_1detail_1_1output__adapter__protocol" ],
    [ "output_stream_adapter", "classnlohmann_1_1detail_1_1output__stream__adapter.html", "classnlohmann_1_1detail_1_1output__stream__adapter" ],
    [ "output_string_adapter", "classnlohmann_1_1detail_1_1output__string__adapter.html", "classnlohmann_1_1detail_1_1output__string__adapter" ],
    [ "output_vector_adapter", "classnlohmann_1_1detail_1_1output__vector__adapter.html", "classnlohmann_1_1detail_1_1output__vector__adapter" ],
    [ "parse_error", "classnlohmann_1_1detail_1_1parse__error.html", "classnlohmann_1_1detail_1_1parse__error" ],
    [ "parser", "classnlohmann_1_1detail_1_1parser.html", "classnlohmann_1_1detail_1_1parser" ],
    [ "position_t", "structnlohmann_1_1detail_1_1position__t.html", "structnlohmann_1_1detail_1_1position__t" ],
    [ "primitive_iterator_t", "classnlohmann_1_1detail_1_1primitive__iterator__t.html", "classnlohmann_1_1detail_1_1primitive__iterator__t" ],
    [ "priority_tag", "structnlohmann_1_1detail_1_1priority__tag.html", null ],
    [ "priority_tag< 0 >", "structnlohmann_1_1detail_1_1priority__tag_3_010_01_4.html", null ],
    [ "serializer", "classnlohmann_1_1detail_1_1serializer.html", "classnlohmann_1_1detail_1_1serializer" ],
    [ "static_const", "structnlohmann_1_1detail_1_1static__const.html", "structnlohmann_1_1detail_1_1static__const" ],
    [ "to_json_fn", "structnlohmann_1_1detail_1_1to__json__fn.html", "structnlohmann_1_1detail_1_1to__json__fn" ],
    [ "type_error", "classnlohmann_1_1detail_1_1type__error.html", "classnlohmann_1_1detail_1_1type__error" ],
    [ "wide_string_input_adapter", "classnlohmann_1_1detail_1_1wide__string__input__adapter.html", "classnlohmann_1_1detail_1_1wide__string__input__adapter" ],
    [ "wide_string_input_helper", "structnlohmann_1_1detail_1_1wide__string__input__helper.html", "structnlohmann_1_1detail_1_1wide__string__input__helper" ],
    [ "wide_string_input_helper< WideStringType, 2 >", "structnlohmann_1_1detail_1_1wide__string__input__helper_3_01WideStringType_00_012_01_4.html", "structnlohmann_1_1detail_1_1wide__string__input__helper_3_01WideStringType_00_012_01_4" ]
];