Fast Methods for Cosmological Simulations: anonymous_namespace{main.cpp} Namespace Reference
anonymous_namespace{main.cpp} Namespace Reference
Classes
class Logger
class Timer
Functions
void init_logging ()
template<class T >
void init_and_run_app (Sim_Param &sim)
Function Documentation
template<class T > void anonymous_namespace{main.cpp}::init_and_run_app (Sim_Param & sim)
Definition at line 92 of file main.cpp.
References Sim_Param::cosmo, cl_cmbl_bm::l, anonymous_namespace{main.cpp}::Timer::stop(), and growth_allz::T.
 {
     // timer for wall time, CPU time
     Timer t;
     // create approximation class and whether we have truncation in initial power spectrum
     T APP(sim);
     APP.update_cosmo(sim.cosmo);
     // register log file
     Logger l(APP.get_out_dir() + "log/log" + "_%N.log");
     // run the simulation
     APP.run_simulation();
     // stop timer manually so it is in the log file
     t.stop();
 }
void anonymous_namespace{main.cpp}::init_logging ()
Definition at line 35 of file main.cpp.
References Catch::cout().
Referenced by main().
 {
     // set logging core to log everything
     logging::core::get()->set_filter
     (
         logging::trivial::severity >= logging::trivial::trace
     );
     // add atributes
     boost::log::add_common_attributes();
     boost::log::register_simple_formatter_factory< boost::log::trivial::severity_level, char >("Severity");
     // register 'std:cout' as sink
     boost::shared_ptr< sink_os_t > g_file_sink = logging::add_console_log(std::cout);
     g_file_sink->set_filter(logging::trivial::severity >= logging::trivial::info);
 }