Fast Methods for Cosmological Simulations: Catch::Matchers::Vector::Detail Namespace Reference
Catch::Matchers::Vector::Detail Namespace Reference
Functions
template<typename InputIterator , typename T >
size_t count (InputIterator first, InputIterator last, T const &item)
template<typename InputIterator , typename T >
bool contains (InputIterator first, InputIterator last, T const &item)
Function Documentation
template<typename InputIterator , typename T > bool Catch::Matchers::Vector::Detail::contains (InputIterator first, InputIterator last, T const & item)
Definition at line 2757 of file catch.hpp.
Referenced by Catch::Matchers::Vector::UnorderedEqualsMatcher< T >::match().
{
                 for (; first != last; ++first) {
                     if (*first == item) {
                         return true;
                     }
                 }
                 return false;
             }
template<typename InputIterator , typename T > size_t Catch::Matchers::Vector::Detail::count (InputIterator first, InputIterator last, T const & item)
Definition at line 2747 of file catch.hpp.
Referenced by gen_cqty_binned(), Catch::Matchers::Vector::UnorderedEqualsMatcher< T >::match(), read_benchmark_file(), read_chi_test_file(), read_dm_test_file(), read_growth_hiz_test_file(), read_growth_test_file(), read_halomod_test_file(), and read_massfunc_test_file().
{
                 size_t cnt = 0;
                 for (; first != last; ++first) {
                     if (*first == item) {
                         ++cnt;
                     }
                 }
                 return cnt;
             }