Fast Methods for Cosmological Simulations: anonymous_namespace{chameleon.cpp} Namespace Reference
anonymous_namespace{chameleon.cpp} Namespace Reference
Classes
class ChiSolver
: class to solve chameleon equations of motion
Typedefs
typedef double CHI_PREC_t
accuracy of chameleon solver
using ES = MultiGridSolver< 3, CHI_PREC_t >::Exit_Status
acces Exit_Status namespace
Functions
template<typename T >
void transform_Mesh_to_Grid (const Mesh &mesh, Grid< 3, T > &grid)
template<typename T >
void transform_Mesh_to_MultiGrid (const Mesh &mesh, MultiGrid< 3, T > &mltgrid)
template<typename T >
void transform_Grid_to_Mesh (Mesh &mesh, const Grid< 3, T > &grid)
template<typename T >
void transform_MultiGrid_to_Mesh (Mesh &mesh, const MultiGrid< 3, T > &mltgrid)
template<typename T >
void transform_MultiGridSolver_to_Mesh (Mesh &mesh, const MultiGridSolver< 3, T > &sol)
template<typename T >
T min (const std::vector< T > &data)
double min (const Mesh &data)
template<typename T >
double min (const Grid< 3, T > &grid)
template<typename T >
double min (const MultiGrid< 3, T > &grid)
Variables
constexpr double MPL = (double)1
mass & chi in units of Planck mass
constexpr double c_kms = (double)299792.458
speed of light [km / s]
constexpr CHI_PREC_t MARK_CHI_BOUND_COND = (CHI_PREC_t)-2
unphysical value of overdensity (< -1) used to indicate that chameleon filed at this point should not be changed
constexpr CHI_PREC_t SWITCH_BIS_NEW = (CHI_PREC_t)0.1
when the relative change in solution is less than this, use Newton`s method. Bisection method otherwise
constexpr CHI_PREC_t CHI_MIN = (CHI_PREC_t)-1
minimum value of chameleon field, in chi_a units it is '0', in phi units it is '-1'
constexpr double CONVERGENCE_RES = 0
stop when total (rms) residual below
constexpr double CONVERGENCE_RES_MIN = 0
do not stop if solution didn`t converge below
constexpr double CONVERGENCE_ERR = 0.97
stop when improvements between steps slow below
constexpr double CONVERGENCE_ERR_MIN = 0.8
do not stop if solution is still improving
constexpr size_t CONVERGENCE_NUM_FAIL = 5
stop when number of failed steps is over
constexpr size_t CONVERGENCE_BI_STEPS = 5
maximal number of steps inside bisection rootfindg method
constexpr size_t CONVERGENCE_BI_STEPS_INIT = 3
maximal number of steps inside bisection initialization method
constexpr CHI_PREC_t CONVERGENCE_BI_DCHI = (CHI_PREC_t)1e-2
stop bisection method when chi doesn`t chanege
constexpr CHI_PREC_t CONVERGENCE_BI_L = (CHI_PREC_t)1e-2
stop bisection method when residual below
Detailed Description
PRIVATE FUNCTIONS DEFINITIONS *
Typedef Documentation
anonymous_namespace{chameleon.cpp}::CHI_PREC_t
accuracy of chameleon solver
Definition at line 31 of file chameleon.cpp.
using anonymous_namespace{chameleon.cpp}::ES = typedef MultiGridSolver<3, CHI_PREC_t>::Exit_Status
acces Exit_Status namespace
Definition at line 86 of file chameleon.cpp.
Function Documentation
template<typename T > T anonymous_namespace{chameleon.cpp}::min (const std::vector< T > & data)
Definition at line 140 of file chameleon.cpp.
Referenced by assign_to_grid(), ContinuitySolver< NDIM, T >::bfunc(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_integer_size(), TEST_CASE(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::ubjson_prefix(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_integer(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_msgpack(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_number_with_ubjson_prefix().
 { return *std::min_element(data.begin(), data.end()); }
double anonymous_namespace{chameleon.cpp}::min (const Mesh & data)
Definition at line 142 of file chameleon.cpp.
References Mesh_base< T >::data, and min().
 { return min(data.data); }
template<typename T > double anonymous_namespace{chameleon.cpp}::min (const Grid< 3, T > & grid)
Definition at line 145 of file chameleon.cpp.
References Grid< NDIM, T >::get_vec(), and min().
 { return min(grid.get_vec()); }
template<typename T > double anonymous_namespace{chameleon.cpp}::min (const MultiGrid< 3, T > & grid)
Definition at line 148 of file chameleon.cpp.
References MultiGrid< NDIM, T >::get_grid().
Referenced by min().
 { return min(grid.get_grid()); }
template<typename T > void anonymous_namespace{chameleon.cpp}::transform_Grid_to_Mesh (Mesh & mesh, const Grid< 3, T > & grid)
Definition at line 115 of file chameleon.cpp.
References Grid< NDIM, T >::get_N(), Grid< NDIM, T >::get_Ntot(), mfunc_bm::iz, and Mesh::N.
Referenced by anonymous_namespace{chameleon.cpp}::ChiSolver< T >::set_linear_recursively(), transform_MultiGrid_to_Mesh(), and transform_MultiGridSolver_to_Mesh().
 {/* copy data in MultiGrid 'N*N*N' onto Mesh 'N*N*(N+2)' */
     size_t ix, iy, iz;
     const size_t N_tot = grid.get_Ntot();
     const size_t N = grid.get_N();
     if (mesh.N != N) throw std::range_error("Mesh of a different size than Grid!");
     #pragma omp parallel for private(ix, iy, iz)
     for (size_t i = 0; i < N_tot; ++i)
     {
         ix = i % N;
         iy = i / N % N;
         iz = i / (N*N);
         mesh(ix, iy, iz) = grid[i];
     }
 }
template<typename T > void anonymous_namespace{chameleon.cpp}::transform_Mesh_to_Grid (const Mesh & mesh, Grid< 3, T > & grid)
Definition at line 89 of file chameleon.cpp.
References Grid< NDIM, T >::get_N(), Grid< NDIM, T >::get_Ntot(), mfunc_bm::iz, and Mesh::N.
Referenced by anonymous_namespace{chameleon.cpp}::ChiSolver< T >::set_linear_sol_at_level(), and transform_Mesh_to_MultiGrid().
 {/* copy data in Mesh 'N*N*(N+2)' onto MultiGrid 'N*N*N' */
     size_t ix, iy, iz;
     const size_t N_tot = grid.get_Ntot();
     const size_t N = grid.get_N();
     if (mesh.N != N) throw std::range_error("Mesh of a different size than Grid!");
     #pragma omp parallel for private(ix, iy, iz)
     for (size_t i = 0; i < N_tot; ++i)
     {
         ix = i % N;
         iy = i / N % N;
         iz = i / (N*N);
         grid[i] = mesh(ix, iy, iz);
     }
 }
template<typename T > void anonymous_namespace{chameleon.cpp}::transform_Mesh_to_MultiGrid (const Mesh & mesh, MultiGrid< 3, T > & mltgrid)
Definition at line 108 of file chameleon.cpp.
References MultiGrid< NDIM, T >::get_grid(), MultiGrid< NDIM, T >::restrict_down_all(), and transform_Mesh_to_Grid().
Referenced by anonymous_namespace{test_chameleon.cpp}::init_overdensity(), App_Var_Chi::ChiImpl::solve(), and TEST_CASE().
 {
     transform_Mesh_to_Grid(mesh, mltgrid.get_grid());
     mltgrid.restrict_down_all();
 }
template<typename T > void anonymous_namespace{chameleon.cpp}::transform_MultiGrid_to_Mesh (Mesh & mesh, const MultiGrid< 3, T > & mltgrid)
Definition at line 134 of file chameleon.cpp.
References MultiGrid< NDIM, T >::get_grid(), and transform_Grid_to_Mesh().
Referenced by TEST_CASE().
 { transform_Grid_to_Mesh(mesh, mltgrid.get_grid()); }
template<typename T > void anonymous_namespace{chameleon.cpp}::transform_MultiGridSolver_to_Mesh (Mesh & mesh, const MultiGridSolver< 3, T > & sol)
Definition at line 137 of file chameleon.cpp.
References MultiGridSolver< NDIM, T >::get_grid(), and transform_Grid_to_Mesh().
Referenced by App_Var_Chi::ChiImpl::gen_pow_spec_binned(), App_Var_Chi::ChiImpl::get_chi_force(), and TEST_CASE().
 { transform_Grid_to_Mesh(mesh, sol.get_grid()); }
Variable Documentation
anonymous_namespace{chameleon.cpp}::c_kms = (double)299792.458
speed of light [km / s]
Definition at line 45 of file chameleon.cpp.
anonymous_namespace{chameleon.cpp}::CHI_MIN = (CHI_PREC_t)-1
minimum value of chameleon field, in chi_a units it is '0', in phi units it is '-1'
Definition at line 66 of file chameleon.cpp.
Referenced by anonymous_namespace{chameleon.cpp}::ChiSolver< T >::bisection_step(), anonymous_namespace{chameleon.cpp}::ChiSolver< T >::chi_min(), anonymous_namespace{chameleon.cpp}::ChiSolver< T >::set_linear_sol_at_level(), and anonymous_namespace{chameleon.cpp}::ChiSolver< T >::set_screened().
anonymous_namespace{chameleon.cpp}::MARK_CHI_BOUND_COND = (CHI_PREC_t)-2
unphysical value of overdensity (< -1) used to indicate that chameleon filed at this point should not be changed
Definition at line 52 of file chameleon.cpp.
Referenced by anonymous_namespace{chameleon.cpp}::ChiSolver< T >::set_screened().
anonymous_namespace{chameleon.cpp}::MPL = (double)1
mass & chi in units of Planck mass
Definition at line 38 of file chameleon.cpp.
anonymous_namespace{chameleon.cpp}::SWITCH_BIS_NEW = (CHI_PREC_t)0.1
when the relative change in solution is less than this, use Newton`s method. Bisection method otherwise
Definition at line 59 of file chameleon.cpp.