Fast Methods for Cosmological Simulations: anonymous_namespace{app_var.cpp} Namespace Reference
anonymous_namespace{app_var.cpp} Namespace Reference
Classes
class Tracking
: class storing info about tracked particles
Functions
const char * humanSize (uint64_t bytes)
void print_mem (uint64_t memory_alloc)
Function Documentation
const char* anonymous_namespace{app_var.cpp}::humanSize (uint64_t bytes)
Definition at line 18 of file app_var.cpp.
Referenced by print_mem().
{
     char const *suffix[] = {"B", "KB", "MB", "GB", "TB"};
     char length = sizeof(suffix) / sizeof(suffix[0]);
     size_t i = 0;
     double dblBytes = bytes;
     if (bytes > 1024) {
         for (i = 0; (bytes / 1024) > 0 && i<length-1; i++, bytes /= 1024)
             dblBytes = bytes / 1024.0;
     }
     static char output[200];
     sprintf(output, "%.02lf %s", dblBytes, suffix[i]);
     return output;
 }
void anonymous_namespace{app_var.cpp}::print_mem (uint64_t memory_alloc)
Definition at line 35 of file app_var.cpp.
References humanSize().
Referenced by App_Var< T >::run_simulation().
 {
     BOOST_LOG_TRIVIAL(debug) << "Allocated " << humanSize(memory_alloc) << " of memory.";
 }