Fast Methods for Cosmological Simulations: src/data/params.cpp File Reference
params.cpp File Reference
: various parameter classes definitions
#include <omp.h>
#include "config.h"
#include "params.hpp"
#include "core_cmd.h"
#include "core_out.h"
#include "core_mesh.h"
#include "core_power.h"
#include <ccl_error.h>
#include <json.hpp>
#include <iomanip>
Namespaces
anonymous_namespace{params.cpp}
Typedefs
using json = nlohmann::json
Functions
template<typename T , typename U >
T anonymous_namespace{params.cpp}::find_value (const std::map< T, U > &map, const U &value)
size_t anonymous_namespace{params.cpp}::get_seed ()
void to_json (json &j, const Cosmo_Param &cosmo)
< end of anonymous namespace (private definitions)
void from_json (const json &j, Cosmo_Param &cosmo)
void to_json (json &j, const Box_Opt &box_opt)
void from_json (const json &j, Box_Opt &box_opt)
void to_json (json &j, const Integ_Opt &integ_opt)
void from_json (const json &j, Integ_Opt &integ_opt)
void to_json (json &j, const App_Opt &app_opt)
void from_json (const json &j, App_Opt &app_op)
void to_json (json &j, const Run_Opt &run_opt)
void from_json (const json &j, Run_Opt &run_opt)
void to_json (json &j, const Out_Opt &out_opt)
void from_json (const json &j, Out_Opt &out_opt)
void to_json (json &j, const Chi_Opt &chi_opt)
void from_json (const json &j, Chi_Opt &chi_opt)
void to_json (json &j, const Test_Opt &test_opt)
void from_json (const json &j, Test_Opt &test_opt)
static ccl_cosmology * ccl_cosmology_create_flat_lcdm (double Omega_c, double Omega_b, double h, double norm_pk, double n_s, ccl_configuration config, int *status)
Variables
const std::map< std::string, transfer_function_t > anonymous_namespace{params.cpp}::transfer_function_method
const std::map< std::string, matter_power_spectrum_t > anonymous_namespace{params.cpp}::matter_power_spectrum_method
const std::map< std::string, mass_function_t > anonymous_namespace{params.cpp}::mass_function_method
const std::map< std::string, baryons_power_spectrum_t > anonymous_namespace{params.cpp}::baryons_power_spectrum_method
Detailed Description
: various parameter classes definitions
Definition in file params.cpp.
Typedef Documentation
using json = nlohmann::json
Definition at line 17 of file params.cpp.
Function Documentation
static ccl_cosmology* ccl_cosmology_create_flat_lcdm (double Omega_c, double Omega_b, double h, double norm_pk, double n_s, ccl_configuration config, int * status) static
Definition at line 280 of file params.cpp.
References ccl_cosmology_create(), ccl_mnu_sum, ccl_parameters_create(), cl_cmbl_bm::cosmo, ccl_test_distances::mnu, ccl_test_distances::Neff, and halomod_bm::params.
Referenced by Cosmo_Param::init().
 {
     double Omega_k = 0.0;
     double Neff = 3.04;
     double w0 = -1.0;
     double wa = 0.0;
     double *mnu;
     double mnuval = 0.;  // a pointer to the variable is not kept past the lifetime of this function
     mnu = &mnuval;
     ccl_mnu_convention mnu_type = ccl_mnu_sum;
     ccl_parameters params = ccl_parameters_create(Omega_c, Omega_b, Omega_k, Neff,
             mnu, mnu_type, w0, wa, h, norm_pk, n_s, -1, -1, -1, -1, NULL, NULL, status);
     ccl_cosmology * cosmo = ccl_cosmology_create(params, config);
     return cosmo;
 }
void from_json (const json & j, Cosmo_Param & cosmo)
Definition at line 109 of file params.cpp.
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::at(), anonymous_namespace{params.cpp}::baryons_power_spectrum_method, ccl_configuration::baryons_power_spectrum_method, ccl_boltzmann_class, ccl_halofit, ccl_nobaryons, ccl_tinker10, Cosmo_Param::config, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::get(), Cosmo_Param::h, Cosmo_Param::H0, Cosmo_Param::init(), Cosmo_Param::k2_G, anonymous_namespace{params.cpp}::mass_function_method, ccl_configuration::mass_function_method, anonymous_namespace{params.cpp}::matter_power_spectrum_method, ccl_configuration::matter_power_spectrum_method, Cosmo_Param::ns, Cosmo_Param::Omega_b, Cosmo_Param::Omega_m, Cosmo_Param::sigma8, anonymous_namespace{params.cpp}::transfer_function_method, and ccl_configuration::transfer_function_method.
Referenced by Sim_Param::Sim_Param().
 {
     cosmo.ns = j.at("index").get<FTYPE_t>();
     cosmo.sigma8 = j.at("sigma8").get<FTYPE_t>();
     cosmo.k2_G = j.at("smoothing_k").get<FTYPE_t>();
     cosmo.Omega_b = j.at("Omega_b").get<FTYPE_t>();
     cosmo.Omega_m = j.at("Omega_m").get<FTYPE_t>();
     cosmo.h = j.at("h").get<FTYPE_t>();
     cosmo.H0 = cosmo.h * 100;
     std::string tmp;
     try{
         tmp = j.at("transfer_function_method").get<std::string>();
         cosmo.config.transfer_function_method = transfer_function_method.at(tmp);
     }catch(const json::out_of_range& oor){
         cosmo.config.transfer_function_method = ccl_boltzmann_class;
     }
     try{
         tmp = j.at("matter_power_spectrum_method").get<std::string>();
         cosmo.config.matter_power_spectrum_method = matter_power_spectrum_method.at(tmp);
     }catch(const json::out_of_range& oor){
         cosmo.config.matter_power_spectrum_method = ccl_halofit;
     }
     try{
         tmp = j.at("mass_function_method").get<std::string>();
         cosmo.config.mass_function_method = mass_function_method.at(tmp);
     }catch(const json::out_of_range& oor){
         cosmo.config.mass_function_method = ccl_tinker10;
     }
     try{
         tmp = j.at("baryons_power_spectrum_method").get<std::string>();
         cosmo.config.baryons_power_spectrum_method = baryons_power_spectrum_method.at(tmp);
     }catch(const json::out_of_range& oor){
         cosmo.config.baryons_power_spectrum_method = ccl_nobaryons;
     }
     cosmo.init();
 }
void from_json (const json & j, Box_Opt & box_opt)
Definition at line 159 of file params.cpp.
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::at(), Box_Opt::box_size, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::get(), Box_Opt::mesh_num, Box_Opt::mesh_num_pwr, and Box_Opt::par_num_1d.
 {
     box_opt.mesh_num = j.at("mesh_num").get<size_t>();
     box_opt.mesh_num_pwr = j.at("mesh_num_pwr").get<size_t>();
     box_opt.par_num_1d = j.at("par_num").get<size_t>();
     box_opt.box_size = j.at("box_size").get<FTYPE_t>();
 }
void from_json (const json & j, Integ_Opt & integ_opt)
Definition at line 176 of file params.cpp.
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::at(), Integ_Opt::db, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::get(), Integ_Opt::init(), Integ_Opt::z_in, and Integ_Opt::z_out.
 {
     integ_opt.z_in = j.at("redshift").get<FTYPE_t>();
     integ_opt.z_out = j.at("redshift_0").get<FTYPE_t>();
     integ_opt.db = j.at("time_step").get<FTYPE_t>();
     integ_opt.init();
 }
void from_json (const json & j, App_Opt & app_op)
Definition at line 193 of file params.cpp.
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::at(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::get(), App_Opt::nu, App_Opt::nu_dim, and App_Opt::rs.
 {
     app_op.nu_dim = j.at("viscosity").get<FTYPE_t>();
     app_op.nu = app_op.nu_dim;
     app_op.rs = j.at("cut_radius").get<FTYPE_t>();
 }
void from_json (const json & j, Run_Opt & run_opt)
Definition at line 210 of file params.cpp.
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::at(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::get(), Run_Opt::init(), Run_Opt::nt, Run_Opt::phase, and Run_Opt::seed.
 {
     run_opt.nt = j.at("num_thread").get<size_t>();
     run_opt.seed = j.at("seed").get<size_t>();
     run_opt.phase = j.at("phase").get<bool>();
     run_opt.init();
 }
void from_json (const json & j, Out_Opt & out_opt)
Definition at line 227 of file params.cpp.
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::at(), Out_Opt::bins_per_decade, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::get(), Out_Opt::out_dir, and Out_Opt::points_per_10_Mpc.
 {
     out_opt.bins_per_decade = j.at("bins_per_decade").get<size_t>();
     out_opt.points_per_10_Mpc = j.at("points_per_10_Mpc").get<size_t>();
     out_opt.out_dir = j.at("out_dir").get<std::string>();
 }
void from_json (const json & j, Chi_Opt & chi_opt)
Definition at line 244 of file params.cpp.
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::at(), Chi_Opt::beta, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::get(), Chi_Opt::linear, Chi_Opt::n, and Chi_Opt::phi.
 {
     chi_opt.beta = j.at("beta").get<FTYPE_t>();
     chi_opt.n = j.at("n").get<FTYPE_t>();
     chi_opt.phi = j.at("phi").get<FTYPE_t>();
     // optional parameters (old runs do not have everything)
     try {chi_opt.linear = j.at("linear").get<bool>();}
     catch (const json::out_of_range& oor){chi_opt.linear = false;}
 }
void from_json (const json & j, Test_Opt & test_opt)
Definition at line 266 of file params.cpp.
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::at(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::get(), Test_Opt::N_grid, Test_Opt::N_min, Test_Opt::R_sphere, Test_Opt::rho_b, and Test_Opt::rho_sphere.
 {
     test_opt.R_sphere = j.at("R_sphere").get<FTYPE_t>();
     test_opt.rho_sphere = j.at("rho_sphere").get<FTYPE_t>();
     test_opt.N_grid = j.at("N_grid").get<size_t>();
     test_opt.N_min = j.at("N_min").get<size_t>();
     test_opt.rho_b = j.at("rho_b").get<FTYPE_t>();
 }
void to_json (json & j, const Cosmo_Param & cosmo)
< end of anonymous namespace (private definitions)
PUBLIC FUNCTIONS DEFINITIONS *
Definition at line 91 of file params.cpp.
References anonymous_namespace{params.cpp}::baryons_power_spectrum_method, ccl_configuration::baryons_power_spectrum_method, Cosmo_Param::config, anonymous_namespace{params.cpp}::find_value(), Cosmo_Param::h, Cosmo_Param::k2_G, anonymous_namespace{params.cpp}::mass_function_method, ccl_configuration::mass_function_method, anonymous_namespace{params.cpp}::matter_power_spectrum_method, ccl_configuration::matter_power_spectrum_method, Cosmo_Param::ns, Cosmo_Param::Omega_b, Cosmo_Param::Omega_c(), Cosmo_Param::Omega_m, Cosmo_Param::sigma8, anonymous_namespace{params.cpp}::transfer_function_method, and ccl_configuration::transfer_function_method.
 {
     j = json{
         {"index", cosmo.ns},
         {"sigma8", cosmo.sigma8},
         {"smoothing_k", cosmo.k2_G},
         {"Omega_c", cosmo.Omega_c()},
         {"Omega_b", cosmo.Omega_b},
         {"Omega_m", cosmo.Omega_m},
         {"h", cosmo.h}
     };
     j["transfer_function_method"] = find_value(transfer_function_method, cosmo.config.transfer_function_method);
     j["matter_power_spectrum_method"] = find_value(matter_power_spectrum_method, cosmo.config.matter_power_spectrum_method);
     j["mass_function_method"] = find_value(mass_function_method, cosmo.config.mass_function_method);
     j["baryons_power_spectrum_method"] = find_value(baryons_power_spectrum_method, cosmo.config.baryons_power_spectrum_method);
 }
void to_json (json & j, const Box_Opt & box_opt)
Definition at line 147 of file params.cpp.
References Box_Opt::box_size, Box_Opt::mass_p_log, Box_Opt::mesh_num, Box_Opt::mesh_num_pwr, Box_Opt::Ng, and Box_Opt::par_num_1d.
 {
     j = json{
         {"mesh_num", box_opt.mesh_num},
         {"mesh_num_pwr", box_opt.mesh_num_pwr},
         {"Ng", box_opt.Ng},
         {"par_num", box_opt.par_num_1d},
         {"box_size", box_opt.box_size},
         {"mass_p_log", box_opt.mass_p_log}
     };
 }
void to_json (json & j, const Integ_Opt & integ_opt)
Definition at line 167 of file params.cpp.
References Integ_Opt::db, Integ_Opt::z_in, and Integ_Opt::z_out.
 {
     j = json{
         {"redshift", integ_opt.z_in},
         {"redshift_0", integ_opt.z_out},
         {"time_step", integ_opt.db}
     };
 }
void to_json (json & j, const App_Opt & app_opt)
Definition at line 185 of file params.cpp.
References App_Opt::nu_dim, and App_Opt::rs.
 {
     j = json{
         {"viscosity", app_opt.nu_dim},
         {"cut_radius", app_opt.rs}
     };
 }
void to_json (json & j, const Run_Opt & run_opt)
Definition at line 200 of file params.cpp.
References Run_Opt::nt, Run_Opt::phase, PROJECT_VERSION, and Run_Opt::seed.
 {
     j = json{
         {"num_thread", run_opt.nt},
         {"seed", run_opt.seed},
         {"phase", run_opt.phase},
         {"version", PROJECT_VERSION}
     };
 }
void to_json (json & j, const Out_Opt & out_opt)
Definition at line 218 of file params.cpp.
References Out_Opt::bins_per_decade, Out_Opt::out_dir, and Out_Opt::points_per_10_Mpc.
 {
     j = json{
         {"bins_per_decade", out_opt.bins_per_decade},
         {"points_per_10_Mpc", out_opt.points_per_10_Mpc},
         {"out_dir", out_opt.out_dir}
     };
 }
void to_json (json & j, const Chi_Opt & chi_opt)
Definition at line 234 of file params.cpp.
References Chi_Opt::beta, Chi_Opt::linear, Chi_Opt::n, and Chi_Opt::phi.
 {
     j = json{
         {"beta", chi_opt.beta},
         {"n", chi_opt.n},
         {"phi", chi_opt.phi},
         {"linear", chi_opt.linear},
     };
 }
void to_json (json & j, const Test_Opt & test_opt)
Definition at line 255 of file params.cpp.
References Test_Opt::N_grid, Test_Opt::N_min, Test_Opt::R_sphere, Test_Opt::rho_b, and Test_Opt::rho_sphere.
 {
     j = json{
         {"R_sphere", test_opt.R_sphere},
         {"rho_sphere", test_opt.rho_sphere},
         {"N_grid", test_opt.N_grid},
         {"N_min", test_opt.N_min},
         {"rho_b", test_opt.rho_b}
     };
 }