Fast Methods for Cosmological Simulations: src/main/include/precision.hpp File Reference
precision.hpp File Reference
single / double / long double definitions
Macros
#define MAKE_FFTW_NAME(FUNC_NAME) fftw_ ## FUNC_NAME
#define FFTW_PLAN_TYPE MAKE_FFTW_NAME(plan)
#define FFTW_DEST_PLAN MAKE_FFTW_NAME(destroy_plan)
#define FFTW_COMPLEX_TYPE MAKE_FFTW_NAME(complex)
#define FFTW_PLAN_R2C MAKE_FFTW_NAME(plan_dft_r2c_3d)
#define FFTW_PLAN_C2R MAKE_FFTW_NAME(plan_dft_c2r_3d)
#define FFTW_PLAN_OMP MAKE_FFTW_NAME(plan_with_nthreads)
#define FFTW_PLAN_OMP_INIT MAKE_FFTW_NAME(init_threads)
#define FFTW_PLAN_OMP_CLEAN MAKE_FFTW_NAME(cleanup_threads)
#define FFTW_EXEC_R2C MAKE_FFTW_NAME(execute_dft_r2c)
#define FFTW_EXEC_C2R MAKE_FFTW_NAME(execute_dft_c2r)
Typedefs
typedef double double
Functions
float pow (float base, unsigned long int exp)
template<typename T >
T pow2 (T base)
Variables
constexpr double PI = double(3.14159265358979323846)
Detailed Description
single / double / long double definitions
Author
Michal Vrastil
Date
2018-07-11
Definition in file precision.hpp.
Macro Definition Documentation
#define FFTW_COMPLEX_TYPE MAKE_FFTW_NAME(complex)
Definition at line 28 of file precision.hpp.
Referenced by Mesh::complex().
#define FFTW_DEST_PLAN MAKE_FFTW_NAME(destroy_plan)
Definition at line 27 of file precision.hpp.
Referenced by TEST_CASE(), and App_Var< T >::~App_Var().
#define FFTW_EXEC_C2R MAKE_FFTW_NAME(execute_dft_c2r)
Definition at line 35 of file precision.hpp.
Referenced by fftw_execute_dft_c2r().
#define FFTW_EXEC_R2C MAKE_FFTW_NAME(execute_dft_r2c)
Definition at line 34 of file precision.hpp.
Referenced by fftw_execute_dft_r2c().
#define FFTW_PLAN_C2R MAKE_FFTW_NAME(plan_dft_c2r_3d)
Definition at line 30 of file precision.hpp.
Referenced by App_Var< T >::Impl< T >::fftw_prep(), anonymous_namespace{chameleon.cpp}::ChiSolver< T >::set_linear_recursively(), and TEST_CASE().
#define FFTW_PLAN_OMP MAKE_FFTW_NAME(plan_with_nthreads)
Definition at line 31 of file precision.hpp.
Referenced by App_Var< T >::Impl< T >::fftw_prep(), and TEST_CASE().
#define FFTW_PLAN_OMP_CLEAN MAKE_FFTW_NAME(cleanup_threads)
Definition at line 33 of file precision.hpp.
Referenced by TEST_CASE(), and App_Var< T >::~App_Var().
#define FFTW_PLAN_OMP_INIT MAKE_FFTW_NAME(init_threads)
Definition at line 32 of file precision.hpp.
Referenced by App_Var< T >::Impl< T >::fftw_prep(), and TEST_CASE().
#define FFTW_PLAN_R2C MAKE_FFTW_NAME(plan_dft_r2c_3d)
Definition at line 29 of file precision.hpp.
Referenced by App_Var< T >::Impl< T >::fftw_prep(), anonymous_namespace{chameleon.cpp}::ChiSolver< T >::set_linear_recursively(), and TEST_CASE().
#define FFTW_PLAN_TYPE MAKE_FFTW_NAME(plan)
Definition at line 26 of file precision.hpp.
Referenced by anonymous_namespace{chameleon.cpp}::ChiSolver< T >::set_linear_recursively(), and TEST_CASE().
#define MAKE_FFTW_NAME (FUNC_NAME) fftw_ ## FUNC_NAME
Definition at line 20 of file precision.hpp.
Typedef Documentation
typedef double double
Definition at line 19 of file precision.hpp.
Function Documentation
float pow (float base, unsigned long int exp) inline
Definition at line 39 of file precision.hpp.
Referenced by bbks_power(), ccl_bcm_model_fka(), ccl_cosmology_compute_sigma(), ccl_get_class_As(), ccl_halo_b1(), ccl_halo_concentration(), ccl_j_bessel(), ccl_massfunc_m2r(), ccl_nu_masses(), ccl_omega_x(), ccl_Omeganuh2(), ccl_parameters_fill_initial(), ccl_pkemu(), ccl_sigmaM(), ccl_tracer_corr_fftlog(), ccl_tracer_corr_legendre(), anonymous_namespace{chameleon.cpp}::ChiSolver< T >::chi_a(), anonymous_namespace{chameleon.cpp}::ChiSolver< T >::chi_min(), cl_integrand(), compare_bbks(), compare_eh(), compare_halomod(), compare_massfunc(), compare_power_nu(), compare_power_nu_nl(), compute_wt_single(), corr_bessel_integrand(), dc_NakamuraSuto(), anonymous_namespace{chameleon.cpp}::ChiSolver< T >::dl_operator(), dNdz_smail(), Dv_BryanNorman(), eh_power(), eh_struct_new(), emuInit(), fftlog_ComputeXiLM(), fftw_execute_dft_r2c(), anonymous_namespace{mod_frozen_potential.cpp}::force_ref(), anonymous_namespace{mod_frozen_potential.cpp}::force_short(), gen_dens_binned(), gen_pow_spec_binned(), gen_pow_spec_binned_from_extrap(), gen_pow_spec_binned_init(), gen_rho_w_pow_k(), anonymous_namespace{chameleon.cpp}::ChiSolver< T >::get_chi_k(), anonymous_namespace{test_chameleon.cpp}::get_grav_pot(), get_rho_from_par(), get_vel_from_par(), anonymous_namespace{core_power.cpp}::growth_factor_integrand(), h_over_h0(), anonymous_namespace{core_power.cpp}::hubble_param(), if(), Box_Opt::init(), App_Var_Chi::ChiImpl::kick_step_w_chi(), kick_step_w_momentum(), kick_step_w_momentum_pm(), anonymous_namespace{mod_frozen_potential.cpp}::kick_step_w_pp(), anonymous_namespace{chameleon.cpp}::ChiSolver< T >::l_operator(), lin_pow_spec(), main(), massfunc_f(), non_lin_pow_spec(), Omega_lambda(), one_halo_integrand(), Extrap_Pk< T, N >::operator()(), power(), pwr_spec_k(), r_delta(), S2_shape(), FofrSolver< NDIM, T >::set_parameters(), anonymous_namespace{chameleon.cpp}::ChiSolver< T >::set_time(), sigmaR_integrand(), sigmaV_integrand(), test_angpow_precision(), tkEH_0(), tkEH_b(), tkEH_c(), transfer_wrap(), tsqr_BBKS(), tsqr_EH(), two_halo_integrand(), user_dNdz(), user_pz_probability(), vel_pwr_spec_k(), and write_wt_single().
 {
     float result = 1.f;
     while (exp)
     {
         if (exp & 1)
             result *= base;
         exp >>= 1;
         base *= base;
     }
     return result;
 }
template<typename T > T pow2 (T base) inline
Definition at line 52 of file precision.hpp.
Referenced by CIC_opt(), Extrap_Pk< T, N >::fit_lin(), Extrap_Pk< T, N >::fit_power_law(), anonymous_namespace{mod_frozen_potential.cpp}::force_short(), App_Var_FP_mod::FP_ppImpl::FP_ppImpl(), gen_pot_k(), get_distance(), get_k_sq(), App_Opt::init(), anonymous_namespace{test_chameleon.cpp}::init_overdensity(), App_Var_Chi::ChiImpl::kick_step_w_chi(), App_Var_Chi::ChiImpl::kick_step_w_chi_no_momentum(), anonymous_namespace{test_chameleon.cpp}::print_mesh(), print_pow_spec_diff(), print_vel_pow_spec_diff(), pwr_spec_k_init(), std_dev(), and wgh_sch< 2 >().
 { return base*base; }
Variable Documentation
constexpr double PI = double(3.14159265358979323846)
Definition at line 37 of file precision.hpp.
Referenced by CIC_opt(), anonymous_namespace{mod_frozen_potential.cpp}::force_short(), App_Var_FP_mod::FP_ppImpl::FP_ppImpl(), gen_displ_k_S2(), gen_pot_k(), gen_pow_spec_binned(), gen_pow_spec_binned_init(), gen_rho_w_pow_k(), anonymous_namespace{chameleon.cpp}::ChiSolver< T >::get_chi_k(), Other_par::init(), pwr_spec_k(), anonymous_namespace{core_power.cpp}::sigma_integrand_G(), vel_pwr_spec_k(), anonymous_namespace{core_power.cpp}::xi_integrand_G(), and anonymous_namespace{core_power.cpp}::xi_integrand_W().