Fast Methods for Cosmological Simulations: src/3party/CCL/tests/benchmark/codes/cl_corr_bm/src/spectra.c File Reference
spectra.c File Reference
#include "common.h"
Classes
struct IntClPar
struct IntWtPar
Functions
static double cl_integrand (double lk, void *params)
static double spectra (char *tr1, char *tr2, int l, RunParams *par)
void compute_spectra (RunParams *par)
static double wt_integrand (double l, void *params)
static void compute_wt_single (RunParams *par, double *cl, double *wt, double *llist, int bessel_order)
void compute_w_theta (RunParams *par)
Function Documentation
static double cl_integrand (double lk, void * params) static
Definition at line 10 of file spectra.c.
References RunParams::cpar, IntClPar::l, p, IntClPar::par, pow(), IntClPar::tr1, IntClPar::tr2, and transfer_wrap().
Referenced by spectra().
 {
   double d1,d2;
   IntClPar *p=(IntClPar *)params;
   double k=pow(10.,lk);
   double pk=csm_Pk_linear_0(p->par->cpar,k);
   d1=transfer_wrap(p->l,k,p->par,p->tr1,0);
   d2=transfer_wrap(p->l,k,p->par,p->tr2,1);
   return k*d1*d2*pk;
 }
void compute_spectra (RunParams * par)
Definition at line 40 of file spectra.c.
References RunParams::cl_cc, RunParams::cl_ci, RunParams::cl_d1l2, RunParams::cl_d2l1, RunParams::cl_dc, RunParams::cl_dd, RunParams::cl_di, RunParams::cl_ii, RunParams::cl_lc, RunParams::cl_li, RunParams::cl_ll, RunParams::do_cmblens, RunParams::do_isw, RunParams::do_nc, RunParams::do_shear, cl_cmbl_bm::l, RunParams::lmax, and spectra().
Referenced by main().
 {
   printf("Computing power spectra\n");
 #ifdef _HAS_OMP
 #pragma omp parallel default(none) shared(par)
   {
 #endif //_HAS_OMP
     int l;
 #ifdef _HAS_OMP
 #pragma omp for
 #endif //_HAS_OMP
     for(l=0;l<=par->lmax;l++) {
 #ifdef _DEBUG
       printf("%d \n",l);
 #endif //_DEBUG
       if(par->do_nc) {
     par->cl_dd[l]=spectra("nc","nc",l,par);
     if(par->do_shear) {
       par->cl_d1l2[l]=spectra("nc","shear",l,par);
       par->cl_d2l1[l]=spectra("shear","nc",l,par);
     }
     if(par->do_cmblens)
       par->cl_dc[l]=spectra("nc","cmblens",l,par);
     if(par->do_isw)
       par->cl_di[l]=spectra("nc","isw",l,par);
       }
       if(par->do_shear) {
     par->cl_ll[l]=spectra("shear","shear",l,par);
     if(par->do_cmblens)
       par->cl_lc[l]=spectra("shear","cmblens",l,par);
     if(par->do_isw)
       par->cl_li[l]=spectra("shear","isw",l,par);
       }
       if(par->do_cmblens) {
     par->cl_cc[l]=spectra("cmblens","cmblens",l,par);
     if(par->do_isw)
       par->cl_ci[l]=spectra("cmblens","isw",l,par);
       }
       if(par->do_isw)
     par->cl_ii[l]=spectra("isw","isw",l,par);
     } //end omp for
 #ifdef _HAS_OMP
   } //end omp parallel
 #endif //_HAS_OMP
 }
void compute_w_theta (RunParams * par)
Definition at line 149 of file spectra.c.
References RunParams::cl_cc, RunParams::cl_ci, RunParams::cl_d1l2, RunParams::cl_d2l1, RunParams::cl_dc, RunParams::cl_dd, RunParams::cl_di, RunParams::cl_ii, RunParams::cl_lc, RunParams::cl_li, RunParams::cl_ll, compute_wt_single(), dam_malloc(), RunParams::do_cmblens, RunParams::do_isw, RunParams::do_nc, RunParams::do_shear, RunParams::do_w_theta, cl_cmbl_bm::l, RunParams::lmax, RunParams::wt_cc, RunParams::wt_ci, RunParams::wt_d1l2, RunParams::wt_d2l1, RunParams::wt_dc, RunParams::wt_dd, RunParams::wt_di, RunParams::wt_ii, RunParams::wt_lc, RunParams::wt_li, RunParams::wt_ll_mm, and RunParams::wt_ll_pp.
Referenced by main().
 {
   if(par->do_w_theta) {
     int l;
     double *llist;
     printf("Computing correlation functions\n");
     llist=dam_malloc((par->lmax+1)*sizeof(double));
     for(l=0;l<=par->lmax;l++)
       llist[l]=(float)l;
     if(par->do_nc) {
       compute_wt_single(par,par->cl_dd,par->wt_dd,llist,0);
       if(par->do_shear) {
     compute_wt_single(par,par->cl_d1l2,par->wt_d1l2,llist,0);
     compute_wt_single(par,par->cl_d2l1,par->wt_d2l1,llist,0);
       }
       if(par->do_cmblens)
     compute_wt_single(par,par->cl_dc,par->wt_dc,llist,0);
       if(par->do_isw)
     compute_wt_single(par,par->cl_di,par->wt_di,llist,0);
     }
     if(par->do_shear) {
       compute_wt_single(par,par->cl_ll,par->wt_ll_pp,llist,0);
       compute_wt_single(par,par->cl_ll,par->wt_ll_mm,llist,4);
       if(par->do_cmblens)
     compute_wt_single(par,par->cl_lc,par->wt_lc,llist,0);
       if(par->do_isw)
     compute_wt_single(par,par->cl_li,par->wt_li,llist,0);
     }
     if(par->do_cmblens) {
       compute_wt_single(par,par->cl_cc,par->wt_cc,llist,0);
       if(par->do_isw)
     compute_wt_single(par,par->cl_ci,par->wt_ci,llist,0);
     }
     if(par->do_isw)
       compute_wt_single(par,par->cl_ii,par->wt_ii,llist,0);
     free(llist);
   }
   else {
     printf("Skipping correlation functions\n");
   }
 }
static void compute_wt_single (RunParams * par, double * cl, double * wt, double * llist, int bessel_order) static
Definition at line 110 of file spectra.c.
References IntWtPar::cl, IntWtPar::clsp, RunParams::do_w_theta_logbin, DTOR, IntWtPar::i_bessel, RunParams::lmax, M_PI, RunParams::n_th, RunParams::n_th_logint, IntWtPar::par, pow(), spline_free(), spline_init(), IntWtPar::th, RunParams::th_max, RunParams::th_min, w, and wt_integrand().
Referenced by compute_w_theta().
 {
 #ifdef _HAS_OMP
 #pragma omp parallel default(none)      \
   shared(par,cl,wt,llist,bessel_order)
   {
 #endif //_HAS_OMP
     int ith;
     double result,eresult;
     gsl_function F;
     gsl_integration_workspace *w=gsl_integration_workspace_alloc(1000);
     SplPar *clsp=spline_init((par->lmax+1),llist,cl,0,0);
     IntWtPar ipar;
     ipar.i_bessel=bessel_order;
     ipar.par=par;
     ipar.clsp=clsp;
     ipar.cl=cl;
 #ifdef _HAS_OMP
 #pragma omp for
 #endif //_HAS_OMP
     for(ith=0;ith<par->n_th;ith++) {
       if(par->do_w_theta_logbin)
     ipar.th=DTOR*par->th_max*pow(10.,(ith+0.5-par->n_th)/par->n_th_logint);
       else
     ipar.th=DTOR*(par->th_min+(par->th_max-par->th_min)*(ith+0.5)/par->n_th);
       F.function=&wt_integrand;
       F.params=&ipar;
       gsl_integration_qag(&F,llist[0],llist[par->lmax],0,1E-4,1000,GSL_INTEG_GAUSS41,w,&result,&eresult);
       wt[ith]=result/(2*M_PI);
     }//end omp for
     gsl_integration_workspace_free(w);
     spline_free(clsp);
 #ifdef _HAS_OMP
   } //end omp parallel
 #endif //_HAS_OMP
 }
static double spectra (char * tr1, char * tr2, int l, RunParams * par) static
Definition at line 22 of file spectra.c.
References cl_integrand(), D_LKMAX, D_LKMIN, IntClPar::l, cl_cmbl_bm::l, IntClPar::par, IntClPar::tr1, IntClPar::tr2, and w.
Referenced by ccl_cosmology_compute_power_class(), ccl_cosmology_compute_power_emu(), ccl_cosmology_write_power_class_z(), ccl_get_class_As(), and compute_spectra().
 {
   IntClPar ipar;
   double result=0,eresult;
   gsl_function F;
   gsl_integration_workspace *w=gsl_integration_workspace_alloc(1000);
   ipar.l=l;
   ipar.par=par;
   ipar.tr1=tr1;
   ipar.tr2=tr2;
   F.function=&cl_integrand;
   F.params=&ipar;
   gsl_integration_qag(&F,D_LKMIN,D_LKMAX,0,1E-4,1000,GSL_INTEG_GAUSS41,w,&result,&eresult);
   gsl_integration_workspace_free(w);
   return M_LN10*2*result/(2*l+1.);
 }
static double wt_integrand (double l, void * params) static
Definition at line 94 of file spectra.c.
References IntWtPar::cl, IntWtPar::i_bessel, p, IntWtPar::th, and x.
Referenced by compute_wt_single().
 {
   IntWtPar *p=(IntWtPar *)params;
   double x=l*p->th;
   //  double cl=spline_eval(l,p->clsp);
   double cl=p->cl[(int)l];
   double jbes;
   if(p->i_bessel)
     jbes=gsl_sf_bessel_Jn(p->i_bessel,x);
   else
     jbes=gsl_sf_bessel_J0(x);
   return l*jbes*cl;
 }