Fast Methods for Cosmological Simulations: Catch::StringMaker< T, typename > Struct Template Reference
Catch::StringMaker< T, typename > Struct Template Reference
#include <catch.hpp>
Static Public Member Functions
template<typename Fake = T>
static std::enable_if<::Catch::Detail::IsStreamInsertable< Fake >::value, std::string >::type convert (const Fake &value)
template<typename Fake = T>
static std::enable_if<!::Catch::Detail::IsStreamInsertable< Fake >::value, std::string >::type convert (const Fake &value)
Detailed Description
template<typename T, typename = void>
struct Catch::StringMaker< T, typename >
Definition at line 926 of file catch.hpp.
Member Function Documentation
template<typename T , typename = void> template<typename Fake = T> static std::enable_if<::Catch::Detail::IsStreamInsertable<Fake>::value, std::string>::type Catch::StringMaker< T, typename >::convert (const Fake & value) inline static
Definition at line 930 of file catch.hpp.
References Catch::ReusableStringStream::str(), and Catch::Generators::value().
Referenced by Catch::Detail::rangeToString().
{
                 ReusableStringStream rss;
                 // NB: call using the function-like syntax to avoid ambiguity with
                 // user-defined templated operator<< under clang.
                 rss.operator<<(value);
                 return rss.str();
         }
template<typename T , typename = void> template<typename Fake = T> static std::enable_if<!::Catch::Detail::IsStreamInsertable<Fake>::value, std::string>::type Catch::StringMaker< T, typename >::convert (const Fake & value) inline static
Definition at line 941 of file catch.hpp.
References Catch::Detail::convertUnstreamable().
{
 #if !defined(CATCH_CONFIG_FALLBACK_STRINGIFIER)
             return Detail::convertUnstreamable(value);
 #else
             return CATCH_CONFIG_FALLBACK_STRINGIFIER(value);
 #endif
         }
The documentation for this struct was generated from the following file:
src/3party/Catch/catch.hpp