Fast Methods for Cosmological Simulations: Catch::StringMaker< T[SZ]> Struct Template Reference
Catch::StringMaker< T[SZ]> Struct Template Reference
#include <catch.hpp>
Static Public Member Functions
static std::string convert (T const (&arr)[SZ])
Detailed Description
template<typename T, int SZ>
struct Catch::StringMaker< T[SZ]>
Definition at line 1323 of file catch.hpp.
Member Function Documentation
template<typename T , int SZ> static std::string Catch::StringMaker< T[SZ]>::convert (T const (&) arr[SZ]) inline static
Definition at line 1324 of file catch.hpp.
References cl_cmbl_bm::fmt, Catch::rangeToString(), Catch::ReusableStringStream::str(), and Catch::Detail::stringify().
{
             return rangeToString(arr);
         }
The documentation for this struct was generated from the following file:
src/3party/Catch/catch.hpp