Fast Methods for Cosmological Simulations: Catch::Matchers::Vector::UnorderedEqualsMatcher< T > Struct Template Reference
Catch::Matchers::Vector::UnorderedEqualsMatcher< T > Struct Template Reference
#include <catch.hpp>
Public Member Functions
UnorderedEqualsMatcher (std::vector< T > const &target)
bool match (std::vector< T > const &vec) const override
std::string describe () const override
Private Attributes
std::vector< T > const & m_target
Detailed Description
template<typename T>
struct Catch::Matchers::Vector::UnorderedEqualsMatcher< T >
Definition at line 2842 of file catch.hpp.
Constructor & Destructor Documentation
template<typename T > Catch::Matchers::Vector::UnorderedEqualsMatcher< T >::UnorderedEqualsMatcher (std::vector< T > const & target) inline
Definition at line 2843 of file catch.hpp.
 : m_target(target) {}
Member Function Documentation
template<typename T > std::string Catch::Matchers::Vector::UnorderedEqualsMatcher< T >::describe () const inline override
Definition at line 2874 of file catch.hpp.
References Catch::Detail::stringify().
{
                 return "UnorderedEquals: " + ::Catch::Detail::stringify(m_target);
             }
template<typename T > bool Catch::Matchers::Vector::UnorderedEqualsMatcher< T >::match (std::vector< T > const & vec) const inline override
Definition at line 2844 of file catch.hpp.
References Catch::Matchers::Vector::Detail::contains(), and Catch::Matchers::Vector::Detail::count().
{
                 // Note: This is a reimplementation of std::is_permutation,
                 //       because I don't want to include <algorithm> inside the common path
                 if (m_target.size() != vec.size()) {
                     return false;
                 }
                 auto lfirst = m_target.begin(), llast = m_target.end();
                 auto rfirst = vec.begin(), rlast = vec.end();
                 // Cut common prefix to optimize checking of permuted parts
                 while (lfirst != llast && *lfirst == *rfirst) {
                     ++lfirst; ++rfirst;
                 }
                 if (lfirst == llast) {
                     return true;
                 }
                 for (auto mid = lfirst; mid != llast; ++mid) {
                     // Skip already counted items
                     if (Detail::contains(lfirst, mid, *mid)) {
                         continue;
                     }
                     size_t num_vec = Detail::count(rfirst, rlast, *mid);
                     if (num_vec == 0 || Detail::count(lfirst, llast, *mid) != num_vec) {
                         return false;
                     }
                 }
                 return true;
             }
Member Data Documentation
template<typename T > std::vector<T> const& Catch::Matchers::Vector::UnorderedEqualsMatcher< T >::m_target private
Definition at line 2878 of file catch.hpp.
The documentation for this struct was generated from the following file:
src/3party/Catch/catch.hpp