Fast Methods for Cosmological Simulations: nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_value Union Reference
nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_value Union Reference
a JSON value
Public Member Functions
json_value ()=default
default constructor (for null values)
json_value (boolean_t v) noexcept
constructor for booleans
json_value (number_integer_t v) noexcept
constructor for numbers (integer)
json_value (number_unsigned_t v) noexcept
constructor for numbers (unsigned)
json_value (number_float_t v) noexcept
constructor for numbers (floating-point)
json_value (value_t t)
constructor for empty values of a given type
json_value (const string_t &value)
constructor for strings
json_value (string_t &&value)
constructor for rvalue strings
json_value (const object_t &value)
constructor for objects
json_value (object_t &&value)
constructor for rvalue objects
json_value (const array_t &value)
constructor for arrays
json_value (array_t &&value)
constructor for rvalue arrays
void destroy (value_t t) noexcept
Public Attributes
object_t * object
object (stored with pointer to save storage)
array_t * array
array (stored with pointer to save storage)
string_t * string
string (stored with pointer to save storage)
boolean_t boolean
boolean
number_integer_t number_integer
number (integer)
number_unsigned_t number_unsigned
number (unsigned integer)
number_float_t number_float
number (floating-point)
Detailed Description
template<template< typename, typename, typename... > class ObjectType, template< typename, typename... > class ArrayType, class StringType, class BooleanType, class NumberIntegerType, class NumberUnsignedType, class NumberFloatType, template< typename > class AllocatorType, template< typename, typename=void > class JSONSerializer>
union nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_value
a JSON value
The actual storage for a JSON value of the basic_json class. This union combines the different storage types for the JSON value types defined in value_t.
JSON type value_t type used type
object object pointer to object_t
array array pointer to array_t
string string pointer to string_t
boolean boolean boolean_t
number number_integer number_integer_t
number number_unsigned number_unsigned_t
number number_float number_float_t
null null no value is stored
Note
Variable-length types (objects, arrays, and strings) are stored as pointers. The size of the union should not exceed 64 bits if the default value types are used.
Since
version 1.0.0
Definition at line 13126 of file json.hpp.
Constructor & Destructor Documentation
template<template< typename, typename, typename... > class ObjectType, template< typename, typename... > class ArrayType, class StringType , class BooleanType , class NumberIntegerType , class NumberUnsignedType , class NumberFloatType , template< typename > class AllocatorType, template< typename, typename=void > class JSONSerializer> nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_value::json_value () default
default constructor (for null values)
template<template< typename, typename, typename... > class ObjectType, template< typename, typename... > class ArrayType, class StringType , class BooleanType , class NumberIntegerType , class NumberUnsignedType , class NumberFloatType , template< typename > class AllocatorType, template< typename, typename=void > class JSONSerializer> nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_value::json_value (boolean_t v) inline noexcept
constructor for booleans
Definition at line 13146 of file json.hpp.
 : boolean(v) {}
template<template< typename, typename, typename... > class ObjectType, template< typename, typename... > class ArrayType, class StringType , class BooleanType , class NumberIntegerType , class NumberUnsignedType , class NumberFloatType , template< typename > class AllocatorType, template< typename, typename=void > class JSONSerializer> nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_value::json_value (number_integer_t v) inline noexcept
constructor for numbers (integer)
Definition at line 13148 of file json.hpp.
 : number_integer(v) {}
template<template< typename, typename, typename... > class ObjectType, template< typename, typename... > class ArrayType, class StringType , class BooleanType , class NumberIntegerType , class NumberUnsignedType , class NumberFloatType , template< typename > class AllocatorType, template< typename, typename=void > class JSONSerializer> nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_value::json_value (number_unsigned_t v) inline noexcept
constructor for numbers (unsigned)
Definition at line 13150 of file json.hpp.
 : number_unsigned(v) {}
template<template< typename, typename, typename... > class ObjectType, template< typename, typename... > class ArrayType, class StringType , class BooleanType , class NumberIntegerType , class NumberUnsignedType , class NumberFloatType , template< typename > class AllocatorType, template< typename, typename=void > class JSONSerializer> nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_value::json_value (number_float_t v) inline noexcept
constructor for numbers (floating-point)
Definition at line 13152 of file json.hpp.
 : number_float(v) {}
template<template< typename, typename, typename... > class ObjectType, template< typename, typename... > class ArrayType, class StringType , class BooleanType , class NumberIntegerType , class NumberUnsignedType , class NumberFloatType , template< typename > class AllocatorType, template< typename, typename=void > class JSONSerializer> nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_value::json_value (value_t t) inline
constructor for empty values of a given type
Definition at line 13154 of file json.hpp.
References nlohmann::detail::array, nlohmann::detail::boolean, nlohmann::detail::other_error::create(), JSON_THROW, JSON_UNLIKELY, nlohmann::detail::null, nlohmann::detail::number_float, nlohmann::detail::number_integer, nlohmann::detail::number_unsigned, nlohmann::detail::object, and nlohmann::detail::string.
         {
             switch (t)
             {
                 case value_t::object:
                 {
                     object = create<object_t>();
                     break;
                 }
                 case value_t::array:
                 {
                     array = create<array_t>();
                     break;
                 }
                 case value_t::string:
                 {
                     string = create<string_t>("");
                     break;
                 }
                 case value_t::boolean:
                 {
                     boolean = boolean_t(false);
                     break;
                 }
                 case value_t::number_integer:
                 {
                     number_integer = number_integer_t(0);
                     break;
                 }
                 case value_t::number_unsigned:
                 {
                     number_unsigned = number_unsigned_t(0);
                     break;
                 }
                 case value_t::number_float:
                 {
                     number_float = number_float_t(0.0);
                     break;
                 }
                 case value_t::null:
                 {
                     object = nullptr;  // silence warning, see #821
                     break;
                 }
                 default:
                 {
                     object = nullptr;  // silence warning, see #821
                     if (JSON_UNLIKELY(t == value_t::null))
                     {
                         JSON_THROW(other_error::create(500, "961c151d2e87f2686a955a9be24d316f1362bf21 3.4.0")); // LCOV_EXCL_LINE
                     }
                     break;
                 }
             }
         }
template<template< typename, typename, typename... > class ObjectType, template< typename, typename... > class ArrayType, class StringType , class BooleanType , class NumberIntegerType , class NumberUnsignedType , class NumberFloatType , template< typename > class AllocatorType, template< typename, typename=void > class JSONSerializer> nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_value::json_value (const string_t & value) inline
constructor for strings
Definition at line 13219 of file json.hpp.
References Catch::Generators::value().
         {
             string = create<string_t>(value);
         }
template<template< typename, typename, typename... > class ObjectType, template< typename, typename... > class ArrayType, class StringType , class BooleanType , class NumberIntegerType , class NumberUnsignedType , class NumberFloatType , template< typename > class AllocatorType, template< typename, typename=void > class JSONSerializer> nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_value::json_value (string_t && value) inline
constructor for rvalue strings
Definition at line 13225 of file json.hpp.
References Catch::Generators::value().
         {
             string = create<string_t>(std::move(value));
         }
template<template< typename, typename, typename... > class ObjectType, template< typename, typename... > class ArrayType, class StringType , class BooleanType , class NumberIntegerType , class NumberUnsignedType , class NumberFloatType , template< typename > class AllocatorType, template< typename, typename=void > class JSONSerializer> nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_value::json_value (const object_t & value) inline
constructor for objects
Definition at line 13231 of file json.hpp.
References Catch::Generators::value().
         {
             object = create<object_t>(value);
         }
template<template< typename, typename, typename... > class ObjectType, template< typename, typename... > class ArrayType, class StringType , class BooleanType , class NumberIntegerType , class NumberUnsignedType , class NumberFloatType , template< typename > class AllocatorType, template< typename, typename=void > class JSONSerializer> nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_value::json_value (object_t && value) inline
constructor for rvalue objects
Definition at line 13237 of file json.hpp.
References Catch::Generators::value().
         {
             object = create<object_t>(std::move(value));
         }
template<template< typename, typename, typename... > class ObjectType, template< typename, typename... > class ArrayType, class StringType , class BooleanType , class NumberIntegerType , class NumberUnsignedType , class NumberFloatType , template< typename > class AllocatorType, template< typename, typename=void > class JSONSerializer> nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_value::json_value (const array_t & value) inline
constructor for arrays
Definition at line 13243 of file json.hpp.
References Catch::Generators::value().
         {
             array = create<array_t>(value);
         }
template<template< typename, typename, typename... > class ObjectType, template< typename, typename... > class ArrayType, class StringType , class BooleanType , class NumberIntegerType , class NumberUnsignedType , class NumberFloatType , template< typename > class AllocatorType, template< typename, typename=void > class JSONSerializer> nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_value::json_value (array_t && value) inline
constructor for rvalue arrays
Definition at line 13249 of file json.hpp.
References Catch::Generators::value().
         {
             array = create<array_t>(std::move(value));
         }
Member Function Documentation
template<template< typename, typename, typename... > class ObjectType, template< typename, typename... > class ArrayType, class StringType , class BooleanType , class NumberIntegerType , class NumberUnsignedType , class NumberFloatType , template< typename > class AllocatorType, template< typename, typename=void > class JSONSerializer> void nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_value::destroy (value_t t) inline noexcept
Definition at line 13254 of file json.hpp.
References nlohmann::detail::array, nlohmann::detail::object, and nlohmann::detail::string.
         {
             switch (t)
             {
                 case value_t::object:
                 {
                     AllocatorType<object_t> alloc;
                     std::allocator_traits<decltype(alloc)>::destroy(alloc, object);
                     std::allocator_traits<decltype(alloc)>::deallocate(alloc, object, 1);
                     break;
                 }
                 case value_t::array:
                 {
                     AllocatorType<array_t> alloc;
                     std::allocator_traits<decltype(alloc)>::destroy(alloc, array);
                     std::allocator_traits<decltype(alloc)>::deallocate(alloc, array, 1);
                     break;
                 }
                 case value_t::string:
                 {
                     AllocatorType<string_t> alloc;
                     std::allocator_traits<decltype(alloc)>::destroy(alloc, string);
                     std::allocator_traits<decltype(alloc)>::deallocate(alloc, string, 1);
                     break;
                 }
                 default:
                 {
                     break;
                 }
             }
         }
Member Data Documentation
template<template< typename, typename, typename... > class ObjectType, template< typename, typename... > class ArrayType, class StringType , class BooleanType , class NumberIntegerType , class NumberUnsignedType , class NumberFloatType , template< typename > class AllocatorType, template< typename, typename=void > class JSONSerializer> array_t* nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_value::array
array (stored with pointer to save storage)
Definition at line 13131 of file json.hpp.
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::basic_json().
template<template< typename, typename, typename... > class ObjectType, template< typename, typename... > class ArrayType, class StringType , class BooleanType , class NumberIntegerType , class NumberUnsignedType , class NumberFloatType , template< typename > class AllocatorType, template< typename, typename=void > class JSONSerializer> boolean_t nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_value::boolean
boolean
Definition at line 13135 of file json.hpp.
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::basic_json().
template<template< typename, typename, typename... > class ObjectType, template< typename, typename... > class ArrayType, class StringType , class BooleanType , class NumberIntegerType , class NumberUnsignedType , class NumberFloatType , template< typename > class AllocatorType, template< typename, typename=void > class JSONSerializer> number_float_t nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_value::number_float
number (floating-point)
Definition at line 13141 of file json.hpp.
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::basic_json().
template<template< typename, typename, typename... > class ObjectType, template< typename, typename... > class ArrayType, class StringType , class BooleanType , class NumberIntegerType , class NumberUnsignedType , class NumberFloatType , template< typename > class AllocatorType, template< typename, typename=void > class JSONSerializer> number_integer_t nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_value::number_integer
number (integer)
Definition at line 13137 of file json.hpp.
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::basic_json().
template<template< typename, typename, typename... > class ObjectType, template< typename, typename... > class ArrayType, class StringType , class BooleanType , class NumberIntegerType , class NumberUnsignedType , class NumberFloatType , template< typename > class AllocatorType, template< typename, typename=void > class JSONSerializer> number_unsigned_t nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_value::number_unsigned
number (unsigned integer)
Definition at line 13139 of file json.hpp.
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::basic_json().
template<template< typename, typename, typename... > class ObjectType, template< typename, typename... > class ArrayType, class StringType , class BooleanType , class NumberIntegerType , class NumberUnsignedType , class NumberFloatType , template< typename > class AllocatorType, template< typename, typename=void > class JSONSerializer> object_t* nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_value::object
object (stored with pointer to save storage)
Definition at line 13129 of file json.hpp.
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::basic_json().
template<template< typename, typename, typename... > class ObjectType, template< typename, typename... > class ArrayType, class StringType , class BooleanType , class NumberIntegerType , class NumberUnsignedType , class NumberFloatType , template< typename > class AllocatorType, template< typename, typename=void > class JSONSerializer> string_t* nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_value::string
string (stored with pointer to save storage)
Definition at line 13133 of file json.hpp.
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::basic_json().
The documentation for this union was generated from the following file:
src/3party/JSON/json.hpp